# Experiment 2: agreement, reliability, and posterior activations

This notebook is the activation-focused successor to notebook 13. It keeps notebook 13's
raw set-membership task and visible-reasoning contrast, but uses $N=9$, $K=3$, ten
symmetric interior reliabilities, 64 seeded question schedules, and one candidate
presentation order. The resulting design has

$$64\text{ schedules}\times 8\text{ report patterns}\times
10\text{ reliabilities}\times2\text{ reasoning modes}=10{,}240\text{ rows}. $$

Ties in agreement counts are retained. `allow_same=False` means that `SAME` is not offered
as an answer token; it does **not** remove tie stimuli.

Every expensive stage has an explicit gate, and every gate is initially false. Building the
notebook does not run inference, train probes, open the locked test, or patch activations.

Reasoning-off and reasoning-on are separate capture/probe datasets. They share the same
schedule-level split, so a held-out schedule cannot appear in either mode's training set.
The activation cache stores one stream—`resid_post`—at every language layer but only at a
preregistered set of semantically aligned prompt locations and the terminal answer tail.

## Execution order and interpretation

1. Leave all gates false and run the notebook once. Confirm 10,240 total rows, the
   4,480/640 split inside each reasoning mode, paired prompt-length equality, the available
   test tie cells, and the storage preflight.
2. When the GPU is free, set `RUN_GPU_CAPTURE=True`. Leave probe and patch switches false.
   Do not change factorial or capture settings under the same mode-specific `RUN_IDS`. A completed run is
   reusable; after interruption, rerunning this gate validates and resumes the durable
   contiguous prefix in eight-row checkpoints.
3. After capture completes, set `RUN_GPU_CAPTURE=False` and
   `LOAD_COMPLETED_CAPTURE=True`; validate the inventory.
4. Set `RUN_PROBE_TRAINING=True`. This reads only training schedules and writes weights and
   grouped-CV scores. Allow it to finish and inspect `locked_layers.json`.
5. Set `RUN_PROBE_TRAINING=False` and `RUN_PROBE_VISUALIZATIONS=True` to render the full
   training-schedule validation and probe-geometry plots without opening the test.
6. Freeze the locked layers, then set `RUN_LOCKED_TEST_EVALUATION=True` once. Keep transfer
   analysis false on that first pass so the confirmatory table is written before exploratory
   matrices are inspected.
7. Set `RUN_PROBE_TRANSFER_ANALYSIS=True` only after the locked test table exists.
8. Only after the decoding result is locked, set `RUN_ACTIVATION_PATCHING=True` for the
   held-out, bidirectional whole-residual reliability swaps.

A high held-out $z^*$ probe does not establish mechanism. The causal question is whether
replacing reliability-conditioned state moves the answer margin toward the donor's exact
counterfactual in both directions and at both reliability magnitudes. Report raw margin
changes and failures as well as successes.

In [19]:
from __future__ import annotations

import gc
import hashlib
import json
import logging
import math
import os
import re
import shutil
import sys
import tempfile
from collections import Counter, defaultdict
from datetime import datetime, timezone
from fractions import Fraction
from itertools import combinations
from pathlib import Path

# torchao probes optional native extensions during some Transformers imports. The local
# experiment stack does not need those extensions.
os.environ.setdefault("TORCHAO_FORCE_SKIP_LOADING_SO_FILES", "1")
logging.getLogger("torchao").setLevel(logging.ERROR)

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from IPython.display import Markdown, display
from safetensors import SafetensorError, safe_open
from safetensors.torch import load_file, save_file
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.decomposition import PCA
from sklearn.metrics import (
    balanced_accuracy_score,
    log_loss,
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    roc_auc_score,
)
from sklearn.model_selection import GridSearchCV, GroupKFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from transformers import AutoConfig, AutoProcessor

REPO_ROOT = next(
    path for path in (Path.cwd(), *Path.cwd().parents)
    if (path / "pyproject.toml").exists()
)
sys.path.insert(0, str(REPO_ROOT))

from mats_experiments.noisy_channel_bayesian import (
    CaptureSpec,
    ExecutionConfig,
    MetricSpec,
    ModelConfig,
    NoisyChannelBayesianEnvironment,
    QwenRunner,
    RandomSubsetQuestion,
    SGLangMTPConfig,
    SystemPrompt,
    TokenizerBinding,
    TranscriptDataset,
    TranscriptDatasetGenerator,
    XVsYPosteriorProbe,
    answer_patterns,
)

## Configuration

Every experimental, storage, split, probe, visualization, and patching parameter is in this
cell. Native Qwen thinking remains disabled in every condition: `reasoning=True` means
ordinary visible assistant text before `ANSWER:`, as in notebook 13.

Reasoning-off has a 64-token watchdog. Reasoning-on has a 4,096-token watchdog so visible
reasoning has enough room to reach the required terminal answer. Only selected activation
positions are persisted, so the longer generation cap does not multiply disk usage.

In [20]:
# ------------------------------- factorial -------------------------------
MODEL_ID = "Qwen/Qwen3.5-9B"
MODEL_REVISION = "c202236235762e1c871ad0ccb60c8ee5ba337b9a"
N = 9
K = 3
R_VALUES = (
    0.05, 0.15, 0.25, 0.35, 0.45,
    0.55, 0.65, 0.75, 0.85, 0.95,
)
R_EXACT_VALUES = tuple(str(Fraction(str(value))) for value in R_VALUES)
REASONING_VALUES = (False, True)
NUM_QUESTION_SETS = 64
NUM_ANSWER_PATTERNS = 8
CONTROL_POSITIONAL_BIAS = False
ALLOW_SAME = False                 # tie rows stay; SAME is not an output option

X = 2
Y = 7
SUBSET_SIZE = 4
SEED = 20260905
SYSTEM_PROMPT_TEXT = (
    "You are a Bayesian reasoner. Follow the user's game rules exactly. "
    "Use plaintext only. Do not use Markdown, headings, bullets, tables, code blocks, "
    "HTML, or any other formatting."
)

# --------------------------- capture and storage --------------------------
ACTIVATION_STREAM = "resid_post"   # exactly one saved activation stream
ACTIVATION_LAYERS = "all"          # all 32 language layers
ACTIVATION_TOKENS = "row_selected" # semantic prompt sites plus final answer tail
NUM_LAYERS = 32
HIDDEN_SIZE = 4096
ACTIVATION_BYTES_PER_ELEMENT = 2    # BF16
MAX_COMPLETION_TOKENS_BY_REASONING = {False: 64, True: 4096}
ANSWER_TAIL_TOKENS = 16
ACTIVATION_STORAGE_BUDGET_GIB = 160.0
ACTIVATION_BUDGET_SAFETY_FRACTION = 0.90
MIN_FREE_DISK_AFTER_CAPTURE_GIB = 25.0

MODEL_DTYPE = "auto"
DEVICE_MAP = None
LOCAL_FILES_ONLY = True
ENABLE_MTP = False
COMPLETION_BATCH_SIZE = 4
CAPTURE_BATCH_SIZE = 1
SCORE_BATCH_SIZE = 4
CAPTURE_CHECKPOINT_ROWS = 8       # persist a contiguous result prefix every 8 rows

EXPERIMENT_ROOT = (
    REPO_ROOT / "artifacts" / "noisy_channel_bayesian_experiment_2_activation_patching"
)
DATASET_RUN_ID = "qwen35_9b_n9_k3_r10_s64_selected_tokens_v2"
MODE_NAMES = {False: "reasoning_off", True: "reasoning_on"}
RUN_IDS = {
    reasoning: f"{DATASET_RUN_ID}_{MODE_NAMES[reasoning]}"
    for reasoning in REASONING_VALUES
}

# ------------------------------ split policy ------------------------------
TEST_SCHEDULE_COUNT = 8
SPLIT_SEARCH_CANDIDATES = 50_000
PREFER_ALL_TIE_CELLS_IN_TEST = True

# ------------------------------- probe plan -------------------------------
# Each entry is a semantically aligned span; multi-token spans are mean pooled.
PROBE_SITES = (
    "domain_boundary",
    "reliability_rule_boundary",
    "reliability_r_value",
    "reliability_one_minus_r_value",
    "report_1_answer",
    "report_2_answer",
    "report_3_answer",
    "observation_question_boundary",
    "candidate_1_value",
    "candidate_2_value",
    "candidate_question_boundary",
    "assistant_turn_boundary",
    "final_prompt",
    "answer_line",
)
CONTINUOUS_PROBE_TARGETS = (
    "delta_a", "gain", "gain_abs", "z_bayes", "z_heuristic",
)
BINARY_PROBE_TARGETS = ("reliability_sign",)
PROBE_LAYERS = tuple(range(NUM_LAYERS))
RIDGE_ALPHAS = tuple(float(value) for value in np.logspace(-3, 6, 10))
RIDGE_SOLVER = "lsqr"
RIDGE_TOL = 1e-5
RIDGE_MAX_ITER = 10_000
LOGISTIC_C_VALUES = tuple(float(value) for value in np.logspace(-4, 4, 9))
PROBE_CV_FOLDS = 5
PROBE_N_JOBS = 32                 # execution-only parallelism; not fingerprinted
PROBE_TOP_K_LAYERS = 3            # selected using training CV only
MIN_GENERATED_SITE_COVERAGE = 0.95
MIN_PROBE_TRAIN_ROWS = HIDDEN_SIZE + 1
PROBE_RUN_ID = "ridge_logistic_split_reasoning_selected_sites_v2"

# ------------------------- probe visualization plan -----------------------
# Full layer sweeps use grouped validation scores, never in-sample R^2.
PROBE_PLOT_TARGETS = CONTINUOUS_PROBE_TARGETS
PROBE_TRANSFER_TARGETS = ("z_bayes",)
PROBE_TRANSFER_LAYERS = (0, 8, 16, 24, 31)
PROBE_FIGURE_DPI = 160

# ------------------------- whole-residual patching ------------------------
PATCH_SITE = "final_prompt"
PATCH_RELIABILITY_PAIRS = (("1/20", "19/20"), ("1/4", "3/4"))
PATCH_MAX_DIRECTIONS = 64
BRIDGE_LOGIT_TOLERANCE = 0.05
PATCH_RUN_ID = "whole_residual_reliability_interchange_v2"

# -------------------------- explicit execution gates ----------------------
RUN_GPU_CAPTURE = False
LOAD_COMPLETED_CAPTURE = True
ANALYSIS_REASONING_VALUES = (False,)  # reasoning_on remains durably paused for later
RUN_PROBE_TRAINING = True
RUN_LOCKED_TEST_EVALUATION = False
RUN_PROBE_VISUALIZATIONS = False
RUN_PROBE_TRANSFER_ANALYSIS = False
RUN_ACTIVATION_PATCHING = False

In [21]:
def model_key(model_id: str) -> str:
    readable = re.sub(r"[^A-Za-z0-9_.-]+", "_", model_id).strip("_")
    digest = hashlib.sha256(model_id.encode()).hexdigest()[:8]
    return f"{readable}_{digest}"


MODEL_ROOT = EXPERIMENT_ROOT / model_key(MODEL_ID)
DATASET_ROOT = MODEL_ROOT / "datasets" / DATASET_RUN_ID
RUN_DIRS = {
    reasoning: MODEL_ROOT / "runs" / RUN_IDS[reasoning]
    for reasoning in REASONING_VALUES
}
SPLIT_ROOT = MODEL_ROOT / "splits" / DATASET_RUN_ID
PROBE_ROOT = MODEL_ROOT / "probes" / PROBE_RUN_ID
PATCH_ROOT = MODEL_ROOT / "patches" / PATCH_RUN_ID

ROWS_PER_SCHEDULE_PER_REASONING = NUM_ANSWER_PATTERNS * len(R_VALUES)
EXPECTED_ROWS_PER_REASONING = NUM_QUESTION_SETS * ROWS_PER_SCHEDULE_PER_REASONING
EXPECTED_TEST_ROWS_PER_REASONING = (
    TEST_SCHEDULE_COUNT * ROWS_PER_SCHEDULE_PER_REASONING
)
EXPECTED_TRAIN_ROWS_PER_REASONING = (
    EXPECTED_ROWS_PER_REASONING - EXPECTED_TEST_ROWS_PER_REASONING
)
EXPECTED_TEST_ROWS = EXPECTED_TEST_ROWS_PER_REASONING * len(REASONING_VALUES)
EXPECTED_TRAIN_ROWS = EXPECTED_TRAIN_ROWS_PER_REASONING * len(REASONING_VALUES)
EXPECTED_ROWS = (
    NUM_QUESTION_SETS
    * NUM_ANSWER_PATTERNS
    * len(R_VALUES)
    * len(REASONING_VALUES)
)
EXPECTED_VARIANTS_PER_BASE_TRANSCRIPT = len(R_VALUES) * len(REASONING_VALUES)
ALL_AGREEMENT_CELLS = tuple(
    (a1, a2) for a1 in range(K + 1) for a2 in range(K + 1)
)
TIE_CELLS = frozenset((value, value) for value in range(K + 1))

assert NUM_ANSWER_PATTERNS == 2**K == 8
assert EXPECTED_ROWS_PER_REASONING == 5120
assert EXPECTED_TRAIN_ROWS_PER_REASONING == 4480
assert EXPECTED_TEST_ROWS_PER_REASONING == 640
assert EXPECTED_ROWS == 10240
assert EXPECTED_TEST_ROWS == (
    TEST_SCHEDULE_COUNT
    * NUM_ANSWER_PATTERNS
    * EXPECTED_VARIANTS_PER_BASE_TRANSCRIPT
) == 1280
assert EXPECTED_TRAIN_ROWS == EXPECTED_ROWS - EXPECTED_TEST_ROWS == 8960
assert len(ALL_AGREEMENT_CELLS) == (K + 1) ** 2 == 16
assert len(R_VALUES) == 10
assert tuple(Fraction(value) for value in R_EXACT_VALUES) == tuple(
    Fraction(numerator, 20) for numerator in range(1, 20, 2)
)
assert CONTROL_POSITIONAL_BIAS is False
assert ACTIVATION_STREAM == "resid_post"
assert ACTIVATION_TOKENS == "row_selected" and ACTIVATION_LAYERS == "all"
assert CAPTURE_CHECKPOINT_ROWS > 0
if RUN_GPU_CAPTURE and LOAD_COMPLETED_CAPTURE:
    raise ValueError("Choose either fresh/resumed capture or loading, not both.")
if RUN_ACTIVATION_PATCHING and RUN_GPU_CAPTURE:
    raise ValueError("Capture and causal patching must run in separate model-loading passes.")

capture_spec = CaptureSpec(
    logits_boundaries=("answer",),
    logits_scope="answer_surfaces",
    streams=(ACTIVATION_STREAM,),
    layers=ACTIVATION_LAYERS,
    tokens=ACTIVATION_TOKENS,
    every_decode_position=False,
)
metric_spec = MetricSpec(sequence_scores=False)

print({
    "model": MODEL_ID,
    "rows": EXPECTED_ROWS,
    "rows_per_reasoning_mode": EXPECTED_ROWS_PER_REASONING,
    "agreement_cells": len(ALL_AGREEMENT_CELLS),
    "train_rows_per_reasoning_mode": EXPECTED_TRAIN_ROWS_PER_REASONING,
    "test_rows_per_reasoning_mode": EXPECTED_TEST_ROWS_PER_REASONING,
    "activation_streams": capture_spec.streams,
    "activation_layers": capture_spec.layers,
    "activation_tokens": capture_spec.tokens,
    "gpu_capture_enabled": RUN_GPU_CAPTURE,
})

{'model': 'Qwen/Qwen3.5-9B', 'rows': 10240, 'rows_per_reasoning_mode': 5120, 'agreement_cells': 16, 'train_rows_per_reasoning_mode': 4480, 'test_rows_per_reasoning_mode': 640, 'activation_streams': ('resid_post',), 'activation_layers': 'all', 'activation_tokens': 'row_selected', 'gpu_capture_enabled': True}

## Generate labels and choose a leakage-safe split

The atomic sampling unit is a complete question schedule. A schedule contains eight
exhaustive report patterns, and every base transcript is replayed at all ten
reliabilities and both reasoning settings. Splitting individual rows would put nearly
identical replays in train and test.

The same eight complete schedules are held out in both reasoning modes. Selection uses
labels only—never activations, logits, completions, or model accuracy. A deterministic
50,000-subset search followed by one-swap local improvement ranks candidates by:

1. fewest missing tie cells;
2. smallest L1 distance between test and full-dataset agreement-cell proportions;
3. smallest worst-cell deviation;
4. greatest agreement-cell coverage;
5. schedule indices as a deterministic tie-breaker.

Once selected, all 20 reliability/reasoning variants of every base transcript stay in the
same partition. Thus no question schedule can cross from either test dataset into either
training dataset. The exact split and its audit are persisted before inference.

### What the probe labels mean

For one transcript, let $a_1,a_2\in\{0,1,2,3\}$ be the numbers of source reports that
candidate 1 and candidate 2 predict correctly. The notebook derives these labels without
consulting Qwen:

$$\Delta a=a_1-a_2,\qquad g(r)=\log\frac{r}{1-r},\qquad
z_{\mathrm{Bayes}}=\Delta a\,g(r).$$

`gain_abs` is $|g(r)|$, `reliability_sign` is $\mathbb{1}[r>1/2]$, and
`z_heuristic` is $\Delta a|g(r)|$. The last target deliberately removes the Bayesian sign
reversal below $r=1/2$, so comparing it with `z_bayes` asks whether the representation
contains the correct signed computation or merely "more agreement means more evidence."

Each target gets a separate probe. Tie rows have $\Delta a=z_{\mathrm{Bayes}}=
z_{\mathrm{heuristic}}=0$, while their gain and reliability-sign labels remain informative.
This is why retaining all four tie constructions helps disentangle evidence balance from
reliability.

In [ ]:
def atomic_write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True, allow_nan=False)
            handle.write("\n")
        os.replace(temporary_name, path)
    finally:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)


def atomic_write_jsonl(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            for row in rows:
                handle.write(json.dumps(row, sort_keys=True, allow_nan=False) + "\n")
        os.replace(temporary_name, path)
    finally:
        if os.path.exists(temporary_name):
            os.unlink(temporary_name)


def row_reliability_exact(row: dict[str, object]) -> str:
    values = tuple(str(value) for value in row["reliabilities_exact"])
    assert len(values) == K and len(set(values)) == 1
    return values[0]


def base_transcript_key(row: dict[str, object]) -> tuple[int, int]:
    return int(row["question_set_index"]), int(row["answer_pattern_index"])


def agreement_cell(row: dict[str, object]) -> tuple[int, int]:
    return (
        int(row["total_agreement_candidate_1"]),
        int(row["total_agreement_candidate_2"]),
    )


def target_fields(row: dict[str, object]) -> dict[str, float | int]:
    reliability = Fraction(row_reliability_exact(row))
    assert 0 < reliability < 1 and reliability != Fraction(1, 2)
    gain = math.log(float(reliability / (1 - reliability)))
    delta_a = (
        int(row["total_agreement_candidate_1"])
        - int(row["total_agreement_candidate_2"])
    )
    return {
        "agreement_c1": int(row["total_agreement_candidate_1"]),
        "agreement_c2": int(row["total_agreement_candidate_2"]),
        "delta_a": float(delta_a),
        "gain": float(gain),
        "gain_abs": float(abs(gain)),
        "reliability_sign": int(reliability > Fraction(1, 2)),
        "z_bayes": float(delta_a * gain),
        "z_heuristic": float(delta_a * abs(gain)),
    }


def token_offsets(
    *, text: str, input_ids: list[int], tokenizer
) -> list[tuple[int, int]]:
    encoded = tokenizer(
        text, add_special_tokens=False, return_offsets_mapping=True
    )
    encoded_ids = [int(value) for value in encoded["input_ids"]]
    if encoded_ids != input_ids:
        raise ValueError("Offset-tokenization IDs differ from runtime chat-template IDs.")
    return [(int(start), int(end)) for start, end in encoded["offset_mapping"]]


def prompt_token_sites(row: dict[str, object], tokenizer) -> dict[str, list[int]]:
    text = str(row["serialized_prompt"])
    input_ids = [int(value) for value in row["input_ids"]]
    offsets = token_offsets(text=text, input_ids=input_ids, tokenizer=tokenizer)

    def indices_for_span(start: int, end: int) -> list[int]:
        indices = [
            index for index, (token_start, token_end) in enumerate(offsets)
            if token_end > start and token_start < end
        ]
        if not indices:
            raise ValueError(f"No tokens overlap character span [{start}, {end}).")
        return indices

    domain = re.search(r"^DOMAIN:.*\.$", text, flags=re.MULTILINE)
    reliability = re.search(
        r"^The observed SOURCE report equals.*\.$", text, flags=re.MULTILINE
    )
    reliability_values = re.search(
        r"\br=([0-9.]+).*?\b1-r=([0-9.]+)",
        reliability.group(0) if reliability else "",
    )
    report_matches = list(re.finditer(
        r"^SOURCE reported (YES|NO)\.$", text, flags=re.MULTILINE
    ))
    if len(report_matches) != K:
        raise ValueError(f"Expected {K} observed-report markers, found {len(report_matches)}.")
    question_boundary = re.search(r"\n\nQUESTION:\n", text)
    candidate_question = re.search(
        r"Given all observations, which has larger posterior probability: "
        r"s=(\d+) or s=(\d+)\?\n",
        text,
    )
    assistant_turn = re.search(
        r"<\|im_end\|>\n<\|im_start\|>assistant\n<think>\n\n</think>\n\n$",
        text,
    )
    if any(match is None for match in (
        domain, reliability, reliability_values, question_boundary,
        candidate_question, assistant_turn,
    )):
        raise ValueError("A preregistered semantic token boundary was not found.")
    assert domain and reliability and reliability_values
    assert question_boundary and candidate_question and assistant_turn

    reliability_base = reliability.start()
    r_assignment_start = reliability_base + reliability_values.start(0)
    r_assignment_end = reliability_base + reliability_values.end(1)
    one_minus_start = reliability_base + reliability_values.start(0) + (
        reliability_values.group(0).index("1-r=")
    )
    one_minus_end = reliability_base + reliability_values.end(2)
    sites = {
        # Period/newline neighborhoods are represented as small mean-pooled spans.
        "domain_boundary": indices_for_span(domain.end() - 2, domain.end() + 1),
        "reliability_rule_boundary": indices_for_span(
            reliability.end() - 2, reliability.end() + 1
        ),
        "reliability_r_value": indices_for_span(r_assignment_start, r_assignment_end),
        "reliability_one_minus_r_value": indices_for_span(one_minus_start, one_minus_end),
        **{
            f"report_{index}_answer": indices_for_span(
                match.start(1), match.end(1)
            )
            for index, match in enumerate(report_matches, start=1)
        },
        "observation_question_boundary": indices_for_span(
            question_boundary.start(), question_boundary.end()
        ),
        "candidate_1_value": indices_for_span(
            candidate_question.start(1) - len("s="), candidate_question.end(1)
        ),
        "candidate_2_value": indices_for_span(
            candidate_question.start(2) - len("s="), candidate_question.end(2)
        ),
        "candidate_question_boundary": indices_for_span(
            candidate_question.end() - 2, candidate_question.end()
        ),
        "assistant_turn_boundary": indices_for_span(
            assistant_turn.start(), assistant_turn.end()
        ),
        "final_prompt": [len(input_ids) - 1],
    }
    assert set(sites) == set(PROBE_SITES) - {"answer_line"}
    assert all(
        positions and all(0 <= position < len(input_ids) for position in positions)
        for positions in sites.values()
    )
    return sites


def unique_base_rows(rows: list[dict[str, object]]) -> dict[tuple[int, int], dict[str, object]]:
    grouped: dict[tuple[int, int], list[dict[str, object]]] = defaultdict(list)
    for row in rows:
        grouped[base_transcript_key(row)].append(row)
    result = {}
    for key, variants in grouped.items():
        if len(variants) != EXPECTED_VARIANTS_PER_BASE_TRANSCRIPT:
            raise ValueError(f"Base transcript {key} has {len(variants)} variants.")
        if {
            (row_reliability_exact(row), bool(row["reasoning"])) for row in variants
        } != set(
            (reliability, reasoning)
            for reliability in R_EXACT_VALUES
            for reasoning in REASONING_VALUES
        ):
            raise ValueError(f"Base transcript {key} is missing a paired factorial cell.")
        invariant_fields = (
            "membership_sets", "observed_reports", "candidate_1", "candidate_2",
            "total_agreement_candidate_1", "total_agreement_candidate_2",
        )
        reference = variants[0]
        assert all(
            row[field] == reference[field]
            for row in variants for field in invariant_fields
        )
        result[key] = reference
    return result


def choose_test_schedules(rows: list[dict[str, object]]) -> tuple[tuple[int, ...], dict[str, object]]:
    base_rows = unique_base_rows(rows)
    schedule_counts = {
        schedule: Counter(
            agreement_cell(row)
            for (row_schedule, _), row in base_rows.items()
            if row_schedule == schedule
        )
        for schedule in range(NUM_QUESTION_SETS)
    }
    global_counts = sum(schedule_counts.values(), Counter())
    assert sum(global_counts.values()) == NUM_QUESTION_SETS * NUM_ANSWER_PATTERNS

    full_total = sum(global_counts.values())

    def evaluate(selected: tuple[int, ...]):
        test_counts = sum((schedule_counts[index] for index in selected), Counter())
        test_total = sum(test_counts.values())
        missing_ties = sorted(TIE_CELLS - set(test_counts))
        deviations = [
            abs(test_counts[cell] / test_total - global_counts[cell] / full_total)
            for cell in ALL_AGREEMENT_CELLS
        ]
        score = (
            len(missing_ties),
            sum(deviations),
            max(deviations),
            -len(test_counts),
            selected,
        )
        return score, test_counts, missing_ties

    rng = np.random.default_rng(SEED + 1)
    sampled = {
        tuple(sorted(int(value) for value in rng.choice(
            NUM_QUESTION_SETS, size=TEST_SCHEDULE_COUNT, replace=False
        )))
        for _ in range(SPLIT_SEARCH_CANDIDATES)
    }
    sampled.add(tuple(range(TEST_SCHEDULE_COUNT)))
    globally_available_ties = TIE_CELLS & set(global_counts)
    if PREFER_ALL_TIE_CELLS_IN_TEST:
        # If each tie cell occurs anywhere, one witness schedule per cell gives a
        # cover of size at most four; fill deterministically to eight schedules.
        tie_cover = set()
        covered_ties = set()
        for tie_cell in sorted(globally_available_ties):
            if tie_cell in covered_ties:
                continue
            witness = next(
                schedule for schedule in range(NUM_QUESTION_SETS)
                if schedule_counts[schedule][tie_cell] > 0
            )
            tie_cover.add(witness)
            covered_ties.update(
                TIE_CELLS & set(schedule_counts[witness])
            )
        tie_cover.update(
            schedule for schedule in range(NUM_QUESTION_SETS)
            if len(tie_cover) < TEST_SCHEDULE_COUNT
        )
        sampled.add(tuple(sorted(tie_cover)))
    selected = min(sampled, key=lambda candidate: evaluate(candidate)[0])

    # Deterministic one-swap refinement of the best sampled subset.
    while True:
        current_score = evaluate(selected)[0]
        selected_set = set(selected)
        neighbors = (
            tuple(sorted(selected_set - {removed} | {added}))
            for removed in selected
            for added in range(NUM_QUESTION_SETS)
            if added not in selected_set
        )
        improved = min(neighbors, key=lambda candidate: evaluate(candidate)[0])
        if evaluate(improved)[0] >= current_score:
            break
        selected = improved

    score, test_counts, missing_ties = evaluate(selected)
    audit = {
        "reasoning_modes_share_schedule_partition": True,
        "random_subsets_requested": SPLIT_SEARCH_CANDIDATES,
        "unique_subsets_evaluated": len(sampled),
        "selection_rule": [
            "fewest_missing_tie_cells",
            "minimum_l1_cell_proportion_distance",
            "minimum_worst_cell_proportion_deviation",
            "maximum_number_of_covered_cells",
            "lexicographic_schedule_indices",
        ],
        "selected_test_schedules": list(selected),
        "score": {
            "missing_tie_cell_count": score[0],
            "l1_cell_proportion_distance": score[1],
            "worst_cell_proportion_deviation": score[2],
            "covered_cell_count": -score[3],
        },
        "missing_tie_cells": [list(cell) for cell in missing_ties],
        "globally_available_tie_cells": [
            list(cell) for cell in sorted(globally_available_ties)
        ],
        "globally_unavailable_tie_cells": [
            list(cell) for cell in sorted(TIE_CELLS - globally_available_ties)
        ],
        "test_base_cell_counts": {
            f"{cell[0]},{cell[1]}": test_counts[cell] for cell in ALL_AGREEMENT_CELLS
        },
        "all_base_cell_counts": {
            f"{cell[0]},{cell[1]}": global_counts[cell] for cell in ALL_AGREEMENT_CELLS
        },
    }
    return selected, audit

In [ ]:
# Tokenizer loading and dataset construction are CPU-only. No Qwen weights are loaded here.
hf_config = AutoConfig.from_pretrained(
    MODEL_ID,
    revision=MODEL_REVISION,
    trust_remote_code=False,
    local_files_only=LOCAL_FILES_ONLY,
)
hf_text_config = getattr(hf_config, "text_config", hf_config)
if (
    int(hf_text_config.num_hidden_layers) != NUM_LAYERS
    or int(hf_text_config.hidden_size) != HIDDEN_SIZE
    or hf_text_config.dtype != torch.bfloat16
):
    raise ValueError(
        "The checkpoint text configuration does not match the layer/width/BF16 "
        "assumptions used by the activation-storage preflight."
    )
processor = AutoProcessor.from_pretrained(
    MODEL_ID,
    revision=MODEL_REVISION,
    trust_remote_code=False,
    local_files_only=LOCAL_FILES_ONLY,
)
tokenizer = getattr(processor, "tokenizer", processor)
tokenizer_binding = TokenizerBinding(tokenizer, enable_thinking=False)

environments = tuple(
    NoisyChannelBayesianEnvironment(
        n=N,
        k=K,
        r_values=reliability,
        control_positional_bias=CONTROL_POSITIONAL_BIAS,
    )
    for reliability in R_VALUES
)
probes = tuple(
    XVsYPosteriorProbe(
        x=X,
        y=Y,
        reasoning=reasoning,
        allow_same=ALLOW_SAME,
        call_layout="conversation",
    )
    for reasoning in REASONING_VALUES
)

raw_dataset = TranscriptDatasetGenerator(
    environment=environments,
    question=RandomSubsetQuestion(
        subset_size=SUBSET_SIZE, replacement=False, sort=True
    ),
    probe=probes,
    tokenizer_binding=tokenizer_binding,
    system_prompt=SystemPrompt(SYSTEM_PROMPT_TEXT),
    seed=SEED,
).generate(num_question_sets=NUM_QUESTION_SETS)
assert len(raw_dataset) == EXPECTED_ROWS
assert raw_dataset.manifest["presentations_per_scenario"] == 1
assert raw_dataset.manifest["control_positional_bias"] is False

raw_rows = [dict(row) for row in raw_dataset]
selected_test_schedules, split_audit = choose_test_schedules(raw_rows)
test_schedule_set = set(selected_test_schedules)

enriched_rows = []
for source in raw_rows:
    row = dict(source)
    row.update(target_fields(row))
    row["base_transcript_id"] = (
        f"schedule_{int(row['question_set_index']):02d}_"
        f"pattern_{int(row['answer_pattern_index']):02d}"
    )
    row["split"] = (
        "test" if int(row["question_set_index"]) in test_schedule_set else "train"
    )
    row["reasoning_mode"] = MODE_NAMES[bool(row["reasoning"])]
    row["prompt_token_sites"] = prompt_token_sites(row, tokenizer)
    prompt_capture_indices = sorted({
        position
        for positions in row["prompt_token_sites"].values()
        for position in positions
    })
    row["activation_token_selector"] = [
        *prompt_capture_indices,
        *range(-ANSWER_TAIL_TOKENS, 0),
    ]
    enriched_rows.append(row)

# The two prompt variants intentionally have equal token length for every paired
# schedule/pattern/reliability cell. Semantic sites are still located independently:
# equal total length does not imply that internal locations share absolute indices.
paired_prompt_lengths: dict[tuple[int, int, str], dict[bool, int]] = defaultdict(dict)
for row in enriched_rows:
    pair_key = (
        int(row["question_set_index"]),
        int(row["answer_pattern_index"]),
        row_reliability_exact(row),
    )
    paired_prompt_lengths[pair_key][bool(row["reasoning"])] = len(row["input_ids"])
if len(paired_prompt_lengths) != NUM_QUESTION_SETS * NUM_ANSWER_PATTERNS * len(R_VALUES):
    raise ValueError("Prompt-length audit has the wrong number of paired cells.")
prompt_length_mismatches = {
    key: lengths for key, lengths in paired_prompt_lengths.items()
    if set(lengths) != set(REASONING_VALUES)
    or lengths[False] != lengths[True]
}
if prompt_length_mismatches:
    examples = list(prompt_length_mismatches.items())[:5]
    raise ValueError(
        "Reasoning-off/on prompts are not token-length matched; examples="
        f"{examples}"
    )

train_rows = [row for row in enriched_rows if row["split"] == "train"]
test_rows = [row for row in enriched_rows if row["split"] == "test"]
assert len(train_rows) == EXPECTED_TRAIN_ROWS
assert len(test_rows) == EXPECTED_TEST_ROWS
assert {int(row["question_set_index"]) for row in train_rows}.isdisjoint(
    int(row["question_set_index"]) for row in test_rows
)
assert {str(row["base_transcript_id"]) for row in train_rows}.isdisjoint(
    str(row["base_transcript_id"]) for row in test_rows
)
for reasoning in REASONING_VALUES:
    mode_train = [row for row in train_rows if bool(row["reasoning"]) is reasoning]
    mode_test = [row for row in test_rows if bool(row["reasoning"]) is reasoning]
    assert len(mode_train) == EXPECTED_TRAIN_ROWS_PER_REASONING
    assert len(mode_test) == EXPECTED_TEST_ROWS_PER_REASONING
    assert {int(row["question_set_index"]) for row in mode_train}.isdisjoint(
        int(row["question_set_index"]) for row in mode_test
    )
if PREFER_ALL_TIE_CELLS_IN_TEST:
    globally_available_ties = TIE_CELLS & {
        agreement_cell(row) for row in enriched_rows
    }
    assert globally_available_ties <= {
        agreement_cell(row) for row in test_rows
    }

# Full prompt prefixes must also be distinct across the schedule split.
train_prompt_hashes = {
    hashlib.sha256(bytes().join(int(token).to_bytes(4, "little") for token in row["input_ids"])).hexdigest()
    for row in train_rows
}
test_prompt_hashes = {
    hashlib.sha256(bytes().join(int(token).to_bytes(4, "little") for token in row["input_ids"])).hexdigest()
    for row in test_rows
}
assert train_prompt_hashes.isdisjoint(test_prompt_hashes)

dataset_manifest = {
    **raw_dataset.manifest,
    "notebook": "16_noisy_channel_bayesian_activation_patching.ipynb",
    "model_id": MODEL_ID,
    "model_revision": MODEL_REVISION,
    "expected_row_count": EXPECTED_ROWS,
    "split_policy": split_audit,
    "train_row_count": len(train_rows),
    "test_row_count": len(test_rows),
    "row_count_per_reasoning_mode": EXPECTED_ROWS_PER_REASONING,
    "train_row_count_per_reasoning_mode": EXPECTED_TRAIN_ROWS_PER_REASONING,
    "test_row_count_per_reasoning_mode": EXPECTED_TEST_ROWS_PER_REASONING,
    "reasoning_modes_share_schedule_partition": True,
    "paired_reasoning_prompts_have_equal_token_length": True,
    "activation_capture": {
        "stream": ACTIVATION_STREAM,
        "layers": ACTIVATION_LAYERS,
        "tokens": ACTIVATION_TOKENS,
        "num_layers": NUM_LAYERS,
        "hidden_size": HIDDEN_SIZE,
        "dtype": "bfloat16",
    },
}
dataset = TranscriptDataset(
    enriched_rows, manifest=dataset_manifest, experiment_dir=DATASET_ROOT
)
dataset.save(DATASET_ROOT)
datasets_by_reasoning = {}
for reasoning in REASONING_VALUES:
    mode_rows = [
        dict(row) for row in enriched_rows if bool(row["reasoning"]) is reasoning
    ]
    mode_root = DATASET_ROOT / MODE_NAMES[reasoning]
    mode_manifest = {
        **dataset_manifest,
        "reasoning": reasoning,
        "reasoning_mode": MODE_NAMES[reasoning],
        "expected_row_count": EXPECTED_ROWS_PER_REASONING,
        "train_row_count": EXPECTED_TRAIN_ROWS_PER_REASONING,
        "test_row_count": EXPECTED_TEST_ROWS_PER_REASONING,
    }
    mode_dataset = TranscriptDataset(
        mode_rows, manifest=mode_manifest, experiment_dir=mode_root
    )
    mode_dataset.save(mode_root)
    datasets_by_reasoning[reasoning] = mode_dataset

dataset_split_fingerprint = hashlib.sha256(json.dumps(
    [(str(row["row_id"]), str(row["split"])) for row in enriched_rows],
    separators=(",", ":"),
).encode()).hexdigest()
probe_plan = {
    "schema_version": 1,
    "dataset_split_fingerprint": dataset_split_fingerprint,
    "activation_run_ids": {
        MODE_NAMES[reasoning]: RUN_IDS[reasoning]
        for reasoning in REASONING_VALUES
    },
    "model_revision": MODEL_REVISION,
    "activation_stream": ACTIVATION_STREAM,
    "activation_tokens": ACTIVATION_TOKENS,
    "reasoning_modes": [MODE_NAMES[value] for value in REASONING_VALUES],
    "separate_probe_per_reasoning_mode": True,
    "sites": list(PROBE_SITES),
    "continuous_targets": list(CONTINUOUS_PROBE_TARGETS),
    "binary_targets": list(BINARY_PROBE_TARGETS),
    "layers": list(PROBE_LAYERS),
    "ridge_alphas": list(RIDGE_ALPHAS),
    "ridge_solver": RIDGE_SOLVER,
    "ridge_tolerance": RIDGE_TOL,
    "ridge_max_iterations": RIDGE_MAX_ITER,
    "logistic_c_values": list(LOGISTIC_C_VALUES),
    "cv_folds": PROBE_CV_FOLDS,
    "top_k_layers": PROBE_TOP_K_LAYERS,
    "minimum_generated_site_coverage": MIN_GENERATED_SITE_COVERAGE,
    "minimum_probe_train_rows": MIN_PROBE_TRAIN_ROWS,
}
PROBE_CONFIG_FINGERPRINT = hashlib.sha256(json.dumps(
    probe_plan, sort_keys=True, separators=(",", ":"), allow_nan=False
).encode()).hexdigest()
probe_plan["probe_config_fingerprint"] = PROBE_CONFIG_FINGERPRINT
atomic_write_json(PROBE_ROOT / "probe_plan.json", probe_plan)

split_assignments = [
    {
        "row_id": row["row_id"],
        "base_transcript_id": row["base_transcript_id"],
        "question_set_index": row["question_set_index"],
        "answer_pattern_index": row["answer_pattern_index"],
        "reliability_exact": row_reliability_exact(row),
        "reasoning": row["reasoning"],
        "reasoning_mode": row["reasoning_mode"],
        "agreement_c1": row["agreement_c1"],
        "agreement_c2": row["agreement_c2"],
        "split": row["split"],
    }
    for row in enriched_rows
]
atomic_write_json(SPLIT_ROOT / "split_manifest.json", split_audit)
atomic_write_jsonl(SPLIT_ROOT / "split_assignments.jsonl", split_assignments)

print({
    "dataset_rows": len(dataset),
    "train_rows": len(train_rows),
    "test_rows": len(test_rows),
    "test_schedules": selected_test_schedules,
    "missing_test_tie_cells": split_audit["missing_tie_cells"],
    "test_cell_coverage": split_audit["score"]["covered_cell_count"],
})

### Split audit

The eight held-out schedules contribute 64 base transcripts and are selected to balance all
16 agreement cells. They cover every tie construction that occurs anywhere in the generated
schedules (normally all four). The tables below show
combined-mode counts after expanding each base transcript across ten reliabilities and two
reasoning modes. The schedule partition itself is identical in both modes.

In [24]:
def expanded_cell_table(rows: list[dict[str, object]], split: str) -> pd.DataFrame:
    counts = Counter(agreement_cell(row) for row in rows if row["split"] == split)
    return pd.DataFrame(
        [[counts[(a1, a2)] for a2 in range(K + 1)] for a1 in range(K + 1)],
        index=pd.Index(range(K + 1), name="agreement C1"),
        columns=pd.Index(range(K + 1), name="agreement C2"),
    )


train_cell_table = expanded_cell_table(enriched_rows, "train")
test_cell_table = expanded_cell_table(enriched_rows, "test")
display(Markdown("#### Training rows"))
display(train_cell_table)
display(Markdown("#### Test rows"))
display(test_cell_table)

tie_test_counts = {
    cell: int(test_cell_table.loc[cell[0], cell[1]]) for cell in sorted(TIE_CELLS)
}
globally_available_ties = TIE_CELLS & {
    agreement_cell(row) for row in enriched_rows
}
assert all(tie_test_counts[cell] > 0 for cell in globally_available_ties)
print("Test tie-cell counts:", tie_test_counts)

#### Training rows

agreement C2    0     1     2    3
agreement C1
0             160   320   460  180
1             320  1400  1180  460
2             460  1180  1400  320
3             180   460   320  160

#### Test rows

agreement C2   0    1    2   3
agreement C1
0             20   60   60  20
1             60  180  180  60
2             60  180  180  60
3             20   60   60  20

Test tie-cell counts: {(0, 0): 20, (1, 1): 180, (2, 2): 180, (3, 3): 20}

## Storage preflight

One BF16 residual vector costs $4096\times2$ bytes. Across 32 layers this is 256 KiB per
stored token per row. The sparse selector stores only the union of the semantic prompt
spans plus the last `ANSWER_TAIL_TOKENS` completion positions. The reasoning-on generation
may contain up to 4,096 tokens, but unselected activations are never written to disk.

The preflight uses every row's requested selector size as a conservative upper bound;
prompt/tail overlaps are de-duplicated during capture. It runs before constructing `QwenRunner`
and refuses to load the model if either the 90%-of-budget payload limit or the free-disk
reserve would be violated.

Safetensors headers and JSON manifests are not included in the tensor-payload formula, which
is why only 90% of the nominal 160 GiB budget is assignable to tensor payloads.

In [25]:
GIB = 1024**3
selected_token_counts = [
    len(row["activation_token_selector"]) for row in enriched_rows
]
worst_case_token_total = sum(selected_token_counts)
bytes_per_token_per_row = NUM_LAYERS * HIDDEN_SIZE * ACTIVATION_BYTES_PER_ELEMENT
worst_case_activation_bytes = worst_case_token_total * bytes_per_token_per_row
worst_case_activation_gib = worst_case_activation_bytes / GIB
allowed_payload_gib = (
    ACTIVATION_STORAGE_BUDGET_GIB * ACTIVATION_BUDGET_SAFETY_FRACTION
)
existing_activation_bytes = sum(
    path.stat().st_size
    for run_dir in RUN_DIRS.values()
    for path in (run_dir / "activations").glob("*.safetensors")
)
free_disk_gib = shutil.disk_usage(EXPERIMENT_ROOT.parent).free / GIB
# Existing files under this exact run ID are overwritten atomically on a retry, so they
# count as reclaimable target capacity. The reserve covers one temporary row copy.
effective_target_capacity_gib = free_disk_gib + existing_activation_bytes / GIB

storage_preflight = {
    "minimum_prompt_tokens": min(len(row["input_ids"]) for row in enriched_rows),
    "maximum_prompt_tokens": max(len(row["input_ids"]) for row in enriched_rows),
    "mean_prompt_tokens": float(np.mean([len(row["input_ids"]) for row in enriched_rows])),
    "maximum_completion_tokens_by_reasoning": {
        MODE_NAMES[reasoning]: MAX_COMPLETION_TOKENS_BY_REASONING[reasoning]
        for reasoning in REASONING_VALUES
    },
    "minimum_selected_activation_positions": min(selected_token_counts),
    "maximum_selected_activation_positions": max(selected_token_counts),
    "mean_selected_activation_positions": float(np.mean(selected_token_counts)),
    "bytes_per_token_across_saved_layers": bytes_per_token_per_row,
    "worst_case_activation_payload_gib": worst_case_activation_gib,
    "allowed_activation_payload_gib": allowed_payload_gib,
    "existing_activation_files_gib": existing_activation_bytes / GIB,
    "free_disk_gib_before_capture": free_disk_gib,
    "effective_target_capacity_gib": effective_target_capacity_gib,
    "required_free_disk_reserve_gib": MIN_FREE_DISK_AFTER_CAPTURE_GIB,
}
display(storage_preflight)

assert worst_case_activation_gib <= allowed_payload_gib, (
    "Sparse activation payload exceeds the safety-adjusted budget. Reduce selected "
    "token spans or the factorial before loading Qwen."
)
assert effective_target_capacity_gib >= (
    worst_case_activation_gib + MIN_FREE_DISK_AFTER_CAPTURE_GIB
), (
    "Insufficient current free disk for the worst-case activation payload plus reserve."
)
atomic_write_json(MODEL_ROOT / "storage_preflight.json", storage_preflight)

{'minimum_prompt_tokens': 523,
 'maximum_prompt_tokens': 523,
 'mean_prompt_tokens': 523.0,
 'maximum_completion_tokens_by_reasoning': {'reasoning_off': 64,
  'reasoning_on': 4096},
 'minimum_selected_activation_positions': 57,
 'maximum_selected_activation_positions': 57,
 'mean_selected_activation_positions': 57.0,
 'bytes_per_token_across_saved_layers': 262144,
 'worst_case_activation_payload_gib': 142.5,
 'allowed_activation_payload_gib': 144.0,
 'existing_activation_files_gib': 0.0,
 'free_disk_gib_before_capture': 188.0024070739746,
 'effective_target_capacity_gib': 188.0024070739746,
 'required_free_disk_reserve_gib': 25.0}

## GPU capture — deliberately gated

`RUN_GPU_CAPTURE=True` performs one continuous generation per row, then teacher-forces the
exact prompt plus generated sequence and saves `resid_post` for only the selected semantic
positions at all 32 layers. Capture batch size is one. Candidate answer logits are stored as two JSON floats;
no full-vocabulary logit tensor is persisted.

The custom runner is used for generation/capture because it already provides atomic
per-row safetensors and exact answer-boundary bookkeeping. The notebook calls it on
contiguous eight-row prefixes, making `results.jsonl` a durable prefix checkpoint. A
fully completed run can be loaded without recomputation; after interruption, at most the
unfinished checkpoint needs to be regenerated and recaptured. TransformerLens's
`TransformerBridge` is used later for interventions. Before any patch is accepted, the
notebook checks that an unpatched bridge forward reproduces the runner's candidate margin.

In [26]:
RESULT_IDENTITY_FIELDS = (
    "row_id",
    "question_set_index",
    "answer_pattern_index",
    "reliabilities_exact",
    "reasoning",
    "reasoning_mode",
    "split",
    "base_transcript_id",
    "agreement_c1",
    "agreement_c2",
    "delta_a",
    "gain",
    "gain_abs",
    "reliability_sign",
    "z_bayes",
    "z_heuristic",
    "serialized_prompt",
    "input_ids",
    "prompt_token_sites",
    "activation_token_selector",
)


def validate_saved_rows_against_dataset(
    rows: list[dict[str, object]], *, reasoning: bool, require_complete: bool
) -> None:
    configured_rows = list(datasets_by_reasoning[reasoning])
    if len(rows) > len(configured_rows):
        raise ValueError("Saved results are longer than the configured dataset.")
    if require_complete and len(rows) != len(configured_rows):
        raise ValueError("Saved results are not a complete configured dataset.")
    for index, (saved, configured) in enumerate(
        zip(rows, configured_rows, strict=False)
    ):
        for field in RESULT_IDENTITY_FIELDS:
            saved_value = json.dumps(saved.get(field), sort_keys=True, allow_nan=False)
            configured_value = json.dumps(
                configured.get(field), sort_keys=True, allow_nan=False
            )
            if saved_value != configured_value:
                raise ValueError(
                    f"Saved row {index} differs from the configured dataset at "
                    f"{field!r}; refusing to mix stale captures or split labels."
                )


def validate_run_manifest_configuration(
    manifest: dict[str, object], *, reasoning: bool
) -> None:
    if manifest.get("model", {}).get("model_name_or_path") != MODEL_ID:
        raise ValueError("Saved run belongs to a different model.")
    if manifest.get("model", {}).get("revision") != MODEL_REVISION:
        raise ValueError("Saved run belongs to a different model revision.")
    execution = manifest.get("execution", {})
    saved_capture = execution.get("capture", {})
    expected_capture = {
        "streams": list(capture_spec.streams),
        "layers": capture_spec.layers,
        "tokens": capture_spec.tokens,
    }
    actual_capture = {
        "streams": saved_capture.get("streams"),
        "layers": saved_capture.get("layers"),
        "tokens": saved_capture.get("tokens"),
    }
    if actual_capture != expected_capture:
        raise ValueError("Saved run uses a different activation-capture configuration.")
    if (
        execution.get("max_completion_tokens")
        != MAX_COMPLETION_TOKENS_BY_REASONING[reasoning]
    ):
        raise ValueError("Saved run uses a different completion-token cap.")


def load_completed_run(reasoning: bool) -> TranscriptDataset:
    run_dir = RUN_DIRS[reasoning]
    run_manifest_path = run_dir / "run_manifest.json"
    if not run_manifest_path.exists():
        raise FileNotFoundError(
            f"No completed run at {run_manifest_path}. Run capture first."
        )
    manifest = json.loads(run_manifest_path.read_text(encoding="utf-8"))
    if manifest.get("row_count") != EXPECTED_ROWS_PER_REASONING:
        raise ValueError("Saved reasoning-mode run has the wrong row count.")
    validate_run_manifest_configuration(manifest, reasoning=reasoning)
    results_path = run_dir / str(manifest.get("results_file", "results.jsonl"))
    rows = [
        json.loads(line)
        for line in results_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    validate_saved_rows_against_dataset(
        rows, reasoning=reasoning, require_complete=True
    )
    return TranscriptDataset(rows, manifest=manifest, experiment_dir=MODEL_ROOT)


def completed_capture_prefix_length(reasoning: bool) -> int:
    # Validate and return the durable contiguous prefix in results.jsonl.

    run_dir = RUN_DIRS[reasoning]
    results_path = run_dir / "results.jsonl"
    if not results_path.exists():
        return 0
    rows = [
        json.loads(line)
        for line in results_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    validate_saved_rows_against_dataset(
        rows, reasoning=reasoning, require_complete=False
    )
    run_manifest_path = run_dir / "run_manifest.json"
    if run_manifest_path.exists():
        validate_run_manifest_configuration(
            json.loads(run_manifest_path.read_text(encoding="utf-8")),
            reasoning=reasoning,
        )
    for row in rows:
        relative = row.get("activation_path")
        if not isinstance(relative, str) or not (run_dir / relative).is_file():
            raise FileNotFoundError(
                f"Checkpointed row {row['row_id']} is missing its activation file."
            )
    return len(rows)


def capture_checkpoint_ends(durable_rows: int) -> tuple[int, ...]:
    if not 0 <= durable_rows <= EXPECTED_ROWS_PER_REASONING:
        raise ValueError("Durable row count is outside the configured dataset.")
    ends = []
    cursor = durable_rows
    while cursor < EXPECTED_ROWS_PER_REASONING:
        cursor = min(
            cursor + CAPTURE_CHECKPOINT_ROWS, EXPECTED_ROWS_PER_REASONING
        )
        ends.append(cursor)
    return tuple(ends)


assert capture_checkpoint_ends(0)[0] == CAPTURE_CHECKPOINT_ROWS
assert capture_checkpoint_ends(EXPECTED_ROWS_PER_REASONING - 1) == (
    EXPECTED_ROWS_PER_REASONING,
)
assert capture_checkpoint_ends(EXPECTED_ROWS_PER_REASONING) == ()


results_by_reasoning: dict[bool, TranscriptDataset] = {}
results: TranscriptDataset | None = None
if RUN_GPU_CAPTURE and LOAD_COMPLETED_CAPTURE:
    raise ValueError("Choose either RUN_GPU_CAPTURE or LOAD_COMPLETED_CAPTURE, not both.")

if RUN_GPU_CAPTURE:
    # The preflight assertions above have already run. This is the first model-loading line.
    runner = QwenRunner(ModelConfig(
        model_name_or_path=MODEL_ID,
        revision=MODEL_REVISION,
        dtype=MODEL_DTYPE,
        device_map=DEVICE_MAP,
        local_files_only=LOCAL_FILES_ONLY,
    ))
    for reasoning in REASONING_VALUES:
        mode_name = MODE_NAMES[reasoning]
        mode_dataset = datasets_by_reasoning[reasoning]
        execution = ExecutionConfig(
            experiment_dir=MODEL_ROOT,
            run_id=RUN_IDS[reasoning],
            batch_size=COMPLETION_BATCH_SIZE,
            completion_batch_size=COMPLETION_BATCH_SIZE,
            capture_batch_size=CAPTURE_BATCH_SIZE,
            score_batch_size=SCORE_BATCH_SIZE,
            max_completion_tokens=MAX_COMPLETION_TOKENS_BY_REASONING[reasoning],
            resume=True,
            metrics=metric_spec,
            capture=capture_spec,
            completion_mtp=SGLangMTPConfig(enabled=ENABLE_MTP),
        )
        durable_rows = completed_capture_prefix_length(reasoning)
        print(
            datetime.now(timezone.utc).isoformat(),
            f"{mode_name}: starting/resuming after {durable_rows} durable rows",
        )
        dataset_rows = list(mode_dataset)
        checkpoint_ends = capture_checkpoint_ends(durable_rows)
        mode_results = (
            load_completed_run(reasoning)
            if durable_rows == EXPECTED_ROWS_PER_REASONING else None
        )
        for checkpoint_end in checkpoint_ends:
            prefix_dataset = TranscriptDataset(
                dataset_rows[:checkpoint_end],
                manifest=mode_dataset.manifest,
                experiment_dir=MODEL_ROOT,
            )
            mode_results = prefix_dataset.execute(runner, execution)
            if len(mode_results) != checkpoint_end:
                raise RuntimeError(
                    "Capture checkpoint did not finalize its complete prefix."
                )
            print(
                datetime.now(timezone.utc).isoformat(),
                f"{mode_name}: durable checkpoint "
                f"{checkpoint_end}/{EXPECTED_ROWS_PER_REASONING}",
            )
        if mode_results is None or len(mode_results) != EXPECTED_ROWS_PER_REASONING:
            raise RuntimeError(f"GPU capture ended without all {mode_name} rows.")
        results_by_reasoning[reasoning] = mode_results
    del runner
    gc.collect()
    torch.cuda.empty_cache()
elif LOAD_COMPLETED_CAPTURE:
    results_by_reasoning = {
        reasoning: load_completed_run(reasoning)
        for reasoning in ANALYSIS_REASONING_VALUES
    }
else:
    print(
        "GPU capture is paused. Set RUN_GPU_CAPTURE=True only when you are ready; "
        "after completion, use LOAD_COMPLETED_CAPTURE=True."
    )

if results_by_reasoning:
    result_by_id = {
        str(row["row_id"]): dict(row)
        for mode_results in results_by_reasoning.values()
        for row in mode_results
    }
    selected_rows = [
        row for row in enriched_rows
        if bool(row["reasoning"]) in results_by_reasoning
    ]
    results = TranscriptDataset(
        [result_by_id[str(row["row_id"])] for row in selected_rows],
        manifest={"schema_version": dataset.manifest["schema_version"]},
        experiment_dir=MODEL_ROOT,
    )

2026-09-04T18:22:36.582885+00:00 reasoning_off: starting/resuming after 0 durable rows

Loading weights:   0%|          | 0/760 [00:00<?, ?it/s]

2026-09-04T18:22:48.323411+00:00 reasoning_off: durable checkpoint 8/5120
2026-09-04T18:22:51.075599+00:00 reasoning_off: durable checkpoint 16/5120
2026-09-04T18:22:53.849645+00:00 reasoning_off: durable checkpoint 24/5120
2026-09-04T18:22:56.608261+00:00 reasoning_off: durable checkpoint 32/5120
2026-09-04T18:22:59.383397+00:00 reasoning_off: durable checkpoint 40/5120
2026-09-04T18:23:02.144852+00:00 reasoning_off: durable checkpoint 48/5120
2026-09-04T18:23:04.934209+00:00 reasoning_off: durable checkpoint 56/5120
2026-09-04T18:23:07.702390+00:00 reasoning_off: durable checkpoint 64/5120
2026-09-04T18:23:10.449252+00:00 reasoning_off: durable checkpoint 72/5120
2026-09-04T18:23:13.202125+00:00 reasoning_off: durable checkpoint 80/5120
2026-09-04T18:23:15.942162+00:00 reasoning_off: durable checkpoint 88/5120
2026-09-04T18:23:18.707987+00:00 reasoning_off: durable checkpoint 96/5120
2026-09-04T18:23:22.448448+00:00 reasoning_off: durable checkpoint 104/5120
2026-09-04T18:23:25.238983+00:00 reasoning_off: durable checkpoint 112/5120
2026-09-04T18:23:28.015838+00:00 reasoning_off: durable checkpoint 120/5120
2026-09-04T18:23:30.814240+00:00 reasoning_off: durable checkpoint 128/5120
2026-09-04T18:23:33.675512+00:00 reasoning_off: durable checkpoint 136/5120
2026-09-04T18:23:36.480575+00:00 reasoning_off: durable checkpoint 144/5120
2026-09-04T18:23:39.459398+00:00 reasoning_off: durable checkpoint 152/5120
2026-09-04T18:23:42.394342+00:00 reasoning_off: durable checkpoint 160/5120
2026-09-04T18:23:45.365903+00:00 reasoning_off: durable checkpoint 168/5120
2026-09-04T18:23:48.216938+00:00 reasoning_off: durable checkpoint 176/5120
2026-09-04T18:23:51.167368+00:00 reasoning_off: durable checkpoint 184/5120
2026-09-04T18:23:54.157562+00:00 reasoning_off: durable checkpoint 192/5120
2026-09-04T18:23:57.050140+00:00 reasoning_off: durable checkpoint 200/5120
2026-09-04T18:23:59.881745+00:00 reasoning_off: durable checkpoint 208/5120
2026-09-04T18:24:02.766136+00:00 reasoning_off: durable checkpoint 216/5120
2026-09-04T18:24:05.821525+00:00 reasoning_off: durable checkpoint 224/5120
2026-09-04T18:24:08.699524+00:00 reasoning_off: durable checkpoint 232/5120
2026-09-04T18:24:11.580106+00:00 reasoning_off: durable checkpoint 240/5120
2026-09-04T18:24:14.499099+00:00 reasoning_off: durable checkpoint 248/5120
2026-09-04T18:24:17.483211+00:00 reasoning_off: durable checkpoint 256/5120
2026-09-04T18:24:20.406343+00:00 reasoning_off: durable checkpoint 264/5120
2026-09-04T18:24:23.344604+00:00 reasoning_off: durable checkpoint 272/5120
2026-09-04T18:24:26.278636+00:00 reasoning_off: durable checkpoint 280/5120
2026-09-04T18:24:29.269068+00:00 reasoning_off: durable checkpoint 288/5120
2026-09-04T18:24:32.187369+00:00 reasoning_off: durable checkpoint 296/5120
2026-09-04T18:24:35.174286+00:00 reasoning_off: durable checkpoint 304/5120
2026-09-04T18:24:38.103523+00:00 reasoning_off: durable checkpoint 312/5120
2026-09-04T18:24:41.991528+00:00 reasoning_off: durable checkpoint 320/5120
2026-09-04T18:24:45.146183+00:00 reasoning_off: durable checkpoint 328/5120
2026-09-04T18:24:48.435132+00:00 reasoning_off: durable checkpoint 336/5120
2026-09-04T18:24:51.527833+00:00 reasoning_off: durable checkpoint 344/5120
2026-09-04T18:24:54.496746+00:00 reasoning_off: durable checkpoint 352/5120
2026-09-04T18:24:57.494765+00:00 reasoning_off: durable checkpoint 360/5120
2026-09-04T18:25:00.489886+00:00 reasoning_off: durable checkpoint 368/5120
2026-09-04T18:25:03.788799+00:00 reasoning_off: durable checkpoint 376/5120
2026-09-04T18:25:06.876661+00:00 reasoning_off: durable checkpoint 384/5120
2026-09-04T18:25:10.144150+00:00 reasoning_off: durable checkpoint 392/5120
2026-09-04T18:25:13.512266+00:00 reasoning_off: durable checkpoint 400/5120
2026-09-04T18:25:16.545819+00:00 reasoning_off: durable checkpoint 408/5120
2026-09-04T18:25:19.598630+00:00 reasoning_off: durable checkpoint 416/5120
2026-09-04T18:25:22.655094+00:00 reasoning_off: durable checkpoint 424/5120
2026-09-04T18:25:25.753857+00:00 reasoning_off: durable checkpoint 432/5120
2026-09-04T18:25:29.818498+00:00 reasoning_off: durable checkpoint 440/5120
2026-09-04T18:25:32.846445+00:00 reasoning_off: durable checkpoint 448/5120
2026-09-04T18:25:36.028866+00:00 reasoning_off: durable checkpoint 456/5120
2026-09-04T18:25:39.311928+00:00 reasoning_off: durable checkpoint 464/5120
2026-09-04T18:25:42.390585+00:00 reasoning_off: durable checkpoint 472/5120
2026-09-04T18:25:45.536239+00:00 reasoning_off: durable checkpoint 480/5120
2026-09-04T18:25:48.737714+00:00 reasoning_off: durable checkpoint 488/5120
2026-09-04T18:25:51.975455+00:00 reasoning_off: durable checkpoint 496/5120
2026-09-04T18:25:55.178951+00:00 reasoning_off: durable checkpoint 504/5120
2026-09-04T18:25:58.386457+00:00 reasoning_off: durable checkpoint 512/5120
2026-09-04T18:26:01.622504+00:00 reasoning_off: durable checkpoint 520/5120
2026-09-04T18:26:04.939508+00:00 reasoning_off: durable checkpoint 528/5120
2026-09-04T18:26:09.223331+00:00 reasoning_off: durable checkpoint 536/5120
2026-09-04T18:26:12.531109+00:00 reasoning_off: durable checkpoint 544/5120
2026-09-04T18:26:15.836718+00:00 reasoning_off: durable checkpoint 552/5120
2026-09-04T18:26:19.126044+00:00 reasoning_off: durable checkpoint 560/5120
2026-09-04T18:26:22.326954+00:00 reasoning_off: durable checkpoint 568/5120
2026-09-04T18:26:25.575579+00:00 reasoning_off: durable checkpoint 576/5120
2026-09-04T18:26:28.730077+00:00 reasoning_off: durable checkpoint 584/5120
2026-09-04T18:26:31.924151+00:00 reasoning_off: durable checkpoint 592/5120
2026-09-04T18:26:35.224701+00:00 reasoning_off: durable checkpoint 600/5120
2026-09-04T18:26:38.536774+00:00 reasoning_off: durable checkpoint 608/5120
2026-09-04T18:26:42.651105+00:00 reasoning_off: durable checkpoint 616/5120
2026-09-04T18:26:45.809564+00:00 reasoning_off: durable checkpoint 624/5120
2026-09-04T18:26:49.010328+00:00 reasoning_off: durable checkpoint 632/5120
2026-09-04T18:26:52.255663+00:00 reasoning_off: durable checkpoint 640/5120
2026-09-04T18:26:55.534795+00:00 reasoning_off: durable checkpoint 648/5120
2026-09-04T18:26:59.033435+00:00 reasoning_off: durable checkpoint 656/5120
2026-09-04T18:27:02.321422+00:00 reasoning_off: durable checkpoint 664/5120
2026-09-04T18:27:05.607358+00:00 reasoning_off: durable checkpoint 672/5120
2026-09-04T18:27:08.882681+00:00 reasoning_off: durable checkpoint 680/5120
2026-09-04T18:27:12.916834+00:00 reasoning_off: durable checkpoint 688/5120
2026-09-04T18:27:16.200880+00:00 reasoning_off: durable checkpoint 696/5120
2026-09-04T18:27:19.489158+00:00 reasoning_off: durable checkpoint 704/5120
2026-09-04T18:27:22.781365+00:00 reasoning_off: durable checkpoint 712/5120
2026-09-04T18:27:26.132291+00:00 reasoning_off: durable checkpoint 720/5120
2026-09-04T18:27:29.550724+00:00 reasoning_off: durable checkpoint 728/5120
2026-09-04T18:27:32.987482+00:00 reasoning_off: durable checkpoint 736/5120
2026-09-04T18:27:36.397988+00:00 reasoning_off: durable checkpoint 744/5120
2026-09-04T18:27:40.654967+00:00 reasoning_off: durable checkpoint 752/5120
2026-09-04T18:27:44.097812+00:00 reasoning_off: durable checkpoint 760/5120
2026-09-04T18:27:47.572116+00:00 reasoning_off: durable checkpoint 768/5120
2026-09-04T18:27:51.086583+00:00 reasoning_off: durable checkpoint 776/5120
2026-09-04T18:27:54.613085+00:00 reasoning_off: durable checkpoint 784/5120
2026-09-04T18:27:58.131367+00:00 reasoning_off: durable checkpoint 792/5120
2026-09-04T18:28:01.453910+00:00 reasoning_off: durable checkpoint 800/5120
2026-09-04T18:28:04.782397+00:00 reasoning_off: durable checkpoint 808/5120
2026-09-04T18:28:09.003980+00:00 reasoning_off: durable checkpoint 816/5120
2026-09-04T18:28:12.478756+00:00 reasoning_off: durable checkpoint 824/5120
2026-09-04T18:28:15.983218+00:00 reasoning_off: durable checkpoint 832/5120
2026-09-04T18:28:19.344027+00:00 reasoning_off: durable checkpoint 840/5120
2026-09-04T18:28:22.690514+00:00 reasoning_off: durable checkpoint 848/5120
2026-09-04T18:28:26.088747+00:00 reasoning_off: durable checkpoint 856/5120
2026-09-04T18:28:29.600887+00:00 reasoning_off: durable checkpoint 864/5120
2026-09-04T18:28:34.042795+00:00 reasoning_off: durable checkpoint 872/5120
2026-09-04T18:28:37.613183+00:00 reasoning_off: durable checkpoint 880/5120
2026-09-04T18:28:41.103776+00:00 reasoning_off: durable checkpoint 888/5120
2026-09-04T18:28:44.500379+00:00 reasoning_off: durable checkpoint 896/5120
2026-09-04T18:28:47.926250+00:00 reasoning_off: durable checkpoint 904/5120
2026-09-04T18:28:51.341917+00:00 reasoning_off: durable checkpoint 912/5120
2026-09-04T18:28:54.800477+00:00 reasoning_off: durable checkpoint 920/5120
2026-09-04T18:28:59.161834+00:00 reasoning_off: durable checkpoint 928/5120
2026-09-04T18:29:02.640574+00:00 reasoning_off: durable checkpoint 936/5120
2026-09-04T18:29:06.070973+00:00 reasoning_off: durable checkpoint 944/5120
2026-09-04T18:29:09.536421+00:00 reasoning_off: durable checkpoint 952/5120
2026-09-04T18:29:13.001935+00:00 reasoning_off: durable checkpoint 960/5120
2026-09-04T18:29:16.441164+00:00 reasoning_off: durable checkpoint 968/5120
2026-09-04T18:29:20.834545+00:00 reasoning_off: durable checkpoint 976/5120
2026-09-04T18:29:24.326729+00:00 reasoning_off: durable checkpoint 984/5120
2026-09-04T18:29:27.779437+00:00 reasoning_off: durable checkpoint 992/5120
2026-09-04T18:29:31.233200+00:00 reasoning_off: durable checkpoint 1000/5120
2026-09-04T18:29:34.762540+00:00 reasoning_off: durable checkpoint 1008/5120
2026-09-04T18:29:38.238997+00:00 reasoning_off: durable checkpoint 1016/5120
2026-09-04T18:29:42.778730+00:00 reasoning_off: durable checkpoint 1024/5120
2026-09-04T18:29:46.387713+00:00 reasoning_off: durable checkpoint 1032/5120
2026-09-04T18:29:50.102531+00:00 reasoning_off: durable checkpoint 1040/5120
2026-09-04T18:29:53.867785+00:00 reasoning_off: durable checkpoint 1048/5120
2026-09-04T18:29:57.516528+00:00 reasoning_off: durable checkpoint 1056/5120
2026-09-04T18:30:02.060502+00:00 reasoning_off: durable checkpoint 1064/5120
2026-09-04T18:30:05.771128+00:00 reasoning_off: durable checkpoint 1072/5120
2026-09-04T18:30:09.387743+00:00 reasoning_off: durable checkpoint 1080/5120
2026-09-04T18:30:12.927779+00:00 reasoning_off: durable checkpoint 1088/5120
2026-09-04T18:30:16.455418+00:00 reasoning_off: durable checkpoint 1096/5120
2026-09-04T18:30:20.003517+00:00 reasoning_off: durable checkpoint 1104/5120
2026-09-04T18:30:24.459039+00:00 reasoning_off: durable checkpoint 1112/5120
2026-09-04T18:30:28.041637+00:00 reasoning_off: durable checkpoint 1120/5120
2026-09-04T18:30:31.647202+00:00 reasoning_off: durable checkpoint 1128/5120
2026-09-04T18:30:35.305244+00:00 reasoning_off: durable checkpoint 1136/5120
2026-09-04T18:30:38.893107+00:00 reasoning_off: durable checkpoint 1144/5120
2026-09-04T18:30:43.401894+00:00 reasoning_off: durable checkpoint 1152/5120
2026-09-04T18:30:47.022924+00:00 reasoning_off: durable checkpoint 1160/5120
2026-09-04T18:30:50.662412+00:00 reasoning_off: durable checkpoint 1168/5120
2026-09-04T18:30:54.338975+00:00 reasoning_off: durable checkpoint 1176/5120
2026-09-04T18:30:58.033515+00:00 reasoning_off: durable checkpoint 1184/5120
2026-09-04T18:31:01.631416+00:00 reasoning_off: durable checkpoint 1192/5120
2026-09-04T18:31:06.221441+00:00 reasoning_off: durable checkpoint 1200/5120
2026-09-04T18:31:09.905735+00:00 reasoning_off: durable checkpoint 1208/5120
2026-09-04T18:31:13.564122+00:00 reasoning_off: durable checkpoint 1216/5120
2026-09-04T18:31:17.529841+00:00 reasoning_off: durable checkpoint 1224/5120
2026-09-04T18:31:22.453462+00:00 reasoning_off: durable checkpoint 1232/5120
2026-09-04T18:31:26.491089+00:00 reasoning_off: durable checkpoint 1240/5120
2026-09-04T18:31:30.485761+00:00 reasoning_off: durable checkpoint 1248/5120
2026-09-04T18:31:34.423262+00:00 reasoning_off: durable checkpoint 1256/5120
2026-09-04T18:31:38.353011+00:00 reasoning_off: durable checkpoint 1264/5120
2026-09-04T18:31:43.358632+00:00 reasoning_off: durable checkpoint 1272/5120
2026-09-04T18:31:47.299180+00:00 reasoning_off: durable checkpoint 1280/5120
2026-09-04T18:31:51.227333+00:00 reasoning_off: durable checkpoint 1288/5120
2026-09-04T18:31:55.234952+00:00 reasoning_off: durable checkpoint 1296/5120
2026-09-04T18:31:59.223857+00:00 reasoning_off: durable checkpoint 1304/5120
2026-09-04T18:32:03.745470+00:00 reasoning_off: durable checkpoint 1312/5120
2026-09-04T18:32:07.488893+00:00 reasoning_off: durable checkpoint 1320/5120
2026-09-04T18:32:11.229546+00:00 reasoning_off: durable checkpoint 1328/5120
2026-09-04T18:32:14.958632+00:00 reasoning_off: durable checkpoint 1336/5120
2026-09-04T18:32:18.670102+00:00 reasoning_off: durable checkpoint 1344/5120
2026-09-04T18:32:23.163448+00:00 reasoning_off: durable checkpoint 1352/5120
2026-09-04T18:32:26.931259+00:00 reasoning_off: durable checkpoint 1360/5120
2026-09-04T18:32:30.725318+00:00 reasoning_off: durable checkpoint 1368/5120
2026-09-04T18:32:34.460355+00:00 reasoning_off: durable checkpoint 1376/5120
2026-09-04T18:32:39.066653+00:00 reasoning_off: durable checkpoint 1384/5120
2026-09-04T18:32:42.864490+00:00 reasoning_off: durable checkpoint 1392/5120
2026-09-04T18:32:46.821758+00:00 reasoning_off: durable checkpoint 1400/5120
2026-09-04T18:32:50.592290+00:00 reasoning_off: durable checkpoint 1408/5120
2026-09-04T18:32:54.337898+00:00 reasoning_off: durable checkpoint 1416/5120
2026-09-04T18:32:59.035976+00:00 reasoning_off: durable checkpoint 1424/5120
2026-09-04T18:33:02.803376+00:00 reasoning_off: durable checkpoint 1432/5120
2026-09-04T18:33:06.643143+00:00 reasoning_off: durable checkpoint 1440/5120
2026-09-04T18:33:10.462250+00:00 reasoning_off: durable checkpoint 1448/5120
2026-09-04T18:33:15.139268+00:00 reasoning_off: durable checkpoint 1456/5120
2026-09-04T18:33:19.086805+00:00 reasoning_off: durable checkpoint 1464/5120
2026-09-04T18:33:22.901120+00:00 reasoning_off: durable checkpoint 1472/5120
2026-09-04T18:33:26.726906+00:00 reasoning_off: durable checkpoint 1480/5120
2026-09-04T18:33:31.519744+00:00 reasoning_off: durable checkpoint 1488/5120
2026-09-04T18:33:35.347449+00:00 reasoning_off: durable checkpoint 1496/5120
2026-09-04T18:33:39.171342+00:00 reasoning_off: durable checkpoint 1504/5120
2026-09-04T18:33:43.053265+00:00 reasoning_off: durable checkpoint 1512/5120
2026-09-04T18:33:47.892504+00:00 reasoning_off: durable checkpoint 1520/5120
2026-09-04T18:33:51.732274+00:00 reasoning_off: durable checkpoint 1528/5120
2026-09-04T18:33:55.598318+00:00 reasoning_off: durable checkpoint 1536/5120
2026-09-04T18:33:59.470590+00:00 reasoning_off: durable checkpoint 1544/5120
2026-09-04T18:34:04.254443+00:00 reasoning_off: durable checkpoint 1552/5120
2026-09-04T18:34:08.131815+00:00 reasoning_off: durable checkpoint 1560/5120
2026-09-04T18:34:12.047489+00:00 reasoning_off: durable checkpoint 1568/5120
2026-09-04T18:34:15.937594+00:00 reasoning_off: durable checkpoint 1576/5120
2026-09-04T18:34:20.840614+00:00 reasoning_off: durable checkpoint 1584/5120
2026-09-04T18:34:24.721581+00:00 reasoning_off: durable checkpoint 1592/5120
2026-09-04T18:34:28.632676+00:00 reasoning_off: durable checkpoint 1600/5120
2026-09-04T18:34:32.584099+00:00 reasoning_off: durable checkpoint 1608/5120
2026-09-04T18:34:37.393060+00:00 reasoning_off: durable checkpoint 1616/5120
2026-09-04T18:34:41.383241+00:00 reasoning_off: durable checkpoint 1624/5120
2026-09-04T18:34:45.307941+00:00 reasoning_off: durable checkpoint 1632/5120
2026-09-04T18:34:49.284740+00:00 reasoning_off: durable checkpoint 1640/5120
2026-09-04T18:34:54.076632+00:00 reasoning_off: durable checkpoint 1648/5120
2026-09-04T18:34:58.024684+00:00 reasoning_off: durable checkpoint 1656/5120
2026-09-04T18:35:01.992839+00:00 reasoning_off: durable checkpoint 1664/5120
2026-09-04T18:35:06.057850+00:00 reasoning_off: durable checkpoint 1672/5120
2026-09-04T18:35:10.859106+00:00 reasoning_off: durable checkpoint 1680/5120
2026-09-04T18:35:14.794617+00:00 reasoning_off: durable checkpoint 1688/5120
2026-09-04T18:35:18.773239+00:00 reasoning_off: durable checkpoint 1696/5120
2026-09-04T18:35:22.776444+00:00 reasoning_off: durable checkpoint 1704/5120
2026-09-04T18:35:27.635150+00:00 reasoning_off: durable checkpoint 1712/5120
2026-09-04T18:35:31.647048+00:00 reasoning_off: durable checkpoint 1720/5120
2026-09-04T18:35:35.637850+00:00 reasoning_off: durable checkpoint 1728/5120
2026-09-04T18:35:39.842026+00:00 reasoning_off: durable checkpoint 1736/5120
2026-09-04T18:35:44.754532+00:00 reasoning_off: durable checkpoint 1744/5120
2026-09-04T18:35:48.762261+00:00 reasoning_off: durable checkpoint 1752/5120
2026-09-04T18:35:52.899946+00:00 reasoning_off: durable checkpoint 1760/5120
2026-09-04T18:35:57.782969+00:00 reasoning_off: durable checkpoint 1768/5120
2026-09-04T18:36:01.818705+00:00 reasoning_off: durable checkpoint 1776/5120
2026-09-04T18:36:05.856119+00:00 reasoning_off: durable checkpoint 1784/5120
2026-09-04T18:36:09.923617+00:00 reasoning_off: durable checkpoint 1792/5120
2026-09-04T18:36:14.948546+00:00 reasoning_off: durable checkpoint 1800/5120
2026-09-04T18:36:19.002641+00:00 reasoning_off: durable checkpoint 1808/5120
2026-09-04T18:36:23.067905+00:00 reasoning_off: durable checkpoint 1816/5120
2026-09-04T18:36:28.048897+00:00 reasoning_off: durable checkpoint 1824/5120
2026-09-04T18:36:32.109455+00:00 reasoning_off: durable checkpoint 1832/5120
2026-09-04T18:36:36.155127+00:00 reasoning_off: durable checkpoint 1840/5120
2026-09-04T18:36:41.227567+00:00 reasoning_off: durable checkpoint 1848/5120
2026-09-04T18:36:45.312066+00:00 reasoning_off: durable checkpoint 1856/5120
2026-09-04T18:36:49.505132+00:00 reasoning_off: durable checkpoint 1864/5120
2026-09-04T18:36:53.685153+00:00 reasoning_off: durable checkpoint 1872/5120
2026-09-04T18:36:59.264259+00:00 reasoning_off: durable checkpoint 1880/5120
2026-09-04T18:37:03.823114+00:00 reasoning_off: durable checkpoint 1888/5120
2026-09-04T18:37:08.364899+00:00 reasoning_off: durable checkpoint 1896/5120
2026-09-04T18:37:14.108910+00:00 reasoning_off: durable checkpoint 1904/5120
2026-09-04T18:37:18.223942+00:00 reasoning_off: durable checkpoint 1912/5120
2026-09-04T18:37:22.361900+00:00 reasoning_off: durable checkpoint 1920/5120
2026-09-04T18:37:27.338757+00:00 reasoning_off: durable checkpoint 1928/5120
2026-09-04T18:37:31.646646+00:00 reasoning_off: durable checkpoint 1936/5120
2026-09-04T18:37:35.832198+00:00 reasoning_off: durable checkpoint 1944/5120
2026-09-04T18:37:40.023734+00:00 reasoning_off: durable checkpoint 1952/5120
2026-09-04T18:37:45.113061+00:00 reasoning_off: durable checkpoint 1960/5120
2026-09-04T18:37:49.314924+00:00 reasoning_off: durable checkpoint 1968/5120
2026-09-04T18:37:53.474821+00:00 reasoning_off: durable checkpoint 1976/5120
2026-09-04T18:37:58.531280+00:00 reasoning_off: durable checkpoint 1984/5120
2026-09-04T18:38:02.790505+00:00 reasoning_off: durable checkpoint 1992/5120
2026-09-04T18:38:07.053205+00:00 reasoning_off: durable checkpoint 2000/5120
2026-09-04T18:38:12.124841+00:00 reasoning_off: durable checkpoint 2008/5120
2026-09-04T18:38:16.321432+00:00 reasoning_off: durable checkpoint 2016/5120
2026-09-04T18:38:20.614930+00:00 reasoning_off: durable checkpoint 2024/5120
2026-09-04T18:38:25.688643+00:00 reasoning_off: durable checkpoint 2032/5120
2026-09-04T18:38:29.927085+00:00 reasoning_off: durable checkpoint 2040/5120
2026-09-04T18:38:34.381936+00:00 reasoning_off: durable checkpoint 2048/5120
2026-09-04T18:38:39.441899+00:00 reasoning_off: durable checkpoint 2056/5120
2026-09-04T18:38:43.695580+00:00 reasoning_off: durable checkpoint 2064/5120
2026-09-04T18:38:47.954451+00:00 reasoning_off: durable checkpoint 2072/5120
2026-09-04T18:38:53.095729+00:00 reasoning_off: durable checkpoint 2080/5120
2026-09-04T18:38:57.391842+00:00 reasoning_off: durable checkpoint 2088/5120

KeyboardInterrupt:

In [40]:
def validate_activation_inventory(
    result_rows: TranscriptDataset, *, reasoning: bool
) -> dict[str, object]:
    if len(result_rows) != EXPECTED_ROWS_PER_REASONING:
        raise ValueError("Mode-specific activation inventory has the wrong row count.")
    if {bool(row["reasoning"]) for row in result_rows} != {reasoning}:
        raise ValueError("Mode-specific activation inventory mixes reasoning modes.")
    expected_keys = {
        f"answer.{ACTIVATION_STREAM}.layer_{layer}" for layer in range(NUM_LAYERS)
    }
    total_bytes = 0
    sequence_lengths = []
    first_dtype = None
    answer_line_available_rows = 0
    for row_index, row in enumerate(result_rows):
        if row.get("generation_serialized_prompt") != row.get("serialized_prompt"):
            raise ValueError(f"Runtime prompt text drifted for row {row['row_id']}.")
        generation_ids = [int(token) for token in row.get("generation_input_ids", [])]
        dataset_ids = [int(token) for token in row.get("input_ids", [])]
        if generation_ids != dataset_ids:
            raise ValueError(f"Runtime prompt token IDs drifted for row {row['row_id']}.")
        teacher_forced_ids = [
            int(token) for token in row.get("teacher_forced_input_ids", [])
        ]
        if teacher_forced_ids[: len(dataset_ids)] != dataset_ids:
            raise ValueError(f"Teacher-forced prompt prefix drifted for row {row['row_id']}.")
        if (
            row.get("runtime_tokenizer_template_fingerprint")
            != tokenizer_binding.fingerprint
        ):
            raise ValueError(f"Runtime tokenizer/template drifted for row {row['row_id']}.")
        relative = row.get("activation_path")
        if not isinstance(relative, str):
            raise ValueError(f"Row {row['row_id']} has no activation_path.")
        path = RUN_DIRS[reasoning] / relative
        if not path.is_file():
            raise FileNotFoundError(path)
        total_bytes += path.stat().st_size
        captured_indices = [
            int(value) for value in row.get("activation_token_indices", [])
        ]
        if not captured_indices or len(captured_indices) != len(set(captured_indices)):
            raise ValueError(f"Row {row['row_id']} lacks unique sparse capture indices.")
        if captured_indices != sorted(captured_indices):
            raise ValueError(f"Row {row['row_id']} sparse indices are not canonical.")
        if not all(0 <= value < len(teacher_forced_ids) for value in captured_indices):
            raise ValueError(f"Row {row['row_id']} has an out-of-range sparse index.")
        prompt_positions = {
            int(position)
            for positions in row["prompt_token_sites"].values()
            for position in positions
        }
        if not prompt_positions <= set(captured_indices):
            raise ValueError(f"Row {row['row_id']} is missing a semantic prompt site.")
        line_start = row.get("answer_line_generated_token_start")
        line_end = row.get("answer_line_generated_token_end")
        completion_start = row.get("teacher_forced_completion_start")
        if line_start is not None and line_end is not None and completion_start is not None:
            answer_positions = set(range(
                int(completion_start) + int(line_start),
                int(completion_start) + int(line_end),
            ))
            if answer_positions and answer_positions <= set(captured_indices):
                answer_line_available_rows += 1
        sequence_lengths.append(len(row["teacher_forced_input_ids"]))
        with safe_open(path, framework="pt", device="cpu") as handle:
            if set(handle.keys()) != expected_keys:
                raise ValueError(f"Unexpected stream/layer keys in {path}.")
            for key in expected_keys:
                shape = tuple(handle.get_slice(key).get_shape())
                if shape != (len(captured_indices), HIDDEN_SIZE):
                    raise ValueError(f"Unexpected shape {shape} for {path}:{key}.")
            if row_index == 0:
                first_dtype = str(handle.get_tensor(sorted(expected_keys)[0]).dtype)
    if first_dtype != "torch.bfloat16":
        raise ValueError(f"Expected BF16 safetensors, found {first_dtype}.")
    return {
        "row_count": len(result_rows),
        "reasoning": reasoning,
        "reasoning_mode": MODE_NAMES[reasoning],
        "stream_count": 1,
        "layer_count": NUM_LAYERS,
        "dtype": first_dtype,
        "minimum_sequence_tokens": min(sequence_lengths),
        "maximum_sequence_tokens": max(sequence_lengths),
        "minimum_captured_positions": min(
            len(row["activation_token_indices"]) for row in result_rows
        ),
        "maximum_captured_positions": max(
            len(row["activation_token_indices"]) for row in result_rows
        ),
        "answer_line_available_rows": answer_line_available_rows,
        "answer_line_coverage_fraction": (
            answer_line_available_rows / EXPECTED_ROWS_PER_REASONING
        ),
        "activation_file_bytes": total_bytes,
        "activation_file_gib": total_bytes / GIB,
    }


def save_activation_split_indices(
    result_rows: TranscriptDataset, *, reasoning: bool
) -> dict[str, int]:
    indices: dict[str, list[dict[str, object]]] = {"train": [], "test": []}
    for row in result_rows:
        split = str(row["split"])
        if split not in indices:
            raise ValueError(f"Unexpected activation split {split!r}.")
        indices[split].append({
            "row_id": str(row["row_id"]),
            "base_transcript_id": str(row["base_transcript_id"]),
            "question_set_index": int(row["question_set_index"]),
            "answer_pattern_index": int(row["answer_pattern_index"]),
            "activation_path": str(row["activation_path"]),
            "activation_run_id": RUN_IDS[reasoning],
            "reasoning": reasoning,
            "split": split,
            "dataset_split_fingerprint": dataset_split_fingerprint,
        })
    if len(indices["train"]) != EXPECTED_TRAIN_ROWS_PER_REASONING:
        raise ValueError("Mode-specific training activation index has the wrong size.")
    if len(indices["test"]) != EXPECTED_TEST_ROWS_PER_REASONING:
        raise ValueError("Mode-specific test activation index has the wrong size.")
    train_paths = {row["activation_path"] for row in indices["train"]}
    test_paths = {row["activation_path"] for row in indices["test"]}
    if (
        len(train_paths) != EXPECTED_TRAIN_ROWS_PER_REASONING
        or len(test_paths) != EXPECTED_TEST_ROWS_PER_REASONING
    ):
        raise ValueError("Activation paths are not unique within each split.")
    if not train_paths.isdisjoint(test_paths):
        raise ValueError("An activation safetensor appears in both train and test indices.")
    train_schedules = {row["question_set_index"] for row in indices["train"]}
    test_schedules = {row["question_set_index"] for row in indices["test"]}
    if not train_schedules.isdisjoint(test_schedules):
        raise ValueError("A question schedule appears in both activation partitions.")
    for split, rows in indices.items():
        atomic_write_jsonl(
            SPLIT_ROOT / MODE_NAMES[reasoning] / f"{split}_activations.jsonl",
            rows,
        )
    return {split: len(rows) for split, rows in indices.items()}


if results is not None:
    capture_inventory = {}
    for reasoning in ANALYSIS_REASONING_VALUES:
        inventory = validate_activation_inventory(
            results_by_reasoning[reasoning], reasoning=reasoning
        )
        inventory["activation_split_rows"] = save_activation_split_indices(
            results_by_reasoning[reasoning], reasoning=reasoning
        )
        atomic_write_json(
            RUN_DIRS[reasoning] / "activation_inventory.json", inventory
        )
        capture_inventory[MODE_NAMES[reasoning]] = inventory
    actual_capture_gib = sum(
        float(inventory["activation_file_gib"])
        for inventory in capture_inventory.values()
    )
    if actual_capture_gib > ACTIVATION_STORAGE_BUDGET_GIB:
        raise RuntimeError("Actual sparse activation files exceed the declared budget.")
    display(capture_inventory)
else:
    capture_inventory = None

{'reasoning_off': {'row_count': 5120,
  'reasoning': False,
  'reasoning_mode': 'reasoning_off',
  'stream_count': 1,
  'layer_count': 32,
  'dtype': 'torch.bfloat16',
  'minimum_sequence_tokens': 529,
  'maximum_sequence_tokens': 529,
  'minimum_captured_positions': 48,
  'maximum_captured_positions': 48,
  'answer_line_available_rows': 5120,
  'answer_line_coverage_fraction': 1.0,
  'activation_file_bytes': 64440442880,
  'activation_file_gib': 60.01483917236328,
  'activation_split_rows': {'train': 4480, 'test': 640}}}

## Linear probes

Qwen remains frozen. For a residual vector $h\in\mathbb{R}^{4096}$, a continuous probe is

$$\hat y=w^\top\operatorname{standardize}(h)+b,$$

fitted with ridge regression. At a fixed site and layer, each reasoning mode has its own
design matrix with 4,480 training transcripts and 4,096 columns. This gives more rows than
features, while ridge still controls multicollinearity by minimizing

$$\lVert y-Xw-b\rVert_2^2+\alpha\lVert w\rVert_2^2.$$

Grouped cross-validation chooses $\alpha$ from `RIDGE_ALPHAS`. The iterative `lsqr` solver
avoids unstable direct solves of the highly correlated residual features. Reliability sign uses
L2-regularized logistic regression and chooses inverse regularization `C`. Feature
normalization is part of the scikit-learn pipeline, so its mean and scale are refitted
inside every training fold rather than computed globally. The eight held-out schedules never
participate in normalization, hyperparameter choice, layer selection, or probe fitting.

Reasoning-off and reasoning-on probes are fit, selected, saved, and tested independently.
No activation from one reasoning mode can enter the other mode's scaler, CV folds, or fit.

No gradients pass through Qwen, and Qwen's weights never change. For every
site/layer/target combination, only the probe's $w$ and $b$ are learned. This makes the
experiment a test of linear decodability, not model fine-tuning.

The 14 preregistered sites cover the domain and reliability sentence boundaries, both
displayed reliability values, all three reported answers, the observation/question gap,
both `s=value` candidate spans and the question boundary, the assistant turn boundary, the final prompt
token, and the mean-pooled generated answer line. Only these locations were cached.

For each site/target, the top layers are locked using grouped training-only cross-validation.
Test evaluation is a separate switch. Probe weights, intercepts, scaler statistics, CV
metrics, and locked layers are saved under `artifacts/.../probes/`.

In [41]:
def result_site_positions(row: dict[str, object], site: str) -> list[int] | None:
    if site == "answer_line":
        start = row.get("answer_line_generated_token_start")
        end = row.get("answer_line_generated_token_end")
        completion_start = row.get("teacher_forced_completion_start")
        if start is None or end is None or completion_start is None:
            return None
        positions = list(range(
            int(completion_start) + int(start),
            int(completion_start) + int(end),
        ))
        return positions or None
    if site == "answer_prefix":
        value = row.get("answer_boundary_input_index")
        return [int(value)] if value is not None else None
    prompt_sites = row.get("prompt_token_sites", {})
    value = prompt_sites.get(site) if isinstance(prompt_sites, dict) else None
    if isinstance(value, list) and value:
        return [int(position) for position in value]
    if value is not None:
        return [int(value)]
    return None


def result_site_position(row: dict[str, object], site: str) -> int | None:
    positions = result_site_positions(row, site)
    return positions[-1] if positions else None


def activation_path(row: dict[str, object]) -> Path:
    relative = row.get("activation_path")
    if not isinstance(relative, str):
        raise ValueError(f"Row {row['row_id']} has no activation capture.")
    return RUN_DIRS[bool(row["reasoning"])] / relative


def activation_vector(row: dict[str, object], *, site: str, layer: int) -> np.ndarray:
    positions = result_site_positions(row, site)
    if positions is None:
        raise ValueError(f"Row {row['row_id']} has no {site} position.")
    captured_indices = [int(value) for value in row["activation_token_indices"]]
    captured_lookup = {
        absolute_position: stored_position
        for stored_position, absolute_position in enumerate(captured_indices)
    }
    missing = [position for position in positions if position not in captured_lookup]
    if missing:
        raise ValueError(
            f"Row {row['row_id']} did not capture {site} positions {missing}."
        )
    stored_positions = [captured_lookup[position] for position in positions]
    key = f"answer.{ACTIVATION_STREAM}.layer_{layer}"
    with safe_open(activation_path(row), framework="pt", device="cpu") as handle:
        vectors = handle.get_tensor(key)[stored_positions].float().numpy()
    vector = vectors.mean(axis=0)
    if vector.shape != (HIDDEN_SIZE,):
        raise ValueError(f"Unexpected activation-vector shape {vector.shape}.")
    return vector


def rows_available_at_site(result_rows: TranscriptDataset, site: str) -> list[dict[str, object]]:
    rows = []
    for source in result_rows:
        row = dict(source)
        positions = result_site_positions(row, site)
        if positions is None:
            continue
        captured = {
            int(value) for value in row.get("activation_token_indices", [])
        }
        if not set(positions) <= captured:
            if site == "answer_line":
                continue
            missing = sorted(set(positions) - captured)
            raise ValueError(
                f"Row {row['row_id']} is missing captured {site} positions {missing}."
            )
        rows.append(row)
    # Early causal sites intentionally share literal prompt prefixes across many
    # schedules (for example, domain_boundary precedes all sampled evidence).
    # Leakage is therefore defined by experimental unit, not text equality.
    train_schedule_ids = {
        int(row["question_set_index"])
        for row in rows if row["split"] == "train"
    }
    test_schedule_ids = {
        int(row["question_set_index"])
        for row in rows if row["split"] == "test"
    }
    if not train_schedule_ids.isdisjoint(test_schedule_ids):
        raise ValueError(f"Question-schedule leakage detected at site {site}.")
    train_row_ids = {str(row["row_id"]) for row in rows if row["split"] == "train"}
    test_row_ids = {str(row["row_id"]) for row in rows if row["split"] == "test"}
    if not train_row_ids.isdisjoint(test_row_ids):
        raise ValueError(f"Row leakage detected at site {site}.")
    return rows


def activation_matrix(
    rows: list[dict[str, object]], *, site: str, layer: int
) -> np.ndarray:
    return np.stack([
        activation_vector(row, site=site, layer=layer) for row in rows
    ]).astype(np.float32, copy=False)


def activation_site_cache(
    rows: list[dict[str, object]], *, site: str, layers: tuple[int, ...]
) -> np.ndarray:
    """Load every requested layer for one site, opening each row file once."""
    layers = tuple(int(layer) for layer in layers)
    if not layers or len(set(layers)) != len(layers):
        raise ValueError("Site-cache layers must be nonempty and unique.")
    cache = np.empty(
        (len(layers), len(rows), HIDDEN_SIZE), dtype=np.float32
    )
    try:
        for row_index, row in enumerate(rows):
            positions = result_site_positions(row, site)
            if positions is None:
                raise ValueError(f"Row {row['row_id']} has no {site} position.")
            captured_indices = [
                int(value) for value in row["activation_token_indices"]
            ]
            captured_lookup = {
                absolute_position: stored_position
                for stored_position, absolute_position in enumerate(captured_indices)
            }
            missing = [
                position for position in positions
                if position not in captured_lookup
            ]
            if missing:
                raise ValueError(
                    f"Row {row['row_id']} did not capture {site} positions {missing}."
                )
            stored_positions = [captured_lookup[position] for position in positions]
            with safe_open(activation_path(row), framework="pt", device="cpu") as handle:
                for cache_layer_index, layer in enumerate(layers):
                    key = f"answer.{ACTIVATION_STREAM}.layer_{layer}"
                    vectors = (
                        handle.get_tensor(key)[stored_positions].float().numpy()
                    )
                    vector = vectors.mean(axis=0)
                    if vector.shape != (HIDDEN_SIZE,):
                        raise ValueError(
                            f"Unexpected activation-vector shape {vector.shape}."
                        )
                    cache[cache_layer_index, row_index] = vector
            if (row_index + 1) % 256 == 0 or row_index + 1 == len(rows):
                print(
                    datetime.now(timezone.utc).isoformat(),
                    f"cached {site}: {row_index + 1}/{len(rows)} files",
                )
        return cache
    except BaseException:
        del cache
        gc.collect()
        raise


def target_array(rows: list[dict[str, object]], target: str) -> np.ndarray:
    dtype = np.int64 if target in BINARY_PROBE_TARGETS else np.float64
    return np.asarray([row[target] for row in rows], dtype=dtype)


def probe_paths(
    reasoning: bool, site: str, target: str, layer: int
) -> tuple[Path, Path]:
    root = PROBE_ROOT / MODE_NAMES[reasoning] / site / target
    return (
        root / f"layer_{layer:02d}.safetensors",
        root / f"layer_{layer:02d}.json",
    )


def probe_artifacts_match_configuration(
    reasoning: bool, site: str, target: str, layer: int
) -> bool:
    weights_path, metadata_path = probe_paths(reasoning, site, target, layer)
    if not weights_path.is_file() or not metadata_path.is_file():
        return False
    try:
        metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        with safe_open(weights_path, framework="pt", device="cpu") as handle:
            tensor_metadata = handle.metadata() or {}
        return (
            metadata.get("probe_config_fingerprint") == PROBE_CONFIG_FINGERPRINT
            and tensor_metadata.get("probe_config_fingerprint")
            == PROBE_CONFIG_FINGERPRINT
        )
    except (OSError, ValueError, json.JSONDecodeError, SafetensorError):
        return False


def save_fitted_probe(
    *, search: GridSearchCV, reasoning: bool, site: str, target: str, layer: int,
    metadata: dict[str, object]
) -> None:
    weights_path, metadata_path = probe_paths(reasoning, site, target, layer)
    weights_path.parent.mkdir(parents=True, exist_ok=True)
    pipeline = search.best_estimator_
    scaler = pipeline.named_steps["scale"]
    estimator = pipeline.named_steps["model"]
    tensors = {
        "coef": torch.as_tensor(np.asarray(estimator.coef_).reshape(-1), dtype=torch.float32),
        "intercept": torch.as_tensor(np.asarray(estimator.intercept_).reshape(-1), dtype=torch.float32),
        "feature_mean": torch.as_tensor(scaler.mean_, dtype=torch.float32),
        "feature_scale": torch.as_tensor(scaler.scale_, dtype=torch.float32),
    }
    temporary = weights_path.with_suffix(".safetensors.tmp")
    save_file(
        tensors,
        temporary,
        metadata={
            "probe_config_fingerprint": PROBE_CONFIG_FINGERPRINT,
            "reasoning_mode": MODE_NAMES[reasoning],
            "site": site,
            "target": target,
            "layer": str(layer),
        },
    )
    os.replace(temporary, weights_path)
    atomic_write_json(metadata_path, metadata)


def fit_one_probe(
    *, X_train: np.ndarray, train_rows: list[dict[str, object]],
    reasoning: bool, site: str, target: str, layer: int
) -> dict[str, object]:
    y_train = target_array(train_rows, target)
    groups = np.asarray([int(row["question_set_index"]) for row in train_rows])
    unique_groups = np.unique(groups)
    if {bool(row["reasoning"]) for row in train_rows} != {reasoning}:
        raise ValueError("A probe training matrix mixes reasoning modes.")
    if len(unique_groups) != NUM_QUESTION_SETS - TEST_SCHEDULE_COUNT:
        raise ValueError("Probe training rows do not contain exactly 56 schedules.")
    folds = list(GroupKFold(n_splits=PROBE_CV_FOLDS).split(X_train, y_train, groups))

    if target in BINARY_PROBE_TARGETS:
        # L2 is LogisticRegression's default. Leaving `penalty` unset avoids the
        # scikit-learn 1.8+ deprecation of that explicit keyword.
        estimator = LogisticRegression(
            solver="lbfgs", max_iter=2_000, random_state=SEED
        )
        parameters = {"model__C": LOGISTIC_C_VALUES}
        scoring = "roc_auc"
        kind = "logistic"
    else:
        estimator = Ridge(
            solver=RIDGE_SOLVER, tol=RIDGE_TOL, max_iter=RIDGE_MAX_ITER
        )
        parameters = {"model__alpha": RIDGE_ALPHAS}
        scoring = "r2"
        kind = "ridge"

    pipeline = Pipeline([
        ("scale", StandardScaler()),
        ("model", estimator),
    ])
    search = GridSearchCV(
        pipeline,
        param_grid=parameters,
        scoring=scoring,
        cv=folds,
        n_jobs=PROBE_N_JOBS,
        refit=True,
        error_score="raise",
        return_train_score=False,
    )
    search.fit(X_train, y_train)
    record = {
        "reasoning": reasoning,
        "reasoning_mode": MODE_NAMES[reasoning],
        "site": site,
        "target": target,
        "layer": layer,
        "kind": kind,
        "selection_metric": scoring,
        "best_cv_score": float(search.best_score_),
        "best_params": {
            key: float(value) for key, value in search.best_params_.items()
        },
        "train_row_count": len(train_rows),
        "train_schedule_ids": sorted(int(value) for value in unique_groups),
        "test_rows_used": 0,
        "feature_count": int(X_train.shape[1]),
        "probe_config_fingerprint": PROBE_CONFIG_FINGERPRINT,
    }
    save_fitted_probe(
        search=search, reasoning=reasoning, site=site, target=target,
        layer=layer, metadata=record
    )
    return record


def read_jsonl_if_present(path: Path) -> list[dict[str, object]]:
    if not path.exists():
        return []
    return [
        json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]

In [43]:
probe_cv_path = PROBE_ROOT / "training_cv_metrics.jsonl"
all_probe_targets = CONTINUOUS_PROBE_TARGETS + BINARY_PROBE_TARGETS
expected_probe_keys = {
    (reasoning, site, target, layer)
    for reasoning in ANALYSIS_REASONING_VALUES
    for site in PROBE_SITES
    for target in all_probe_targets
    for layer in PROBE_LAYERS
}
probe_records_by_key = {}
for row in read_jsonl_if_present(probe_cv_path):
    key = (
        bool(row["reasoning"]), str(row["site"]),
        str(row["target"]), int(row["layer"]),
    )
    if (
        key in expected_probe_keys
        and row.get("probe_config_fingerprint") == PROBE_CONFIG_FINGERPRINT
        and probe_artifacts_match_configuration(*key)
    ):
        probe_records_by_key[key] = row

probe_execution_sites = tuple(reversed(PROBE_SITES))
expected_probe_count = len(expected_probe_keys)


def log_probe_progress(event: str, **context: object) -> None:
    completed = len(probe_records_by_key)
    pending = expected_probe_count - completed
    print(
        datetime.now(timezone.utc).isoformat(),
        event,
        {
            **context,
            "completed": completed,
            "total": expected_probe_count,
            "pending": pending,
            "percent_complete": round(100.0 * completed / expected_probe_count, 4),
        },
    )


log_probe_progress(
    "PROBE_RESUME_STATUS",
    execution_site_order=list(probe_execution_sites),
)

if RUN_PROBE_TRAINING:
    if results is None:
        raise RuntimeError("Load or run the completed activation capture first.")
    for reasoning in ANALYSIS_REASONING_VALUES:
        mode_results = results_by_reasoning[reasoning]
        for site in probe_execution_sites:
            missing_targets_by_layer = {
                layer: tuple(
                    target for target in all_probe_targets
                    if (reasoning, site, target, layer) not in probe_records_by_key
                )
                for layer in PROBE_LAYERS
            }
            missing_layers = tuple(
                layer for layer in PROBE_LAYERS
                if missing_targets_by_layer[layer]
            )
            site_pending = sum(
                len(targets) for targets in missing_targets_by_layer.values()
            )
            if not missing_layers:
                log_probe_progress(
                    "PROBE_SITE_SKIPPED_COMPLETE",
                    reasoning_mode=MODE_NAMES[reasoning], site=site,
                )
                continue
            site_rows = rows_available_at_site(mode_results, site)
            site_train_rows = [row for row in site_rows if row["split"] == "train"]
            required_rows = max(
                MIN_PROBE_TRAIN_ROWS,
                math.ceil(MIN_GENERATED_SITE_COVERAGE * EXPECTED_TRAIN_ROWS_PER_REASONING),
            )
            if len(site_train_rows) < required_rows:
                raise RuntimeError(
                    f"{MODE_NAMES[reasoning]}/{site} has {len(site_train_rows)} usable "
                    f"training rows; at least {required_rows} are required."
                )
            if len(site_train_rows) < EXPECTED_TRAIN_ROWS_PER_REASONING:
                print(
                    f"{MODE_NAMES[reasoning]}/{site}: "
                    f"{EXPECTED_TRAIN_ROWS_PER_REASONING - len(site_train_rows)} rows "
                    "lack a usable generated answer boundary and are excluded."
                )
            estimated_cache_bytes = (
                len(missing_layers) * len(site_train_rows) * HIDDEN_SIZE
                * np.dtype(np.float32).itemsize
            )
            log_probe_progress(
                "PROBE_SITE_CACHE_START",
                reasoning_mode=MODE_NAMES[reasoning],
                site=site,
                site_pending=site_pending,
                missing_layers=list(missing_layers),
                activation_files=len(site_train_rows),
                estimated_cache_gib=round(estimated_cache_bytes / (1024 ** 3), 4),
            )
            site_activation_cache = activation_site_cache(
                site_train_rows, site=site, layers=missing_layers
            )
            print(
                datetime.now(timezone.utc).isoformat(),
                "PROBE_SITE_CACHE_READY",
                {
                    "reasoning_mode": MODE_NAMES[reasoning],
                    "site": site,
                    "shape": tuple(site_activation_cache.shape),
                    "cache_gib": round(site_activation_cache.nbytes / (1024 ** 3), 4),
                    "activation_file_opens": len(site_train_rows),
                },
            )
            try:
                for cache_layer_index, layer in enumerate(missing_layers):
                    missing_targets = missing_targets_by_layer[layer]
                    log_probe_progress(
                        "PROBE_LAYER_START",
                        reasoning_mode=MODE_NAMES[reasoning],
                        site=site, layer=layer,
                        missing_targets=list(missing_targets),
                    )
                    X_train = site_activation_cache[cache_layer_index]
                    try:
                        for target in missing_targets:
                            record = fit_one_probe(
                                X_train=X_train,
                                train_rows=site_train_rows,
                                reasoning=reasoning,
                                site=site,
                                target=target,
                                layer=layer,
                            )
                            probe_records_by_key[(reasoning, site, target, layer)] = record
                            atomic_write_jsonl(
                                probe_cv_path,
                                sorted(
                                    probe_records_by_key.values(),
                                    key=lambda row: (
                                        bool(row["reasoning"]), str(row["site"]),
                                        str(row["target"]), int(row["layer"]),
                                    ),
                                ),
                            )
                            log_probe_progress(
                                "PROBE_TARGET_CHECKPOINTED",
                                reasoning_mode=MODE_NAMES[reasoning],
                                site=site, layer=layer, target=target,
                            )
                    finally:
                        del X_train
            finally:
                del site_activation_cache
                gc.collect()
                print(
                    datetime.now(timezone.utc).isoformat(),
                    "PROBE_SITE_CACHE_RELEASED",
                    {"reasoning_mode": MODE_NAMES[reasoning], "site": site},
                )
else:
    print("Probe training is paused; set RUN_PROBE_TRAINING=True after capture.")

probe_cv_records = list(probe_records_by_key.values())
print("Completed training-only probe records:", len(probe_cv_records))

2026-09-05T00:28:06.562918+00:00 PROBE_RESUME_STATUS {'execution_site_order': ['answer_line', 'final_prompt', 'assistant_turn_boundary', 'candidate_question_boundary', 'candidate_2_value', 'candidate_1_value', 'observation_question_boundary', 'report_3_answer', 'report_2_answer', 'report_1_answer', 'reliability_one_minus_r_value', 'reliability_r_value', 'reliability_rule_boundary', 'domain_boundary'], 'completed': 1440, 'total': 2688, 'pending': 1248, 'percent_complete': 53.5714}
2026-09-05T00:28:06.690221+00:00 PROBE_SITE_CACHE_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'site_pending': 192, 'missing_layers': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], 'activation_files': 4480, 'estimated_cache_gib': 2.1875, 'completed': 1440, 'total': 2688, 'pending': 1248, 'percent_complete': 53.5714}

2026-09-05T00:28:14.082688+00:00 cached answer_line: 256/4480 files

2026-09-05T00:28:21.875801+00:00 cached answer_line: 512/4480 files

2026-09-05T00:28:29.782059+00:00 cached answer_line: 768/4480 files

2026-09-05T00:28:36.974938+00:00 cached answer_line: 1024/4480 files

2026-09-05T00:28:44.685813+00:00 cached answer_line: 1280/4480 files

2026-09-05T00:28:52.280496+00:00 cached answer_line: 1536/4480 files

2026-09-05T00:29:00.177417+00:00 cached answer_line: 1792/4480 files

2026-09-05T00:29:07.584516+00:00 cached answer_line: 2048/4480 files

2026-09-05T00:29:15.173899+00:00 cached answer_line: 2304/4480 files

2026-09-05T00:29:23.075068+00:00 cached answer_line: 2560/4480 files

2026-09-05T00:29:30.980182+00:00 cached answer_line: 2816/4480 files

2026-09-05T00:29:38.290152+00:00 cached answer_line: 3072/4480 files

2026-09-05T00:29:44.887200+00:00 cached answer_line: 3328/4480 files

2026-09-05T00:29:51.176347+00:00 cached answer_line: 3584/4480 files

2026-09-05T00:29:57.290607+00:00 cached answer_line: 3840/4480 files

2026-09-05T00:30:03.774877+00:00 cached answer_line: 4096/4480 files

2026-09-05T00:30:10.692494+00:00 cached answer_line: 4352/4480 files

2026-09-05T00:30:14.175237+00:00 cached answer_line: 4480/4480 files
2026-09-05T00:30:14.175525+00:00 PROBE_SITE_CACHE_READY {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'shape': (32, 4480, 4096), 'cache_gib': 2.1875, 'activation_file_opens': 4480}
2026-09-05T00:30:14.175760+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 0, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1440, 'total': 2688, 'pending': 1248, 'percent_complete': 53.5714}

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

2026-09-05T00:30:28.973787+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 0, 'target': 'delta_a', 'completed': 1441, 'total': 2688, 'pending': 1247, 'percent_complete': 53.6086}

2026-09-05T00:30:35.491191+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 0, 'target': 'gain', 'completed': 1442, 'total': 2688, 'pending': 1246, 'percent_complete': 53.6458}

2026-09-05T00:30:41.675742+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 0, 'target': 'gain_abs', 'completed': 1443, 'total': 2688, 'pending': 1245, 'percent_complete': 53.683}

2026-09-05T00:30:47.073548+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 0, 'target': 'z_bayes', 'completed': 1444, 'total': 2688, 'pending': 1244, 'percent_complete': 53.7202}

2026-09-05T00:30:53.912672+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 0, 'target': 'z_heuristic', 'completed': 1445, 'total': 2688, 'pending': 1243, 'percent_complete': 53.7574}

2026-09-05T00:30:58.572921+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 0, 'target': 'reliability_sign', 'completed': 1446, 'total': 2688, 'pending': 1242, 'percent_complete': 53.7946}
2026-09-05T00:30:58.573203+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 1, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1446, 'total': 2688, 'pending': 1242, 'percent_complete': 53.7946}

2026-09-05T00:31:05.275257+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 1, 'target': 'delta_a', 'completed': 1447, 'total': 2688, 'pending': 1241, 'percent_complete': 53.8318}

2026-09-05T00:31:11.873522+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 1, 'target': 'gain', 'completed': 1448, 'total': 2688, 'pending': 1240, 'percent_complete': 53.869}

2026-09-05T00:31:18.671700+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 1, 'target': 'gain_abs', 'completed': 1449, 'total': 2688, 'pending': 1239, 'percent_complete': 53.9062}

2026-09-05T00:31:25.588518+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 1, 'target': 'z_bayes', 'completed': 1450, 'total': 2688, 'pending': 1238, 'percent_complete': 53.9435}

2026-09-05T00:31:32.784972+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 1, 'target': 'z_heuristic', 'completed': 1451, 'total': 2688, 'pending': 1237, 'percent_complete': 53.9807}

2026-09-05T00:31:35.093991+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 1, 'target': 'reliability_sign', 'completed': 1452, 'total': 2688, 'pending': 1236, 'percent_complete': 54.0179}
2026-09-05T00:31:35.094279+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 2, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1452, 'total': 2688, 'pending': 1236, 'percent_complete': 54.0179}

2026-09-05T00:31:41.433767+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 2, 'target': 'delta_a', 'completed': 1453, 'total': 2688, 'pending': 1235, 'percent_complete': 54.0551}

2026-09-05T00:31:48.081406+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 2, 'target': 'gain', 'completed': 1454, 'total': 2688, 'pending': 1234, 'percent_complete': 54.0923}

2026-09-05T00:31:55.175760+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 2, 'target': 'gain_abs', 'completed': 1455, 'total': 2688, 'pending': 1233, 'percent_complete': 54.1295}

2026-09-05T00:32:02.576123+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 2, 'target': 'z_bayes', 'completed': 1456, 'total': 2688, 'pending': 1232, 'percent_complete': 54.1667}

2026-09-05T00:32:10.286302+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 2, 'target': 'z_heuristic', 'completed': 1457, 'total': 2688, 'pending': 1231, 'percent_complete': 54.2039}

2026-09-05T00:32:12.381434+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 2, 'target': 'reliability_sign', 'completed': 1458, 'total': 2688, 'pending': 1230, 'percent_complete': 54.2411}
2026-09-05T00:32:12.381711+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 3, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1458, 'total': 2688, 'pending': 1230, 'percent_complete': 54.2411}

2026-09-05T00:32:19.597431+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 3, 'target': 'delta_a', 'completed': 1459, 'total': 2688, 'pending': 1229, 'percent_complete': 54.2783}

2026-09-05T00:32:27.696821+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 3, 'target': 'gain', 'completed': 1460, 'total': 2688, 'pending': 1228, 'percent_complete': 54.3155}

2026-09-05T00:32:36.516671+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 3, 'target': 'gain_abs', 'completed': 1461, 'total': 2688, 'pending': 1227, 'percent_complete': 54.3527}

2026-09-05T00:32:44.187859+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 3, 'target': 'z_bayes', 'completed': 1462, 'total': 2688, 'pending': 1226, 'percent_complete': 54.3899}

2026-09-05T00:32:53.087314+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 3, 'target': 'z_heuristic', 'completed': 1463, 'total': 2688, 'pending': 1225, 'percent_complete': 54.4271}

2026-09-05T00:32:55.699153+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 3, 'target': 'reliability_sign', 'completed': 1464, 'total': 2688, 'pending': 1224, 'percent_complete': 54.4643}
2026-09-05T00:32:55.699427+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 4, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1464, 'total': 2688, 'pending': 1224, 'percent_complete': 54.4643}

2026-09-05T00:33:05.128406+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 4, 'target': 'delta_a', 'completed': 1465, 'total': 2688, 'pending': 1223, 'percent_complete': 54.5015}

2026-09-05T00:33:14.208542+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 4, 'target': 'gain', 'completed': 1466, 'total': 2688, 'pending': 1222, 'percent_complete': 54.5387}

2026-09-05T00:33:23.390986+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 4, 'target': 'gain_abs', 'completed': 1467, 'total': 2688, 'pending': 1221, 'percent_complete': 54.5759}

2026-09-05T00:33:32.288632+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 4, 'target': 'z_bayes', 'completed': 1468, 'total': 2688, 'pending': 1220, 'percent_complete': 54.6131}

2026-09-05T00:33:40.980628+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 4, 'target': 'z_heuristic', 'completed': 1469, 'total': 2688, 'pending': 1219, 'percent_complete': 54.6503}

2026-09-05T00:33:43.215386+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 4, 'target': 'reliability_sign', 'completed': 1470, 'total': 2688, 'pending': 1218, 'percent_complete': 54.6875}
2026-09-05T00:33:43.215690+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 5, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1470, 'total': 2688, 'pending': 1218, 'percent_complete': 54.6875}

2026-09-05T00:33:52.880678+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 5, 'target': 'delta_a', 'completed': 1471, 'total': 2688, 'pending': 1217, 'percent_complete': 54.7247}

2026-09-05T00:34:01.984891+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 5, 'target': 'gain', 'completed': 1472, 'total': 2688, 'pending': 1216, 'percent_complete': 54.7619}

2026-09-05T00:34:11.278875+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 5, 'target': 'gain_abs', 'completed': 1473, 'total': 2688, 'pending': 1215, 'percent_complete': 54.7991}

2026-09-05T00:34:20.113078+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 5, 'target': 'z_bayes', 'completed': 1474, 'total': 2688, 'pending': 1214, 'percent_complete': 54.8363}

2026-09-05T00:34:28.678674+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 5, 'target': 'z_heuristic', 'completed': 1475, 'total': 2688, 'pending': 1213, 'percent_complete': 54.8735}

2026-09-05T00:34:30.494033+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 5, 'target': 'reliability_sign', 'completed': 1476, 'total': 2688, 'pending': 1212, 'percent_complete': 54.9107}
2026-09-05T00:34:30.494282+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 6, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1476, 'total': 2688, 'pending': 1212, 'percent_complete': 54.9107}

2026-09-05T00:34:38.202755+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 6, 'target': 'delta_a', 'completed': 1477, 'total': 2688, 'pending': 1211, 'percent_complete': 54.9479}

2026-09-05T00:34:47.483979+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 6, 'target': 'gain', 'completed': 1478, 'total': 2688, 'pending': 1210, 'percent_complete': 54.9851}

2026-09-05T00:34:57.585677+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 6, 'target': 'gain_abs', 'completed': 1479, 'total': 2688, 'pending': 1209, 'percent_complete': 55.0223}

2026-09-05T00:35:06.912410+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 6, 'target': 'z_bayes', 'completed': 1480, 'total': 2688, 'pending': 1208, 'percent_complete': 55.0595}

2026-09-05T00:35:17.298965+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 6, 'target': 'z_heuristic', 'completed': 1481, 'total': 2688, 'pending': 1207, 'percent_complete': 55.0967}

2026-09-05T00:35:19.082829+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 6, 'target': 'reliability_sign', 'completed': 1482, 'total': 2688, 'pending': 1206, 'percent_complete': 55.1339}
2026-09-05T00:35:19.083177+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 7, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1482, 'total': 2688, 'pending': 1206, 'percent_complete': 55.1339}

2026-09-05T00:35:28.728343+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 7, 'target': 'delta_a', 'completed': 1483, 'total': 2688, 'pending': 1205, 'percent_complete': 55.1711}

2026-09-05T00:35:40.390567+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 7, 'target': 'gain', 'completed': 1484, 'total': 2688, 'pending': 1204, 'percent_complete': 55.2083}

2026-09-05T00:35:51.312583+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 7, 'target': 'gain_abs', 'completed': 1485, 'total': 2688, 'pending': 1203, 'percent_complete': 55.2455}

2026-09-05T00:36:02.089982+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 7, 'target': 'z_bayes', 'completed': 1486, 'total': 2688, 'pending': 1202, 'percent_complete': 55.2827}

2026-09-05T00:36:12.880633+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 7, 'target': 'z_heuristic', 'completed': 1487, 'total': 2688, 'pending': 1201, 'percent_complete': 55.3199}

2026-09-05T00:36:15.104631+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 7, 'target': 'reliability_sign', 'completed': 1488, 'total': 2688, 'pending': 1200, 'percent_complete': 55.3571}
2026-09-05T00:36:15.104871+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 8, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1488, 'total': 2688, 'pending': 1200, 'percent_complete': 55.3571}

2026-09-05T00:36:25.892306+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 8, 'target': 'delta_a', 'completed': 1489, 'total': 2688, 'pending': 1199, 'percent_complete': 55.3943}

2026-09-05T00:36:40.496648+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 8, 'target': 'gain', 'completed': 1490, 'total': 2688, 'pending': 1198, 'percent_complete': 55.4315}

2026-09-05T00:36:51.974442+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 8, 'target': 'gain_abs', 'completed': 1491, 'total': 2688, 'pending': 1197, 'percent_complete': 55.4688}

2026-09-05T00:37:05.100327+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 8, 'target': 'z_bayes', 'completed': 1492, 'total': 2688, 'pending': 1196, 'percent_complete': 55.506}

2026-09-05T00:37:16.519164+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 8, 'target': 'z_heuristic', 'completed': 1493, 'total': 2688, 'pending': 1195, 'percent_complete': 55.5432}

2026-09-05T00:37:18.379831+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 8, 'target': 'reliability_sign', 'completed': 1494, 'total': 2688, 'pending': 1194, 'percent_complete': 55.5804}
2026-09-05T00:37:18.380174+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 9, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1494, 'total': 2688, 'pending': 1194, 'percent_complete': 55.5804}

2026-09-05T00:37:28.181599+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 9, 'target': 'delta_a', 'completed': 1495, 'total': 2688, 'pending': 1193, 'percent_complete': 55.6176}

2026-09-05T00:37:40.080228+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 9, 'target': 'gain', 'completed': 1496, 'total': 2688, 'pending': 1192, 'percent_complete': 55.6548}

2026-09-05T00:37:53.577661+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 9, 'target': 'gain_abs', 'completed': 1497, 'total': 2688, 'pending': 1191, 'percent_complete': 55.692}

2026-09-05T00:38:06.989029+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 9, 'target': 'z_bayes', 'completed': 1498, 'total': 2688, 'pending': 1190, 'percent_complete': 55.7292}

2026-09-05T00:38:20.384573+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 9, 'target': 'z_heuristic', 'completed': 1499, 'total': 2688, 'pending': 1189, 'percent_complete': 55.7664}

2026-09-05T00:38:22.212362+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 9, 'target': 'reliability_sign', 'completed': 1500, 'total': 2688, 'pending': 1188, 'percent_complete': 55.8036}
2026-09-05T00:38:22.212653+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 10, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1500, 'total': 2688, 'pending': 1188, 'percent_complete': 55.8036}

2026-09-05T00:38:33.282995+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 10, 'target': 'delta_a', 'completed': 1501, 'total': 2688, 'pending': 1187, 'percent_complete': 55.8408}

2026-09-05T00:38:48.785307+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 10, 'target': 'gain', 'completed': 1502, 'total': 2688, 'pending': 1186, 'percent_complete': 55.878}

2026-09-05T00:39:00.283440+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 10, 'target': 'gain_abs', 'completed': 1503, 'total': 2688, 'pending': 1185, 'percent_complete': 55.9152}

2026-09-05T00:39:12.090067+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 10, 'target': 'z_bayes', 'completed': 1504, 'total': 2688, 'pending': 1184, 'percent_complete': 55.9524}

2026-09-05T00:39:25.610563+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 10, 'target': 'z_heuristic', 'completed': 1505, 'total': 2688, 'pending': 1183, 'percent_complete': 55.9896}

2026-09-05T00:39:27.295042+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 10, 'target': 'reliability_sign', 'completed': 1506, 'total': 2688, 'pending': 1182, 'percent_complete': 56.0268}
2026-09-05T00:39:27.295289+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 11, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1506, 'total': 2688, 'pending': 1182, 'percent_complete': 56.0268}

2026-09-05T00:39:38.717190+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 11, 'target': 'delta_a', 'completed': 1507, 'total': 2688, 'pending': 1181, 'percent_complete': 56.064}

2026-09-05T00:39:53.887158+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 11, 'target': 'gain', 'completed': 1508, 'total': 2688, 'pending': 1180, 'percent_complete': 56.1012}

2026-09-05T00:40:09.604068+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 11, 'target': 'gain_abs', 'completed': 1509, 'total': 2688, 'pending': 1179, 'percent_complete': 56.1384}

2026-09-05T00:40:26.981155+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 11, 'target': 'z_bayes', 'completed': 1510, 'total': 2688, 'pending': 1178, 'percent_complete': 56.1756}

2026-09-05T00:40:41.808421+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 11, 'target': 'z_heuristic', 'completed': 1511, 'total': 2688, 'pending': 1177, 'percent_complete': 56.2128}

2026-09-05T00:40:43.776802+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 11, 'target': 'reliability_sign', 'completed': 1512, 'total': 2688, 'pending': 1176, 'percent_complete': 56.25}
2026-09-05T00:40:43.777047+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 12, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1512, 'total': 2688, 'pending': 1176, 'percent_complete': 56.25}

2026-09-05T00:40:56.375964+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 12, 'target': 'delta_a', 'completed': 1513, 'total': 2688, 'pending': 1175, 'percent_complete': 56.2872}

2026-09-05T00:41:10.273503+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 12, 'target': 'gain', 'completed': 1514, 'total': 2688, 'pending': 1174, 'percent_complete': 56.3244}

2026-09-05T00:41:22.999972+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 12, 'target': 'gain_abs', 'completed': 1515, 'total': 2688, 'pending': 1173, 'percent_complete': 56.3616}

2026-09-05T00:41:37.773845+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 12, 'target': 'z_bayes', 'completed': 1516, 'total': 2688, 'pending': 1172, 'percent_complete': 56.3988}

2026-09-05T00:41:53.119719+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 12, 'target': 'z_heuristic', 'completed': 1517, 'total': 2688, 'pending': 1171, 'percent_complete': 56.436}

2026-09-05T00:41:55.098021+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 12, 'target': 'reliability_sign', 'completed': 1518, 'total': 2688, 'pending': 1170, 'percent_complete': 56.4732}
2026-09-05T00:41:55.098289+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 13, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1518, 'total': 2688, 'pending': 1170, 'percent_complete': 56.4732}

2026-09-05T00:42:09.713671+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 13, 'target': 'delta_a', 'completed': 1519, 'total': 2688, 'pending': 1169, 'percent_complete': 56.5104}

2026-09-05T00:42:25.198515+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 13, 'target': 'gain', 'completed': 1520, 'total': 2688, 'pending': 1168, 'percent_complete': 56.5476}

2026-09-05T00:42:43.003752+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 13, 'target': 'gain_abs', 'completed': 1521, 'total': 2688, 'pending': 1167, 'percent_complete': 56.5848}

2026-09-05T00:42:57.910214+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 13, 'target': 'z_bayes', 'completed': 1522, 'total': 2688, 'pending': 1166, 'percent_complete': 56.622}

2026-09-05T00:43:14.313645+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 13, 'target': 'z_heuristic', 'completed': 1523, 'total': 2688, 'pending': 1165, 'percent_complete': 56.6592}

2026-09-05T00:43:16.210287+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 13, 'target': 'reliability_sign', 'completed': 1524, 'total': 2688, 'pending': 1164, 'percent_complete': 56.6964}
2026-09-05T00:43:16.210532+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 14, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1524, 'total': 2688, 'pending': 1164, 'percent_complete': 56.6964}

2026-09-05T00:43:30.277364+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 14, 'target': 'delta_a', 'completed': 1525, 'total': 2688, 'pending': 1163, 'percent_complete': 56.7336}

2026-09-05T00:43:45.480459+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 14, 'target': 'gain', 'completed': 1526, 'total': 2688, 'pending': 1162, 'percent_complete': 56.7708}

2026-09-05T00:44:02.795175+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 14, 'target': 'gain_abs', 'completed': 1527, 'total': 2688, 'pending': 1161, 'percent_complete': 56.808}

2026-09-05T00:44:21.483973+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 14, 'target': 'z_bayes', 'completed': 1528, 'total': 2688, 'pending': 1160, 'percent_complete': 56.8452}

2026-09-05T00:44:35.679317+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 14, 'target': 'z_heuristic', 'completed': 1529, 'total': 2688, 'pending': 1159, 'percent_complete': 56.8824}

2026-09-05T00:44:37.210078+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 14, 'target': 'reliability_sign', 'completed': 1530, 'total': 2688, 'pending': 1158, 'percent_complete': 56.9196}
2026-09-05T00:44:37.210330+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 15, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1530, 'total': 2688, 'pending': 1158, 'percent_complete': 56.9196}

2026-09-05T00:44:57.514749+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 15, 'target': 'delta_a', 'completed': 1531, 'total': 2688, 'pending': 1157, 'percent_complete': 56.9568}

2026-09-05T00:45:17.976908+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 15, 'target': 'gain', 'completed': 1532, 'total': 2688, 'pending': 1156, 'percent_complete': 56.994}

2026-09-05T00:45:37.399661+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 15, 'target': 'gain_abs', 'completed': 1533, 'total': 2688, 'pending': 1155, 'percent_complete': 57.0312}

2026-09-05T00:45:55.801176+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 15, 'target': 'z_bayes', 'completed': 1534, 'total': 2688, 'pending': 1154, 'percent_complete': 57.0685}

2026-09-05T00:46:15.191917+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 15, 'target': 'z_heuristic', 'completed': 1535, 'total': 2688, 'pending': 1153, 'percent_complete': 57.1057}

2026-09-05T00:46:16.674927+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 15, 'target': 'reliability_sign', 'completed': 1536, 'total': 2688, 'pending': 1152, 'percent_complete': 57.1429}
2026-09-05T00:46:16.675235+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 16, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1536, 'total': 2688, 'pending': 1152, 'percent_complete': 57.1429}

2026-09-05T00:46:30.884786+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 16, 'target': 'delta_a', 'completed': 1537, 'total': 2688, 'pending': 1151, 'percent_complete': 57.1801}

2026-09-05T00:46:46.085774+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 16, 'target': 'gain', 'completed': 1538, 'total': 2688, 'pending': 1150, 'percent_complete': 57.2173}

2026-09-05T00:47:01.399826+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 16, 'target': 'gain_abs', 'completed': 1539, 'total': 2688, 'pending': 1149, 'percent_complete': 57.2545}

2026-09-05T00:47:25.289206+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 16, 'target': 'z_bayes', 'completed': 1540, 'total': 2688, 'pending': 1148, 'percent_complete': 57.2917}

2026-09-05T00:47:46.190419+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 16, 'target': 'z_heuristic', 'completed': 1541, 'total': 2688, 'pending': 1147, 'percent_complete': 57.3289}

2026-09-05T00:47:49.403168+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 16, 'target': 'reliability_sign', 'completed': 1542, 'total': 2688, 'pending': 1146, 'percent_complete': 57.3661}
2026-09-05T00:47:49.403439+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 17, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1542, 'total': 2688, 'pending': 1146, 'percent_complete': 57.3661}

2026-09-05T00:48:19.787821+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 17, 'target': 'delta_a', 'completed': 1543, 'total': 2688, 'pending': 1145, 'percent_complete': 57.4033}

2026-09-05T00:48:43.278380+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 17, 'target': 'gain', 'completed': 1544, 'total': 2688, 'pending': 1144, 'percent_complete': 57.4405}

2026-09-05T00:48:59.592297+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 17, 'target': 'gain_abs', 'completed': 1545, 'total': 2688, 'pending': 1143, 'percent_complete': 57.4777}

2026-09-05T00:49:13.798915+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 17, 'target': 'z_bayes', 'completed': 1546, 'total': 2688, 'pending': 1142, 'percent_complete': 57.5149}

2026-09-05T00:49:32.888363+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 17, 'target': 'z_heuristic', 'completed': 1547, 'total': 2688, 'pending': 1141, 'percent_complete': 57.5521}

2026-09-05T00:49:34.496964+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 17, 'target': 'reliability_sign', 'completed': 1548, 'total': 2688, 'pending': 1140, 'percent_complete': 57.5893}
2026-09-05T00:49:34.497212+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 18, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1548, 'total': 2688, 'pending': 1140, 'percent_complete': 57.5893}

2026-09-05T00:49:48.614600+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 18, 'target': 'delta_a', 'completed': 1549, 'total': 2688, 'pending': 1139, 'percent_complete': 57.6265}

2026-09-05T00:50:06.313256+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 18, 'target': 'gain', 'completed': 1550, 'total': 2688, 'pending': 1138, 'percent_complete': 57.6637}

2026-09-05T00:50:23.403228+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 18, 'target': 'gain_abs', 'completed': 1551, 'total': 2688, 'pending': 1137, 'percent_complete': 57.7009}

2026-09-05T00:50:45.518048+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 18, 'target': 'z_bayes', 'completed': 1552, 'total': 2688, 'pending': 1136, 'percent_complete': 57.7381}

2026-09-05T00:51:03.388847+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 18, 'target': 'z_heuristic', 'completed': 1553, 'total': 2688, 'pending': 1135, 'percent_complete': 57.7753}

2026-09-05T00:51:05.173520+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 18, 'target': 'reliability_sign', 'completed': 1554, 'total': 2688, 'pending': 1134, 'percent_complete': 57.8125}
2026-09-05T00:51:05.173884+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 19, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1554, 'total': 2688, 'pending': 1134, 'percent_complete': 57.8125}

2026-09-05T00:51:22.211022+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 19, 'target': 'delta_a', 'completed': 1555, 'total': 2688, 'pending': 1133, 'percent_complete': 57.8497}

2026-09-05T00:51:41.687692+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 19, 'target': 'gain', 'completed': 1556, 'total': 2688, 'pending': 1132, 'percent_complete': 57.8869}

2026-09-05T00:52:00.596691+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 19, 'target': 'gain_abs', 'completed': 1557, 'total': 2688, 'pending': 1131, 'percent_complete': 57.9241}

2026-09-05T00:52:21.214478+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 19, 'target': 'z_bayes', 'completed': 1558, 'total': 2688, 'pending': 1130, 'percent_complete': 57.9613}

2026-09-05T00:52:42.096369+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 19, 'target': 'z_heuristic', 'completed': 1559, 'total': 2688, 'pending': 1129, 'percent_complete': 57.9985}

2026-09-05T00:52:43.798964+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 19, 'target': 'reliability_sign', 'completed': 1560, 'total': 2688, 'pending': 1128, 'percent_complete': 58.0357}
2026-09-05T00:52:43.799215+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 20, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1560, 'total': 2688, 'pending': 1128, 'percent_complete': 58.0357}

2026-09-05T00:53:01.317912+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 20, 'target': 'delta_a', 'completed': 1561, 'total': 2688, 'pending': 1127, 'percent_complete': 58.0729}

2026-09-05T00:53:20.200196+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 20, 'target': 'gain', 'completed': 1562, 'total': 2688, 'pending': 1126, 'percent_complete': 58.1101}

2026-09-05T00:53:40.086744+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 20, 'target': 'gain_abs', 'completed': 1563, 'total': 2688, 'pending': 1125, 'percent_complete': 58.1473}

2026-09-05T00:54:02.614768+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 20, 'target': 'z_bayes', 'completed': 1564, 'total': 2688, 'pending': 1124, 'percent_complete': 58.1845}

2026-09-05T00:54:18.686846+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 20, 'target': 'z_heuristic', 'completed': 1565, 'total': 2688, 'pending': 1123, 'percent_complete': 58.2217}

2026-09-05T00:54:20.374744+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 20, 'target': 'reliability_sign', 'completed': 1566, 'total': 2688, 'pending': 1122, 'percent_complete': 58.2589}
2026-09-05T00:54:20.375097+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 21, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1566, 'total': 2688, 'pending': 1122, 'percent_complete': 58.2589}

2026-09-05T00:54:34.197348+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 21, 'target': 'delta_a', 'completed': 1567, 'total': 2688, 'pending': 1121, 'percent_complete': 58.2961}

2026-09-05T00:54:50.180251+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 21, 'target': 'gain', 'completed': 1568, 'total': 2688, 'pending': 1120, 'percent_complete': 58.3333}

2026-09-05T00:55:04.196826+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 21, 'target': 'gain_abs', 'completed': 1569, 'total': 2688, 'pending': 1119, 'percent_complete': 58.3705}

2026-09-05T00:55:18.715352+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 21, 'target': 'z_bayes', 'completed': 1570, 'total': 2688, 'pending': 1118, 'percent_complete': 58.4077}

2026-09-05T00:55:35.697249+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 21, 'target': 'z_heuristic', 'completed': 1571, 'total': 2688, 'pending': 1117, 'percent_complete': 58.4449}

2026-09-05T00:55:37.672698+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 21, 'target': 'reliability_sign', 'completed': 1572, 'total': 2688, 'pending': 1116, 'percent_complete': 58.4821}
2026-09-05T00:55:37.673019+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 22, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1572, 'total': 2688, 'pending': 1116, 'percent_complete': 58.4821}

2026-09-05T00:55:52.871722+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 22, 'target': 'delta_a', 'completed': 1573, 'total': 2688, 'pending': 1115, 'percent_complete': 58.5193}

2026-09-05T00:56:08.678116+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 22, 'target': 'gain', 'completed': 1574, 'total': 2688, 'pending': 1114, 'percent_complete': 58.5565}

2026-09-05T00:56:27.900205+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 22, 'target': 'gain_abs', 'completed': 1575, 'total': 2688, 'pending': 1113, 'percent_complete': 58.5938}

2026-09-05T00:56:49.775996+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 22, 'target': 'z_bayes', 'completed': 1576, 'total': 2688, 'pending': 1112, 'percent_complete': 58.631}

2026-09-05T00:57:06.975448+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 22, 'target': 'z_heuristic', 'completed': 1577, 'total': 2688, 'pending': 1111, 'percent_complete': 58.6682}

2026-09-05T00:57:08.698914+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 22, 'target': 'reliability_sign', 'completed': 1578, 'total': 2688, 'pending': 1110, 'percent_complete': 58.7054}
2026-09-05T00:57:08.699245+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 23, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1578, 'total': 2688, 'pending': 1110, 'percent_complete': 58.7054}

2026-09-05T00:57:21.596463+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 23, 'target': 'delta_a', 'completed': 1579, 'total': 2688, 'pending': 1109, 'percent_complete': 58.7426}

2026-09-05T00:57:35.096223+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 23, 'target': 'gain', 'completed': 1580, 'total': 2688, 'pending': 1108, 'percent_complete': 58.7798}

2026-09-05T00:57:50.586902+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 23, 'target': 'gain_abs', 'completed': 1581, 'total': 2688, 'pending': 1107, 'percent_complete': 58.817}

2026-09-05T00:58:03.582089+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 23, 'target': 'z_bayes', 'completed': 1582, 'total': 2688, 'pending': 1106, 'percent_complete': 58.8542}

2026-09-05T00:58:17.190409+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 23, 'target': 'z_heuristic', 'completed': 1583, 'total': 2688, 'pending': 1105, 'percent_complete': 58.8914}

2026-09-05T00:58:18.699821+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 23, 'target': 'reliability_sign', 'completed': 1584, 'total': 2688, 'pending': 1104, 'percent_complete': 58.9286}
2026-09-05T00:58:18.700089+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 24, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1584, 'total': 2688, 'pending': 1104, 'percent_complete': 58.9286}

2026-09-05T00:58:32.780173+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 24, 'target': 'delta_a', 'completed': 1585, 'total': 2688, 'pending': 1103, 'percent_complete': 58.9658}

2026-09-05T00:58:46.193053+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 24, 'target': 'gain', 'completed': 1586, 'total': 2688, 'pending': 1102, 'percent_complete': 59.003}

2026-09-05T00:59:00.613268+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 24, 'target': 'gain_abs', 'completed': 1587, 'total': 2688, 'pending': 1101, 'percent_complete': 59.0402}

2026-09-05T00:59:14.616299+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 24, 'target': 'z_bayes', 'completed': 1588, 'total': 2688, 'pending': 1100, 'percent_complete': 59.0774}

2026-09-05T00:59:30.087705+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 24, 'target': 'z_heuristic', 'completed': 1589, 'total': 2688, 'pending': 1099, 'percent_complete': 59.1146}

2026-09-05T00:59:31.603908+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 24, 'target': 'reliability_sign', 'completed': 1590, 'total': 2688, 'pending': 1098, 'percent_complete': 59.1518}
2026-09-05T00:59:31.604202+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 25, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1590, 'total': 2688, 'pending': 1098, 'percent_complete': 59.1518}

2026-09-05T00:59:48.179311+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 25, 'target': 'delta_a', 'completed': 1591, 'total': 2688, 'pending': 1097, 'percent_complete': 59.189}

2026-09-05T01:00:05.974944+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 25, 'target': 'gain', 'completed': 1592, 'total': 2688, 'pending': 1096, 'percent_complete': 59.2262}

2026-09-05T01:00:23.271554+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 25, 'target': 'gain_abs', 'completed': 1593, 'total': 2688, 'pending': 1095, 'percent_complete': 59.2634}

2026-09-05T01:00:41.616396+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 25, 'target': 'z_bayes', 'completed': 1594, 'total': 2688, 'pending': 1094, 'percent_complete': 59.3006}

2026-09-05T01:00:59.085666+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 25, 'target': 'z_heuristic', 'completed': 1595, 'total': 2688, 'pending': 1093, 'percent_complete': 59.3378}

2026-09-05T01:01:01.097067+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 25, 'target': 'reliability_sign', 'completed': 1596, 'total': 2688, 'pending': 1092, 'percent_complete': 59.375}
2026-09-05T01:01:01.097332+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 26, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1596, 'total': 2688, 'pending': 1092, 'percent_complete': 59.375}

2026-09-05T01:01:14.888335+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 26, 'target': 'delta_a', 'completed': 1597, 'total': 2688, 'pending': 1091, 'percent_complete': 59.4122}

2026-09-05T01:01:32.715982+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 26, 'target': 'gain', 'completed': 1598, 'total': 2688, 'pending': 1090, 'percent_complete': 59.4494}

2026-09-05T01:01:48.483067+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 26, 'target': 'gain_abs', 'completed': 1599, 'total': 2688, 'pending': 1089, 'percent_complete': 59.4866}

2026-09-05T01:02:07.813084+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 26, 'target': 'z_bayes', 'completed': 1600, 'total': 2688, 'pending': 1088, 'percent_complete': 59.5238}

2026-09-05T01:02:30.089265+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 26, 'target': 'z_heuristic', 'completed': 1601, 'total': 2688, 'pending': 1087, 'percent_complete': 59.561}

2026-09-05T01:02:31.885784+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 26, 'target': 'reliability_sign', 'completed': 1602, 'total': 2688, 'pending': 1086, 'percent_complete': 59.5982}
2026-09-05T01:02:31.886146+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 27, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1602, 'total': 2688, 'pending': 1086, 'percent_complete': 59.5982}

2026-09-05T01:02:48.216517+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 27, 'target': 'delta_a', 'completed': 1603, 'total': 2688, 'pending': 1085, 'percent_complete': 59.6354}

2026-09-05T01:03:08.681795+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 27, 'target': 'gain', 'completed': 1604, 'total': 2688, 'pending': 1084, 'percent_complete': 59.6726}

2026-09-05T01:03:33.289077+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 27, 'target': 'gain_abs', 'completed': 1605, 'total': 2688, 'pending': 1083, 'percent_complete': 59.7098}

2026-09-05T01:03:52.681432+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 27, 'target': 'z_bayes', 'completed': 1606, 'total': 2688, 'pending': 1082, 'percent_complete': 59.747}

2026-09-05T01:04:07.781302+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 27, 'target': 'z_heuristic', 'completed': 1607, 'total': 2688, 'pending': 1081, 'percent_complete': 59.7842}

2026-09-05T01:04:09.375496+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 27, 'target': 'reliability_sign', 'completed': 1608, 'total': 2688, 'pending': 1080, 'percent_complete': 59.8214}
2026-09-05T01:04:09.375822+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 28, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1608, 'total': 2688, 'pending': 1080, 'percent_complete': 59.8214}

2026-09-05T01:04:27.088637+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 28, 'target': 'delta_a', 'completed': 1609, 'total': 2688, 'pending': 1079, 'percent_complete': 59.8586}

2026-09-05T01:04:45.913858+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 28, 'target': 'gain', 'completed': 1610, 'total': 2688, 'pending': 1078, 'percent_complete': 59.8958}

2026-09-05T01:05:00.111370+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 28, 'target': 'gain_abs', 'completed': 1611, 'total': 2688, 'pending': 1077, 'percent_complete': 59.933}

2026-09-05T01:05:13.513587+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 28, 'target': 'z_bayes', 'completed': 1612, 'total': 2688, 'pending': 1076, 'percent_complete': 59.9702}

2026-09-05T01:05:26.087408+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 28, 'target': 'z_heuristic', 'completed': 1613, 'total': 2688, 'pending': 1075, 'percent_complete': 60.0074}

2026-09-05T01:05:27.804525+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 28, 'target': 'reliability_sign', 'completed': 1614, 'total': 2688, 'pending': 1074, 'percent_complete': 60.0446}
2026-09-05T01:05:27.804816+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 29, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1614, 'total': 2688, 'pending': 1074, 'percent_complete': 60.0446}

2026-09-05T01:05:40.873715+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 29, 'target': 'delta_a', 'completed': 1615, 'total': 2688, 'pending': 1073, 'percent_complete': 60.0818}

2026-09-05T01:05:54.895481+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 29, 'target': 'gain', 'completed': 1616, 'total': 2688, 'pending': 1072, 'percent_complete': 60.119}

2026-09-05T01:06:11.516947+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 29, 'target': 'gain_abs', 'completed': 1617, 'total': 2688, 'pending': 1071, 'percent_complete': 60.1562}

2026-09-05T01:06:27.200963+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 29, 'target': 'z_bayes', 'completed': 1618, 'total': 2688, 'pending': 1070, 'percent_complete': 60.1935}

2026-09-05T01:06:44.186588+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 29, 'target': 'z_heuristic', 'completed': 1619, 'total': 2688, 'pending': 1069, 'percent_complete': 60.2307}

2026-09-05T01:06:45.988912+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 29, 'target': 'reliability_sign', 'completed': 1620, 'total': 2688, 'pending': 1068, 'percent_complete': 60.2679}
2026-09-05T01:06:45.989280+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 30, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1620, 'total': 2688, 'pending': 1068, 'percent_complete': 60.2679}

2026-09-05T01:07:02.792548+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 30, 'target': 'delta_a', 'completed': 1621, 'total': 2688, 'pending': 1067, 'percent_complete': 60.3051}

2026-09-05T01:07:25.294557+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 30, 'target': 'gain', 'completed': 1622, 'total': 2688, 'pending': 1066, 'percent_complete': 60.3423}

2026-09-05T01:07:42.705957+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 30, 'target': 'gain_abs', 'completed': 1623, 'total': 2688, 'pending': 1065, 'percent_complete': 60.3795}

2026-09-05T01:08:05.912326+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 30, 'target': 'z_bayes', 'completed': 1624, 'total': 2688, 'pending': 1064, 'percent_complete': 60.4167}

2026-09-05T01:08:27.602499+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 30, 'target': 'z_heuristic', 'completed': 1625, 'total': 2688, 'pending': 1063, 'percent_complete': 60.4539}

2026-09-05T01:08:29.573794+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 30, 'target': 'reliability_sign', 'completed': 1626, 'total': 2688, 'pending': 1062, 'percent_complete': 60.4911}
2026-09-05T01:08:29.574089+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 31, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1626, 'total': 2688, 'pending': 1062, 'percent_complete': 60.4911}

2026-09-05T01:08:50.006855+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 31, 'target': 'delta_a', 'completed': 1627, 'total': 2688, 'pending': 1061, 'percent_complete': 60.5283}

2026-09-05T01:09:59.380254+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 31, 'target': 'gain', 'completed': 1628, 'total': 2688, 'pending': 1060, 'percent_complete': 60.5655}

2026-09-05T01:10:17.778484+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 31, 'target': 'gain_abs', 'completed': 1629, 'total': 2688, 'pending': 1059, 'percent_complete': 60.6027}

2026-09-05T01:10:42.615458+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 31, 'target': 'z_bayes', 'completed': 1630, 'total': 2688, 'pending': 1058, 'percent_complete': 60.6399}

2026-09-05T01:11:02.195899+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 31, 'target': 'z_heuristic', 'completed': 1631, 'total': 2688, 'pending': 1057, 'percent_complete': 60.6771}

2026-09-05T01:11:04.081114+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line', 'layer': 31, 'target': 'reliability_sign', 'completed': 1632, 'total': 2688, 'pending': 1056, 'percent_complete': 60.7143}
2026-09-05T01:11:06.035159+00:00 PROBE_SITE_CACHE_RELEASED {'reasoning_mode': 'reasoning_off', 'site': 'answer_line'}
2026-09-05T01:11:06.138436+00:00 PROBE_SITE_CACHE_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'site_pending': 192, 'missing_layers': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], 'activation_files': 4480, 'estimated_cache_gib': 2.1875, 'completed': 1632, 'total': 2688, 'pending': 1056, 'percent_complete': 60.7143}

2026-09-05T01:11:12.381750+00:00 cached final_prompt: 256/4480 files

2026-09-05T01:11:18.882998+00:00 cached final_prompt: 512/4480 files

2026-09-05T01:11:25.293459+00:00 cached final_prompt: 768/4480 files

2026-09-05T01:11:32.281046+00:00 cached final_prompt: 1024/4480 files

2026-09-05T01:11:38.774447+00:00 cached final_prompt: 1280/4480 files

2026-09-05T01:11:44.974374+00:00 cached final_prompt: 1536/4480 files

2026-09-05T01:11:52.477569+00:00 cached final_prompt: 1792/4480 files

2026-09-05T01:11:59.479831+00:00 cached final_prompt: 2048/4480 files

2026-09-05T01:12:06.091471+00:00 cached final_prompt: 2304/4480 files

2026-09-05T01:12:12.491634+00:00 cached final_prompt: 2560/4480 files

2026-09-05T01:12:18.873730+00:00 cached final_prompt: 2816/4480 files

2026-09-05T01:12:24.874762+00:00 cached final_prompt: 3072/4480 files

2026-09-05T01:12:30.974184+00:00 cached final_prompt: 3328/4480 files

2026-09-05T01:12:37.076408+00:00 cached final_prompt: 3584/4480 files

2026-09-05T01:12:43.177320+00:00 cached final_prompt: 3840/4480 files

2026-09-05T01:12:49.190510+00:00 cached final_prompt: 4096/4480 files

2026-09-05T01:12:55.483384+00:00 cached final_prompt: 4352/4480 files

2026-09-05T01:12:58.584482+00:00 cached final_prompt: 4480/4480 files
2026-09-05T01:12:58.584747+00:00 PROBE_SITE_CACHE_READY {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'shape': (32, 4480, 4096), 'cache_gib': 2.1875, 'activation_file_opens': 4480}
2026-09-05T01:12:58.584900+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 0, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1632, 'total': 2688, 'pending': 1056, 'percent_complete': 60.7143}

2026-09-05T01:13:17.279570+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 0, 'target': 'delta_a', 'completed': 1633, 'total': 2688, 'pending': 1055, 'percent_complete': 60.7515}

2026-09-05T01:13:36.290697+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 0, 'target': 'gain', 'completed': 1634, 'total': 2688, 'pending': 1054, 'percent_complete': 60.7887}

2026-09-05T01:13:55.589218+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 0, 'target': 'gain_abs', 'completed': 1635, 'total': 2688, 'pending': 1053, 'percent_complete': 60.8259}

2026-09-05T01:14:14.778402+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 0, 'target': 'z_bayes', 'completed': 1636, 'total': 2688, 'pending': 1052, 'percent_complete': 60.8631}

2026-09-05T01:14:34.173878+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 0, 'target': 'z_heuristic', 'completed': 1637, 'total': 2688, 'pending': 1051, 'percent_complete': 60.9003}

2026-09-05T01:14:36.088142+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 0, 'target': 'reliability_sign', 'completed': 1638, 'total': 2688, 'pending': 1050, 'percent_complete': 60.9375}
2026-09-05T01:14:36.088516+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 1, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1638, 'total': 2688, 'pending': 1050, 'percent_complete': 60.9375}

2026-09-05T01:14:55.283755+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 1, 'target': 'delta_a', 'completed': 1639, 'total': 2688, 'pending': 1049, 'percent_complete': 60.9747}

2026-09-05T01:15:13.778221+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 1, 'target': 'gain', 'completed': 1640, 'total': 2688, 'pending': 1048, 'percent_complete': 61.0119}

2026-09-05T01:15:33.202516+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 1, 'target': 'gain_abs', 'completed': 1641, 'total': 2688, 'pending': 1047, 'percent_complete': 61.0491}

2026-09-05T01:15:47.177122+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 1, 'target': 'z_bayes', 'completed': 1642, 'total': 2688, 'pending': 1046, 'percent_complete': 61.0863}

2026-09-05T01:16:06.338908+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 1, 'target': 'z_heuristic', 'completed': 1643, 'total': 2688, 'pending': 1045, 'percent_complete': 61.1235}

2026-09-05T01:16:08.505792+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 1, 'target': 'reliability_sign', 'completed': 1644, 'total': 2688, 'pending': 1044, 'percent_complete': 61.1607}
2026-09-05T01:16:08.506084+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 2, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1644, 'total': 2688, 'pending': 1044, 'percent_complete': 61.1607}

2026-09-05T01:16:29.373549+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 2, 'target': 'delta_a', 'completed': 1645, 'total': 2688, 'pending': 1043, 'percent_complete': 61.1979}

2026-09-05T01:16:49.296335+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 2, 'target': 'gain', 'completed': 1646, 'total': 2688, 'pending': 1042, 'percent_complete': 61.2351}

2026-09-05T01:17:05.916589+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 2, 'target': 'gain_abs', 'completed': 1647, 'total': 2688, 'pending': 1041, 'percent_complete': 61.2723}

2026-09-05T01:17:25.279089+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 2, 'target': 'z_bayes', 'completed': 1648, 'total': 2688, 'pending': 1040, 'percent_complete': 61.3095}

2026-09-05T01:17:44.753929+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 2, 'target': 'z_heuristic', 'completed': 1649, 'total': 2688, 'pending': 1039, 'percent_complete': 61.3467}

2026-09-05T01:17:46.787440+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 2, 'target': 'reliability_sign', 'completed': 1650, 'total': 2688, 'pending': 1038, 'percent_complete': 61.3839}
2026-09-05T01:17:46.787721+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 3, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1650, 'total': 2688, 'pending': 1038, 'percent_complete': 61.3839}

2026-09-05T01:18:07.675652+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 3, 'target': 'delta_a', 'completed': 1651, 'total': 2688, 'pending': 1037, 'percent_complete': 61.4211}

2026-09-05T01:18:24.903075+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 3, 'target': 'gain', 'completed': 1652, 'total': 2688, 'pending': 1036, 'percent_complete': 61.4583}

2026-09-05T01:18:38.622543+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 3, 'target': 'gain_abs', 'completed': 1653, 'total': 2688, 'pending': 1035, 'percent_complete': 61.4955}

2026-09-05T01:18:53.575835+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 3, 'target': 'z_bayes', 'completed': 1654, 'total': 2688, 'pending': 1034, 'percent_complete': 61.5327}

2026-09-05T01:19:07.772871+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 3, 'target': 'z_heuristic', 'completed': 1655, 'total': 2688, 'pending': 1033, 'percent_complete': 61.5699}

2026-09-05T01:19:09.989917+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 3, 'target': 'reliability_sign', 'completed': 1656, 'total': 2688, 'pending': 1032, 'percent_complete': 61.6071}
2026-09-05T01:19:09.990224+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 4, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1656, 'total': 2688, 'pending': 1032, 'percent_complete': 61.6071}

2026-09-05T01:19:26.174712+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 4, 'target': 'delta_a', 'completed': 1657, 'total': 2688, 'pending': 1031, 'percent_complete': 61.6443}

2026-09-05T01:19:44.987207+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 4, 'target': 'gain', 'completed': 1658, 'total': 2688, 'pending': 1030, 'percent_complete': 61.6815}

2026-09-05T01:20:06.100215+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 4, 'target': 'gain_abs', 'completed': 1659, 'total': 2688, 'pending': 1029, 'percent_complete': 61.7188}

2026-09-05T01:20:25.371338+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 4, 'target': 'z_bayes', 'completed': 1660, 'total': 2688, 'pending': 1028, 'percent_complete': 61.756}

2026-09-05T01:20:45.635840+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 4, 'target': 'z_heuristic', 'completed': 1661, 'total': 2688, 'pending': 1027, 'percent_complete': 61.7932}

2026-09-05T01:20:47.673219+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 4, 'target': 'reliability_sign', 'completed': 1662, 'total': 2688, 'pending': 1026, 'percent_complete': 61.8304}
2026-09-05T01:20:47.673518+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 5, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1662, 'total': 2688, 'pending': 1026, 'percent_complete': 61.8304}

2026-09-05T01:21:09.174991+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 5, 'target': 'delta_a', 'completed': 1663, 'total': 2688, 'pending': 1025, 'percent_complete': 61.8676}

2026-09-05T01:21:29.405034+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 5, 'target': 'gain', 'completed': 1664, 'total': 2688, 'pending': 1024, 'percent_complete': 61.9048}

2026-09-05T01:21:48.694285+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 5, 'target': 'gain_abs', 'completed': 1665, 'total': 2688, 'pending': 1023, 'percent_complete': 61.942}

2026-09-05T01:22:03.775381+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 5, 'target': 'z_bayes', 'completed': 1666, 'total': 2688, 'pending': 1022, 'percent_complete': 61.9792}

2026-09-05T01:22:25.989707+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 5, 'target': 'z_heuristic', 'completed': 1667, 'total': 2688, 'pending': 1021, 'percent_complete': 62.0164}

2026-09-05T01:22:28.075852+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 5, 'target': 'reliability_sign', 'completed': 1668, 'total': 2688, 'pending': 1020, 'percent_complete': 62.0536}
2026-09-05T01:22:28.076142+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 6, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1668, 'total': 2688, 'pending': 1020, 'percent_complete': 62.0536}

2026-09-05T01:22:47.375445+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 6, 'target': 'delta_a', 'completed': 1669, 'total': 2688, 'pending': 1019, 'percent_complete': 62.0908}

2026-09-05T01:23:07.215430+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 6, 'target': 'gain', 'completed': 1670, 'total': 2688, 'pending': 1018, 'percent_complete': 62.128}

2026-09-05T01:23:24.204866+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 6, 'target': 'gain_abs', 'completed': 1671, 'total': 2688, 'pending': 1017, 'percent_complete': 62.1652}

2026-09-05T01:23:39.674375+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 6, 'target': 'z_bayes', 'completed': 1672, 'total': 2688, 'pending': 1016, 'percent_complete': 62.2024}

2026-09-05T01:23:57.704820+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 6, 'target': 'z_heuristic', 'completed': 1673, 'total': 2688, 'pending': 1015, 'percent_complete': 62.2396}

2026-09-05T01:23:59.485857+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 6, 'target': 'reliability_sign', 'completed': 1674, 'total': 2688, 'pending': 1014, 'percent_complete': 62.2768}
2026-09-05T01:23:59.486223+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 7, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1674, 'total': 2688, 'pending': 1014, 'percent_complete': 62.2768}

2026-09-05T01:24:24.684914+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 7, 'target': 'delta_a', 'completed': 1675, 'total': 2688, 'pending': 1013, 'percent_complete': 62.314}

2026-09-05T01:24:47.071463+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 7, 'target': 'gain', 'completed': 1676, 'total': 2688, 'pending': 1012, 'percent_complete': 62.3512}

2026-09-05T01:25:08.474566+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 7, 'target': 'gain_abs', 'completed': 1677, 'total': 2688, 'pending': 1011, 'percent_complete': 62.3884}

2026-09-05T01:25:28.778362+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 7, 'target': 'z_bayes', 'completed': 1678, 'total': 2688, 'pending': 1010, 'percent_complete': 62.4256}

2026-09-05T01:25:50.583504+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 7, 'target': 'z_heuristic', 'completed': 1679, 'total': 2688, 'pending': 1009, 'percent_complete': 62.4628}

2026-09-05T01:25:52.601063+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 7, 'target': 'reliability_sign', 'completed': 1680, 'total': 2688, 'pending': 1008, 'percent_complete': 62.5}
2026-09-05T01:25:52.601383+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 8, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1680, 'total': 2688, 'pending': 1008, 'percent_complete': 62.5}

2026-09-05T01:26:17.203816+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 8, 'target': 'delta_a', 'completed': 1681, 'total': 2688, 'pending': 1007, 'percent_complete': 62.5372}

2026-09-05T01:26:35.994989+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 8, 'target': 'gain', 'completed': 1682, 'total': 2688, 'pending': 1006, 'percent_complete': 62.5744}

2026-09-05T01:26:52.899196+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 8, 'target': 'gain_abs', 'completed': 1683, 'total': 2688, 'pending': 1005, 'percent_complete': 62.6116}

2026-09-05T01:27:16.475845+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 8, 'target': 'z_bayes', 'completed': 1684, 'total': 2688, 'pending': 1004, 'percent_complete': 62.6488}

2026-09-05T01:27:36.992026+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 8, 'target': 'z_heuristic', 'completed': 1685, 'total': 2688, 'pending': 1003, 'percent_complete': 62.686}

2026-09-05T01:27:38.972256+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 8, 'target': 'reliability_sign', 'completed': 1686, 'total': 2688, 'pending': 1002, 'percent_complete': 62.7232}
2026-09-05T01:27:38.972522+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 9, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1686, 'total': 2688, 'pending': 1002, 'percent_complete': 62.7232}

2026-09-05T01:28:00.400029+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 9, 'target': 'delta_a', 'completed': 1687, 'total': 2688, 'pending': 1001, 'percent_complete': 62.7604}

2026-09-05T01:28:25.594260+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 9, 'target': 'gain', 'completed': 1688, 'total': 2688, 'pending': 1000, 'percent_complete': 62.7976}

2026-09-05T01:28:45.315371+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 9, 'target': 'gain_abs', 'completed': 1689, 'total': 2688, 'pending': 999, 'percent_complete': 62.8348}

2026-09-05T01:29:11.775509+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 9, 'target': 'z_bayes', 'completed': 1690, 'total': 2688, 'pending': 998, 'percent_complete': 62.872}

2026-09-05T01:29:35.793141+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 9, 'target': 'z_heuristic', 'completed': 1691, 'total': 2688, 'pending': 997, 'percent_complete': 62.9092}

2026-09-05T01:29:37.374654+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 9, 'target': 'reliability_sign', 'completed': 1692, 'total': 2688, 'pending': 996, 'percent_complete': 62.9464}
2026-09-05T01:29:37.374897+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 10, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1692, 'total': 2688, 'pending': 996, 'percent_complete': 62.9464}

2026-09-05T01:29:52.172968+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 10, 'target': 'delta_a', 'completed': 1693, 'total': 2688, 'pending': 995, 'percent_complete': 62.9836}

2026-09-05T01:30:07.080466+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 10, 'target': 'gain', 'completed': 1694, 'total': 2688, 'pending': 994, 'percent_complete': 63.0208}

2026-09-05T01:30:23.072822+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 10, 'target': 'gain_abs', 'completed': 1695, 'total': 2688, 'pending': 993, 'percent_complete': 63.058}

2026-09-05T01:30:35.173043+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 10, 'target': 'z_bayes', 'completed': 1696, 'total': 2688, 'pending': 992, 'percent_complete': 63.0952}

2026-09-05T01:30:47.904902+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 10, 'target': 'z_heuristic', 'completed': 1697, 'total': 2688, 'pending': 991, 'percent_complete': 63.1324}

2026-09-05T01:30:49.400810+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 10, 'target': 'reliability_sign', 'completed': 1698, 'total': 2688, 'pending': 990, 'percent_complete': 63.1696}
2026-09-05T01:30:49.401194+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 11, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1698, 'total': 2688, 'pending': 990, 'percent_complete': 63.1696}

2026-09-05T01:31:03.710817+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 11, 'target': 'delta_a', 'completed': 1699, 'total': 2688, 'pending': 989, 'percent_complete': 63.2068}

2026-09-05T01:31:16.893576+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 11, 'target': 'gain', 'completed': 1700, 'total': 2688, 'pending': 988, 'percent_complete': 63.244}

2026-09-05T01:31:30.905373+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 11, 'target': 'gain_abs', 'completed': 1701, 'total': 2688, 'pending': 987, 'percent_complete': 63.2812}

2026-09-05T01:31:47.775443+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 11, 'target': 'z_bayes', 'completed': 1702, 'total': 2688, 'pending': 986, 'percent_complete': 63.3185}

2026-09-05T01:32:03.697636+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 11, 'target': 'z_heuristic', 'completed': 1703, 'total': 2688, 'pending': 985, 'percent_complete': 63.3557}

2026-09-05T01:32:05.090264+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 11, 'target': 'reliability_sign', 'completed': 1704, 'total': 2688, 'pending': 984, 'percent_complete': 63.3929}
2026-09-05T01:32:05.090652+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 12, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1704, 'total': 2688, 'pending': 984, 'percent_complete': 63.3929}

2026-09-05T01:32:19.499670+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 12, 'target': 'delta_a', 'completed': 1705, 'total': 2688, 'pending': 983, 'percent_complete': 63.4301}

2026-09-05T01:32:33.491466+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 12, 'target': 'gain', 'completed': 1706, 'total': 2688, 'pending': 982, 'percent_complete': 63.4673}

2026-09-05T01:32:50.686572+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 12, 'target': 'gain_abs', 'completed': 1707, 'total': 2688, 'pending': 981, 'percent_complete': 63.5045}

2026-09-05T01:33:05.186328+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 12, 'target': 'z_bayes', 'completed': 1708, 'total': 2688, 'pending': 980, 'percent_complete': 63.5417}

2026-09-05T01:33:18.574213+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 12, 'target': 'z_heuristic', 'completed': 1709, 'total': 2688, 'pending': 979, 'percent_complete': 63.5789}

2026-09-05T01:33:19.902659+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 12, 'target': 'reliability_sign', 'completed': 1710, 'total': 2688, 'pending': 978, 'percent_complete': 63.6161}
2026-09-05T01:33:19.902907+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 13, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1710, 'total': 2688, 'pending': 978, 'percent_complete': 63.6161}

2026-09-05T01:33:38.199743+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 13, 'target': 'delta_a', 'completed': 1711, 'total': 2688, 'pending': 977, 'percent_complete': 63.6533}

2026-09-05T01:33:56.507401+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 13, 'target': 'gain', 'completed': 1712, 'total': 2688, 'pending': 976, 'percent_complete': 63.6905}

2026-09-05T01:34:11.886788+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 13, 'target': 'gain_abs', 'completed': 1713, 'total': 2688, 'pending': 975, 'percent_complete': 63.7277}

2026-09-05T01:34:28.888772+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 13, 'target': 'z_bayes', 'completed': 1714, 'total': 2688, 'pending': 974, 'percent_complete': 63.7649}

2026-09-05T01:34:42.971342+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 13, 'target': 'z_heuristic', 'completed': 1715, 'total': 2688, 'pending': 973, 'percent_complete': 63.8021}

2026-09-05T01:34:44.598507+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 13, 'target': 'reliability_sign', 'completed': 1716, 'total': 2688, 'pending': 972, 'percent_complete': 63.8393}
2026-09-05T01:34:44.598808+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 14, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1716, 'total': 2688, 'pending': 972, 'percent_complete': 63.8393}

2026-09-05T01:34:57.790081+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 14, 'target': 'delta_a', 'completed': 1717, 'total': 2688, 'pending': 971, 'percent_complete': 63.8765}

2026-09-05T01:35:11.200670+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 14, 'target': 'gain', 'completed': 1718, 'total': 2688, 'pending': 970, 'percent_complete': 63.9137}

2026-09-05T01:35:24.590599+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 14, 'target': 'gain_abs', 'completed': 1719, 'total': 2688, 'pending': 969, 'percent_complete': 63.9509}

2026-09-05T01:35:37.995961+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 14, 'target': 'z_bayes', 'completed': 1720, 'total': 2688, 'pending': 968, 'percent_complete': 63.9881}

2026-09-05T01:35:50.307279+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 14, 'target': 'z_heuristic', 'completed': 1721, 'total': 2688, 'pending': 967, 'percent_complete': 64.0253}

2026-09-05T01:35:51.801405+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 14, 'target': 'reliability_sign', 'completed': 1722, 'total': 2688, 'pending': 966, 'percent_complete': 64.0625}
2026-09-05T01:35:51.801650+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 15, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1722, 'total': 2688, 'pending': 966, 'percent_complete': 64.0625}

2026-09-05T01:36:06.586220+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 15, 'target': 'delta_a', 'completed': 1723, 'total': 2688, 'pending': 965, 'percent_complete': 64.0997}

2026-09-05T01:36:22.672430+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 15, 'target': 'gain', 'completed': 1724, 'total': 2688, 'pending': 964, 'percent_complete': 64.1369}

2026-09-05T01:36:37.100317+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 15, 'target': 'gain_abs', 'completed': 1725, 'total': 2688, 'pending': 963, 'percent_complete': 64.1741}

2026-09-05T01:36:50.575994+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 15, 'target': 'z_bayes', 'completed': 1726, 'total': 2688, 'pending': 962, 'percent_complete': 64.2113}

2026-09-05T01:37:05.096483+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 15, 'target': 'z_heuristic', 'completed': 1727, 'total': 2688, 'pending': 961, 'percent_complete': 64.2485}

2026-09-05T01:37:06.776073+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 15, 'target': 'reliability_sign', 'completed': 1728, 'total': 2688, 'pending': 960, 'percent_complete': 64.2857}
2026-09-05T01:37:06.776367+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 16, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1728, 'total': 2688, 'pending': 960, 'percent_complete': 64.2857}

2026-09-05T01:37:19.273065+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 16, 'target': 'delta_a', 'completed': 1729, 'total': 2688, 'pending': 959, 'percent_complete': 64.3229}

2026-09-05T01:37:35.017077+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 16, 'target': 'gain', 'completed': 1730, 'total': 2688, 'pending': 958, 'percent_complete': 64.3601}

2026-09-05T01:37:51.086760+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 16, 'target': 'gain_abs', 'completed': 1731, 'total': 2688, 'pending': 957, 'percent_complete': 64.3973}

2026-09-05T01:38:06.871452+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 16, 'target': 'z_bayes', 'completed': 1732, 'total': 2688, 'pending': 956, 'percent_complete': 64.4345}

2026-09-05T01:38:23.584521+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 16, 'target': 'z_heuristic', 'completed': 1733, 'total': 2688, 'pending': 955, 'percent_complete': 64.4717}

2026-09-05T01:38:25.192335+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 16, 'target': 'reliability_sign', 'completed': 1734, 'total': 2688, 'pending': 954, 'percent_complete': 64.5089}
2026-09-05T01:38:25.192624+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 17, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1734, 'total': 2688, 'pending': 954, 'percent_complete': 64.5089}

2026-09-05T01:38:39.300408+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 17, 'target': 'delta_a', 'completed': 1735, 'total': 2688, 'pending': 953, 'percent_complete': 64.5461}

2026-09-05T01:38:52.605838+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 17, 'target': 'gain', 'completed': 1736, 'total': 2688, 'pending': 952, 'percent_complete': 64.5833}

2026-09-05T01:39:07.700413+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 17, 'target': 'gain_abs', 'completed': 1737, 'total': 2688, 'pending': 951, 'percent_complete': 64.6205}

2026-09-05T01:39:19.884517+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 17, 'target': 'z_bayes', 'completed': 1738, 'total': 2688, 'pending': 950, 'percent_complete': 64.6577}

2026-09-05T01:39:32.015462+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 17, 'target': 'z_heuristic', 'completed': 1739, 'total': 2688, 'pending': 949, 'percent_complete': 64.6949}

2026-09-05T01:39:33.576092+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 17, 'target': 'reliability_sign', 'completed': 1740, 'total': 2688, 'pending': 948, 'percent_complete': 64.7321}
2026-09-05T01:39:33.576396+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 18, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1740, 'total': 2688, 'pending': 948, 'percent_complete': 64.7321}

2026-09-05T01:39:46.800354+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 18, 'target': 'delta_a', 'completed': 1741, 'total': 2688, 'pending': 947, 'percent_complete': 64.7693}

2026-09-05T01:40:01.114956+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 18, 'target': 'gain', 'completed': 1742, 'total': 2688, 'pending': 946, 'percent_complete': 64.8065}

2026-09-05T01:40:17.097908+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 18, 'target': 'gain_abs', 'completed': 1743, 'total': 2688, 'pending': 945, 'percent_complete': 64.8438}

2026-09-05T01:40:32.877982+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 18, 'target': 'z_bayes', 'completed': 1744, 'total': 2688, 'pending': 944, 'percent_complete': 64.881}

2026-09-05T01:40:50.791292+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 18, 'target': 'z_heuristic', 'completed': 1745, 'total': 2688, 'pending': 943, 'percent_complete': 64.9182}

2026-09-05T01:40:52.296432+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 18, 'target': 'reliability_sign', 'completed': 1746, 'total': 2688, 'pending': 942, 'percent_complete': 64.9554}
2026-09-05T01:40:52.296674+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 19, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1746, 'total': 2688, 'pending': 942, 'percent_complete': 64.9554}

2026-09-05T01:41:06.893074+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 19, 'target': 'delta_a', 'completed': 1747, 'total': 2688, 'pending': 941, 'percent_complete': 64.9926}

2026-09-05T01:41:24.301430+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 19, 'target': 'gain', 'completed': 1748, 'total': 2688, 'pending': 940, 'percent_complete': 65.0298}

2026-09-05T01:41:39.802780+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 19, 'target': 'gain_abs', 'completed': 1749, 'total': 2688, 'pending': 939, 'percent_complete': 65.067}

2026-09-05T01:41:55.679025+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 19, 'target': 'z_bayes', 'completed': 1750, 'total': 2688, 'pending': 938, 'percent_complete': 65.1042}

2026-09-05T01:42:11.903698+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 19, 'target': 'z_heuristic', 'completed': 1751, 'total': 2688, 'pending': 937, 'percent_complete': 65.1414}

2026-09-05T01:42:13.576356+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 19, 'target': 'reliability_sign', 'completed': 1752, 'total': 2688, 'pending': 936, 'percent_complete': 65.1786}
2026-09-05T01:42:13.576656+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 20, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1752, 'total': 2688, 'pending': 936, 'percent_complete': 65.1786}

2026-09-05T01:42:26.877129+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 20, 'target': 'delta_a', 'completed': 1753, 'total': 2688, 'pending': 935, 'percent_complete': 65.2158}

2026-09-05T01:42:42.303431+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 20, 'target': 'gain', 'completed': 1754, 'total': 2688, 'pending': 934, 'percent_complete': 65.253}

2026-09-05T01:42:56.599052+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 20, 'target': 'gain_abs', 'completed': 1755, 'total': 2688, 'pending': 933, 'percent_complete': 65.2902}

2026-09-05T01:43:13.911043+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 20, 'target': 'z_bayes', 'completed': 1756, 'total': 2688, 'pending': 932, 'percent_complete': 65.3274}

2026-09-05T01:43:32.090386+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 20, 'target': 'z_heuristic', 'completed': 1757, 'total': 2688, 'pending': 931, 'percent_complete': 65.3646}

2026-09-05T01:43:33.600637+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 20, 'target': 'reliability_sign', 'completed': 1758, 'total': 2688, 'pending': 930, 'percent_complete': 65.4018}
2026-09-05T01:43:33.600881+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 21, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1758, 'total': 2688, 'pending': 930, 'percent_complete': 65.4018}

2026-09-05T01:43:47.410075+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 21, 'target': 'delta_a', 'completed': 1759, 'total': 2688, 'pending': 929, 'percent_complete': 65.439}

2026-09-05T01:43:59.888066+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 21, 'target': 'gain', 'completed': 1760, 'total': 2688, 'pending': 928, 'percent_complete': 65.4762}

2026-09-05T01:44:14.181985+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 21, 'target': 'gain_abs', 'completed': 1761, 'total': 2688, 'pending': 927, 'percent_complete': 65.5134}

2026-09-05T01:44:28.676758+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 21, 'target': 'z_bayes', 'completed': 1762, 'total': 2688, 'pending': 926, 'percent_complete': 65.5506}

2026-09-05T01:44:44.809133+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 21, 'target': 'z_heuristic', 'completed': 1763, 'total': 2688, 'pending': 925, 'percent_complete': 65.5878}

2026-09-05T01:44:46.589643+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 21, 'target': 'reliability_sign', 'completed': 1764, 'total': 2688, 'pending': 924, 'percent_complete': 65.625}
2026-09-05T01:44:46.589924+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 22, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1764, 'total': 2688, 'pending': 924, 'percent_complete': 65.625}

2026-09-05T01:45:00.023855+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 22, 'target': 'delta_a', 'completed': 1765, 'total': 2688, 'pending': 923, 'percent_complete': 65.6622}

2026-09-05T01:45:14.276273+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 22, 'target': 'gain', 'completed': 1766, 'total': 2688, 'pending': 922, 'percent_complete': 65.6994}

2026-09-05T01:45:32.402645+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 22, 'target': 'gain_abs', 'completed': 1767, 'total': 2688, 'pending': 921, 'percent_complete': 65.7366}

2026-09-05T01:45:45.872340+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 22, 'target': 'z_bayes', 'completed': 1768, 'total': 2688, 'pending': 920, 'percent_complete': 65.7738}

2026-09-05T01:46:02.917099+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 22, 'target': 'z_heuristic', 'completed': 1769, 'total': 2688, 'pending': 919, 'percent_complete': 65.811}

2026-09-05T01:46:04.511075+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 22, 'target': 'reliability_sign', 'completed': 1770, 'total': 2688, 'pending': 918, 'percent_complete': 65.8482}
2026-09-05T01:46:04.511315+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 23, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1770, 'total': 2688, 'pending': 918, 'percent_complete': 65.8482}

2026-09-05T01:46:19.304567+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 23, 'target': 'delta_a', 'completed': 1771, 'total': 2688, 'pending': 917, 'percent_complete': 65.8854}

2026-09-05T01:46:33.175216+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 23, 'target': 'gain', 'completed': 1772, 'total': 2688, 'pending': 916, 'percent_complete': 65.9226}

2026-09-05T01:46:48.097643+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 23, 'target': 'gain_abs', 'completed': 1773, 'total': 2688, 'pending': 915, 'percent_complete': 65.9598}

2026-09-05T01:47:00.298884+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 23, 'target': 'z_bayes', 'completed': 1774, 'total': 2688, 'pending': 914, 'percent_complete': 65.997}

2026-09-05T01:47:17.092110+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 23, 'target': 'z_heuristic', 'completed': 1775, 'total': 2688, 'pending': 913, 'percent_complete': 66.0342}

2026-09-05T01:47:18.878310+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 23, 'target': 'reliability_sign', 'completed': 1776, 'total': 2688, 'pending': 912, 'percent_complete': 66.0714}
2026-09-05T01:47:18.878547+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 24, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1776, 'total': 2688, 'pending': 912, 'percent_complete': 66.0714}

2026-09-05T01:47:34.392319+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 24, 'target': 'delta_a', 'completed': 1777, 'total': 2688, 'pending': 911, 'percent_complete': 66.1086}

2026-09-05T01:47:49.002602+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 24, 'target': 'gain', 'completed': 1778, 'total': 2688, 'pending': 910, 'percent_complete': 66.1458}

2026-09-05T01:48:06.491106+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 24, 'target': 'gain_abs', 'completed': 1779, 'total': 2688, 'pending': 909, 'percent_complete': 66.183}

2026-09-05T01:48:20.281443+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 24, 'target': 'z_bayes', 'completed': 1780, 'total': 2688, 'pending': 908, 'percent_complete': 66.2202}

2026-09-05T01:48:36.213389+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 24, 'target': 'z_heuristic', 'completed': 1781, 'total': 2688, 'pending': 907, 'percent_complete': 66.2574}

2026-09-05T01:48:37.788764+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 24, 'target': 'reliability_sign', 'completed': 1782, 'total': 2688, 'pending': 906, 'percent_complete': 66.2946}
2026-09-05T01:48:37.789132+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 25, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1782, 'total': 2688, 'pending': 906, 'percent_complete': 66.2946}

2026-09-05T01:48:53.892388+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 25, 'target': 'delta_a', 'completed': 1783, 'total': 2688, 'pending': 905, 'percent_complete': 66.3318}

2026-09-05T01:49:07.904088+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 25, 'target': 'gain', 'completed': 1784, 'total': 2688, 'pending': 904, 'percent_complete': 66.369}

2026-09-05T01:49:21.618925+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 25, 'target': 'gain_abs', 'completed': 1785, 'total': 2688, 'pending': 903, 'percent_complete': 66.4062}

2026-09-05T01:49:38.081906+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 25, 'target': 'z_bayes', 'completed': 1786, 'total': 2688, 'pending': 902, 'percent_complete': 66.4435}

2026-09-05T01:49:51.285811+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 25, 'target': 'z_heuristic', 'completed': 1787, 'total': 2688, 'pending': 901, 'percent_complete': 66.4807}

2026-09-05T01:49:52.803726+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 25, 'target': 'reliability_sign', 'completed': 1788, 'total': 2688, 'pending': 900, 'percent_complete': 66.5179}
2026-09-05T01:49:52.803975+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 26, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1788, 'total': 2688, 'pending': 900, 'percent_complete': 66.5179}

2026-09-05T01:50:08.403216+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 26, 'target': 'delta_a', 'completed': 1789, 'total': 2688, 'pending': 899, 'percent_complete': 66.5551}

2026-09-05T01:50:24.673688+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 26, 'target': 'gain', 'completed': 1790, 'total': 2688, 'pending': 898, 'percent_complete': 66.5923}

2026-09-05T01:50:38.007063+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 26, 'target': 'gain_abs', 'completed': 1791, 'total': 2688, 'pending': 897, 'percent_complete': 66.6295}

2026-09-05T01:50:51.522661+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 26, 'target': 'z_bayes', 'completed': 1792, 'total': 2688, 'pending': 896, 'percent_complete': 66.6667}

2026-09-05T01:51:06.594158+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 26, 'target': 'z_heuristic', 'completed': 1793, 'total': 2688, 'pending': 895, 'percent_complete': 66.7039}

2026-09-05T01:51:08.002720+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 26, 'target': 'reliability_sign', 'completed': 1794, 'total': 2688, 'pending': 894, 'percent_complete': 66.7411}
2026-09-05T01:51:08.002983+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 27, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1794, 'total': 2688, 'pending': 894, 'percent_complete': 66.7411}

2026-09-05T01:51:22.284630+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 27, 'target': 'delta_a', 'completed': 1795, 'total': 2688, 'pending': 893, 'percent_complete': 66.7783}

2026-09-05T01:51:36.402551+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 27, 'target': 'gain', 'completed': 1796, 'total': 2688, 'pending': 892, 'percent_complete': 66.8155}

2026-09-05T01:51:52.900445+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 27, 'target': 'gain_abs', 'completed': 1797, 'total': 2688, 'pending': 891, 'percent_complete': 66.8527}

2026-09-05T01:52:06.780981+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 27, 'target': 'z_bayes', 'completed': 1798, 'total': 2688, 'pending': 890, 'percent_complete': 66.8899}

2026-09-05T01:52:22.007886+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 27, 'target': 'z_heuristic', 'completed': 1799, 'total': 2688, 'pending': 889, 'percent_complete': 66.9271}

2026-09-05T01:52:23.702443+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 27, 'target': 'reliability_sign', 'completed': 1800, 'total': 2688, 'pending': 888, 'percent_complete': 66.9643}
2026-09-05T01:52:23.702738+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 28, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1800, 'total': 2688, 'pending': 888, 'percent_complete': 66.9643}

2026-09-05T01:52:38.716779+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 28, 'target': 'delta_a', 'completed': 1801, 'total': 2688, 'pending': 887, 'percent_complete': 67.0015}

2026-09-05T01:52:53.304230+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 28, 'target': 'gain', 'completed': 1802, 'total': 2688, 'pending': 886, 'percent_complete': 67.0387}

2026-09-05T01:53:13.371368+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 28, 'target': 'gain_abs', 'completed': 1803, 'total': 2688, 'pending': 885, 'percent_complete': 67.0759}

2026-09-05T01:53:26.898496+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 28, 'target': 'z_bayes', 'completed': 1804, 'total': 2688, 'pending': 884, 'percent_complete': 67.1131}

2026-09-05T01:53:42.117680+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 28, 'target': 'z_heuristic', 'completed': 1805, 'total': 2688, 'pending': 883, 'percent_complete': 67.1503}

2026-09-05T01:53:43.904654+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 28, 'target': 'reliability_sign', 'completed': 1806, 'total': 2688, 'pending': 882, 'percent_complete': 67.1875}
2026-09-05T01:53:43.904890+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 29, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1806, 'total': 2688, 'pending': 882, 'percent_complete': 67.1875}

2026-09-05T01:54:00.197769+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 29, 'target': 'delta_a', 'completed': 1807, 'total': 2688, 'pending': 881, 'percent_complete': 67.2247}

2026-09-05T01:54:14.585841+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 29, 'target': 'gain', 'completed': 1808, 'total': 2688, 'pending': 880, 'percent_complete': 67.2619}

2026-09-05T01:54:30.694018+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 29, 'target': 'gain_abs', 'completed': 1809, 'total': 2688, 'pending': 879, 'percent_complete': 67.2991}

2026-09-05T01:54:46.178966+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 29, 'target': 'z_bayes', 'completed': 1810, 'total': 2688, 'pending': 878, 'percent_complete': 67.3363}

2026-09-05T01:55:02.183505+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 29, 'target': 'z_heuristic', 'completed': 1811, 'total': 2688, 'pending': 877, 'percent_complete': 67.3735}

2026-09-05T01:55:03.978226+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 29, 'target': 'reliability_sign', 'completed': 1812, 'total': 2688, 'pending': 876, 'percent_complete': 67.4107}
2026-09-05T01:55:03.978511+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 30, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1812, 'total': 2688, 'pending': 876, 'percent_complete': 67.4107}

2026-09-05T01:55:18.116734+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 30, 'target': 'delta_a', 'completed': 1813, 'total': 2688, 'pending': 875, 'percent_complete': 67.4479}

2026-09-05T01:55:30.783124+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 30, 'target': 'gain', 'completed': 1814, 'total': 2688, 'pending': 874, 'percent_complete': 67.4851}

2026-09-05T01:55:44.683954+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 30, 'target': 'gain_abs', 'completed': 1815, 'total': 2688, 'pending': 873, 'percent_complete': 67.5223}

2026-09-05T01:56:00.678578+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 30, 'target': 'z_bayes', 'completed': 1816, 'total': 2688, 'pending': 872, 'percent_complete': 67.5595}

2026-09-05T01:56:17.988736+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 30, 'target': 'z_heuristic', 'completed': 1817, 'total': 2688, 'pending': 871, 'percent_complete': 67.5967}

2026-09-05T01:56:19.701567+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 30, 'target': 'reliability_sign', 'completed': 1818, 'total': 2688, 'pending': 870, 'percent_complete': 67.6339}
2026-09-05T01:56:19.701816+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 31, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1818, 'total': 2688, 'pending': 870, 'percent_complete': 67.6339}

2026-09-05T01:56:34.415535+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 31, 'target': 'delta_a', 'completed': 1819, 'total': 2688, 'pending': 869, 'percent_complete': 67.6711}

2026-09-05T01:56:49.513820+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 31, 'target': 'gain', 'completed': 1820, 'total': 2688, 'pending': 868, 'percent_complete': 67.7083}

2026-09-05T01:57:08.714601+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 31, 'target': 'gain_abs', 'completed': 1821, 'total': 2688, 'pending': 867, 'percent_complete': 67.7455}

2026-09-05T01:57:22.397670+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 31, 'target': 'z_bayes', 'completed': 1822, 'total': 2688, 'pending': 866, 'percent_complete': 67.7827}

2026-09-05T01:57:39.687656+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 31, 'target': 'z_heuristic', 'completed': 1823, 'total': 2688, 'pending': 865, 'percent_complete': 67.8199}

2026-09-05T01:57:41.205466+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt', 'layer': 31, 'target': 'reliability_sign', 'completed': 1824, 'total': 2688, 'pending': 864, 'percent_complete': 67.8571}
2026-09-05T01:57:42.987460+00:00 PROBE_SITE_CACHE_RELEASED {'reasoning_mode': 'reasoning_off', 'site': 'final_prompt'}
2026-09-05T01:57:43.094358+00:00 PROBE_SITE_CACHE_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'site_pending': 192, 'missing_layers': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], 'activation_files': 4480, 'estimated_cache_gib': 2.1875, 'completed': 1824, 'total': 2688, 'pending': 864, 'percent_complete': 67.8571}

2026-09-05T01:57:53.291957+00:00 cached assistant_turn_boundary: 256/4480 files

2026-09-05T01:58:03.582394+00:00 cached assistant_turn_boundary: 512/4480 files

2026-09-05T01:58:13.485310+00:00 cached assistant_turn_boundary: 768/4480 files

2026-09-05T01:58:23.880621+00:00 cached assistant_turn_boundary: 1024/4480 files

2026-09-05T01:58:33.893059+00:00 cached assistant_turn_boundary: 1280/4480 files

2026-09-05T01:58:43.277856+00:00 cached assistant_turn_boundary: 1536/4480 files

2026-09-05T01:58:52.689502+00:00 cached assistant_turn_boundary: 1792/4480 files

2026-09-05T01:59:01.890122+00:00 cached assistant_turn_boundary: 2048/4480 files

2026-09-05T01:59:11.178859+00:00 cached assistant_turn_boundary: 2304/4480 files

2026-09-05T01:59:20.774475+00:00 cached assistant_turn_boundary: 2560/4480 files

2026-09-05T01:59:30.583331+00:00 cached assistant_turn_boundary: 2816/4480 files

2026-09-05T01:59:39.984103+00:00 cached assistant_turn_boundary: 3072/4480 files

2026-09-05T01:59:49.382061+00:00 cached assistant_turn_boundary: 3328/4480 files

2026-09-05T01:59:58.280539+00:00 cached assistant_turn_boundary: 3584/4480 files

2026-09-05T02:00:09.592340+00:00 cached assistant_turn_boundary: 3840/4480 files

2026-09-05T02:00:22.980696+00:00 cached assistant_turn_boundary: 4096/4480 files

2026-09-05T02:00:31.477330+00:00 cached assistant_turn_boundary: 4352/4480 files

2026-09-05T02:00:35.777409+00:00 cached assistant_turn_boundary: 4480/4480 files
2026-09-05T02:00:35.777786+00:00 PROBE_SITE_CACHE_READY {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'shape': (32, 4480, 4096), 'cache_gib': 2.1875, 'activation_file_opens': 4480}
2026-09-05T02:00:35.777962+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 0, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1824, 'total': 2688, 'pending': 864, 'percent_complete': 67.8571}

2026-09-05T02:00:45.644583+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 0, 'target': 'delta_a', 'completed': 1825, 'total': 2688, 'pending': 863, 'percent_complete': 67.8943}

2026-09-05T02:00:54.674162+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 0, 'target': 'gain', 'completed': 1826, 'total': 2688, 'pending': 862, 'percent_complete': 67.9315}

2026-09-05T02:01:04.183690+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 0, 'target': 'gain_abs', 'completed': 1827, 'total': 2688, 'pending': 861, 'percent_complete': 67.9688}

2026-09-05T02:01:13.477216+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 0, 'target': 'z_bayes', 'completed': 1828, 'total': 2688, 'pending': 860, 'percent_complete': 68.006}

2026-09-05T02:01:23.272884+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 0, 'target': 'z_heuristic', 'completed': 1829, 'total': 2688, 'pending': 859, 'percent_complete': 68.0432}

2026-09-05T02:01:24.973355+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 0, 'target': 'reliability_sign', 'completed': 1830, 'total': 2688, 'pending': 858, 'percent_complete': 68.0804}
2026-09-05T02:01:24.973681+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 1, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1830, 'total': 2688, 'pending': 858, 'percent_complete': 68.0804}

2026-09-05T02:01:34.688220+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 1, 'target': 'delta_a', 'completed': 1831, 'total': 2688, 'pending': 857, 'percent_complete': 68.1176}

2026-09-05T02:01:44.217885+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 1, 'target': 'gain', 'completed': 1832, 'total': 2688, 'pending': 856, 'percent_complete': 68.1548}

2026-09-05T02:01:53.506308+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 1, 'target': 'gain_abs', 'completed': 1833, 'total': 2688, 'pending': 855, 'percent_complete': 68.192}

2026-09-05T02:02:03.476132+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 1, 'target': 'z_bayes', 'completed': 1834, 'total': 2688, 'pending': 854, 'percent_complete': 68.2292}

2026-09-05T02:02:14.388900+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 1, 'target': 'z_heuristic', 'completed': 1835, 'total': 2688, 'pending': 853, 'percent_complete': 68.2664}

2026-09-05T02:02:16.199838+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 1, 'target': 'reliability_sign', 'completed': 1836, 'total': 2688, 'pending': 852, 'percent_complete': 68.3036}
2026-09-05T02:02:16.200154+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 2, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1836, 'total': 2688, 'pending': 852, 'percent_complete': 68.3036}

2026-09-05T02:02:26.777299+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 2, 'target': 'delta_a', 'completed': 1837, 'total': 2688, 'pending': 851, 'percent_complete': 68.3408}

2026-09-05T02:02:37.790755+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 2, 'target': 'gain', 'completed': 1838, 'total': 2688, 'pending': 850, 'percent_complete': 68.378}

2026-09-05T02:02:47.520109+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 2, 'target': 'gain_abs', 'completed': 1839, 'total': 2688, 'pending': 849, 'percent_complete': 68.4152}

2026-09-05T02:02:57.378329+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 2, 'target': 'z_bayes', 'completed': 1840, 'total': 2688, 'pending': 848, 'percent_complete': 68.4524}

2026-09-05T02:03:06.673850+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 2, 'target': 'z_heuristic', 'completed': 1841, 'total': 2688, 'pending': 847, 'percent_complete': 68.4896}

2026-09-05T02:03:08.502998+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 2, 'target': 'reliability_sign', 'completed': 1842, 'total': 2688, 'pending': 846, 'percent_complete': 68.5268}
2026-09-05T02:03:08.503319+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 3, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1842, 'total': 2688, 'pending': 846, 'percent_complete': 68.5268}

2026-09-05T02:03:20.693568+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 3, 'target': 'delta_a', 'completed': 1843, 'total': 2688, 'pending': 845, 'percent_complete': 68.564}

2026-09-05T02:03:29.977984+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 3, 'target': 'gain', 'completed': 1844, 'total': 2688, 'pending': 844, 'percent_complete': 68.6012}

2026-09-05T02:03:39.777677+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 3, 'target': 'gain_abs', 'completed': 1845, 'total': 2688, 'pending': 843, 'percent_complete': 68.6384}

2026-09-05T02:03:50.220803+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 3, 'target': 'z_bayes', 'completed': 1846, 'total': 2688, 'pending': 842, 'percent_complete': 68.6756}

2026-09-05T02:04:00.173072+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 3, 'target': 'z_heuristic', 'completed': 1847, 'total': 2688, 'pending': 841, 'percent_complete': 68.7128}

2026-09-05T02:04:01.607559+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 3, 'target': 'reliability_sign', 'completed': 1848, 'total': 2688, 'pending': 840, 'percent_complete': 68.75}
2026-09-05T02:04:01.607797+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 4, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1848, 'total': 2688, 'pending': 840, 'percent_complete': 68.75}

2026-09-05T02:04:12.173697+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 4, 'target': 'delta_a', 'completed': 1849, 'total': 2688, 'pending': 839, 'percent_complete': 68.7872}

2026-09-05T02:04:22.073691+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 4, 'target': 'gain', 'completed': 1850, 'total': 2688, 'pending': 838, 'percent_complete': 68.8244}

2026-09-05T02:04:33.487650+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 4, 'target': 'gain_abs', 'completed': 1851, 'total': 2688, 'pending': 837, 'percent_complete': 68.8616}

2026-09-05T02:04:43.283155+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 4, 'target': 'z_bayes', 'completed': 1852, 'total': 2688, 'pending': 836, 'percent_complete': 68.8988}

2026-09-05T02:04:52.576777+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 4, 'target': 'z_heuristic', 'completed': 1853, 'total': 2688, 'pending': 835, 'percent_complete': 68.936}

2026-09-05T02:04:54.283275+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 4, 'target': 'reliability_sign', 'completed': 1854, 'total': 2688, 'pending': 834, 'percent_complete': 68.9732}
2026-09-05T02:04:54.283564+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 5, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1854, 'total': 2688, 'pending': 834, 'percent_complete': 68.9732}

2026-09-05T02:05:05.377521+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 5, 'target': 'delta_a', 'completed': 1855, 'total': 2688, 'pending': 833, 'percent_complete': 69.0104}

2026-09-05T02:05:16.177739+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 5, 'target': 'gain', 'completed': 1856, 'total': 2688, 'pending': 832, 'percent_complete': 69.0476}

2026-09-05T02:05:26.592405+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 5, 'target': 'gain_abs', 'completed': 1857, 'total': 2688, 'pending': 831, 'percent_complete': 69.0848}

2026-09-05T02:05:36.022241+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 5, 'target': 'z_bayes', 'completed': 1858, 'total': 2688, 'pending': 830, 'percent_complete': 69.122}

2026-09-05T02:05:47.120141+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 5, 'target': 'z_heuristic', 'completed': 1859, 'total': 2688, 'pending': 829, 'percent_complete': 69.1592}

2026-09-05T02:05:48.584224+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 5, 'target': 'reliability_sign', 'completed': 1860, 'total': 2688, 'pending': 828, 'percent_complete': 69.1964}
2026-09-05T02:05:48.584514+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 6, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1860, 'total': 2688, 'pending': 828, 'percent_complete': 69.1964}

2026-09-05T02:05:58.399602+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 6, 'target': 'delta_a', 'completed': 1861, 'total': 2688, 'pending': 827, 'percent_complete': 69.2336}

2026-09-05T02:06:08.678271+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 6, 'target': 'gain', 'completed': 1862, 'total': 2688, 'pending': 826, 'percent_complete': 69.2708}

2026-09-05T02:06:19.286532+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 6, 'target': 'gain_abs', 'completed': 1863, 'total': 2688, 'pending': 825, 'percent_complete': 69.308}

2026-09-05T02:06:28.873335+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 6, 'target': 'z_bayes', 'completed': 1864, 'total': 2688, 'pending': 824, 'percent_complete': 69.3452}

2026-09-05T02:06:39.090169+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 6, 'target': 'z_heuristic', 'completed': 1865, 'total': 2688, 'pending': 823, 'percent_complete': 69.3824}

2026-09-05T02:06:40.806989+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 6, 'target': 'reliability_sign', 'completed': 1866, 'total': 2688, 'pending': 822, 'percent_complete': 69.4196}
2026-09-05T02:06:40.807408+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 7, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1866, 'total': 2688, 'pending': 822, 'percent_complete': 69.4196}

2026-09-05T02:06:53.182067+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 7, 'target': 'delta_a', 'completed': 1867, 'total': 2688, 'pending': 821, 'percent_complete': 69.4568}

2026-09-05T02:07:08.075044+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 7, 'target': 'gain', 'completed': 1868, 'total': 2688, 'pending': 820, 'percent_complete': 69.494}

2026-09-05T02:07:19.680469+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 7, 'target': 'gain_abs', 'completed': 1869, 'total': 2688, 'pending': 819, 'percent_complete': 69.5312}

2026-09-05T02:07:30.680551+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 7, 'target': 'z_bayes', 'completed': 1870, 'total': 2688, 'pending': 818, 'percent_complete': 69.5685}

2026-09-05T02:07:44.216578+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 7, 'target': 'z_heuristic', 'completed': 1871, 'total': 2688, 'pending': 817, 'percent_complete': 69.6057}

2026-09-05T02:07:45.906704+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 7, 'target': 'reliability_sign', 'completed': 1872, 'total': 2688, 'pending': 816, 'percent_complete': 69.6429}
2026-09-05T02:07:45.907031+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 8, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1872, 'total': 2688, 'pending': 816, 'percent_complete': 69.6429}

2026-09-05T02:07:57.694407+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 8, 'target': 'delta_a', 'completed': 1873, 'total': 2688, 'pending': 815, 'percent_complete': 69.6801}

2026-09-05T02:08:12.606098+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 8, 'target': 'gain', 'completed': 1874, 'total': 2688, 'pending': 814, 'percent_complete': 69.7173}

2026-09-05T02:08:27.986540+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 8, 'target': 'gain_abs', 'completed': 1875, 'total': 2688, 'pending': 813, 'percent_complete': 69.7545}

2026-09-05T02:08:42.176128+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 8, 'target': 'z_bayes', 'completed': 1876, 'total': 2688, 'pending': 812, 'percent_complete': 69.7917}

2026-09-05T02:08:56.407768+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 8, 'target': 'z_heuristic', 'completed': 1877, 'total': 2688, 'pending': 811, 'percent_complete': 69.8289}

2026-09-05T02:08:58.008014+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 8, 'target': 'reliability_sign', 'completed': 1878, 'total': 2688, 'pending': 810, 'percent_complete': 69.8661}
2026-09-05T02:08:58.008278+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 9, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1878, 'total': 2688, 'pending': 810, 'percent_complete': 69.8661}

2026-09-05T02:09:10.402060+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 9, 'target': 'delta_a', 'completed': 1879, 'total': 2688, 'pending': 809, 'percent_complete': 69.9033}

2026-09-05T02:09:22.787128+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 9, 'target': 'gain', 'completed': 1880, 'total': 2688, 'pending': 808, 'percent_complete': 69.9405}

2026-09-05T02:09:36.971712+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 9, 'target': 'gain_abs', 'completed': 1881, 'total': 2688, 'pending': 807, 'percent_complete': 69.9777}

2026-09-05T02:10:00.188468+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 9, 'target': 'z_bayes', 'completed': 1882, 'total': 2688, 'pending': 806, 'percent_complete': 70.0149}

2026-09-05T02:10:17.313342+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 9, 'target': 'z_heuristic', 'completed': 1883, 'total': 2688, 'pending': 805, 'percent_complete': 70.0521}

2026-09-05T02:10:19.008956+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 9, 'target': 'reliability_sign', 'completed': 1884, 'total': 2688, 'pending': 804, 'percent_complete': 70.0893}
2026-09-05T02:10:19.009276+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 10, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1884, 'total': 2688, 'pending': 804, 'percent_complete': 70.0893}

2026-09-05T02:10:39.413641+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 10, 'target': 'delta_a', 'completed': 1885, 'total': 2688, 'pending': 803, 'percent_complete': 70.1265}

2026-09-05T02:11:01.690396+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 10, 'target': 'gain', 'completed': 1886, 'total': 2688, 'pending': 802, 'percent_complete': 70.1637}

2026-09-05T02:11:23.405911+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 10, 'target': 'gain_abs', 'completed': 1887, 'total': 2688, 'pending': 801, 'percent_complete': 70.2009}

2026-09-05T02:11:40.180238+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 10, 'target': 'z_bayes', 'completed': 1888, 'total': 2688, 'pending': 800, 'percent_complete': 70.2381}

2026-09-05T02:11:52.820067+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 10, 'target': 'z_heuristic', 'completed': 1889, 'total': 2688, 'pending': 799, 'percent_complete': 70.2753}

2026-09-05T02:11:54.389953+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 10, 'target': 'reliability_sign', 'completed': 1890, 'total': 2688, 'pending': 798, 'percent_complete': 70.3125}
2026-09-05T02:11:54.390469+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 11, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1890, 'total': 2688, 'pending': 798, 'percent_complete': 70.3125}

2026-09-05T02:12:07.882023+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 11, 'target': 'delta_a', 'completed': 1891, 'total': 2688, 'pending': 797, 'percent_complete': 70.3497}

2026-09-05T02:12:19.984382+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 11, 'target': 'gain', 'completed': 1892, 'total': 2688, 'pending': 796, 'percent_complete': 70.3869}

2026-09-05T02:12:33.283270+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 11, 'target': 'gain_abs', 'completed': 1893, 'total': 2688, 'pending': 795, 'percent_complete': 70.4241}

2026-09-05T02:12:44.902784+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 11, 'target': 'z_bayes', 'completed': 1894, 'total': 2688, 'pending': 794, 'percent_complete': 70.4613}

2026-09-05T02:13:00.898786+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 11, 'target': 'z_heuristic', 'completed': 1895, 'total': 2688, 'pending': 793, 'percent_complete': 70.4985}

2026-09-05T02:13:02.993342+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 11, 'target': 'reliability_sign', 'completed': 1896, 'total': 2688, 'pending': 792, 'percent_complete': 70.5357}
2026-09-05T02:13:02.993655+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 12, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1896, 'total': 2688, 'pending': 792, 'percent_complete': 70.5357}

2026-09-05T02:13:19.808815+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 12, 'target': 'delta_a', 'completed': 1897, 'total': 2688, 'pending': 791, 'percent_complete': 70.5729}

2026-09-05T02:13:45.192947+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 12, 'target': 'gain', 'completed': 1898, 'total': 2688, 'pending': 790, 'percent_complete': 70.6101}

2026-09-05T02:14:09.690413+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 12, 'target': 'gain_abs', 'completed': 1899, 'total': 2688, 'pending': 789, 'percent_complete': 70.6473}

2026-09-05T02:14:36.998036+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 12, 'target': 'z_bayes', 'completed': 1900, 'total': 2688, 'pending': 788, 'percent_complete': 70.6845}

2026-09-05T02:14:57.795874+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 12, 'target': 'z_heuristic', 'completed': 1901, 'total': 2688, 'pending': 787, 'percent_complete': 70.7217}

2026-09-05T02:14:59.510558+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 12, 'target': 'reliability_sign', 'completed': 1902, 'total': 2688, 'pending': 786, 'percent_complete': 70.7589}
2026-09-05T02:14:59.510878+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 13, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1902, 'total': 2688, 'pending': 786, 'percent_complete': 70.7589}

2026-09-05T02:15:15.894278+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 13, 'target': 'delta_a', 'completed': 1903, 'total': 2688, 'pending': 785, 'percent_complete': 70.7961}

2026-09-05T02:15:31.605591+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 13, 'target': 'gain', 'completed': 1904, 'total': 2688, 'pending': 784, 'percent_complete': 70.8333}

2026-09-05T02:15:45.296449+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 13, 'target': 'gain_abs', 'completed': 1905, 'total': 2688, 'pending': 783, 'percent_complete': 70.8705}

2026-09-05T02:16:00.786759+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 13, 'target': 'z_bayes', 'completed': 1906, 'total': 2688, 'pending': 782, 'percent_complete': 70.9077}

2026-09-05T02:16:14.597800+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 13, 'target': 'z_heuristic', 'completed': 1907, 'total': 2688, 'pending': 781, 'percent_complete': 70.9449}

2026-09-05T02:16:16.204271+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 13, 'target': 'reliability_sign', 'completed': 1908, 'total': 2688, 'pending': 780, 'percent_complete': 70.9821}
2026-09-05T02:16:16.204515+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 14, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1908, 'total': 2688, 'pending': 780, 'percent_complete': 70.9821}

2026-09-05T02:16:30.097367+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 14, 'target': 'delta_a', 'completed': 1909, 'total': 2688, 'pending': 779, 'percent_complete': 71.0193}

2026-09-05T02:16:42.503125+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 14, 'target': 'gain', 'completed': 1910, 'total': 2688, 'pending': 778, 'percent_complete': 71.0565}

2026-09-05T02:16:55.208818+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 14, 'target': 'gain_abs', 'completed': 1911, 'total': 2688, 'pending': 777, 'percent_complete': 71.0938}

2026-09-05T02:17:08.789389+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 14, 'target': 'z_bayes', 'completed': 1912, 'total': 2688, 'pending': 776, 'percent_complete': 71.131}

2026-09-05T02:17:25.205758+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 14, 'target': 'z_heuristic', 'completed': 1913, 'total': 2688, 'pending': 775, 'percent_complete': 71.1682}

2026-09-05T02:17:26.802814+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 14, 'target': 'reliability_sign', 'completed': 1914, 'total': 2688, 'pending': 774, 'percent_complete': 71.2054}
2026-09-05T02:17:26.803126+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 15, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1914, 'total': 2688, 'pending': 774, 'percent_complete': 71.2054}

2026-09-05T02:17:39.015596+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 15, 'target': 'delta_a', 'completed': 1915, 'total': 2688, 'pending': 773, 'percent_complete': 71.2426}

2026-09-05T02:17:52.207016+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 15, 'target': 'gain', 'completed': 1916, 'total': 2688, 'pending': 772, 'percent_complete': 71.2798}

2026-09-05T02:18:04.707800+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 15, 'target': 'gain_abs', 'completed': 1917, 'total': 2688, 'pending': 771, 'percent_complete': 71.317}

2026-09-05T02:18:16.893033+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 15, 'target': 'z_bayes', 'completed': 1918, 'total': 2688, 'pending': 770, 'percent_complete': 71.3542}

2026-09-05T02:18:29.382754+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 15, 'target': 'z_heuristic', 'completed': 1919, 'total': 2688, 'pending': 769, 'percent_complete': 71.3914}

2026-09-05T02:18:31.184315+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 15, 'target': 'reliability_sign', 'completed': 1920, 'total': 2688, 'pending': 768, 'percent_complete': 71.4286}
2026-09-05T02:18:31.184558+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 16, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1920, 'total': 2688, 'pending': 768, 'percent_complete': 71.4286}

2026-09-05T02:18:47.607200+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 16, 'target': 'delta_a', 'completed': 1921, 'total': 2688, 'pending': 767, 'percent_complete': 71.4658}

2026-09-05T02:19:05.898247+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 16, 'target': 'gain', 'completed': 1922, 'total': 2688, 'pending': 766, 'percent_complete': 71.503}

2026-09-05T02:19:19.292423+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 16, 'target': 'gain_abs', 'completed': 1923, 'total': 2688, 'pending': 765, 'percent_complete': 71.5402}

2026-09-05T02:19:36.381812+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 16, 'target': 'z_bayes', 'completed': 1924, 'total': 2688, 'pending': 764, 'percent_complete': 71.5774}

2026-09-05T02:19:56.206941+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 16, 'target': 'z_heuristic', 'completed': 1925, 'total': 2688, 'pending': 763, 'percent_complete': 71.6146}

2026-09-05T02:19:57.985317+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 16, 'target': 'reliability_sign', 'completed': 1926, 'total': 2688, 'pending': 762, 'percent_complete': 71.6518}
2026-09-05T02:19:57.985669+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 17, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1926, 'total': 2688, 'pending': 762, 'percent_complete': 71.6518}

2026-09-05T02:20:17.401679+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 17, 'target': 'delta_a', 'completed': 1927, 'total': 2688, 'pending': 761, 'percent_complete': 71.689}

2026-09-05T02:20:35.275925+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 17, 'target': 'gain', 'completed': 1928, 'total': 2688, 'pending': 760, 'percent_complete': 71.7262}

2026-09-05T02:20:51.400905+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 17, 'target': 'gain_abs', 'completed': 1929, 'total': 2688, 'pending': 759, 'percent_complete': 71.7634}

2026-09-05T02:21:07.989360+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 17, 'target': 'z_bayes', 'completed': 1930, 'total': 2688, 'pending': 758, 'percent_complete': 71.8006}

2026-09-05T02:21:26.307030+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 17, 'target': 'z_heuristic', 'completed': 1931, 'total': 2688, 'pending': 757, 'percent_complete': 71.8378}

2026-09-05T02:21:28.205447+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 17, 'target': 'reliability_sign', 'completed': 1932, 'total': 2688, 'pending': 756, 'percent_complete': 71.875}
2026-09-05T02:21:28.205802+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 18, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1932, 'total': 2688, 'pending': 756, 'percent_complete': 71.875}

2026-09-05T02:21:45.790978+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 18, 'target': 'delta_a', 'completed': 1933, 'total': 2688, 'pending': 755, 'percent_complete': 71.9122}

2026-09-05T02:21:59.879519+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 18, 'target': 'gain', 'completed': 1934, 'total': 2688, 'pending': 754, 'percent_complete': 71.9494}

2026-09-05T02:22:13.691421+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 18, 'target': 'gain_abs', 'completed': 1935, 'total': 2688, 'pending': 753, 'percent_complete': 71.9866}

2026-09-05T02:22:28.780931+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 18, 'target': 'z_bayes', 'completed': 1936, 'total': 2688, 'pending': 752, 'percent_complete': 72.0238}

2026-09-05T02:22:41.601453+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 18, 'target': 'z_heuristic', 'completed': 1937, 'total': 2688, 'pending': 751, 'percent_complete': 72.061}

2026-09-05T02:22:43.182902+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 18, 'target': 'reliability_sign', 'completed': 1938, 'total': 2688, 'pending': 750, 'percent_complete': 72.0982}
2026-09-05T02:22:43.183322+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 19, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1938, 'total': 2688, 'pending': 750, 'percent_complete': 72.0982}

2026-09-05T02:22:55.300830+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 19, 'target': 'delta_a', 'completed': 1939, 'total': 2688, 'pending': 749, 'percent_complete': 72.1354}

2026-09-05T02:23:08.206043+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 19, 'target': 'gain', 'completed': 1940, 'total': 2688, 'pending': 748, 'percent_complete': 72.1726}

2026-09-05T02:23:22.487325+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 19, 'target': 'gain_abs', 'completed': 1941, 'total': 2688, 'pending': 747, 'percent_complete': 72.2098}

2026-09-05T02:23:35.072926+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 19, 'target': 'z_bayes', 'completed': 1942, 'total': 2688, 'pending': 746, 'percent_complete': 72.247}

2026-09-05T02:23:50.399557+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 19, 'target': 'z_heuristic', 'completed': 1943, 'total': 2688, 'pending': 745, 'percent_complete': 72.2842}

2026-09-05T02:23:51.874531+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 19, 'target': 'reliability_sign', 'completed': 1944, 'total': 2688, 'pending': 744, 'percent_complete': 72.3214}
2026-09-05T02:23:51.874869+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 20, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1944, 'total': 2688, 'pending': 744, 'percent_complete': 72.3214}

2026-09-05T02:24:04.777101+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 20, 'target': 'delta_a', 'completed': 1945, 'total': 2688, 'pending': 743, 'percent_complete': 72.3586}

2026-09-05T02:24:19.912588+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 20, 'target': 'gain', 'completed': 1946, 'total': 2688, 'pending': 742, 'percent_complete': 72.3958}

2026-09-05T02:24:34.582444+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 20, 'target': 'gain_abs', 'completed': 1947, 'total': 2688, 'pending': 741, 'percent_complete': 72.433}

2026-09-05T02:24:49.918925+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 20, 'target': 'z_bayes', 'completed': 1948, 'total': 2688, 'pending': 740, 'percent_complete': 72.4702}

2026-09-05T02:25:03.298353+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 20, 'target': 'z_heuristic', 'completed': 1949, 'total': 2688, 'pending': 739, 'percent_complete': 72.5074}

2026-09-05T02:25:04.792681+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 20, 'target': 'reliability_sign', 'completed': 1950, 'total': 2688, 'pending': 738, 'percent_complete': 72.5446}
2026-09-05T02:25:04.793039+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 21, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1950, 'total': 2688, 'pending': 738, 'percent_complete': 72.5446}

2026-09-05T02:25:17.080414+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 21, 'target': 'delta_a', 'completed': 1951, 'total': 2688, 'pending': 737, 'percent_complete': 72.5818}

2026-09-05T02:25:30.583328+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 21, 'target': 'gain', 'completed': 1952, 'total': 2688, 'pending': 736, 'percent_complete': 72.619}

2026-09-05T02:25:44.910178+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 21, 'target': 'gain_abs', 'completed': 1953, 'total': 2688, 'pending': 735, 'percent_complete': 72.6562}

2026-09-05T02:26:00.793587+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 21, 'target': 'z_bayes', 'completed': 1954, 'total': 2688, 'pending': 734, 'percent_complete': 72.6935}

2026-09-05T02:26:15.100246+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 21, 'target': 'z_heuristic', 'completed': 1955, 'total': 2688, 'pending': 733, 'percent_complete': 72.7307}

2026-09-05T02:26:16.503603+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 21, 'target': 'reliability_sign', 'completed': 1956, 'total': 2688, 'pending': 732, 'percent_complete': 72.7679}
2026-09-05T02:26:16.503854+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 22, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1956, 'total': 2688, 'pending': 732, 'percent_complete': 72.7679}

2026-09-05T02:26:28.187386+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 22, 'target': 'delta_a', 'completed': 1957, 'total': 2688, 'pending': 731, 'percent_complete': 72.8051}

2026-09-05T02:26:41.312946+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 22, 'target': 'gain', 'completed': 1958, 'total': 2688, 'pending': 730, 'percent_complete': 72.8423}

2026-09-05T02:26:54.378813+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 22, 'target': 'gain_abs', 'completed': 1959, 'total': 2688, 'pending': 729, 'percent_complete': 72.8795}

2026-09-05T02:27:05.789361+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 22, 'target': 'z_bayes', 'completed': 1960, 'total': 2688, 'pending': 728, 'percent_complete': 72.9167}

2026-09-05T02:27:17.603628+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 22, 'target': 'z_heuristic', 'completed': 1961, 'total': 2688, 'pending': 727, 'percent_complete': 72.9539}

2026-09-05T02:27:19.307661+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 22, 'target': 'reliability_sign', 'completed': 1962, 'total': 2688, 'pending': 726, 'percent_complete': 72.9911}
2026-09-05T02:27:19.307985+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 23, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1962, 'total': 2688, 'pending': 726, 'percent_complete': 72.9911}

2026-09-05T02:27:34.378524+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 23, 'target': 'delta_a', 'completed': 1963, 'total': 2688, 'pending': 725, 'percent_complete': 73.0283}

2026-09-05T02:27:49.198304+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 23, 'target': 'gain', 'completed': 1964, 'total': 2688, 'pending': 724, 'percent_complete': 73.0655}

2026-09-05T02:28:03.900319+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 23, 'target': 'gain_abs', 'completed': 1965, 'total': 2688, 'pending': 723, 'percent_complete': 73.1027}

2026-09-05T02:28:16.912549+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 23, 'target': 'z_bayes', 'completed': 1966, 'total': 2688, 'pending': 722, 'percent_complete': 73.1399}

2026-09-05T02:28:33.581139+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 23, 'target': 'z_heuristic', 'completed': 1967, 'total': 2688, 'pending': 721, 'percent_complete': 73.1771}

2026-09-05T02:28:34.994321+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 23, 'target': 'reliability_sign', 'completed': 1968, 'total': 2688, 'pending': 720, 'percent_complete': 73.2143}
2026-09-05T02:28:34.994671+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 24, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1968, 'total': 2688, 'pending': 720, 'percent_complete': 73.2143}

2026-09-05T02:28:49.280257+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 24, 'target': 'delta_a', 'completed': 1969, 'total': 2688, 'pending': 719, 'percent_complete': 73.2515}

2026-09-05T02:29:03.175860+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 24, 'target': 'gain', 'completed': 1970, 'total': 2688, 'pending': 718, 'percent_complete': 73.2887}

2026-09-05T02:29:17.782418+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 24, 'target': 'gain_abs', 'completed': 1971, 'total': 2688, 'pending': 717, 'percent_complete': 73.3259}

2026-09-05T02:29:31.499605+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 24, 'target': 'z_bayes', 'completed': 1972, 'total': 2688, 'pending': 716, 'percent_complete': 73.3631}

2026-09-05T02:29:45.581096+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 24, 'target': 'z_heuristic', 'completed': 1973, 'total': 2688, 'pending': 715, 'percent_complete': 73.4003}

2026-09-05T02:29:46.972896+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 24, 'target': 'reliability_sign', 'completed': 1974, 'total': 2688, 'pending': 714, 'percent_complete': 73.4375}
2026-09-05T02:29:46.973258+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 25, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1974, 'total': 2688, 'pending': 714, 'percent_complete': 73.4375}

2026-09-05T02:29:58.508986+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 25, 'target': 'delta_a', 'completed': 1975, 'total': 2688, 'pending': 713, 'percent_complete': 73.4747}

2026-09-05T02:30:11.985307+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 25, 'target': 'gain', 'completed': 1976, 'total': 2688, 'pending': 712, 'percent_complete': 73.5119}

2026-09-05T02:30:29.700190+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 25, 'target': 'gain_abs', 'completed': 1977, 'total': 2688, 'pending': 711, 'percent_complete': 73.5491}

2026-09-05T02:30:44.490385+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 25, 'target': 'z_bayes', 'completed': 1978, 'total': 2688, 'pending': 710, 'percent_complete': 73.5863}

2026-09-05T02:30:59.305987+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 25, 'target': 'z_heuristic', 'completed': 1979, 'total': 2688, 'pending': 709, 'percent_complete': 73.6235}

2026-09-05T02:31:01.185205+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 25, 'target': 'reliability_sign', 'completed': 1980, 'total': 2688, 'pending': 708, 'percent_complete': 73.6607}
2026-09-05T02:31:01.185596+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 26, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1980, 'total': 2688, 'pending': 708, 'percent_complete': 73.6607}

2026-09-05T02:31:15.782101+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 26, 'target': 'delta_a', 'completed': 1981, 'total': 2688, 'pending': 707, 'percent_complete': 73.6979}

2026-09-05T02:31:32.990975+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 26, 'target': 'gain', 'completed': 1982, 'total': 2688, 'pending': 706, 'percent_complete': 73.7351}

2026-09-05T02:31:48.102190+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 26, 'target': 'gain_abs', 'completed': 1983, 'total': 2688, 'pending': 705, 'percent_complete': 73.7723}

2026-09-05T02:32:04.809604+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 26, 'target': 'z_bayes', 'completed': 1984, 'total': 2688, 'pending': 704, 'percent_complete': 73.8095}

2026-09-05T02:32:21.072934+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 26, 'target': 'z_heuristic', 'completed': 1985, 'total': 2688, 'pending': 703, 'percent_complete': 73.8467}

2026-09-05T02:32:22.672398+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 26, 'target': 'reliability_sign', 'completed': 1986, 'total': 2688, 'pending': 702, 'percent_complete': 73.8839}
2026-09-05T02:32:22.672729+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 27, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1986, 'total': 2688, 'pending': 702, 'percent_complete': 73.8839}

2026-09-05T02:32:36.985478+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 27, 'target': 'delta_a', 'completed': 1987, 'total': 2688, 'pending': 701, 'percent_complete': 73.9211}

2026-09-05T02:32:51.075078+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 27, 'target': 'gain', 'completed': 1988, 'total': 2688, 'pending': 700, 'percent_complete': 73.9583}

2026-09-05T02:33:06.406755+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 27, 'target': 'gain_abs', 'completed': 1989, 'total': 2688, 'pending': 699, 'percent_complete': 73.9955}

2026-09-05T02:33:18.711176+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 27, 'target': 'z_bayes', 'completed': 1990, 'total': 2688, 'pending': 698, 'percent_complete': 74.0327}

2026-09-05T02:33:33.581766+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 27, 'target': 'z_heuristic', 'completed': 1991, 'total': 2688, 'pending': 697, 'percent_complete': 74.0699}

2026-09-05T02:33:35.110965+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 27, 'target': 'reliability_sign', 'completed': 1992, 'total': 2688, 'pending': 696, 'percent_complete': 74.1071}
2026-09-05T02:33:35.111235+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 28, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1992, 'total': 2688, 'pending': 696, 'percent_complete': 74.1071}

2026-09-05T02:33:47.899885+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 28, 'target': 'delta_a', 'completed': 1993, 'total': 2688, 'pending': 695, 'percent_complete': 74.1443}

2026-09-05T02:34:00.805898+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 28, 'target': 'gain', 'completed': 1994, 'total': 2688, 'pending': 694, 'percent_complete': 74.1815}

2026-09-05T02:34:12.705297+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 28, 'target': 'gain_abs', 'completed': 1995, 'total': 2688, 'pending': 693, 'percent_complete': 74.2188}

2026-09-05T02:34:25.890851+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 28, 'target': 'z_bayes', 'completed': 1996, 'total': 2688, 'pending': 692, 'percent_complete': 74.256}

2026-09-05T02:34:41.977475+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 28, 'target': 'z_heuristic', 'completed': 1997, 'total': 2688, 'pending': 691, 'percent_complete': 74.2932}

2026-09-05T02:34:43.609272+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 28, 'target': 'reliability_sign', 'completed': 1998, 'total': 2688, 'pending': 690, 'percent_complete': 74.3304}
2026-09-05T02:34:43.609574+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 29, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 1998, 'total': 2688, 'pending': 690, 'percent_complete': 74.3304}

2026-09-05T02:34:58.375669+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 29, 'target': 'delta_a', 'completed': 1999, 'total': 2688, 'pending': 689, 'percent_complete': 74.3676}

2026-09-05T02:35:12.880433+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 29, 'target': 'gain', 'completed': 2000, 'total': 2688, 'pending': 688, 'percent_complete': 74.4048}

2026-09-05T02:35:27.713479+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 29, 'target': 'gain_abs', 'completed': 2001, 'total': 2688, 'pending': 687, 'percent_complete': 74.442}

2026-09-05T02:35:42.580097+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 29, 'target': 'z_bayes', 'completed': 2002, 'total': 2688, 'pending': 686, 'percent_complete': 74.4792}

2026-09-05T02:35:58.577332+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 29, 'target': 'z_heuristic', 'completed': 2003, 'total': 2688, 'pending': 685, 'percent_complete': 74.5164}

2026-09-05T02:35:59.813771+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 29, 'target': 'reliability_sign', 'completed': 2004, 'total': 2688, 'pending': 684, 'percent_complete': 74.5536}
2026-09-05T02:35:59.871606+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 30, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2004, 'total': 2688, 'pending': 684, 'percent_complete': 74.5536}

2026-09-05T02:36:14.178965+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 30, 'target': 'delta_a', 'completed': 2005, 'total': 2688, 'pending': 683, 'percent_complete': 74.5908}

2026-09-05T02:36:26.972409+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 30, 'target': 'gain', 'completed': 2006, 'total': 2688, 'pending': 682, 'percent_complete': 74.628}

2026-09-05T02:36:41.014379+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 30, 'target': 'gain_abs', 'completed': 2007, 'total': 2688, 'pending': 681, 'percent_complete': 74.6652}

2026-09-05T02:36:55.682642+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 30, 'target': 'z_bayes', 'completed': 2008, 'total': 2688, 'pending': 680, 'percent_complete': 74.7024}

2026-09-05T02:37:11.671454+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 30, 'target': 'z_heuristic', 'completed': 2009, 'total': 2688, 'pending': 679, 'percent_complete': 74.7396}

2026-09-05T02:37:13.305770+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 30, 'target': 'reliability_sign', 'completed': 2010, 'total': 2688, 'pending': 678, 'percent_complete': 74.7768}
2026-09-05T02:37:13.306019+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 31, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2010, 'total': 2688, 'pending': 678, 'percent_complete': 74.7768}

2026-09-05T02:37:27.975168+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 31, 'target': 'delta_a', 'completed': 2011, 'total': 2688, 'pending': 677, 'percent_complete': 74.814}

2026-09-05T02:37:45.405006+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 31, 'target': 'gain', 'completed': 2012, 'total': 2688, 'pending': 676, 'percent_complete': 74.8512}

2026-09-05T02:37:59.880890+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 31, 'target': 'gain_abs', 'completed': 2013, 'total': 2688, 'pending': 675, 'percent_complete': 74.8884}

2026-09-05T02:38:16.110158+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 31, 'target': 'z_bayes', 'completed': 2014, 'total': 2688, 'pending': 674, 'percent_complete': 74.9256}

2026-09-05T02:38:41.409476+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 31, 'target': 'z_heuristic', 'completed': 2015, 'total': 2688, 'pending': 673, 'percent_complete': 74.9628}

2026-09-05T02:38:43.305532+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary', 'layer': 31, 'target': 'reliability_sign', 'completed': 2016, 'total': 2688, 'pending': 672, 'percent_complete': 75.0}
2026-09-05T02:38:45.483991+00:00 PROBE_SITE_CACHE_RELEASED {'reasoning_mode': 'reasoning_off', 'site': 'assistant_turn_boundary'}
2026-09-05T02:38:45.585578+00:00 PROBE_SITE_CACHE_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'site_pending': 192, 'missing_layers': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], 'activation_files': 4480, 'estimated_cache_gib': 2.1875, 'completed': 2016, 'total': 2688, 'pending': 672, 'percent_complete': 75.0}

2026-09-05T02:38:52.490961+00:00 cached candidate_question_boundary: 256/4480 files

2026-09-05T02:38:59.473977+00:00 cached candidate_question_boundary: 512/4480 files

2026-09-05T02:39:07.378305+00:00 cached candidate_question_boundary: 768/4480 files

2026-09-05T02:39:14.585926+00:00 cached candidate_question_boundary: 1024/4480 files

2026-09-05T02:39:21.885062+00:00 cached candidate_question_boundary: 1280/4480 files

2026-09-05T02:39:29.080604+00:00 cached candidate_question_boundary: 1536/4480 files

2026-09-05T02:39:36.375780+00:00 cached candidate_question_boundary: 1792/4480 files

2026-09-05T02:39:43.674727+00:00 cached candidate_question_boundary: 2048/4480 files

2026-09-05T02:39:50.773266+00:00 cached candidate_question_boundary: 2304/4480 files

2026-09-05T02:39:57.689303+00:00 cached candidate_question_boundary: 2560/4480 files

2026-09-05T02:40:04.876165+00:00 cached candidate_question_boundary: 2816/4480 files

2026-09-05T02:40:13.282673+00:00 cached candidate_question_boundary: 3072/4480 files

2026-09-05T02:40:21.990466+00:00 cached candidate_question_boundary: 3328/4480 files

2026-09-05T02:40:31.674347+00:00 cached candidate_question_boundary: 3584/4480 files

2026-09-05T02:40:41.374665+00:00 cached candidate_question_boundary: 3840/4480 files

2026-09-05T02:40:51.082327+00:00 cached candidate_question_boundary: 4096/4480 files

2026-09-05T02:41:00.088670+00:00 cached candidate_question_boundary: 4352/4480 files

2026-09-05T02:41:03.391432+00:00 cached candidate_question_boundary: 4480/4480 files
2026-09-05T02:41:03.391663+00:00 PROBE_SITE_CACHE_READY {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'shape': (32, 4480, 4096), 'cache_gib': 2.1875, 'activation_file_opens': 4480}
2026-09-05T02:41:03.391811+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 0, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2016, 'total': 2688, 'pending': 672, 'percent_complete': 75.0}

2026-09-05T02:41:26.954796+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 0, 'target': 'delta_a', 'completed': 2017, 'total': 2688, 'pending': 671, 'percent_complete': 75.0372}

2026-09-05T02:41:47.787009+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 0, 'target': 'gain', 'completed': 2018, 'total': 2688, 'pending': 670, 'percent_complete': 75.0744}

2026-09-05T02:42:09.909103+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 0, 'target': 'gain_abs', 'completed': 2019, 'total': 2688, 'pending': 669, 'percent_complete': 75.1116}

2026-09-05T02:42:33.888286+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 0, 'target': 'z_bayes', 'completed': 2020, 'total': 2688, 'pending': 668, 'percent_complete': 75.1488}

2026-09-05T02:42:55.406329+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 0, 'target': 'z_heuristic', 'completed': 2021, 'total': 2688, 'pending': 667, 'percent_complete': 75.186}

2026-09-05T02:42:59.210085+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 0, 'target': 'reliability_sign', 'completed': 2022, 'total': 2688, 'pending': 666, 'percent_complete': 75.2232}
2026-09-05T02:42:59.210341+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 1, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2022, 'total': 2688, 'pending': 666, 'percent_complete': 75.2232}

2026-09-05T02:43:21.485394+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 1, 'target': 'delta_a', 'completed': 2023, 'total': 2688, 'pending': 665, 'percent_complete': 75.2604}

2026-09-05T02:43:44.883898+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 1, 'target': 'gain', 'completed': 2024, 'total': 2688, 'pending': 664, 'percent_complete': 75.2976}

2026-09-05T02:44:08.408334+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 1, 'target': 'gain_abs', 'completed': 2025, 'total': 2688, 'pending': 663, 'percent_complete': 75.3348}

2026-09-05T02:44:30.695589+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 1, 'target': 'z_bayes', 'completed': 2026, 'total': 2688, 'pending': 662, 'percent_complete': 75.372}

2026-09-05T02:44:51.717470+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 1, 'target': 'z_heuristic', 'completed': 2027, 'total': 2688, 'pending': 661, 'percent_complete': 75.4092}

2026-09-05T02:44:54.583500+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 1, 'target': 'reliability_sign', 'completed': 2028, 'total': 2688, 'pending': 660, 'percent_complete': 75.4464}
2026-09-05T02:44:54.583894+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 2, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2028, 'total': 2688, 'pending': 660, 'percent_complete': 75.4464}

2026-09-05T02:45:15.575579+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 2, 'target': 'delta_a', 'completed': 2029, 'total': 2688, 'pending': 659, 'percent_complete': 75.4836}

2026-09-05T02:45:39.011353+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 2, 'target': 'gain', 'completed': 2030, 'total': 2688, 'pending': 658, 'percent_complete': 75.5208}

2026-09-05T02:46:01.674218+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 2, 'target': 'gain_abs', 'completed': 2031, 'total': 2688, 'pending': 657, 'percent_complete': 75.558}

2026-09-05T02:46:22.879919+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 2, 'target': 'z_bayes', 'completed': 2032, 'total': 2688, 'pending': 656, 'percent_complete': 75.5952}

2026-09-05T02:46:45.777847+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 2, 'target': 'z_heuristic', 'completed': 2033, 'total': 2688, 'pending': 655, 'percent_complete': 75.6324}

2026-09-05T02:46:49.010971+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 2, 'target': 'reliability_sign', 'completed': 2034, 'total': 2688, 'pending': 654, 'percent_complete': 75.6696}
2026-09-05T02:46:49.011221+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 3, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2034, 'total': 2688, 'pending': 654, 'percent_complete': 75.6696}

2026-09-05T02:47:11.276694+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 3, 'target': 'delta_a', 'completed': 2035, 'total': 2688, 'pending': 653, 'percent_complete': 75.7068}

2026-09-05T02:47:35.500132+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 3, 'target': 'gain', 'completed': 2036, 'total': 2688, 'pending': 652, 'percent_complete': 75.744}

2026-09-05T02:48:00.717916+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 3, 'target': 'gain_abs', 'completed': 2037, 'total': 2688, 'pending': 651, 'percent_complete': 75.7812}

2026-09-05T02:48:24.420028+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 3, 'target': 'z_bayes', 'completed': 2038, 'total': 2688, 'pending': 650, 'percent_complete': 75.8185}

2026-09-05T02:48:46.376061+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 3, 'target': 'z_heuristic', 'completed': 2039, 'total': 2688, 'pending': 649, 'percent_complete': 75.8557}

2026-09-05T02:48:48.696796+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 3, 'target': 'reliability_sign', 'completed': 2040, 'total': 2688, 'pending': 648, 'percent_complete': 75.8929}
2026-09-05T02:48:48.697101+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 4, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2040, 'total': 2688, 'pending': 648, 'percent_complete': 75.8929}

2026-09-05T02:49:11.778736+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 4, 'target': 'delta_a', 'completed': 2041, 'total': 2688, 'pending': 647, 'percent_complete': 75.9301}

2026-09-05T02:49:33.576236+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 4, 'target': 'gain', 'completed': 2042, 'total': 2688, 'pending': 646, 'percent_complete': 75.9673}

2026-09-05T02:49:57.700542+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 4, 'target': 'gain_abs', 'completed': 2043, 'total': 2688, 'pending': 645, 'percent_complete': 76.0045}

2026-09-05T02:50:18.979871+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 4, 'target': 'z_bayes', 'completed': 2044, 'total': 2688, 'pending': 644, 'percent_complete': 76.0417}

2026-09-05T02:50:42.275113+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 4, 'target': 'z_heuristic', 'completed': 2045, 'total': 2688, 'pending': 643, 'percent_complete': 76.0789}

2026-09-05T02:50:45.196584+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 4, 'target': 'reliability_sign', 'completed': 2046, 'total': 2688, 'pending': 642, 'percent_complete': 76.1161}
2026-09-05T02:50:45.196897+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 5, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2046, 'total': 2688, 'pending': 642, 'percent_complete': 76.1161}

2026-09-05T02:51:09.898769+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 5, 'target': 'delta_a', 'completed': 2047, 'total': 2688, 'pending': 641, 'percent_complete': 76.1533}

2026-09-05T02:51:33.992415+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 5, 'target': 'gain', 'completed': 2048, 'total': 2688, 'pending': 640, 'percent_complete': 76.1905}

2026-09-05T02:51:56.897195+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 5, 'target': 'gain_abs', 'completed': 2049, 'total': 2688, 'pending': 639, 'percent_complete': 76.2277}

2026-09-05T02:52:19.381998+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 5, 'target': 'z_bayes', 'completed': 2050, 'total': 2688, 'pending': 638, 'percent_complete': 76.2649}

2026-09-05T02:52:43.173984+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 5, 'target': 'z_heuristic', 'completed': 2051, 'total': 2688, 'pending': 637, 'percent_complete': 76.3021}

2026-09-05T02:52:45.898721+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 5, 'target': 'reliability_sign', 'completed': 2052, 'total': 2688, 'pending': 636, 'percent_complete': 76.3393}
2026-09-05T02:52:45.899028+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 6, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2052, 'total': 2688, 'pending': 636, 'percent_complete': 76.3393}

2026-09-05T02:53:07.878536+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 6, 'target': 'delta_a', 'completed': 2053, 'total': 2688, 'pending': 635, 'percent_complete': 76.3765}

2026-09-05T02:53:33.391677+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 6, 'target': 'gain', 'completed': 2054, 'total': 2688, 'pending': 634, 'percent_complete': 76.4137}

2026-09-05T02:53:57.907435+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 6, 'target': 'gain_abs', 'completed': 2055, 'total': 2688, 'pending': 633, 'percent_complete': 76.4509}

2026-09-05T02:54:21.383278+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 6, 'target': 'z_bayes', 'completed': 2056, 'total': 2688, 'pending': 632, 'percent_complete': 76.4881}

2026-09-05T02:54:45.778453+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 6, 'target': 'z_heuristic', 'completed': 2057, 'total': 2688, 'pending': 631, 'percent_complete': 76.5253}

2026-09-05T02:54:49.209144+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 6, 'target': 'reliability_sign', 'completed': 2058, 'total': 2688, 'pending': 630, 'percent_complete': 76.5625}
2026-09-05T02:54:49.209504+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 7, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2058, 'total': 2688, 'pending': 630, 'percent_complete': 76.5625}

2026-09-05T02:55:13.509650+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 7, 'target': 'delta_a', 'completed': 2059, 'total': 2688, 'pending': 629, 'percent_complete': 76.5997}

2026-09-05T02:55:35.986646+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 7, 'target': 'gain', 'completed': 2060, 'total': 2688, 'pending': 628, 'percent_complete': 76.6369}

2026-09-05T02:55:59.215212+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 7, 'target': 'gain_abs', 'completed': 2061, 'total': 2688, 'pending': 627, 'percent_complete': 76.6741}

2026-09-05T02:56:22.990664+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 7, 'target': 'z_bayes', 'completed': 2062, 'total': 2688, 'pending': 626, 'percent_complete': 76.7113}

2026-09-05T02:56:45.978336+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 7, 'target': 'z_heuristic', 'completed': 2063, 'total': 2688, 'pending': 625, 'percent_complete': 76.7485}

2026-09-05T02:56:49.396539+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 7, 'target': 'reliability_sign', 'completed': 2064, 'total': 2688, 'pending': 624, 'percent_complete': 76.7857}
2026-09-05T02:56:49.396789+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 8, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2064, 'total': 2688, 'pending': 624, 'percent_complete': 76.7857}

2026-09-05T02:57:11.982767+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 8, 'target': 'delta_a', 'completed': 2065, 'total': 2688, 'pending': 623, 'percent_complete': 76.8229}

2026-09-05T02:57:37.114657+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 8, 'target': 'gain', 'completed': 2066, 'total': 2688, 'pending': 622, 'percent_complete': 76.8601}

2026-09-05T02:58:00.477126+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 8, 'target': 'gain_abs', 'completed': 2067, 'total': 2688, 'pending': 621, 'percent_complete': 76.8973}

2026-09-05T02:58:21.304725+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 8, 'target': 'z_bayes', 'completed': 2068, 'total': 2688, 'pending': 620, 'percent_complete': 76.9345}

2026-09-05T02:58:42.477837+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 8, 'target': 'z_heuristic', 'completed': 2069, 'total': 2688, 'pending': 619, 'percent_complete': 76.9717}

2026-09-05T02:58:45.602367+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 8, 'target': 'reliability_sign', 'completed': 2070, 'total': 2688, 'pending': 618, 'percent_complete': 77.0089}
2026-09-05T02:58:45.602752+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 9, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2070, 'total': 2688, 'pending': 618, 'percent_complete': 77.0089}

2026-09-05T02:59:09.998614+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 9, 'target': 'delta_a', 'completed': 2071, 'total': 2688, 'pending': 617, 'percent_complete': 77.0461}

2026-09-05T02:59:34.716927+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 9, 'target': 'gain', 'completed': 2072, 'total': 2688, 'pending': 616, 'percent_complete': 77.0833}

2026-09-05T02:59:56.894963+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 9, 'target': 'gain_abs', 'completed': 2073, 'total': 2688, 'pending': 615, 'percent_complete': 77.1205}

2026-09-05T03:00:21.382384+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 9, 'target': 'z_bayes', 'completed': 2074, 'total': 2688, 'pending': 614, 'percent_complete': 77.1577}

2026-09-05T03:00:44.384123+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 9, 'target': 'z_heuristic', 'completed': 2075, 'total': 2688, 'pending': 613, 'percent_complete': 77.1949}

2026-09-05T03:00:47.600705+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 9, 'target': 'reliability_sign', 'completed': 2076, 'total': 2688, 'pending': 612, 'percent_complete': 77.2321}
2026-09-05T03:00:47.600998+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 10, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2076, 'total': 2688, 'pending': 612, 'percent_complete': 77.2321}

2026-09-05T03:01:10.700600+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 10, 'target': 'delta_a', 'completed': 2077, 'total': 2688, 'pending': 611, 'percent_complete': 77.2693}

2026-09-05T03:01:32.995527+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 10, 'target': 'gain', 'completed': 2078, 'total': 2688, 'pending': 610, 'percent_complete': 77.3065}

2026-09-05T03:01:55.281160+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 10, 'target': 'gain_abs', 'completed': 2079, 'total': 2688, 'pending': 609, 'percent_complete': 77.3438}

2026-09-05T03:02:20.580019+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 10, 'target': 'z_bayes', 'completed': 2080, 'total': 2688, 'pending': 608, 'percent_complete': 77.381}

2026-09-05T03:02:43.124176+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 10, 'target': 'z_heuristic', 'completed': 2081, 'total': 2688, 'pending': 607, 'percent_complete': 77.4182}

2026-09-05T03:02:45.287664+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 10, 'target': 'reliability_sign', 'completed': 2082, 'total': 2688, 'pending': 606, 'percent_complete': 77.4554}
2026-09-05T03:02:45.287949+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 11, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2082, 'total': 2688, 'pending': 606, 'percent_complete': 77.4554}

2026-09-05T03:03:10.179828+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 11, 'target': 'delta_a', 'completed': 2083, 'total': 2688, 'pending': 605, 'percent_complete': 77.4926}

2026-09-05T03:03:31.678286+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 11, 'target': 'gain', 'completed': 2084, 'total': 2688, 'pending': 604, 'percent_complete': 77.5298}

2026-09-05T03:03:57.685775+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 11, 'target': 'gain_abs', 'completed': 2085, 'total': 2688, 'pending': 603, 'percent_complete': 77.567}

2026-09-05T03:04:19.105352+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 11, 'target': 'z_bayes', 'completed': 2086, 'total': 2688, 'pending': 602, 'percent_complete': 77.6042}

2026-09-05T03:04:50.715565+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 11, 'target': 'z_heuristic', 'completed': 2087, 'total': 2688, 'pending': 601, 'percent_complete': 77.6414}

2026-09-05T03:04:53.102123+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 11, 'target': 'reliability_sign', 'completed': 2088, 'total': 2688, 'pending': 600, 'percent_complete': 77.6786}
2026-09-05T03:04:53.102420+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 12, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2088, 'total': 2688, 'pending': 600, 'percent_complete': 77.6786}

2026-09-05T03:05:22.599024+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 12, 'target': 'delta_a', 'completed': 2089, 'total': 2688, 'pending': 599, 'percent_complete': 77.7158}

2026-09-05T03:05:47.307688+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 12, 'target': 'gain', 'completed': 2090, 'total': 2688, 'pending': 598, 'percent_complete': 77.753}

2026-09-05T03:06:14.691051+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 12, 'target': 'gain_abs', 'completed': 2091, 'total': 2688, 'pending': 597, 'percent_complete': 77.7902}

2026-09-05T03:06:37.305573+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 12, 'target': 'z_bayes', 'completed': 2092, 'total': 2688, 'pending': 596, 'percent_complete': 77.8274}

2026-09-05T03:07:04.996166+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 12, 'target': 'z_heuristic', 'completed': 2093, 'total': 2688, 'pending': 595, 'percent_complete': 77.8646}

2026-09-05T03:07:07.479874+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 12, 'target': 'reliability_sign', 'completed': 2094, 'total': 2688, 'pending': 594, 'percent_complete': 77.9018}
2026-09-05T03:07:07.480174+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 13, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2094, 'total': 2688, 'pending': 594, 'percent_complete': 77.9018}

2026-09-05T03:07:34.418253+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 13, 'target': 'delta_a', 'completed': 2095, 'total': 2688, 'pending': 593, 'percent_complete': 77.939}

2026-09-05T03:07:59.205749+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 13, 'target': 'gain', 'completed': 2096, 'total': 2688, 'pending': 592, 'percent_complete': 77.9762}

2026-09-05T03:08:26.312353+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 13, 'target': 'gain_abs', 'completed': 2097, 'total': 2688, 'pending': 591, 'percent_complete': 78.0134}

2026-09-05T03:08:53.079043+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 13, 'target': 'z_bayes', 'completed': 2098, 'total': 2688, 'pending': 590, 'percent_complete': 78.0506}

2026-09-05T03:09:18.274499+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 13, 'target': 'z_heuristic', 'completed': 2099, 'total': 2688, 'pending': 589, 'percent_complete': 78.0878}

2026-09-05T03:09:21.077254+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 13, 'target': 'reliability_sign', 'completed': 2100, 'total': 2688, 'pending': 588, 'percent_complete': 78.125}
2026-09-05T03:09:21.077493+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 14, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2100, 'total': 2688, 'pending': 588, 'percent_complete': 78.125}

2026-09-05T03:09:48.097993+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 14, 'target': 'delta_a', 'completed': 2101, 'total': 2688, 'pending': 587, 'percent_complete': 78.1622}

2026-09-05T03:10:15.694853+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 14, 'target': 'gain', 'completed': 2102, 'total': 2688, 'pending': 586, 'percent_complete': 78.1994}

2026-09-05T03:10:42.685321+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 14, 'target': 'gain_abs', 'completed': 2103, 'total': 2688, 'pending': 585, 'percent_complete': 78.2366}

2026-09-05T03:11:09.573048+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 14, 'target': 'z_bayes', 'completed': 2104, 'total': 2688, 'pending': 584, 'percent_complete': 78.2738}

2026-09-05T03:11:36.614872+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 14, 'target': 'z_heuristic', 'completed': 2105, 'total': 2688, 'pending': 583, 'percent_complete': 78.311}

2026-09-05T03:11:39.286785+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 14, 'target': 'reliability_sign', 'completed': 2106, 'total': 2688, 'pending': 582, 'percent_complete': 78.3482}
2026-09-05T03:11:39.287119+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 15, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2106, 'total': 2688, 'pending': 582, 'percent_complete': 78.3482}

2026-09-05T03:12:08.082543+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 15, 'target': 'delta_a', 'completed': 2107, 'total': 2688, 'pending': 581, 'percent_complete': 78.3854}

2026-09-05T03:12:34.317949+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 15, 'target': 'gain', 'completed': 2108, 'total': 2688, 'pending': 580, 'percent_complete': 78.4226}

2026-09-05T03:13:04.184526+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 15, 'target': 'gain_abs', 'completed': 2109, 'total': 2688, 'pending': 579, 'percent_complete': 78.4598}

2026-09-05T03:13:31.719110+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 15, 'target': 'z_bayes', 'completed': 2110, 'total': 2688, 'pending': 578, 'percent_complete': 78.497}

2026-09-05T03:13:59.015950+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 15, 'target': 'z_heuristic', 'completed': 2111, 'total': 2688, 'pending': 577, 'percent_complete': 78.5342}

2026-09-05T03:14:01.694391+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 15, 'target': 'reliability_sign', 'completed': 2112, 'total': 2688, 'pending': 576, 'percent_complete': 78.5714}
2026-09-05T03:14:01.694727+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 16, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2112, 'total': 2688, 'pending': 576, 'percent_complete': 78.5714}

2026-09-05T03:14:28.196292+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 16, 'target': 'delta_a', 'completed': 2113, 'total': 2688, 'pending': 575, 'percent_complete': 78.6086}

2026-09-05T03:14:55.596559+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 16, 'target': 'gain', 'completed': 2114, 'total': 2688, 'pending': 574, 'percent_complete': 78.6458}

2026-09-05T03:15:26.420181+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 16, 'target': 'gain_abs', 'completed': 2115, 'total': 2688, 'pending': 573, 'percent_complete': 78.683}

2026-09-05T03:15:52.601893+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 16, 'target': 'z_bayes', 'completed': 2116, 'total': 2688, 'pending': 572, 'percent_complete': 78.7202}

2026-09-05T03:16:19.693673+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 16, 'target': 'z_heuristic', 'completed': 2117, 'total': 2688, 'pending': 571, 'percent_complete': 78.7574}

2026-09-05T03:16:22.204237+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 16, 'target': 'reliability_sign', 'completed': 2118, 'total': 2688, 'pending': 570, 'percent_complete': 78.7946}
2026-09-05T03:16:22.204500+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 17, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2118, 'total': 2688, 'pending': 570, 'percent_complete': 78.7946}

2026-09-05T03:16:48.795514+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 17, 'target': 'delta_a', 'completed': 2119, 'total': 2688, 'pending': 569, 'percent_complete': 78.8318}

2026-09-05T03:17:17.589301+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 17, 'target': 'gain', 'completed': 2120, 'total': 2688, 'pending': 568, 'percent_complete': 78.869}

2026-09-05T03:17:44.613805+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 17, 'target': 'gain_abs', 'completed': 2121, 'total': 2688, 'pending': 567, 'percent_complete': 78.9062}

2026-09-05T03:18:13.087578+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 17, 'target': 'z_bayes', 'completed': 2122, 'total': 2688, 'pending': 566, 'percent_complete': 78.9435}

2026-09-05T03:18:41.907299+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 17, 'target': 'z_heuristic', 'completed': 2123, 'total': 2688, 'pending': 565, 'percent_complete': 78.9807}

2026-09-05T03:18:44.172385+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 17, 'target': 'reliability_sign', 'completed': 2124, 'total': 2688, 'pending': 564, 'percent_complete': 79.0179}
2026-09-05T03:18:44.172686+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 18, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2124, 'total': 2688, 'pending': 564, 'percent_complete': 79.0179}

2026-09-05T03:19:14.502080+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 18, 'target': 'delta_a', 'completed': 2125, 'total': 2688, 'pending': 563, 'percent_complete': 79.0551}

2026-09-05T03:19:43.305567+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 18, 'target': 'gain', 'completed': 2126, 'total': 2688, 'pending': 562, 'percent_complete': 79.0923}

2026-09-05T03:20:11.793804+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 18, 'target': 'gain_abs', 'completed': 2127, 'total': 2688, 'pending': 561, 'percent_complete': 79.1295}

2026-09-05T03:20:37.607469+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 18, 'target': 'z_bayes', 'completed': 2128, 'total': 2688, 'pending': 560, 'percent_complete': 79.1667}

2026-09-05T03:21:05.271764+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 18, 'target': 'z_heuristic', 'completed': 2129, 'total': 2688, 'pending': 559, 'percent_complete': 79.2039}

2026-09-05T03:21:07.596334+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 18, 'target': 'reliability_sign', 'completed': 2130, 'total': 2688, 'pending': 558, 'percent_complete': 79.2411}
2026-09-05T03:21:07.596621+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 19, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2130, 'total': 2688, 'pending': 558, 'percent_complete': 79.2411}

2026-09-05T03:21:34.996052+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 19, 'target': 'delta_a', 'completed': 2131, 'total': 2688, 'pending': 557, 'percent_complete': 79.2783}

2026-09-05T03:22:02.883415+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 19, 'target': 'gain', 'completed': 2132, 'total': 2688, 'pending': 556, 'percent_complete': 79.3155}

2026-09-05T03:22:29.978318+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 19, 'target': 'gain_abs', 'completed': 2133, 'total': 2688, 'pending': 555, 'percent_complete': 79.3527}

2026-09-05T03:22:56.786251+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 19, 'target': 'z_bayes', 'completed': 2134, 'total': 2688, 'pending': 554, 'percent_complete': 79.3899}

2026-09-05T03:23:22.894728+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 19, 'target': 'z_heuristic', 'completed': 2135, 'total': 2688, 'pending': 553, 'percent_complete': 79.4271}

2026-09-05T03:23:25.083225+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 19, 'target': 'reliability_sign', 'completed': 2136, 'total': 2688, 'pending': 552, 'percent_complete': 79.4643}
2026-09-05T03:23:25.083516+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 20, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2136, 'total': 2688, 'pending': 552, 'percent_complete': 79.4643}

2026-09-05T03:23:53.774278+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 20, 'target': 'delta_a', 'completed': 2137, 'total': 2688, 'pending': 551, 'percent_complete': 79.5015}

2026-09-05T03:24:20.910222+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 20, 'target': 'gain', 'completed': 2138, 'total': 2688, 'pending': 550, 'percent_complete': 79.5387}

2026-09-05T03:24:48.404347+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 20, 'target': 'gain_abs', 'completed': 2139, 'total': 2688, 'pending': 549, 'percent_complete': 79.5759}

2026-09-05T03:25:17.183298+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 20, 'target': 'z_bayes', 'completed': 2140, 'total': 2688, 'pending': 548, 'percent_complete': 79.6131}

2026-09-05T03:25:43.776373+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 20, 'target': 'z_heuristic', 'completed': 2141, 'total': 2688, 'pending': 547, 'percent_complete': 79.6503}

2026-09-05T03:25:46.101407+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 20, 'target': 'reliability_sign', 'completed': 2142, 'total': 2688, 'pending': 546, 'percent_complete': 79.6875}
2026-09-05T03:25:46.101646+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 21, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2142, 'total': 2688, 'pending': 546, 'percent_complete': 79.6875}

2026-09-05T03:26:14.301933+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 21, 'target': 'delta_a', 'completed': 2143, 'total': 2688, 'pending': 545, 'percent_complete': 79.7247}

2026-09-05T03:26:42.478682+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 21, 'target': 'gain', 'completed': 2144, 'total': 2688, 'pending': 544, 'percent_complete': 79.7619}

2026-09-05T03:27:11.587643+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 21, 'target': 'gain_abs', 'completed': 2145, 'total': 2688, 'pending': 543, 'percent_complete': 79.7991}

2026-09-05T03:27:36.282058+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 21, 'target': 'z_bayes', 'completed': 2146, 'total': 2688, 'pending': 542, 'percent_complete': 79.8363}

2026-09-05T03:27:59.586507+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 21, 'target': 'z_heuristic', 'completed': 2147, 'total': 2688, 'pending': 541, 'percent_complete': 79.8735}

2026-09-05T03:28:01.413201+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 21, 'target': 'reliability_sign', 'completed': 2148, 'total': 2688, 'pending': 540, 'percent_complete': 79.9107}
2026-09-05T03:28:01.413512+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 22, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2148, 'total': 2688, 'pending': 540, 'percent_complete': 79.9107}

2026-09-05T03:28:25.593042+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 22, 'target': 'delta_a', 'completed': 2149, 'total': 2688, 'pending': 539, 'percent_complete': 79.9479}

2026-09-05T03:28:46.907950+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 22, 'target': 'gain', 'completed': 2150, 'total': 2688, 'pending': 538, 'percent_complete': 79.9851}

2026-09-05T03:29:04.809480+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 22, 'target': 'gain_abs', 'completed': 2151, 'total': 2688, 'pending': 537, 'percent_complete': 80.0223}

2026-09-05T03:29:19.885089+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 22, 'target': 'z_bayes', 'completed': 2152, 'total': 2688, 'pending': 536, 'percent_complete': 80.0595}

2026-09-05T03:29:32.576594+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 22, 'target': 'z_heuristic', 'completed': 2153, 'total': 2688, 'pending': 535, 'percent_complete': 80.0967}

2026-09-05T03:29:34.289829+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 22, 'target': 'reliability_sign', 'completed': 2154, 'total': 2688, 'pending': 534, 'percent_complete': 80.1339}
2026-09-05T03:29:34.290101+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 23, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2154, 'total': 2688, 'pending': 534, 'percent_complete': 80.1339}

2026-09-05T03:29:49.903441+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 23, 'target': 'delta_a', 'completed': 2155, 'total': 2688, 'pending': 533, 'percent_complete': 80.1711}

2026-09-05T03:30:03.303866+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 23, 'target': 'gain', 'completed': 2156, 'total': 2688, 'pending': 532, 'percent_complete': 80.2083}

2026-09-05T03:30:25.877991+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 23, 'target': 'gain_abs', 'completed': 2157, 'total': 2688, 'pending': 531, 'percent_complete': 80.2455}

2026-09-05T03:30:44.304815+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 23, 'target': 'z_bayes', 'completed': 2158, 'total': 2688, 'pending': 530, 'percent_complete': 80.2827}

2026-09-05T03:31:10.302530+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 23, 'target': 'z_heuristic', 'completed': 2159, 'total': 2688, 'pending': 529, 'percent_complete': 80.3199}

2026-09-05T03:31:12.390375+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 23, 'target': 'reliability_sign', 'completed': 2160, 'total': 2688, 'pending': 528, 'percent_complete': 80.3571}
2026-09-05T03:31:12.390674+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 24, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2160, 'total': 2688, 'pending': 528, 'percent_complete': 80.3571}

2026-09-05T03:31:30.499796+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 24, 'target': 'delta_a', 'completed': 2161, 'total': 2688, 'pending': 527, 'percent_complete': 80.3943}

2026-09-05T03:31:48.000943+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 24, 'target': 'gain', 'completed': 2162, 'total': 2688, 'pending': 526, 'percent_complete': 80.4315}

2026-09-05T03:32:10.981961+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 24, 'target': 'gain_abs', 'completed': 2163, 'total': 2688, 'pending': 525, 'percent_complete': 80.4688}

2026-09-05T03:32:33.087483+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 24, 'target': 'z_bayes', 'completed': 2164, 'total': 2688, 'pending': 524, 'percent_complete': 80.506}

2026-09-05T03:32:57.573703+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 24, 'target': 'z_heuristic', 'completed': 2165, 'total': 2688, 'pending': 523, 'percent_complete': 80.5432}

2026-09-05T03:32:59.497495+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 24, 'target': 'reliability_sign', 'completed': 2166, 'total': 2688, 'pending': 522, 'percent_complete': 80.5804}
2026-09-05T03:32:59.497816+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 25, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2166, 'total': 2688, 'pending': 522, 'percent_complete': 80.5804}

2026-09-05T03:33:19.790098+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 25, 'target': 'delta_a', 'completed': 2167, 'total': 2688, 'pending': 521, 'percent_complete': 80.6176}

2026-09-05T03:33:36.584651+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 25, 'target': 'gain', 'completed': 2168, 'total': 2688, 'pending': 520, 'percent_complete': 80.6548}

2026-09-05T03:34:03.803928+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 25, 'target': 'gain_abs', 'completed': 2169, 'total': 2688, 'pending': 519, 'percent_complete': 80.692}

2026-09-05T03:34:24.307907+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 25, 'target': 'z_bayes', 'completed': 2170, 'total': 2688, 'pending': 518, 'percent_complete': 80.7292}

2026-09-05T03:34:54.202030+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 25, 'target': 'z_heuristic', 'completed': 2171, 'total': 2688, 'pending': 517, 'percent_complete': 80.7664}

2026-09-05T03:34:56.186554+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 25, 'target': 'reliability_sign', 'completed': 2172, 'total': 2688, 'pending': 516, 'percent_complete': 80.8036}
2026-09-05T03:34:56.186880+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 26, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2172, 'total': 2688, 'pending': 516, 'percent_complete': 80.8036}

2026-09-05T03:35:25.474710+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 26, 'target': 'delta_a', 'completed': 2173, 'total': 2688, 'pending': 515, 'percent_complete': 80.8408}

2026-09-05T03:35:50.274298+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 26, 'target': 'gain', 'completed': 2174, 'total': 2688, 'pending': 514, 'percent_complete': 80.878}

2026-09-05T03:36:15.701303+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 26, 'target': 'gain_abs', 'completed': 2175, 'total': 2688, 'pending': 513, 'percent_complete': 80.9152}

2026-09-05T03:36:40.987727+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 26, 'target': 'z_bayes', 'completed': 2176, 'total': 2688, 'pending': 512, 'percent_complete': 80.9524}

2026-09-05T03:37:07.594922+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 26, 'target': 'z_heuristic', 'completed': 2177, 'total': 2688, 'pending': 511, 'percent_complete': 80.9896}

2026-09-05T03:37:09.589948+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 26, 'target': 'reliability_sign', 'completed': 2178, 'total': 2688, 'pending': 510, 'percent_complete': 81.0268}
2026-09-05T03:37:09.590219+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 27, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2178, 'total': 2688, 'pending': 510, 'percent_complete': 81.0268}

2026-09-05T03:37:32.182133+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 27, 'target': 'delta_a', 'completed': 2179, 'total': 2688, 'pending': 509, 'percent_complete': 81.064}

2026-09-05T03:37:47.698619+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 27, 'target': 'gain', 'completed': 2180, 'total': 2688, 'pending': 508, 'percent_complete': 81.1012}

2026-09-05T03:38:02.781759+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 27, 'target': 'gain_abs', 'completed': 2181, 'total': 2688, 'pending': 507, 'percent_complete': 81.1384}

2026-09-05T03:38:19.389686+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 27, 'target': 'z_bayes', 'completed': 2182, 'total': 2688, 'pending': 506, 'percent_complete': 81.1756}

2026-09-05T03:38:35.109582+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 27, 'target': 'z_heuristic', 'completed': 2183, 'total': 2688, 'pending': 505, 'percent_complete': 81.2128}

2026-09-05T03:38:36.793128+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 27, 'target': 'reliability_sign', 'completed': 2184, 'total': 2688, 'pending': 504, 'percent_complete': 81.25}
2026-09-05T03:38:36.793409+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 28, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2184, 'total': 2688, 'pending': 504, 'percent_complete': 81.25}

2026-09-05T03:38:49.799163+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 28, 'target': 'delta_a', 'completed': 2185, 'total': 2688, 'pending': 503, 'percent_complete': 81.2872}

2026-09-05T03:39:04.807816+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 28, 'target': 'gain', 'completed': 2186, 'total': 2688, 'pending': 502, 'percent_complete': 81.3244}

2026-09-05T03:39:23.485765+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 28, 'target': 'gain_abs', 'completed': 2187, 'total': 2688, 'pending': 501, 'percent_complete': 81.3616}

2026-09-05T03:39:37.100837+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 28, 'target': 'z_bayes', 'completed': 2188, 'total': 2688, 'pending': 500, 'percent_complete': 81.3988}

2026-09-05T03:39:51.703479+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 28, 'target': 'z_heuristic', 'completed': 2189, 'total': 2688, 'pending': 499, 'percent_complete': 81.436}

2026-09-05T03:39:53.511594+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 28, 'target': 'reliability_sign', 'completed': 2190, 'total': 2688, 'pending': 498, 'percent_complete': 81.4732}
2026-09-05T03:39:53.511881+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 29, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2190, 'total': 2688, 'pending': 498, 'percent_complete': 81.4732}

2026-09-05T03:40:08.194453+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 29, 'target': 'delta_a', 'completed': 2191, 'total': 2688, 'pending': 497, 'percent_complete': 81.5104}

2026-09-05T03:40:26.005181+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 29, 'target': 'gain', 'completed': 2192, 'total': 2688, 'pending': 496, 'percent_complete': 81.5476}

2026-09-05T03:40:43.682749+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 29, 'target': 'gain_abs', 'completed': 2193, 'total': 2688, 'pending': 495, 'percent_complete': 81.5848}

2026-09-05T03:40:59.608643+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 29, 'target': 'z_bayes', 'completed': 2194, 'total': 2688, 'pending': 494, 'percent_complete': 81.622}

2026-09-05T03:41:15.188947+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 29, 'target': 'z_heuristic', 'completed': 2195, 'total': 2688, 'pending': 493, 'percent_complete': 81.6592}

2026-09-05T03:41:17.008627+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 29, 'target': 'reliability_sign', 'completed': 2196, 'total': 2688, 'pending': 492, 'percent_complete': 81.6964}
2026-09-05T03:41:17.008898+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 30, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2196, 'total': 2688, 'pending': 492, 'percent_complete': 81.6964}

2026-09-05T03:41:30.403752+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 30, 'target': 'delta_a', 'completed': 2197, 'total': 2688, 'pending': 491, 'percent_complete': 81.7336}

2026-09-05T03:41:43.478132+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 30, 'target': 'gain', 'completed': 2198, 'total': 2688, 'pending': 490, 'percent_complete': 81.7708}

2026-09-05T03:41:56.998168+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 30, 'target': 'gain_abs', 'completed': 2199, 'total': 2688, 'pending': 489, 'percent_complete': 81.808}

2026-09-05T03:42:11.288093+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 30, 'target': 'z_bayes', 'completed': 2200, 'total': 2688, 'pending': 488, 'percent_complete': 81.8452}

2026-09-05T03:42:24.917723+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 30, 'target': 'z_heuristic', 'completed': 2201, 'total': 2688, 'pending': 487, 'percent_complete': 81.8824}

2026-09-05T03:42:26.584099+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 30, 'target': 'reliability_sign', 'completed': 2202, 'total': 2688, 'pending': 486, 'percent_complete': 81.9196}
2026-09-05T03:42:26.584382+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 31, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2202, 'total': 2688, 'pending': 486, 'percent_complete': 81.9196}

2026-09-05T03:42:41.175258+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 31, 'target': 'delta_a', 'completed': 2203, 'total': 2688, 'pending': 485, 'percent_complete': 81.9568}

2026-09-05T03:42:54.280507+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 31, 'target': 'gain', 'completed': 2204, 'total': 2688, 'pending': 484, 'percent_complete': 81.994}

2026-09-05T03:43:08.275820+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 31, 'target': 'gain_abs', 'completed': 2205, 'total': 2688, 'pending': 483, 'percent_complete': 82.0312}

2026-09-05T03:43:21.790761+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 31, 'target': 'z_bayes', 'completed': 2206, 'total': 2688, 'pending': 482, 'percent_complete': 82.0685}

2026-09-05T03:43:34.801705+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 31, 'target': 'z_heuristic', 'completed': 2207, 'total': 2688, 'pending': 481, 'percent_complete': 82.1057}

2026-09-05T03:43:36.314088+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary', 'layer': 31, 'target': 'reliability_sign', 'completed': 2208, 'total': 2688, 'pending': 480, 'percent_complete': 82.1429}
2026-09-05T03:43:38.340921+00:00 PROBE_SITE_CACHE_RELEASED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_question_boundary'}
2026-09-05T03:43:38.447673+00:00 PROBE_SITE_CACHE_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'site_pending': 192, 'missing_layers': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], 'activation_files': 4480, 'estimated_cache_gib': 2.1875, 'completed': 2208, 'total': 2688, 'pending': 480, 'percent_complete': 82.1429}

2026-09-05T03:43:46.073258+00:00 cached candidate_2_value: 256/4480 files

2026-09-05T03:43:54.274074+00:00 cached candidate_2_value: 512/4480 files

2026-09-05T03:44:02.788274+00:00 cached candidate_2_value: 768/4480 files

2026-09-05T03:44:11.572561+00:00 cached candidate_2_value: 1024/4480 files

2026-09-05T03:44:19.282590+00:00 cached candidate_2_value: 1280/4480 files

2026-09-05T03:44:26.590239+00:00 cached candidate_2_value: 1536/4480 files

2026-09-05T03:44:33.894240+00:00 cached candidate_2_value: 1792/4480 files

2026-09-05T03:44:41.482145+00:00 cached candidate_2_value: 2048/4480 files

2026-09-05T03:44:48.776886+00:00 cached candidate_2_value: 2304/4480 files

2026-09-05T03:44:55.787578+00:00 cached candidate_2_value: 2560/4480 files

2026-09-05T03:45:03.590377+00:00 cached candidate_2_value: 2816/4480 files

2026-09-05T03:45:11.292980+00:00 cached candidate_2_value: 3072/4480 files

2026-09-05T03:45:17.981963+00:00 cached candidate_2_value: 3328/4480 files

2026-09-05T03:45:24.575644+00:00 cached candidate_2_value: 3584/4480 files

2026-09-05T03:45:31.483410+00:00 cached candidate_2_value: 3840/4480 files

2026-09-05T03:45:38.282667+00:00 cached candidate_2_value: 4096/4480 files

2026-09-05T03:45:45.483500+00:00 cached candidate_2_value: 4352/4480 files

2026-09-05T03:45:49.382576+00:00 cached candidate_2_value: 4480/4480 files
2026-09-05T03:45:49.382959+00:00 PROBE_SITE_CACHE_READY {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'shape': (32, 4480, 4096), 'cache_gib': 2.1875, 'activation_file_opens': 4480}
2026-09-05T03:45:49.383169+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 0, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2208, 'total': 2688, 'pending': 480, 'percent_complete': 82.1429}

2026-09-05T03:46:00.521666+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 0, 'target': 'delta_a', 'completed': 2209, 'total': 2688, 'pending': 479, 'percent_complete': 82.1801}

2026-09-05T03:46:10.293853+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 0, 'target': 'gain', 'completed': 2210, 'total': 2688, 'pending': 478, 'percent_complete': 82.2173}

2026-09-05T03:46:20.380284+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 0, 'target': 'gain_abs', 'completed': 2211, 'total': 2688, 'pending': 477, 'percent_complete': 82.2545}

2026-09-05T03:46:30.174157+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 0, 'target': 'z_bayes', 'completed': 2212, 'total': 2688, 'pending': 476, 'percent_complete': 82.2917}

2026-09-05T03:46:40.079914+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 0, 'target': 'z_heuristic', 'completed': 2213, 'total': 2688, 'pending': 475, 'percent_complete': 82.3289}

2026-09-05T03:46:42.408658+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 0, 'target': 'reliability_sign', 'completed': 2214, 'total': 2688, 'pending': 474, 'percent_complete': 82.3661}
2026-09-05T03:46:42.408941+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 1, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2214, 'total': 2688, 'pending': 474, 'percent_complete': 82.3661}

2026-09-05T03:46:55.177916+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 1, 'target': 'delta_a', 'completed': 2215, 'total': 2688, 'pending': 473, 'percent_complete': 82.4033}

2026-09-05T03:47:06.311899+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 1, 'target': 'gain', 'completed': 2216, 'total': 2688, 'pending': 472, 'percent_complete': 82.4405}

2026-09-05T03:47:19.595341+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 1, 'target': 'gain_abs', 'completed': 2217, 'total': 2688, 'pending': 471, 'percent_complete': 82.4777}

2026-09-05T03:47:30.090430+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 1, 'target': 'z_bayes', 'completed': 2218, 'total': 2688, 'pending': 470, 'percent_complete': 82.5149}

2026-09-05T03:47:42.810654+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 1, 'target': 'z_heuristic', 'completed': 2219, 'total': 2688, 'pending': 469, 'percent_complete': 82.5521}

2026-09-05T03:47:45.084944+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 1, 'target': 'reliability_sign', 'completed': 2220, 'total': 2688, 'pending': 468, 'percent_complete': 82.5893}
2026-09-05T03:47:45.085275+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 2, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2220, 'total': 2688, 'pending': 468, 'percent_complete': 82.5893}

2026-09-05T03:47:56.013697+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 2, 'target': 'delta_a', 'completed': 2221, 'total': 2688, 'pending': 467, 'percent_complete': 82.6265}

2026-09-05T03:48:09.708531+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 2, 'target': 'gain', 'completed': 2222, 'total': 2688, 'pending': 466, 'percent_complete': 82.6637}

2026-09-05T03:48:22.719447+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 2, 'target': 'gain_abs', 'completed': 2223, 'total': 2688, 'pending': 465, 'percent_complete': 82.7009}

2026-09-05T03:48:36.101354+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 2, 'target': 'z_bayes', 'completed': 2224, 'total': 2688, 'pending': 464, 'percent_complete': 82.7381}

2026-09-05T03:48:51.875646+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 2, 'target': 'z_heuristic', 'completed': 2225, 'total': 2688, 'pending': 463, 'percent_complete': 82.7753}

2026-09-05T03:48:54.094896+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 2, 'target': 'reliability_sign', 'completed': 2226, 'total': 2688, 'pending': 462, 'percent_complete': 82.8125}
2026-09-05T03:48:54.095181+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 3, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2226, 'total': 2688, 'pending': 462, 'percent_complete': 82.8125}

2026-09-05T03:49:06.684584+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 3, 'target': 'delta_a', 'completed': 2227, 'total': 2688, 'pending': 461, 'percent_complete': 82.8497}

2026-09-05T03:49:21.680322+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 3, 'target': 'gain', 'completed': 2228, 'total': 2688, 'pending': 460, 'percent_complete': 82.8869}

2026-09-05T03:49:38.310799+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 3, 'target': 'gain_abs', 'completed': 2229, 'total': 2688, 'pending': 459, 'percent_complete': 82.9241}

2026-09-05T03:49:54.508468+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 3, 'target': 'z_bayes', 'completed': 2230, 'total': 2688, 'pending': 458, 'percent_complete': 82.9613}

2026-09-05T03:50:09.494364+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 3, 'target': 'z_heuristic', 'completed': 2231, 'total': 2688, 'pending': 457, 'percent_complete': 82.9985}

2026-09-05T03:50:11.585824+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 3, 'target': 'reliability_sign', 'completed': 2232, 'total': 2688, 'pending': 456, 'percent_complete': 83.0357}
2026-09-05T03:50:11.586127+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 4, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2232, 'total': 2688, 'pending': 456, 'percent_complete': 83.0357}

2026-09-05T03:50:25.888167+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 4, 'target': 'delta_a', 'completed': 2233, 'total': 2688, 'pending': 455, 'percent_complete': 83.0729}

2026-09-05T03:50:41.203848+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 4, 'target': 'gain', 'completed': 2234, 'total': 2688, 'pending': 454, 'percent_complete': 83.1101}

2026-09-05T03:50:58.498472+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 4, 'target': 'gain_abs', 'completed': 2235, 'total': 2688, 'pending': 453, 'percent_complete': 83.1473}

2026-09-05T03:51:14.079142+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 4, 'target': 'z_bayes', 'completed': 2236, 'total': 2688, 'pending': 452, 'percent_complete': 83.1845}

2026-09-05T03:51:29.904689+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 4, 'target': 'z_heuristic', 'completed': 2237, 'total': 2688, 'pending': 451, 'percent_complete': 83.2217}

2026-09-05T03:51:32.073889+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 4, 'target': 'reliability_sign', 'completed': 2238, 'total': 2688, 'pending': 450, 'percent_complete': 83.2589}
2026-09-05T03:51:32.074397+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 5, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2238, 'total': 2688, 'pending': 450, 'percent_complete': 83.2589}

2026-09-05T03:51:46.185758+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 5, 'target': 'delta_a', 'completed': 2239, 'total': 2688, 'pending': 449, 'percent_complete': 83.2961}

2026-09-05T03:52:02.296339+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 5, 'target': 'gain', 'completed': 2240, 'total': 2688, 'pending': 448, 'percent_complete': 83.3333}

2026-09-05T03:52:18.971917+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 5, 'target': 'gain_abs', 'completed': 2241, 'total': 2688, 'pending': 447, 'percent_complete': 83.3705}

2026-09-05T03:52:35.888962+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 5, 'target': 'z_bayes', 'completed': 2242, 'total': 2688, 'pending': 446, 'percent_complete': 83.4077}

2026-09-05T03:52:49.002606+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 5, 'target': 'z_heuristic', 'completed': 2243, 'total': 2688, 'pending': 445, 'percent_complete': 83.4449}

2026-09-05T03:52:51.295598+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 5, 'target': 'reliability_sign', 'completed': 2244, 'total': 2688, 'pending': 444, 'percent_complete': 83.4821}
2026-09-05T03:52:51.295922+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 6, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2244, 'total': 2688, 'pending': 444, 'percent_complete': 83.4821}

2026-09-05T03:53:04.187711+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 6, 'target': 'delta_a', 'completed': 2245, 'total': 2688, 'pending': 443, 'percent_complete': 83.5193}

2026-09-05T03:53:18.499361+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 6, 'target': 'gain', 'completed': 2246, 'total': 2688, 'pending': 442, 'percent_complete': 83.5565}

2026-09-05T03:53:35.689091+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 6, 'target': 'gain_abs', 'completed': 2247, 'total': 2688, 'pending': 441, 'percent_complete': 83.5938}

2026-09-05T03:53:51.085087+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 6, 'target': 'z_bayes', 'completed': 2248, 'total': 2688, 'pending': 440, 'percent_complete': 83.631}

2026-09-05T03:54:08.604144+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 6, 'target': 'z_heuristic', 'completed': 2249, 'total': 2688, 'pending': 439, 'percent_complete': 83.6682}

2026-09-05T03:54:10.711025+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 6, 'target': 'reliability_sign', 'completed': 2250, 'total': 2688, 'pending': 438, 'percent_complete': 83.7054}
2026-09-05T03:54:10.711326+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 7, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2250, 'total': 2688, 'pending': 438, 'percent_complete': 83.7054}

2026-09-05T03:54:22.686396+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 7, 'target': 'delta_a', 'completed': 2251, 'total': 2688, 'pending': 437, 'percent_complete': 83.7426}

2026-09-05T03:54:38.282917+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 7, 'target': 'gain', 'completed': 2252, 'total': 2688, 'pending': 436, 'percent_complete': 83.7798}

2026-09-05T03:54:55.082980+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 7, 'target': 'gain_abs', 'completed': 2253, 'total': 2688, 'pending': 435, 'percent_complete': 83.817}

2026-09-05T03:55:13.700549+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 7, 'target': 'z_bayes', 'completed': 2254, 'total': 2688, 'pending': 434, 'percent_complete': 83.8542}

2026-09-05T03:55:32.276139+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 7, 'target': 'z_heuristic', 'completed': 2255, 'total': 2688, 'pending': 433, 'percent_complete': 83.8914}

2026-09-05T03:55:34.599038+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 7, 'target': 'reliability_sign', 'completed': 2256, 'total': 2688, 'pending': 432, 'percent_complete': 83.9286}
2026-09-05T03:55:34.599326+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 8, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2256, 'total': 2688, 'pending': 432, 'percent_complete': 83.9286}

2026-09-05T03:55:47.506596+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 8, 'target': 'delta_a', 'completed': 2257, 'total': 2688, 'pending': 431, 'percent_complete': 83.9658}

2026-09-05T03:56:04.500581+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 8, 'target': 'gain', 'completed': 2258, 'total': 2688, 'pending': 430, 'percent_complete': 84.003}

2026-09-05T03:56:21.114622+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 8, 'target': 'gain_abs', 'completed': 2259, 'total': 2688, 'pending': 429, 'percent_complete': 84.0402}

2026-09-05T03:56:37.293494+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 8, 'target': 'z_bayes', 'completed': 2260, 'total': 2688, 'pending': 428, 'percent_complete': 84.0774}

2026-09-05T03:56:54.196792+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 8, 'target': 'z_heuristic', 'completed': 2261, 'total': 2688, 'pending': 427, 'percent_complete': 84.1146}

2026-09-05T03:56:56.591782+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 8, 'target': 'reliability_sign', 'completed': 2262, 'total': 2688, 'pending': 426, 'percent_complete': 84.1518}
2026-09-05T03:56:56.592065+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 9, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2262, 'total': 2688, 'pending': 426, 'percent_complete': 84.1518}

2026-09-05T03:57:10.999823+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 9, 'target': 'delta_a', 'completed': 2263, 'total': 2688, 'pending': 425, 'percent_complete': 84.189}

2026-09-05T03:57:25.595706+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 9, 'target': 'gain', 'completed': 2264, 'total': 2688, 'pending': 424, 'percent_complete': 84.2262}

2026-09-05T03:57:41.285331+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 9, 'target': 'gain_abs', 'completed': 2265, 'total': 2688, 'pending': 423, 'percent_complete': 84.2634}

2026-09-05T03:57:59.798665+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 9, 'target': 'z_bayes', 'completed': 2266, 'total': 2688, 'pending': 422, 'percent_complete': 84.3006}

2026-09-05T03:58:18.897981+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 9, 'target': 'z_heuristic', 'completed': 2267, 'total': 2688, 'pending': 421, 'percent_complete': 84.3378}

2026-09-05T03:58:21.303584+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 9, 'target': 'reliability_sign', 'completed': 2268, 'total': 2688, 'pending': 420, 'percent_complete': 84.375}
2026-09-05T03:58:21.303961+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 10, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2268, 'total': 2688, 'pending': 420, 'percent_complete': 84.375}

2026-09-05T03:58:38.112684+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 10, 'target': 'delta_a', 'completed': 2269, 'total': 2688, 'pending': 419, 'percent_complete': 84.4122}

2026-09-05T03:58:54.505597+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 10, 'target': 'gain', 'completed': 2270, 'total': 2688, 'pending': 418, 'percent_complete': 84.4494}

2026-09-05T03:59:14.113755+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 10, 'target': 'gain_abs', 'completed': 2271, 'total': 2688, 'pending': 417, 'percent_complete': 84.4866}

2026-09-05T03:59:32.308456+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 10, 'target': 'z_bayes', 'completed': 2272, 'total': 2688, 'pending': 416, 'percent_complete': 84.5238}

2026-09-05T03:59:49.076595+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 10, 'target': 'z_heuristic', 'completed': 2273, 'total': 2688, 'pending': 415, 'percent_complete': 84.561}

2026-09-05T03:59:51.293889+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 10, 'target': 'reliability_sign', 'completed': 2274, 'total': 2688, 'pending': 414, 'percent_complete': 84.5982}
2026-09-05T03:59:51.294176+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 11, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2274, 'total': 2688, 'pending': 414, 'percent_complete': 84.5982}

2026-09-05T04:00:05.582674+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 11, 'target': 'delta_a', 'completed': 2275, 'total': 2688, 'pending': 413, 'percent_complete': 84.6354}

2026-09-05T04:00:22.380318+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 11, 'target': 'gain', 'completed': 2276, 'total': 2688, 'pending': 412, 'percent_complete': 84.6726}

2026-09-05T04:00:39.987514+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 11, 'target': 'gain_abs', 'completed': 2277, 'total': 2688, 'pending': 411, 'percent_complete': 84.7098}

2026-09-05T04:01:00.590305+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 11, 'target': 'z_bayes', 'completed': 2278, 'total': 2688, 'pending': 410, 'percent_complete': 84.747}

2026-09-05T04:01:23.003315+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 11, 'target': 'z_heuristic', 'completed': 2279, 'total': 2688, 'pending': 409, 'percent_complete': 84.7842}

2026-09-05T04:01:25.399227+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 11, 'target': 'reliability_sign', 'completed': 2280, 'total': 2688, 'pending': 408, 'percent_complete': 84.8214}
2026-09-05T04:01:25.399533+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 12, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2280, 'total': 2688, 'pending': 408, 'percent_complete': 84.8214}

2026-09-05T04:01:42.987762+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 12, 'target': 'delta_a', 'completed': 2281, 'total': 2688, 'pending': 407, 'percent_complete': 84.8586}

2026-09-05T04:01:59.804876+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 12, 'target': 'gain', 'completed': 2282, 'total': 2688, 'pending': 406, 'percent_complete': 84.8958}

2026-09-05T04:02:18.085914+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 12, 'target': 'gain_abs', 'completed': 2283, 'total': 2688, 'pending': 405, 'percent_complete': 84.933}

2026-09-05T04:02:38.898629+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 12, 'target': 'z_bayes', 'completed': 2284, 'total': 2688, 'pending': 404, 'percent_complete': 84.9702}

2026-09-05T04:02:58.888366+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 12, 'target': 'z_heuristic', 'completed': 2285, 'total': 2688, 'pending': 403, 'percent_complete': 85.0074}

2026-09-05T04:03:00.890987+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 12, 'target': 'reliability_sign', 'completed': 2286, 'total': 2688, 'pending': 402, 'percent_complete': 85.0446}
2026-09-05T04:03:00.891286+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 13, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2286, 'total': 2688, 'pending': 402, 'percent_complete': 85.0446}

2026-09-05T04:03:16.902455+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 13, 'target': 'delta_a', 'completed': 2287, 'total': 2688, 'pending': 401, 'percent_complete': 85.0818}

2026-09-05T04:03:35.711675+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 13, 'target': 'gain', 'completed': 2288, 'total': 2688, 'pending': 400, 'percent_complete': 85.119}

2026-09-05T04:03:54.585829+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 13, 'target': 'gain_abs', 'completed': 2289, 'total': 2688, 'pending': 399, 'percent_complete': 85.1562}

2026-09-05T04:04:14.519811+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 13, 'target': 'z_bayes', 'completed': 2290, 'total': 2688, 'pending': 398, 'percent_complete': 85.1935}

2026-09-05T04:04:36.011398+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 13, 'target': 'z_heuristic', 'completed': 2291, 'total': 2688, 'pending': 397, 'percent_complete': 85.2307}

2026-09-05T04:04:38.300802+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 13, 'target': 'reliability_sign', 'completed': 2292, 'total': 2688, 'pending': 396, 'percent_complete': 85.2679}
2026-09-05T04:04:38.301091+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 14, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2292, 'total': 2688, 'pending': 396, 'percent_complete': 85.2679}

2026-09-05T04:04:53.104835+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 14, 'target': 'delta_a', 'completed': 2293, 'total': 2688, 'pending': 395, 'percent_complete': 85.3051}

2026-09-05T04:05:16.388797+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 14, 'target': 'gain', 'completed': 2294, 'total': 2688, 'pending': 394, 'percent_complete': 85.3423}

2026-09-05T04:05:33.507155+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 14, 'target': 'gain_abs', 'completed': 2295, 'total': 2688, 'pending': 393, 'percent_complete': 85.3795}

2026-09-05T04:05:51.209511+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 14, 'target': 'z_bayes', 'completed': 2296, 'total': 2688, 'pending': 392, 'percent_complete': 85.4167}

2026-09-05T04:06:08.203730+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 14, 'target': 'z_heuristic', 'completed': 2297, 'total': 2688, 'pending': 391, 'percent_complete': 85.4539}

2026-09-05T04:06:10.077119+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 14, 'target': 'reliability_sign', 'completed': 2298, 'total': 2688, 'pending': 390, 'percent_complete': 85.4911}
2026-09-05T04:06:10.077408+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 15, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2298, 'total': 2688, 'pending': 390, 'percent_complete': 85.4911}

2026-09-05T04:06:25.602960+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 15, 'target': 'delta_a', 'completed': 2299, 'total': 2688, 'pending': 389, 'percent_complete': 85.5283}

2026-09-05T04:06:43.905994+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 15, 'target': 'gain', 'completed': 2300, 'total': 2688, 'pending': 388, 'percent_complete': 85.5655}

2026-09-05T04:07:02.010316+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 15, 'target': 'gain_abs', 'completed': 2301, 'total': 2688, 'pending': 387, 'percent_complete': 85.6027}

2026-09-05T04:07:21.822088+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 15, 'target': 'z_bayes', 'completed': 2302, 'total': 2688, 'pending': 386, 'percent_complete': 85.6399}

2026-09-05T04:07:42.371625+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 15, 'target': 'z_heuristic', 'completed': 2303, 'total': 2688, 'pending': 385, 'percent_complete': 85.6771}

2026-09-05T04:07:44.585991+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 15, 'target': 'reliability_sign', 'completed': 2304, 'total': 2688, 'pending': 384, 'percent_complete': 85.7143}
2026-09-05T04:07:44.586295+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 16, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2304, 'total': 2688, 'pending': 384, 'percent_complete': 85.7143}

2026-09-05T04:08:06.218600+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 16, 'target': 'delta_a', 'completed': 2305, 'total': 2688, 'pending': 383, 'percent_complete': 85.7515}

2026-09-05T04:08:31.104281+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 16, 'target': 'gain', 'completed': 2306, 'total': 2688, 'pending': 382, 'percent_complete': 85.7887}

2026-09-05T04:08:51.996459+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 16, 'target': 'gain_abs', 'completed': 2307, 'total': 2688, 'pending': 381, 'percent_complete': 85.8259}

2026-09-05T04:09:17.198970+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 16, 'target': 'z_bayes', 'completed': 2308, 'total': 2688, 'pending': 380, 'percent_complete': 85.8631}

2026-09-05T04:09:39.000838+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 16, 'target': 'z_heuristic', 'completed': 2309, 'total': 2688, 'pending': 379, 'percent_complete': 85.9003}

2026-09-05T04:09:40.982259+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 16, 'target': 'reliability_sign', 'completed': 2310, 'total': 2688, 'pending': 378, 'percent_complete': 85.9375}
2026-09-05T04:09:40.982565+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 17, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2310, 'total': 2688, 'pending': 378, 'percent_complete': 85.9375}

2026-09-05T04:09:58.422347+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 17, 'target': 'delta_a', 'completed': 2311, 'total': 2688, 'pending': 377, 'percent_complete': 85.9747}

2026-09-05T04:10:22.993785+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 17, 'target': 'gain', 'completed': 2312, 'total': 2688, 'pending': 376, 'percent_complete': 86.0119}

2026-09-05T04:10:44.714965+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 17, 'target': 'gain_abs', 'completed': 2313, 'total': 2688, 'pending': 375, 'percent_complete': 86.0491}

2026-09-05T04:11:09.597076+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 17, 'target': 'z_bayes', 'completed': 2314, 'total': 2688, 'pending': 374, 'percent_complete': 86.0863}

2026-09-05T04:11:31.803290+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 17, 'target': 'z_heuristic', 'completed': 2315, 'total': 2688, 'pending': 373, 'percent_complete': 86.1235}

2026-09-05T04:11:33.882176+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 17, 'target': 'reliability_sign', 'completed': 2316, 'total': 2688, 'pending': 372, 'percent_complete': 86.1607}
2026-09-05T04:11:33.882479+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 18, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2316, 'total': 2688, 'pending': 372, 'percent_complete': 86.1607}

2026-09-05T04:11:50.788088+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 18, 'target': 'delta_a', 'completed': 2317, 'total': 2688, 'pending': 371, 'percent_complete': 86.1979}

2026-09-05T04:12:12.396189+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 18, 'target': 'gain', 'completed': 2318, 'total': 2688, 'pending': 370, 'percent_complete': 86.2351}

2026-09-05T04:12:31.296400+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 18, 'target': 'gain_abs', 'completed': 2319, 'total': 2688, 'pending': 369, 'percent_complete': 86.2723}

2026-09-05T04:12:53.009320+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 18, 'target': 'z_bayes', 'completed': 2320, 'total': 2688, 'pending': 368, 'percent_complete': 86.3095}

2026-09-05T04:13:14.715060+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 18, 'target': 'z_heuristic', 'completed': 2321, 'total': 2688, 'pending': 367, 'percent_complete': 86.3467}

2026-09-05T04:13:16.695523+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 18, 'target': 'reliability_sign', 'completed': 2322, 'total': 2688, 'pending': 366, 'percent_complete': 86.3839}
2026-09-05T04:13:16.695820+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 19, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2322, 'total': 2688, 'pending': 366, 'percent_complete': 86.3839}

2026-09-05T04:13:32.802527+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 19, 'target': 'delta_a', 'completed': 2323, 'total': 2688, 'pending': 365, 'percent_complete': 86.4211}

2026-09-05T04:13:48.612602+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 19, 'target': 'gain', 'completed': 2324, 'total': 2688, 'pending': 364, 'percent_complete': 86.4583}

2026-09-05T04:14:04.176961+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 19, 'target': 'gain_abs', 'completed': 2325, 'total': 2688, 'pending': 363, 'percent_complete': 86.4955}

2026-09-05T04:14:21.499599+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 19, 'target': 'z_bayes', 'completed': 2326, 'total': 2688, 'pending': 362, 'percent_complete': 86.5327}

2026-09-05T04:14:41.421516+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 19, 'target': 'z_heuristic', 'completed': 2327, 'total': 2688, 'pending': 361, 'percent_complete': 86.5699}

2026-09-05T04:14:43.079957+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 19, 'target': 'reliability_sign', 'completed': 2328, 'total': 2688, 'pending': 360, 'percent_complete': 86.6071}
2026-09-05T04:14:43.080264+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 20, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2328, 'total': 2688, 'pending': 360, 'percent_complete': 86.6071}

2026-09-05T04:15:02.001473+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 20, 'target': 'delta_a', 'completed': 2329, 'total': 2688, 'pending': 359, 'percent_complete': 86.6443}

2026-09-05T04:15:24.176823+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 20, 'target': 'gain', 'completed': 2330, 'total': 2688, 'pending': 358, 'percent_complete': 86.6815}

2026-09-05T04:15:42.391833+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 20, 'target': 'gain_abs', 'completed': 2331, 'total': 2688, 'pending': 357, 'percent_complete': 86.7188}

2026-09-05T04:15:59.198381+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 20, 'target': 'z_bayes', 'completed': 2332, 'total': 2688, 'pending': 356, 'percent_complete': 86.756}

2026-09-05T04:16:20.503955+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 20, 'target': 'z_heuristic', 'completed': 2333, 'total': 2688, 'pending': 355, 'percent_complete': 86.7932}

2026-09-05T04:16:22.478309+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 20, 'target': 'reliability_sign', 'completed': 2334, 'total': 2688, 'pending': 354, 'percent_complete': 86.8304}
2026-09-05T04:16:22.478566+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 21, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2334, 'total': 2688, 'pending': 354, 'percent_complete': 86.8304}

2026-09-05T04:16:41.705511+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 21, 'target': 'delta_a', 'completed': 2335, 'total': 2688, 'pending': 353, 'percent_complete': 86.8676}

2026-09-05T04:16:58.493153+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 21, 'target': 'gain', 'completed': 2336, 'total': 2688, 'pending': 352, 'percent_complete': 86.9048}

2026-09-05T04:17:21.774436+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 21, 'target': 'gain_abs', 'completed': 2337, 'total': 2688, 'pending': 351, 'percent_complete': 86.942}

2026-09-05T04:17:38.912519+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 21, 'target': 'z_bayes', 'completed': 2338, 'total': 2688, 'pending': 350, 'percent_complete': 86.9792}

2026-09-05T04:17:57.800573+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 21, 'target': 'z_heuristic', 'completed': 2339, 'total': 2688, 'pending': 349, 'percent_complete': 87.0164}

2026-09-05T04:17:59.811133+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 21, 'target': 'reliability_sign', 'completed': 2340, 'total': 2688, 'pending': 348, 'percent_complete': 87.0536}
2026-09-05T04:17:59.811359+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 22, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2340, 'total': 2688, 'pending': 348, 'percent_complete': 87.0536}

2026-09-05T04:18:14.699883+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 22, 'target': 'delta_a', 'completed': 2341, 'total': 2688, 'pending': 347, 'percent_complete': 87.0908}

2026-09-05T04:18:32.300627+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 22, 'target': 'gain', 'completed': 2342, 'total': 2688, 'pending': 346, 'percent_complete': 87.128}

2026-09-05T04:18:53.693563+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 22, 'target': 'gain_abs', 'completed': 2343, 'total': 2688, 'pending': 345, 'percent_complete': 87.1652}

2026-09-05T04:19:11.200027+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 22, 'target': 'z_bayes', 'completed': 2344, 'total': 2688, 'pending': 344, 'percent_complete': 87.2024}

2026-09-05T04:19:30.798940+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 22, 'target': 'z_heuristic', 'completed': 2345, 'total': 2688, 'pending': 343, 'percent_complete': 87.2396}

2026-09-05T04:19:32.711833+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 22, 'target': 'reliability_sign', 'completed': 2346, 'total': 2688, 'pending': 342, 'percent_complete': 87.2768}
2026-09-05T04:19:32.712118+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 23, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2346, 'total': 2688, 'pending': 342, 'percent_complete': 87.2768}

2026-09-05T04:19:46.803911+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 23, 'target': 'delta_a', 'completed': 2347, 'total': 2688, 'pending': 341, 'percent_complete': 87.314}

2026-09-05T04:20:01.189820+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 23, 'target': 'gain', 'completed': 2348, 'total': 2688, 'pending': 340, 'percent_complete': 87.3512}

2026-09-05T04:20:17.881463+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 23, 'target': 'gain_abs', 'completed': 2349, 'total': 2688, 'pending': 339, 'percent_complete': 87.3884}

2026-09-05T04:20:31.999977+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 23, 'target': 'z_bayes', 'completed': 2350, 'total': 2688, 'pending': 338, 'percent_complete': 87.4256}

2026-09-05T04:20:47.194105+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 23, 'target': 'z_heuristic', 'completed': 2351, 'total': 2688, 'pending': 337, 'percent_complete': 87.4628}

2026-09-05T04:20:48.905942+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 23, 'target': 'reliability_sign', 'completed': 2352, 'total': 2688, 'pending': 336, 'percent_complete': 87.5}
2026-09-05T04:20:48.906190+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 24, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2352, 'total': 2688, 'pending': 336, 'percent_complete': 87.5}

2026-09-05T04:21:03.404353+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 24, 'target': 'delta_a', 'completed': 2353, 'total': 2688, 'pending': 335, 'percent_complete': 87.5372}

2026-09-05T04:21:20.591859+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 24, 'target': 'gain', 'completed': 2354, 'total': 2688, 'pending': 334, 'percent_complete': 87.5744}

2026-09-05T04:21:42.472827+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 24, 'target': 'gain_abs', 'completed': 2355, 'total': 2688, 'pending': 333, 'percent_complete': 87.6116}

2026-09-05T04:22:00.707984+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 24, 'target': 'z_bayes', 'completed': 2356, 'total': 2688, 'pending': 332, 'percent_complete': 87.6488}

2026-09-05T04:22:20.306218+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 24, 'target': 'z_heuristic', 'completed': 2357, 'total': 2688, 'pending': 331, 'percent_complete': 87.686}

2026-09-05T04:22:22.010829+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 24, 'target': 'reliability_sign', 'completed': 2358, 'total': 2688, 'pending': 330, 'percent_complete': 87.7232}
2026-09-05T04:22:22.011084+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 25, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2358, 'total': 2688, 'pending': 330, 'percent_complete': 87.7232}

2026-09-05T04:22:36.509347+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 25, 'target': 'delta_a', 'completed': 2359, 'total': 2688, 'pending': 329, 'percent_complete': 87.7604}

2026-09-05T04:22:54.193578+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 25, 'target': 'gain', 'completed': 2360, 'total': 2688, 'pending': 328, 'percent_complete': 87.7976}

2026-09-05T04:23:17.304217+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 25, 'target': 'gain_abs', 'completed': 2361, 'total': 2688, 'pending': 327, 'percent_complete': 87.8348}

2026-09-05T04:23:32.901384+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 25, 'target': 'z_bayes', 'completed': 2362, 'total': 2688, 'pending': 326, 'percent_complete': 87.872}

2026-09-05T04:23:53.797158+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 25, 'target': 'z_heuristic', 'completed': 2363, 'total': 2688, 'pending': 325, 'percent_complete': 87.9092}

2026-09-05T04:23:55.803275+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 25, 'target': 'reliability_sign', 'completed': 2364, 'total': 2688, 'pending': 324, 'percent_complete': 87.9464}
2026-09-05T04:23:55.803559+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 26, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2364, 'total': 2688, 'pending': 324, 'percent_complete': 87.9464}

2026-09-05T04:24:10.616918+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 26, 'target': 'delta_a', 'completed': 2365, 'total': 2688, 'pending': 323, 'percent_complete': 87.9836}

2026-09-05T04:24:30.494372+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 26, 'target': 'gain', 'completed': 2366, 'total': 2688, 'pending': 322, 'percent_complete': 88.0208}

2026-09-05T04:24:48.194309+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 26, 'target': 'gain_abs', 'completed': 2367, 'total': 2688, 'pending': 321, 'percent_complete': 88.058}

2026-09-05T04:25:07.502727+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 26, 'target': 'z_bayes', 'completed': 2368, 'total': 2688, 'pending': 320, 'percent_complete': 88.0952}

2026-09-05T04:25:24.084073+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 26, 'target': 'z_heuristic', 'completed': 2369, 'total': 2688, 'pending': 319, 'percent_complete': 88.1324}

2026-09-05T04:25:25.874140+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 26, 'target': 'reliability_sign', 'completed': 2370, 'total': 2688, 'pending': 318, 'percent_complete': 88.1696}
2026-09-05T04:25:25.874435+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 27, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2370, 'total': 2688, 'pending': 318, 'percent_complete': 88.1696}

2026-09-05T04:25:40.506679+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 27, 'target': 'delta_a', 'completed': 2371, 'total': 2688, 'pending': 317, 'percent_complete': 88.2068}

2026-09-05T04:25:58.092165+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 27, 'target': 'gain', 'completed': 2372, 'total': 2688, 'pending': 316, 'percent_complete': 88.244}

2026-09-05T04:26:16.595642+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 27, 'target': 'gain_abs', 'completed': 2373, 'total': 2688, 'pending': 315, 'percent_complete': 88.2812}

2026-09-05T04:26:35.774154+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 27, 'target': 'z_bayes', 'completed': 2374, 'total': 2688, 'pending': 314, 'percent_complete': 88.3185}

2026-09-05T04:26:52.008740+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 27, 'target': 'z_heuristic', 'completed': 2375, 'total': 2688, 'pending': 313, 'percent_complete': 88.3557}

2026-09-05T04:26:53.912383+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 27, 'target': 'reliability_sign', 'completed': 2376, 'total': 2688, 'pending': 312, 'percent_complete': 88.3929}
2026-09-05T04:26:53.912712+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 28, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2376, 'total': 2688, 'pending': 312, 'percent_complete': 88.3929}

2026-09-05T04:27:09.002280+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 28, 'target': 'delta_a', 'completed': 2377, 'total': 2688, 'pending': 311, 'percent_complete': 88.4301}

2026-09-05T04:27:24.395839+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 28, 'target': 'gain', 'completed': 2378, 'total': 2688, 'pending': 310, 'percent_complete': 88.4673}

2026-09-05T04:27:43.899544+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 28, 'target': 'gain_abs', 'completed': 2379, 'total': 2688, 'pending': 309, 'percent_complete': 88.5045}

2026-09-05T04:28:03.973422+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 28, 'target': 'z_bayes', 'completed': 2380, 'total': 2688, 'pending': 308, 'percent_complete': 88.5417}

2026-09-05T04:28:25.377432+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 28, 'target': 'z_heuristic', 'completed': 2381, 'total': 2688, 'pending': 307, 'percent_complete': 88.5789}

2026-09-05T04:28:27.290560+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 28, 'target': 'reliability_sign', 'completed': 2382, 'total': 2688, 'pending': 306, 'percent_complete': 88.6161}
2026-09-05T04:28:27.290833+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 29, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2382, 'total': 2688, 'pending': 306, 'percent_complete': 88.6161}

2026-09-05T04:28:42.406936+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 29, 'target': 'delta_a', 'completed': 2383, 'total': 2688, 'pending': 305, 'percent_complete': 88.6533}

2026-09-05T04:28:59.280672+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 29, 'target': 'gain', 'completed': 2384, 'total': 2688, 'pending': 304, 'percent_complete': 88.6905}

2026-09-05T04:29:19.780081+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 29, 'target': 'gain_abs', 'completed': 2385, 'total': 2688, 'pending': 303, 'percent_complete': 88.7277}

2026-09-05T04:29:38.800734+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 29, 'target': 'z_bayes', 'completed': 2386, 'total': 2688, 'pending': 302, 'percent_complete': 88.7649}

2026-09-05T04:29:57.704676+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 29, 'target': 'z_heuristic', 'completed': 2387, 'total': 2688, 'pending': 301, 'percent_complete': 88.8021}

2026-09-05T04:29:59.980667+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 29, 'target': 'reliability_sign', 'completed': 2388, 'total': 2688, 'pending': 300, 'percent_complete': 88.8393}
2026-09-05T04:29:59.980940+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 30, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2388, 'total': 2688, 'pending': 300, 'percent_complete': 88.8393}

2026-09-05T04:30:15.772390+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 30, 'target': 'delta_a', 'completed': 2389, 'total': 2688, 'pending': 299, 'percent_complete': 88.8765}

2026-09-05T04:30:34.580572+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 30, 'target': 'gain', 'completed': 2390, 'total': 2688, 'pending': 298, 'percent_complete': 88.9137}

2026-09-05T04:30:56.905396+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 30, 'target': 'gain_abs', 'completed': 2391, 'total': 2688, 'pending': 297, 'percent_complete': 88.9509}

2026-09-05T04:31:15.794535+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 30, 'target': 'z_bayes', 'completed': 2392, 'total': 2688, 'pending': 296, 'percent_complete': 88.9881}

2026-09-05T04:31:32.303317+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 30, 'target': 'z_heuristic', 'completed': 2393, 'total': 2688, 'pending': 295, 'percent_complete': 89.0253}

2026-09-05T04:31:34.210673+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 30, 'target': 'reliability_sign', 'completed': 2394, 'total': 2688, 'pending': 294, 'percent_complete': 89.0625}
2026-09-05T04:31:34.210981+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 31, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2394, 'total': 2688, 'pending': 294, 'percent_complete': 89.0625}

2026-09-05T04:31:51.000052+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 31, 'target': 'delta_a', 'completed': 2395, 'total': 2688, 'pending': 293, 'percent_complete': 89.0997}

2026-09-05T04:32:07.392134+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 31, 'target': 'gain', 'completed': 2396, 'total': 2688, 'pending': 292, 'percent_complete': 89.1369}

2026-09-05T04:32:26.116132+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 31, 'target': 'gain_abs', 'completed': 2397, 'total': 2688, 'pending': 291, 'percent_complete': 89.1741}

2026-09-05T04:32:44.098658+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 31, 'target': 'z_bayes', 'completed': 2398, 'total': 2688, 'pending': 290, 'percent_complete': 89.2113}

2026-09-05T04:33:01.004635+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 31, 'target': 'z_heuristic', 'completed': 2399, 'total': 2688, 'pending': 289, 'percent_complete': 89.2485}

2026-09-05T04:33:02.797071+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value', 'layer': 31, 'target': 'reliability_sign', 'completed': 2400, 'total': 2688, 'pending': 288, 'percent_complete': 89.2857}
2026-09-05T04:33:04.858873+00:00 PROBE_SITE_CACHE_RELEASED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_2_value'}
2026-09-05T04:33:04.964748+00:00 PROBE_SITE_CACHE_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'site_pending': 192, 'missing_layers': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], 'activation_files': 4480, 'estimated_cache_gib': 2.1875, 'completed': 2400, 'total': 2688, 'pending': 288, 'percent_complete': 89.2857}

2026-09-05T04:33:12.576936+00:00 cached candidate_1_value: 256/4480 files

2026-09-05T04:33:20.273214+00:00 cached candidate_1_value: 512/4480 files

2026-09-05T04:33:28.487473+00:00 cached candidate_1_value: 768/4480 files

2026-09-05T04:33:35.693399+00:00 cached candidate_1_value: 1024/4480 files

2026-09-05T04:33:42.886767+00:00 cached candidate_1_value: 1280/4480 files

2026-09-05T04:33:50.087186+00:00 cached candidate_1_value: 1536/4480 files

2026-09-05T04:33:57.383885+00:00 cached candidate_1_value: 1792/4480 files

2026-09-05T04:34:04.481695+00:00 cached candidate_1_value: 2048/4480 files

2026-09-05T04:34:11.876292+00:00 cached candidate_1_value: 2304/4480 files

2026-09-05T04:34:19.393241+00:00 cached candidate_1_value: 2560/4480 files

2026-09-05T04:34:26.992870+00:00 cached candidate_1_value: 2816/4480 files

2026-09-05T04:34:33.983663+00:00 cached candidate_1_value: 3072/4480 files

2026-09-05T04:34:40.988025+00:00 cached candidate_1_value: 3328/4480 files

2026-09-05T04:34:48.078580+00:00 cached candidate_1_value: 3584/4480 files

2026-09-05T04:34:54.886987+00:00 cached candidate_1_value: 3840/4480 files

2026-09-05T04:35:01.892255+00:00 cached candidate_1_value: 4096/4480 files

2026-09-05T04:35:08.878264+00:00 cached candidate_1_value: 4352/4480 files

2026-09-05T04:35:12.479621+00:00 cached candidate_1_value: 4480/4480 files
2026-09-05T04:35:12.479971+00:00 PROBE_SITE_CACHE_READY {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'shape': (32, 4480, 4096), 'cache_gib': 2.1875, 'activation_file_opens': 4480}
2026-09-05T04:35:12.480181+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 0, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2400, 'total': 2688, 'pending': 288, 'percent_complete': 89.2857}

2026-09-05T04:35:24.918743+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 0, 'target': 'delta_a', 'completed': 2401, 'total': 2688, 'pending': 287, 'percent_complete': 89.3229}

2026-09-05T04:35:36.375125+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 0, 'target': 'gain', 'completed': 2402, 'total': 2688, 'pending': 286, 'percent_complete': 89.3601}

2026-09-05T04:35:49.416714+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 0, 'target': 'gain_abs', 'completed': 2403, 'total': 2688, 'pending': 285, 'percent_complete': 89.3973}

2026-09-05T04:36:00.672649+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 0, 'target': 'z_bayes', 'completed': 2404, 'total': 2688, 'pending': 284, 'percent_complete': 89.4345}

2026-09-05T04:36:11.890977+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 0, 'target': 'z_heuristic', 'completed': 2405, 'total': 2688, 'pending': 283, 'percent_complete': 89.4717}

2026-09-05T04:36:14.093161+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 0, 'target': 'reliability_sign', 'completed': 2406, 'total': 2688, 'pending': 282, 'percent_complete': 89.5089}
2026-09-05T04:36:14.093419+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 1, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2406, 'total': 2688, 'pending': 282, 'percent_complete': 89.5089}

2026-09-05T04:36:27.189918+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 1, 'target': 'delta_a', 'completed': 2407, 'total': 2688, 'pending': 281, 'percent_complete': 89.5461}

2026-09-05T04:36:42.693884+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 1, 'target': 'gain', 'completed': 2408, 'total': 2688, 'pending': 280, 'percent_complete': 89.5833}

2026-09-05T04:36:55.011201+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 1, 'target': 'gain_abs', 'completed': 2409, 'total': 2688, 'pending': 279, 'percent_complete': 89.6205}

2026-09-05T04:37:05.885717+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 1, 'target': 'z_bayes', 'completed': 2410, 'total': 2688, 'pending': 278, 'percent_complete': 89.6577}

2026-09-05T04:37:18.808642+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 1, 'target': 'z_heuristic', 'completed': 2411, 'total': 2688, 'pending': 277, 'percent_complete': 89.6949}

2026-09-05T04:37:20.596326+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 1, 'target': 'reliability_sign', 'completed': 2412, 'total': 2688, 'pending': 276, 'percent_complete': 89.7321}
2026-09-05T04:37:20.596570+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 2, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2412, 'total': 2688, 'pending': 276, 'percent_complete': 89.7321}

2026-09-05T04:37:32.282841+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 2, 'target': 'delta_a', 'completed': 2413, 'total': 2688, 'pending': 275, 'percent_complete': 89.7693}

2026-09-05T04:37:46.195300+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 2, 'target': 'gain', 'completed': 2414, 'total': 2688, 'pending': 274, 'percent_complete': 89.8065}

2026-09-05T04:38:00.987669+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 2, 'target': 'gain_abs', 'completed': 2415, 'total': 2688, 'pending': 273, 'percent_complete': 89.8438}

2026-09-05T04:38:14.972412+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 2, 'target': 'z_bayes', 'completed': 2416, 'total': 2688, 'pending': 272, 'percent_complete': 89.881}

2026-09-05T04:38:28.174890+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 2, 'target': 'z_heuristic', 'completed': 2417, 'total': 2688, 'pending': 271, 'percent_complete': 89.9182}

2026-09-05T04:38:29.887437+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 2, 'target': 'reliability_sign', 'completed': 2418, 'total': 2688, 'pending': 270, 'percent_complete': 89.9554}
2026-09-05T04:38:29.887683+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 3, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2418, 'total': 2688, 'pending': 270, 'percent_complete': 89.9554}

2026-09-05T04:38:42.586964+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 3, 'target': 'delta_a', 'completed': 2419, 'total': 2688, 'pending': 269, 'percent_complete': 89.9926}

2026-09-05T04:38:58.706980+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 3, 'target': 'gain', 'completed': 2420, 'total': 2688, 'pending': 268, 'percent_complete': 90.0298}

2026-09-05T04:39:11.887955+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 3, 'target': 'gain_abs', 'completed': 2421, 'total': 2688, 'pending': 267, 'percent_complete': 90.067}

2026-09-05T04:39:23.894405+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 3, 'target': 'z_bayes', 'completed': 2422, 'total': 2688, 'pending': 266, 'percent_complete': 90.1042}

2026-09-05T04:39:36.287049+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 3, 'target': 'z_heuristic', 'completed': 2423, 'total': 2688, 'pending': 265, 'percent_complete': 90.1414}

2026-09-05T04:39:38.096363+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 3, 'target': 'reliability_sign', 'completed': 2424, 'total': 2688, 'pending': 264, 'percent_complete': 90.1786}
2026-09-05T04:39:38.096600+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 4, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2424, 'total': 2688, 'pending': 264, 'percent_complete': 90.1786}

2026-09-05T04:39:51.207098+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 4, 'target': 'delta_a', 'completed': 2425, 'total': 2688, 'pending': 263, 'percent_complete': 90.2158}

2026-09-05T04:40:02.072154+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 4, 'target': 'gain', 'completed': 2426, 'total': 2688, 'pending': 262, 'percent_complete': 90.253}

2026-09-05T04:40:14.681803+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 4, 'target': 'gain_abs', 'completed': 2427, 'total': 2688, 'pending': 261, 'percent_complete': 90.2902}

2026-09-05T04:40:27.584284+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 4, 'target': 'z_bayes', 'completed': 2428, 'total': 2688, 'pending': 260, 'percent_complete': 90.3274}

2026-09-05T04:40:43.087581+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 4, 'target': 'z_heuristic', 'completed': 2429, 'total': 2688, 'pending': 259, 'percent_complete': 90.3646}

2026-09-05T04:40:45.100211+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 4, 'target': 'reliability_sign', 'completed': 2430, 'total': 2688, 'pending': 258, 'percent_complete': 90.4018}
2026-09-05T04:40:45.100449+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 5, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2430, 'total': 2688, 'pending': 258, 'percent_complete': 90.4018}

2026-09-05T04:40:56.484788+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 5, 'target': 'delta_a', 'completed': 2431, 'total': 2688, 'pending': 257, 'percent_complete': 90.439}

2026-09-05T04:41:08.476168+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 5, 'target': 'gain', 'completed': 2432, 'total': 2688, 'pending': 256, 'percent_complete': 90.4762}

2026-09-05T04:41:23.116663+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 5, 'target': 'gain_abs', 'completed': 2433, 'total': 2688, 'pending': 255, 'percent_complete': 90.5134}

2026-09-05T04:41:37.189479+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 5, 'target': 'z_bayes', 'completed': 2434, 'total': 2688, 'pending': 254, 'percent_complete': 90.5506}

2026-09-05T04:41:50.175264+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 5, 'target': 'z_heuristic', 'completed': 2435, 'total': 2688, 'pending': 253, 'percent_complete': 90.5878}

2026-09-05T04:41:52.201710+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 5, 'target': 'reliability_sign', 'completed': 2436, 'total': 2688, 'pending': 252, 'percent_complete': 90.625}
2026-09-05T04:41:52.201957+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 6, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2436, 'total': 2688, 'pending': 252, 'percent_complete': 90.625}

2026-09-05T04:42:03.781987+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 6, 'target': 'delta_a', 'completed': 2437, 'total': 2688, 'pending': 251, 'percent_complete': 90.6622}

2026-09-05T04:42:15.790516+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 6, 'target': 'gain', 'completed': 2438, 'total': 2688, 'pending': 250, 'percent_complete': 90.6994}

2026-09-05T04:42:28.207030+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 6, 'target': 'gain_abs', 'completed': 2439, 'total': 2688, 'pending': 249, 'percent_complete': 90.7366}

2026-09-05T04:42:40.683352+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 6, 'target': 'z_bayes', 'completed': 2440, 'total': 2688, 'pending': 248, 'percent_complete': 90.7738}

2026-09-05T04:42:56.690174+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 6, 'target': 'z_heuristic', 'completed': 2441, 'total': 2688, 'pending': 247, 'percent_complete': 90.811}

2026-09-05T04:42:58.676075+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 6, 'target': 'reliability_sign', 'completed': 2442, 'total': 2688, 'pending': 246, 'percent_complete': 90.8482}
2026-09-05T04:42:58.676314+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 7, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2442, 'total': 2688, 'pending': 246, 'percent_complete': 90.8482}

2026-09-05T04:43:12.997169+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 7, 'target': 'delta_a', 'completed': 2443, 'total': 2688, 'pending': 245, 'percent_complete': 90.8854}

2026-09-05T04:43:27.682991+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 7, 'target': 'gain', 'completed': 2444, 'total': 2688, 'pending': 244, 'percent_complete': 90.9226}

2026-09-05T04:43:43.398636+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 7, 'target': 'gain_abs', 'completed': 2445, 'total': 2688, 'pending': 243, 'percent_complete': 90.9598}

2026-09-05T04:43:59.885622+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 7, 'target': 'z_bayes', 'completed': 2446, 'total': 2688, 'pending': 242, 'percent_complete': 90.997}

2026-09-05T04:44:17.212882+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 7, 'target': 'z_heuristic', 'completed': 2447, 'total': 2688, 'pending': 241, 'percent_complete': 91.0342}

2026-09-05T04:44:19.478225+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 7, 'target': 'reliability_sign', 'completed': 2448, 'total': 2688, 'pending': 240, 'percent_complete': 91.0714}
2026-09-05T04:44:19.478471+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 8, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2448, 'total': 2688, 'pending': 240, 'percent_complete': 91.0714}

2026-09-05T04:44:34.402045+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 8, 'target': 'delta_a', 'completed': 2449, 'total': 2688, 'pending': 239, 'percent_complete': 91.1086}

2026-09-05T04:44:50.092196+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 8, 'target': 'gain', 'completed': 2450, 'total': 2688, 'pending': 238, 'percent_complete': 91.1458}

2026-09-05T04:45:06.089153+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 8, 'target': 'gain_abs', 'completed': 2451, 'total': 2688, 'pending': 237, 'percent_complete': 91.183}

2026-09-05T04:45:24.109084+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 8, 'target': 'z_bayes', 'completed': 2452, 'total': 2688, 'pending': 236, 'percent_complete': 91.2202}

2026-09-05T04:45:41.416380+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 8, 'target': 'z_heuristic', 'completed': 2453, 'total': 2688, 'pending': 235, 'percent_complete': 91.2574}

2026-09-05T04:45:43.803615+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 8, 'target': 'reliability_sign', 'completed': 2454, 'total': 2688, 'pending': 234, 'percent_complete': 91.2946}
2026-09-05T04:45:43.803876+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 9, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2454, 'total': 2688, 'pending': 234, 'percent_complete': 91.2946}

2026-09-05T04:45:56.502887+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 9, 'target': 'delta_a', 'completed': 2455, 'total': 2688, 'pending': 233, 'percent_complete': 91.3318}

2026-09-05T04:46:10.589836+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 9, 'target': 'gain', 'completed': 2456, 'total': 2688, 'pending': 232, 'percent_complete': 91.369}

2026-09-05T04:46:22.983170+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 9, 'target': 'gain_abs', 'completed': 2457, 'total': 2688, 'pending': 231, 'percent_complete': 91.4062}

2026-09-05T04:46:37.796190+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 9, 'target': 'z_bayes', 'completed': 2458, 'total': 2688, 'pending': 230, 'percent_complete': 91.4435}

2026-09-05T04:46:55.300224+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 9, 'target': 'z_heuristic', 'completed': 2459, 'total': 2688, 'pending': 229, 'percent_complete': 91.4807}

2026-09-05T04:46:57.387047+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 9, 'target': 'reliability_sign', 'completed': 2460, 'total': 2688, 'pending': 228, 'percent_complete': 91.5179}
2026-09-05T04:46:57.387298+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 10, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2460, 'total': 2688, 'pending': 228, 'percent_complete': 91.5179}

2026-09-05T04:47:11.103445+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 10, 'target': 'delta_a', 'completed': 2461, 'total': 2688, 'pending': 227, 'percent_complete': 91.5551}

2026-09-05T04:47:29.310766+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 10, 'target': 'gain', 'completed': 2462, 'total': 2688, 'pending': 226, 'percent_complete': 91.5923}

2026-09-05T04:47:44.109188+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 10, 'target': 'gain_abs', 'completed': 2463, 'total': 2688, 'pending': 225, 'percent_complete': 91.6295}

2026-09-05T04:48:00.811700+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 10, 'target': 'z_bayes', 'completed': 2464, 'total': 2688, 'pending': 224, 'percent_complete': 91.6667}

2026-09-05T04:48:17.097345+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 10, 'target': 'z_heuristic', 'completed': 2465, 'total': 2688, 'pending': 223, 'percent_complete': 91.7039}

2026-09-05T04:48:19.788634+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 10, 'target': 'reliability_sign', 'completed': 2466, 'total': 2688, 'pending': 222, 'percent_complete': 91.7411}
2026-09-05T04:48:19.788879+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 11, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2466, 'total': 2688, 'pending': 222, 'percent_complete': 91.7411}

2026-09-05T04:48:34.716771+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 11, 'target': 'delta_a', 'completed': 2467, 'total': 2688, 'pending': 221, 'percent_complete': 91.7783}

2026-09-05T04:48:54.013834+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 11, 'target': 'gain', 'completed': 2468, 'total': 2688, 'pending': 220, 'percent_complete': 91.8155}

2026-09-05T04:49:11.217864+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 11, 'target': 'gain_abs', 'completed': 2469, 'total': 2688, 'pending': 219, 'percent_complete': 91.8527}

2026-09-05T04:49:29.393913+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 11, 'target': 'z_bayes', 'completed': 2470, 'total': 2688, 'pending': 218, 'percent_complete': 91.8899}

2026-09-05T04:49:45.702902+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 11, 'target': 'z_heuristic', 'completed': 2471, 'total': 2688, 'pending': 217, 'percent_complete': 91.9271}

2026-09-05T04:49:47.987984+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 11, 'target': 'reliability_sign', 'completed': 2472, 'total': 2688, 'pending': 216, 'percent_complete': 91.9643}
2026-09-05T04:49:47.988233+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 12, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2472, 'total': 2688, 'pending': 216, 'percent_complete': 91.9643}

2026-09-05T04:50:05.111604+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 12, 'target': 'delta_a', 'completed': 2473, 'total': 2688, 'pending': 215, 'percent_complete': 92.0015}

2026-09-05T04:50:22.483819+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 12, 'target': 'gain', 'completed': 2474, 'total': 2688, 'pending': 214, 'percent_complete': 92.0387}

2026-09-05T04:50:40.413908+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 12, 'target': 'gain_abs', 'completed': 2475, 'total': 2688, 'pending': 213, 'percent_complete': 92.0759}

2026-09-05T04:51:00.503589+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 12, 'target': 'z_bayes', 'completed': 2476, 'total': 2688, 'pending': 212, 'percent_complete': 92.1131}

2026-09-05T04:51:21.797627+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 12, 'target': 'z_heuristic', 'completed': 2477, 'total': 2688, 'pending': 211, 'percent_complete': 92.1503}

2026-09-05T04:51:23.906435+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 12, 'target': 'reliability_sign', 'completed': 2478, 'total': 2688, 'pending': 210, 'percent_complete': 92.1875}
2026-09-05T04:51:23.906676+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 13, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2478, 'total': 2688, 'pending': 210, 'percent_complete': 92.1875}

2026-09-05T04:51:37.517656+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 13, 'target': 'delta_a', 'completed': 2479, 'total': 2688, 'pending': 209, 'percent_complete': 92.2247}

2026-09-05T04:51:51.898798+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 13, 'target': 'gain', 'completed': 2480, 'total': 2688, 'pending': 208, 'percent_complete': 92.2619}

2026-09-05T04:52:10.116072+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 13, 'target': 'gain_abs', 'completed': 2481, 'total': 2688, 'pending': 207, 'percent_complete': 92.2991}

2026-09-05T04:52:27.502285+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 13, 'target': 'z_bayes', 'completed': 2482, 'total': 2688, 'pending': 206, 'percent_complete': 92.3363}

2026-09-05T04:52:47.790659+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 13, 'target': 'z_heuristic', 'completed': 2483, 'total': 2688, 'pending': 205, 'percent_complete': 92.3735}

2026-09-05T04:52:50.008125+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 13, 'target': 'reliability_sign', 'completed': 2484, 'total': 2688, 'pending': 204, 'percent_complete': 92.4107}
2026-09-05T04:52:50.008365+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 14, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2484, 'total': 2688, 'pending': 204, 'percent_complete': 92.4107}

2026-09-05T04:53:06.404156+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 14, 'target': 'delta_a', 'completed': 2485, 'total': 2688, 'pending': 203, 'percent_complete': 92.4479}

2026-09-05T04:53:25.680802+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 14, 'target': 'gain', 'completed': 2486, 'total': 2688, 'pending': 202, 'percent_complete': 92.4851}

2026-09-05T04:53:45.078688+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 14, 'target': 'gain_abs', 'completed': 2487, 'total': 2688, 'pending': 201, 'percent_complete': 92.5223}

2026-09-05T04:54:03.897780+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 14, 'target': 'z_bayes', 'completed': 2488, 'total': 2688, 'pending': 200, 'percent_complete': 92.5595}

2026-09-05T04:54:24.505398+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 14, 'target': 'z_heuristic', 'completed': 2489, 'total': 2688, 'pending': 199, 'percent_complete': 92.5967}

2026-09-05T04:54:26.501450+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 14, 'target': 'reliability_sign', 'completed': 2490, 'total': 2688, 'pending': 198, 'percent_complete': 92.6339}
2026-09-05T04:54:26.501682+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 15, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2490, 'total': 2688, 'pending': 198, 'percent_complete': 92.6339}

2026-09-05T04:54:40.616033+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 15, 'target': 'delta_a', 'completed': 2491, 'total': 2688, 'pending': 197, 'percent_complete': 92.6711}

2026-09-05T04:54:57.281560+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 15, 'target': 'gain', 'completed': 2492, 'total': 2688, 'pending': 196, 'percent_complete': 92.7083}

2026-09-05T04:55:11.882621+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 15, 'target': 'gain_abs', 'completed': 2493, 'total': 2688, 'pending': 195, 'percent_complete': 92.7455}

2026-09-05T04:55:28.475591+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 15, 'target': 'z_bayes', 'completed': 2494, 'total': 2688, 'pending': 194, 'percent_complete': 92.7827}

2026-09-05T04:55:46.301786+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 15, 'target': 'z_heuristic', 'completed': 2495, 'total': 2688, 'pending': 193, 'percent_complete': 92.8199}

2026-09-05T04:55:48.487877+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 15, 'target': 'reliability_sign', 'completed': 2496, 'total': 2688, 'pending': 192, 'percent_complete': 92.8571}
2026-09-05T04:55:48.488123+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 16, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2496, 'total': 2688, 'pending': 192, 'percent_complete': 92.8571}

2026-09-05T04:56:06.081289+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 16, 'target': 'delta_a', 'completed': 2497, 'total': 2688, 'pending': 191, 'percent_complete': 92.8943}

2026-09-05T04:56:24.372903+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 16, 'target': 'gain', 'completed': 2498, 'total': 2688, 'pending': 190, 'percent_complete': 92.9315}

2026-09-05T04:56:42.491214+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 16, 'target': 'gain_abs', 'completed': 2499, 'total': 2688, 'pending': 189, 'percent_complete': 92.9688}

2026-09-05T04:57:05.788917+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 16, 'target': 'z_bayes', 'completed': 2500, 'total': 2688, 'pending': 188, 'percent_complete': 93.006}

2026-09-05T04:57:25.902533+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 16, 'target': 'z_heuristic', 'completed': 2501, 'total': 2688, 'pending': 187, 'percent_complete': 93.0432}

2026-09-05T04:57:27.897413+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 16, 'target': 'reliability_sign', 'completed': 2502, 'total': 2688, 'pending': 186, 'percent_complete': 93.0804}
2026-09-05T04:57:27.897647+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 17, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2502, 'total': 2688, 'pending': 186, 'percent_complete': 93.0804}

2026-09-05T04:57:44.806018+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 17, 'target': 'delta_a', 'completed': 2503, 'total': 2688, 'pending': 185, 'percent_complete': 93.1176}

2026-09-05T04:58:03.114364+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 17, 'target': 'gain', 'completed': 2504, 'total': 2688, 'pending': 184, 'percent_complete': 93.1548}

2026-09-05T04:58:17.294451+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 17, 'target': 'gain_abs', 'completed': 2505, 'total': 2688, 'pending': 183, 'percent_complete': 93.192}

2026-09-05T04:58:32.910396+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 17, 'target': 'z_bayes', 'completed': 2506, 'total': 2688, 'pending': 182, 'percent_complete': 93.2292}

2026-09-05T04:58:53.317062+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 17, 'target': 'z_heuristic', 'completed': 2507, 'total': 2688, 'pending': 181, 'percent_complete': 93.2664}

2026-09-05T04:58:55.373132+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 17, 'target': 'reliability_sign', 'completed': 2508, 'total': 2688, 'pending': 180, 'percent_complete': 93.3036}
2026-09-05T04:58:55.373381+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 18, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2508, 'total': 2688, 'pending': 180, 'percent_complete': 93.3036}

2026-09-05T04:59:12.197574+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 18, 'target': 'delta_a', 'completed': 2509, 'total': 2688, 'pending': 179, 'percent_complete': 93.3408}

2026-09-05T04:59:30.081039+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 18, 'target': 'gain', 'completed': 2510, 'total': 2688, 'pending': 178, 'percent_complete': 93.378}

2026-09-05T04:59:49.997409+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 18, 'target': 'gain_abs', 'completed': 2511, 'total': 2688, 'pending': 177, 'percent_complete': 93.4152}

2026-09-05T05:00:09.391518+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 18, 'target': 'z_bayes', 'completed': 2512, 'total': 2688, 'pending': 176, 'percent_complete': 93.4524}

2026-09-05T05:00:29.782197+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 18, 'target': 'z_heuristic', 'completed': 2513, 'total': 2688, 'pending': 175, 'percent_complete': 93.4896}

2026-09-05T05:00:31.707059+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 18, 'target': 'reliability_sign', 'completed': 2514, 'total': 2688, 'pending': 174, 'percent_complete': 93.5268}
2026-09-05T05:00:31.707297+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 19, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2514, 'total': 2688, 'pending': 174, 'percent_complete': 93.5268}

2026-09-05T05:00:49.905681+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 19, 'target': 'delta_a', 'completed': 2515, 'total': 2688, 'pending': 173, 'percent_complete': 93.564}

2026-09-05T05:01:07.292373+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 19, 'target': 'gain', 'completed': 2516, 'total': 2688, 'pending': 172, 'percent_complete': 93.6012}

2026-09-05T05:01:30.294873+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 19, 'target': 'gain_abs', 'completed': 2517, 'total': 2688, 'pending': 171, 'percent_complete': 93.6384}

2026-09-05T05:01:49.995729+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 19, 'target': 'z_bayes', 'completed': 2518, 'total': 2688, 'pending': 170, 'percent_complete': 93.6756}

2026-09-05T05:02:09.101152+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 19, 'target': 'z_heuristic', 'completed': 2519, 'total': 2688, 'pending': 169, 'percent_complete': 93.7128}

2026-09-05T05:02:10.913049+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 19, 'target': 'reliability_sign', 'completed': 2520, 'total': 2688, 'pending': 168, 'percent_complete': 93.75}
2026-09-05T05:02:10.913286+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 20, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2520, 'total': 2688, 'pending': 168, 'percent_complete': 93.75}

2026-09-05T05:02:25.903032+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 20, 'target': 'delta_a', 'completed': 2521, 'total': 2688, 'pending': 167, 'percent_complete': 93.7872}

2026-09-05T05:02:41.914933+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 20, 'target': 'gain', 'completed': 2522, 'total': 2688, 'pending': 166, 'percent_complete': 93.8244}

2026-09-05T05:02:59.293705+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 20, 'target': 'gain_abs', 'completed': 2523, 'total': 2688, 'pending': 165, 'percent_complete': 93.8616}

2026-09-05T05:03:22.398424+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 20, 'target': 'z_bayes', 'completed': 2524, 'total': 2688, 'pending': 164, 'percent_complete': 93.8988}

2026-09-05T05:03:40.372091+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 20, 'target': 'z_heuristic', 'completed': 2525, 'total': 2688, 'pending': 163, 'percent_complete': 93.936}

2026-09-05T05:03:41.911750+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 20, 'target': 'reliability_sign', 'completed': 2526, 'total': 2688, 'pending': 162, 'percent_complete': 93.9732}
2026-09-05T05:03:41.911995+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 21, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2526, 'total': 2688, 'pending': 162, 'percent_complete': 93.9732}

2026-09-05T05:03:59.479887+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 21, 'target': 'delta_a', 'completed': 2527, 'total': 2688, 'pending': 161, 'percent_complete': 94.0104}

2026-09-05T05:04:20.080726+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 21, 'target': 'gain', 'completed': 2528, 'total': 2688, 'pending': 160, 'percent_complete': 94.0476}

2026-09-05T05:04:42.592539+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 21, 'target': 'gain_abs', 'completed': 2529, 'total': 2688, 'pending': 159, 'percent_complete': 94.0848}

2026-09-05T05:05:02.618683+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 21, 'target': 'z_bayes', 'completed': 2530, 'total': 2688, 'pending': 158, 'percent_complete': 94.122}

2026-09-05T05:05:24.203129+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 21, 'target': 'z_heuristic', 'completed': 2531, 'total': 2688, 'pending': 157, 'percent_complete': 94.1592}

2026-09-05T05:05:26.006948+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 21, 'target': 'reliability_sign', 'completed': 2532, 'total': 2688, 'pending': 156, 'percent_complete': 94.1964}
2026-09-05T05:05:26.007200+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 22, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2532, 'total': 2688, 'pending': 156, 'percent_complete': 94.1964}

2026-09-05T05:05:43.508895+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 22, 'target': 'delta_a', 'completed': 2533, 'total': 2688, 'pending': 155, 'percent_complete': 94.2336}

2026-09-05T05:06:03.610716+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 22, 'target': 'gain', 'completed': 2534, 'total': 2688, 'pending': 154, 'percent_complete': 94.2708}

2026-09-05T05:06:22.003913+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 22, 'target': 'gain_abs', 'completed': 2535, 'total': 2688, 'pending': 153, 'percent_complete': 94.308}

2026-09-05T05:06:43.299859+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 22, 'target': 'z_bayes', 'completed': 2536, 'total': 2688, 'pending': 152, 'percent_complete': 94.3452}

2026-09-05T05:06:57.713067+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 22, 'target': 'z_heuristic', 'completed': 2537, 'total': 2688, 'pending': 151, 'percent_complete': 94.3824}

2026-09-05T05:06:59.474472+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 22, 'target': 'reliability_sign', 'completed': 2538, 'total': 2688, 'pending': 150, 'percent_complete': 94.4196}
2026-09-05T05:06:59.474703+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 23, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2538, 'total': 2688, 'pending': 150, 'percent_complete': 94.4196}

2026-09-05T05:07:17.985535+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 23, 'target': 'delta_a', 'completed': 2539, 'total': 2688, 'pending': 149, 'percent_complete': 94.4568}

2026-09-05T05:07:37.213159+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 23, 'target': 'gain', 'completed': 2540, 'total': 2688, 'pending': 148, 'percent_complete': 94.494}

2026-09-05T05:08:01.181557+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 23, 'target': 'gain_abs', 'completed': 2541, 'total': 2688, 'pending': 147, 'percent_complete': 94.5312}

2026-09-05T05:08:22.401886+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 23, 'target': 'z_bayes', 'completed': 2542, 'total': 2688, 'pending': 146, 'percent_complete': 94.5685}

2026-09-05T05:08:41.792518+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 23, 'target': 'z_heuristic', 'completed': 2543, 'total': 2688, 'pending': 145, 'percent_complete': 94.6057}

2026-09-05T05:08:43.574178+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 23, 'target': 'reliability_sign', 'completed': 2544, 'total': 2688, 'pending': 144, 'percent_complete': 94.6429}
2026-09-05T05:08:43.574405+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 24, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2544, 'total': 2688, 'pending': 144, 'percent_complete': 94.6429}

2026-09-05T05:09:03.704221+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 24, 'target': 'delta_a', 'completed': 2545, 'total': 2688, 'pending': 143, 'percent_complete': 94.6801}

2026-09-05T05:09:26.090406+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 24, 'target': 'gain', 'completed': 2546, 'total': 2688, 'pending': 142, 'percent_complete': 94.7173}

2026-09-05T05:09:45.399849+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 24, 'target': 'gain_abs', 'completed': 2547, 'total': 2688, 'pending': 141, 'percent_complete': 94.7545}

2026-09-05T05:10:10.503220+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 24, 'target': 'z_bayes', 'completed': 2548, 'total': 2688, 'pending': 140, 'percent_complete': 94.7917}

2026-09-05T05:10:32.915931+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 24, 'target': 'z_heuristic', 'completed': 2549, 'total': 2688, 'pending': 139, 'percent_complete': 94.8289}

2026-09-05T05:10:34.707376+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 24, 'target': 'reliability_sign', 'completed': 2550, 'total': 2688, 'pending': 138, 'percent_complete': 94.8661}
2026-09-05T05:10:34.707631+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 25, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2550, 'total': 2688, 'pending': 138, 'percent_complete': 94.8661}

2026-09-05T05:10:51.893265+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 25, 'target': 'delta_a', 'completed': 2551, 'total': 2688, 'pending': 137, 'percent_complete': 94.9033}

2026-09-05T05:11:08.190903+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 25, 'target': 'gain', 'completed': 2552, 'total': 2688, 'pending': 136, 'percent_complete': 94.9405}

2026-09-05T05:11:25.904461+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 25, 'target': 'gain_abs', 'completed': 2553, 'total': 2688, 'pending': 135, 'percent_complete': 94.9777}

2026-09-05T05:11:46.705912+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 25, 'target': 'z_bayes', 'completed': 2554, 'total': 2688, 'pending': 134, 'percent_complete': 95.0149}

2026-09-05T05:12:05.975735+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 25, 'target': 'z_heuristic', 'completed': 2555, 'total': 2688, 'pending': 133, 'percent_complete': 95.0521}

2026-09-05T05:12:07.698341+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 25, 'target': 'reliability_sign', 'completed': 2556, 'total': 2688, 'pending': 132, 'percent_complete': 95.0893}
2026-09-05T05:12:07.698600+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 26, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2556, 'total': 2688, 'pending': 132, 'percent_complete': 95.0893}

2026-09-05T05:12:25.889583+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 26, 'target': 'delta_a', 'completed': 2557, 'total': 2688, 'pending': 131, 'percent_complete': 95.1265}

2026-09-05T05:12:42.909623+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 26, 'target': 'gain', 'completed': 2558, 'total': 2688, 'pending': 130, 'percent_complete': 95.1637}

2026-09-05T05:13:03.496185+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 26, 'target': 'gain_abs', 'completed': 2559, 'total': 2688, 'pending': 129, 'percent_complete': 95.2009}

2026-09-05T05:13:22.916520+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 26, 'target': 'z_bayes', 'completed': 2560, 'total': 2688, 'pending': 128, 'percent_complete': 95.2381}

2026-09-05T05:13:43.691815+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 26, 'target': 'z_heuristic', 'completed': 2561, 'total': 2688, 'pending': 127, 'percent_complete': 95.2753}

2026-09-05T05:13:45.405596+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 26, 'target': 'reliability_sign', 'completed': 2562, 'total': 2688, 'pending': 126, 'percent_complete': 95.3125}
2026-09-05T05:13:45.405844+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 27, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2562, 'total': 2688, 'pending': 126, 'percent_complete': 95.3125}

2026-09-05T05:14:00.575622+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 27, 'target': 'delta_a', 'completed': 2563, 'total': 2688, 'pending': 125, 'percent_complete': 95.3497}

2026-09-05T05:14:21.786012+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 27, 'target': 'gain', 'completed': 2564, 'total': 2688, 'pending': 124, 'percent_complete': 95.3869}

2026-09-05T05:14:40.390793+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 27, 'target': 'gain_abs', 'completed': 2565, 'total': 2688, 'pending': 123, 'percent_complete': 95.4241}

2026-09-05T05:15:00.801958+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 27, 'target': 'z_bayes', 'completed': 2566, 'total': 2688, 'pending': 122, 'percent_complete': 95.4613}

2026-09-05T05:15:22.177698+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 27, 'target': 'z_heuristic', 'completed': 2567, 'total': 2688, 'pending': 121, 'percent_complete': 95.4985}

2026-09-05T05:15:24.302461+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 27, 'target': 'reliability_sign', 'completed': 2568, 'total': 2688, 'pending': 120, 'percent_complete': 95.5357}
2026-09-05T05:15:24.302692+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 28, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2568, 'total': 2688, 'pending': 120, 'percent_complete': 95.5357}

2026-09-05T05:15:41.015059+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 28, 'target': 'delta_a', 'completed': 2569, 'total': 2688, 'pending': 119, 'percent_complete': 95.5729}

2026-09-05T05:16:02.216454+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 28, 'target': 'gain', 'completed': 2570, 'total': 2688, 'pending': 118, 'percent_complete': 95.6101}

2026-09-05T05:16:22.088643+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 28, 'target': 'gain_abs', 'completed': 2571, 'total': 2688, 'pending': 117, 'percent_complete': 95.6473}

2026-09-05T05:16:43.698219+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 28, 'target': 'z_bayes', 'completed': 2572, 'total': 2688, 'pending': 116, 'percent_complete': 95.6845}

2026-09-05T05:17:03.893474+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 28, 'target': 'z_heuristic', 'completed': 2573, 'total': 2688, 'pending': 115, 'percent_complete': 95.7217}

2026-09-05T05:17:05.589725+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 28, 'target': 'reliability_sign', 'completed': 2574, 'total': 2688, 'pending': 114, 'percent_complete': 95.7589}
2026-09-05T05:17:05.590028+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 29, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2574, 'total': 2688, 'pending': 114, 'percent_complete': 95.7589}

2026-09-05T05:17:24.715542+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 29, 'target': 'delta_a', 'completed': 2575, 'total': 2688, 'pending': 113, 'percent_complete': 95.7961}

2026-09-05T05:17:43.209573+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 29, 'target': 'gain', 'completed': 2576, 'total': 2688, 'pending': 112, 'percent_complete': 95.8333}

2026-09-05T05:18:02.411692+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 29, 'target': 'gain_abs', 'completed': 2577, 'total': 2688, 'pending': 111, 'percent_complete': 95.8705}

2026-09-05T05:18:22.303125+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 29, 'target': 'z_bayes', 'completed': 2578, 'total': 2688, 'pending': 110, 'percent_complete': 95.9077}

2026-09-05T05:18:43.699241+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 29, 'target': 'z_heuristic', 'completed': 2579, 'total': 2688, 'pending': 109, 'percent_complete': 95.9449}

2026-09-05T05:18:45.497619+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 29, 'target': 'reliability_sign', 'completed': 2580, 'total': 2688, 'pending': 108, 'percent_complete': 95.9821}
2026-09-05T05:18:45.497916+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 30, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2580, 'total': 2688, 'pending': 108, 'percent_complete': 95.9821}

2026-09-05T05:19:02.194961+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 30, 'target': 'delta_a', 'completed': 2581, 'total': 2688, 'pending': 107, 'percent_complete': 96.0193}

2026-09-05T05:19:20.978452+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 30, 'target': 'gain', 'completed': 2582, 'total': 2688, 'pending': 106, 'percent_complete': 96.0565}

2026-09-05T05:19:40.476106+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 30, 'target': 'gain_abs', 'completed': 2583, 'total': 2688, 'pending': 105, 'percent_complete': 96.0938}

2026-09-05T05:19:59.303139+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 30, 'target': 'z_bayes', 'completed': 2584, 'total': 2688, 'pending': 104, 'percent_complete': 96.131}

2026-09-05T05:20:18.588504+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 30, 'target': 'z_heuristic', 'completed': 2585, 'total': 2688, 'pending': 103, 'percent_complete': 96.1682}

2026-09-05T05:20:20.274521+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 30, 'target': 'reliability_sign', 'completed': 2586, 'total': 2688, 'pending': 102, 'percent_complete': 96.2054}
2026-09-05T05:20:20.274817+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 31, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2586, 'total': 2688, 'pending': 102, 'percent_complete': 96.2054}

2026-09-05T05:20:35.192042+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 31, 'target': 'delta_a', 'completed': 2587, 'total': 2688, 'pending': 101, 'percent_complete': 96.2426}

2026-09-05T05:20:53.286674+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 31, 'target': 'gain', 'completed': 2588, 'total': 2688, 'pending': 100, 'percent_complete': 96.2798}

2026-09-05T05:21:14.076458+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 31, 'target': 'gain_abs', 'completed': 2589, 'total': 2688, 'pending': 99, 'percent_complete': 96.317}

2026-09-05T05:21:34.506115+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 31, 'target': 'z_bayes', 'completed': 2590, 'total': 2688, 'pending': 98, 'percent_complete': 96.3542}

2026-09-05T05:21:53.998245+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 31, 'target': 'z_heuristic', 'completed': 2591, 'total': 2688, 'pending': 97, 'percent_complete': 96.3914}

2026-09-05T05:21:55.876660+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value', 'layer': 31, 'target': 'reliability_sign', 'completed': 2592, 'total': 2688, 'pending': 96, 'percent_complete': 96.4286}
2026-09-05T05:21:57.853291+00:00 PROBE_SITE_CACHE_RELEASED {'reasoning_mode': 'reasoning_off', 'site': 'candidate_1_value'}
2026-09-05T05:21:57.960366+00:00 PROBE_SITE_CACHE_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'site_pending': 96, 'missing_layers': [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], 'activation_files': 4480, 'estimated_cache_gib': 1.0938, 'completed': 2592, 'total': 2688, 'pending': 96, 'percent_complete': 96.4286}

2026-09-05T05:22:01.790821+00:00 cached observation_question_boundary: 256/4480 files

2026-09-05T05:22:05.786969+00:00 cached observation_question_boundary: 512/4480 files

2026-09-05T05:22:09.682776+00:00 cached observation_question_boundary: 768/4480 files

2026-09-05T05:22:13.591420+00:00 cached observation_question_boundary: 1024/4480 files

2026-09-05T05:22:17.474416+00:00 cached observation_question_boundary: 1280/4480 files

2026-09-05T05:22:21.377672+00:00 cached observation_question_boundary: 1536/4480 files

2026-09-05T05:22:25.289253+00:00 cached observation_question_boundary: 1792/4480 files

2026-09-05T05:22:29.280315+00:00 cached observation_question_boundary: 2048/4480 files

2026-09-05T05:22:33.093534+00:00 cached observation_question_boundary: 2304/4480 files

2026-09-05T05:22:36.984414+00:00 cached observation_question_boundary: 2560/4480 files

2026-09-05T05:22:40.881856+00:00 cached observation_question_boundary: 2816/4480 files

2026-09-05T05:22:44.484728+00:00 cached observation_question_boundary: 3072/4480 files

2026-09-05T05:22:47.984035+00:00 cached observation_question_boundary: 3328/4480 files

2026-09-05T05:22:51.577951+00:00 cached observation_question_boundary: 3584/4480 files

2026-09-05T05:22:55.275299+00:00 cached observation_question_boundary: 3840/4480 files

2026-09-05T05:22:58.872741+00:00 cached observation_question_boundary: 4096/4480 files

2026-09-05T05:23:02.378487+00:00 cached observation_question_boundary: 4352/4480 files

2026-09-05T05:23:04.176828+00:00 cached observation_question_boundary: 4480/4480 files
2026-09-05T05:23:04.177048+00:00 PROBE_SITE_CACHE_READY {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'shape': (16, 4480, 4096), 'cache_gib': 1.0938, 'activation_file_opens': 4480}
2026-09-05T05:23:04.177199+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 16, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2592, 'total': 2688, 'pending': 96, 'percent_complete': 96.4286}

2026-09-05T05:23:20.383788+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 16, 'target': 'delta_a', 'completed': 2593, 'total': 2688, 'pending': 95, 'percent_complete': 96.4658}

2026-09-05T05:23:38.499244+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 16, 'target': 'gain', 'completed': 2594, 'total': 2688, 'pending': 94, 'percent_complete': 96.503}

2026-09-05T05:23:54.186885+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 16, 'target': 'gain_abs', 'completed': 2595, 'total': 2688, 'pending': 93, 'percent_complete': 96.5402}

2026-09-05T05:24:14.008036+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 16, 'target': 'z_bayes', 'completed': 2596, 'total': 2688, 'pending': 92, 'percent_complete': 96.5774}

2026-09-05T05:24:33.107807+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 16, 'target': 'z_heuristic', 'completed': 2597, 'total': 2688, 'pending': 91, 'percent_complete': 96.6146}

2026-09-05T05:24:34.810252+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 16, 'target': 'reliability_sign', 'completed': 2598, 'total': 2688, 'pending': 90, 'percent_complete': 96.6518}
2026-09-05T05:24:34.810560+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 17, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2598, 'total': 2688, 'pending': 90, 'percent_complete': 96.6518}

2026-09-05T05:24:51.709343+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 17, 'target': 'delta_a', 'completed': 2599, 'total': 2688, 'pending': 89, 'percent_complete': 96.689}

2026-09-05T05:25:08.910872+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 17, 'target': 'gain', 'completed': 2600, 'total': 2688, 'pending': 88, 'percent_complete': 96.7262}

2026-09-05T05:25:28.208228+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 17, 'target': 'gain_abs', 'completed': 2601, 'total': 2688, 'pending': 87, 'percent_complete': 96.7634}

2026-09-05T05:25:44.302612+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 17, 'target': 'z_bayes', 'completed': 2602, 'total': 2688, 'pending': 86, 'percent_complete': 96.8006}

2026-09-05T05:26:01.375415+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 17, 'target': 'z_heuristic', 'completed': 2603, 'total': 2688, 'pending': 85, 'percent_complete': 96.8378}

2026-09-05T05:26:02.989058+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 17, 'target': 'reliability_sign', 'completed': 2604, 'total': 2688, 'pending': 84, 'percent_complete': 96.875}
2026-09-05T05:26:02.989334+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 18, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2604, 'total': 2688, 'pending': 84, 'percent_complete': 96.875}

2026-09-05T05:26:19.695997+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 18, 'target': 'delta_a', 'completed': 2605, 'total': 2688, 'pending': 83, 'percent_complete': 96.9122}

2026-09-05T05:26:37.687470+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 18, 'target': 'gain', 'completed': 2606, 'total': 2688, 'pending': 82, 'percent_complete': 96.9494}

2026-09-05T05:26:54.985015+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 18, 'target': 'gain_abs', 'completed': 2607, 'total': 2688, 'pending': 81, 'percent_complete': 96.9866}

2026-09-05T05:27:11.010066+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 18, 'target': 'z_bayes', 'completed': 2608, 'total': 2688, 'pending': 80, 'percent_complete': 97.0238}

2026-09-05T05:27:27.113196+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 18, 'target': 'z_heuristic', 'completed': 2609, 'total': 2688, 'pending': 79, 'percent_complete': 97.061}

2026-09-05T05:27:28.779242+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 18, 'target': 'reliability_sign', 'completed': 2610, 'total': 2688, 'pending': 78, 'percent_complete': 97.0982}
2026-09-05T05:27:28.779544+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 19, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2610, 'total': 2688, 'pending': 78, 'percent_complete': 97.0982}

2026-09-05T05:27:46.000440+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 19, 'target': 'delta_a', 'completed': 2611, 'total': 2688, 'pending': 77, 'percent_complete': 97.1354}

2026-09-05T05:28:01.519156+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 19, 'target': 'gain', 'completed': 2612, 'total': 2688, 'pending': 76, 'percent_complete': 97.1726}

2026-09-05T05:28:18.097332+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 19, 'target': 'gain_abs', 'completed': 2613, 'total': 2688, 'pending': 75, 'percent_complete': 97.2098}

2026-09-05T05:28:34.390860+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 19, 'target': 'z_bayes', 'completed': 2614, 'total': 2688, 'pending': 74, 'percent_complete': 97.247}

2026-09-05T05:28:51.282137+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 19, 'target': 'z_heuristic', 'completed': 2615, 'total': 2688, 'pending': 73, 'percent_complete': 97.2842}

2026-09-05T05:28:52.801606+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 19, 'target': 'reliability_sign', 'completed': 2616, 'total': 2688, 'pending': 72, 'percent_complete': 97.3214}
2026-09-05T05:28:52.801891+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 20, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2616, 'total': 2688, 'pending': 72, 'percent_complete': 97.3214}

2026-09-05T05:29:09.417215+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 20, 'target': 'delta_a', 'completed': 2617, 'total': 2688, 'pending': 71, 'percent_complete': 97.3586}

2026-09-05T05:29:26.609197+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 20, 'target': 'gain', 'completed': 2618, 'total': 2688, 'pending': 70, 'percent_complete': 97.3958}

2026-09-05T05:29:42.500416+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 20, 'target': 'gain_abs', 'completed': 2619, 'total': 2688, 'pending': 69, 'percent_complete': 97.433}

2026-09-05T05:29:58.414264+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 20, 'target': 'z_bayes', 'completed': 2620, 'total': 2688, 'pending': 68, 'percent_complete': 97.4702}

2026-09-05T05:30:14.093623+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 20, 'target': 'z_heuristic', 'completed': 2621, 'total': 2688, 'pending': 67, 'percent_complete': 97.5074}

2026-09-05T05:30:15.906204+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 20, 'target': 'reliability_sign', 'completed': 2622, 'total': 2688, 'pending': 66, 'percent_complete': 97.5446}
2026-09-05T05:30:15.906506+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 21, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2622, 'total': 2688, 'pending': 66, 'percent_complete': 97.5446}

2026-09-05T05:30:31.008384+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 21, 'target': 'delta_a', 'completed': 2623, 'total': 2688, 'pending': 65, 'percent_complete': 97.5818}

2026-09-05T05:30:46.803041+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 21, 'target': 'gain', 'completed': 2624, 'total': 2688, 'pending': 64, 'percent_complete': 97.619}

2026-09-05T05:31:02.213087+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 21, 'target': 'gain_abs', 'completed': 2625, 'total': 2688, 'pending': 63, 'percent_complete': 97.6562}

2026-09-05T05:31:16.991143+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 21, 'target': 'z_bayes', 'completed': 2626, 'total': 2688, 'pending': 62, 'percent_complete': 97.6935}

2026-09-05T05:31:34.507039+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 21, 'target': 'z_heuristic', 'completed': 2627, 'total': 2688, 'pending': 61, 'percent_complete': 97.7307}

2026-09-05T05:31:36.292110+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 21, 'target': 'reliability_sign', 'completed': 2628, 'total': 2688, 'pending': 60, 'percent_complete': 97.7679}
2026-09-05T05:31:36.292440+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 22, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2628, 'total': 2688, 'pending': 60, 'percent_complete': 97.7679}

2026-09-05T05:31:50.575415+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 22, 'target': 'delta_a', 'completed': 2629, 'total': 2688, 'pending': 59, 'percent_complete': 97.8051}

2026-09-05T05:32:03.509251+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 22, 'target': 'gain', 'completed': 2630, 'total': 2688, 'pending': 58, 'percent_complete': 97.8423}

2026-09-05T05:32:17.385905+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 22, 'target': 'gain_abs', 'completed': 2631, 'total': 2688, 'pending': 57, 'percent_complete': 97.8795}

2026-09-05T05:32:29.690945+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 22, 'target': 'z_bayes', 'completed': 2632, 'total': 2688, 'pending': 56, 'percent_complete': 97.9167}

2026-09-05T05:32:42.199482+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 22, 'target': 'z_heuristic', 'completed': 2633, 'total': 2688, 'pending': 55, 'percent_complete': 97.9539}

2026-09-05T05:32:43.910200+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 22, 'target': 'reliability_sign', 'completed': 2634, 'total': 2688, 'pending': 54, 'percent_complete': 97.9911}
2026-09-05T05:32:43.910472+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 23, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2634, 'total': 2688, 'pending': 54, 'percent_complete': 97.9911}

2026-09-05T05:32:58.110774+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 23, 'target': 'delta_a', 'completed': 2635, 'total': 2688, 'pending': 53, 'percent_complete': 98.0283}

2026-09-05T05:33:16.474980+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 23, 'target': 'gain', 'completed': 2636, 'total': 2688, 'pending': 52, 'percent_complete': 98.0655}

2026-09-05T05:33:32.613386+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 23, 'target': 'gain_abs', 'completed': 2637, 'total': 2688, 'pending': 51, 'percent_complete': 98.1027}

2026-09-05T05:33:50.285890+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 23, 'target': 'z_bayes', 'completed': 2638, 'total': 2688, 'pending': 50, 'percent_complete': 98.1399}

2026-09-05T05:34:06.973937+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 23, 'target': 'z_heuristic', 'completed': 2639, 'total': 2688, 'pending': 49, 'percent_complete': 98.1771}

2026-09-05T05:34:08.779124+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 23, 'target': 'reliability_sign', 'completed': 2640, 'total': 2688, 'pending': 48, 'percent_complete': 98.2143}
2026-09-05T05:34:08.779414+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 24, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2640, 'total': 2688, 'pending': 48, 'percent_complete': 98.2143}

2026-09-05T05:34:27.706714+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 24, 'target': 'delta_a', 'completed': 2641, 'total': 2688, 'pending': 47, 'percent_complete': 98.2515}

2026-09-05T05:34:44.817397+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 24, 'target': 'gain', 'completed': 2642, 'total': 2688, 'pending': 46, 'percent_complete': 98.2887}

2026-09-05T05:35:02.384299+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 24, 'target': 'gain_abs', 'completed': 2643, 'total': 2688, 'pending': 45, 'percent_complete': 98.3259}

2026-09-05T05:35:19.596507+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 24, 'target': 'z_bayes', 'completed': 2644, 'total': 2688, 'pending': 44, 'percent_complete': 98.3631}

2026-09-05T05:35:35.883186+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 24, 'target': 'z_heuristic', 'completed': 2645, 'total': 2688, 'pending': 43, 'percent_complete': 98.4003}

2026-09-05T05:35:37.584623+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 24, 'target': 'reliability_sign', 'completed': 2646, 'total': 2688, 'pending': 42, 'percent_complete': 98.4375}
2026-09-05T05:35:37.584914+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 25, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2646, 'total': 2688, 'pending': 42, 'percent_complete': 98.4375}

2026-09-05T05:35:52.504974+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 25, 'target': 'delta_a', 'completed': 2647, 'total': 2688, 'pending': 41, 'percent_complete': 98.4747}

2026-09-05T05:36:10.610935+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 25, 'target': 'gain', 'completed': 2648, 'total': 2688, 'pending': 40, 'percent_complete': 98.5119}

2026-09-05T05:36:25.491545+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 25, 'target': 'gain_abs', 'completed': 2649, 'total': 2688, 'pending': 39, 'percent_complete': 98.5491}

2026-09-05T05:36:43.493548+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 25, 'target': 'z_bayes', 'completed': 2650, 'total': 2688, 'pending': 38, 'percent_complete': 98.5863}

2026-09-05T05:36:57.906194+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 25, 'target': 'z_heuristic', 'completed': 2651, 'total': 2688, 'pending': 37, 'percent_complete': 98.6235}

2026-09-05T05:36:59.880169+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 25, 'target': 'reliability_sign', 'completed': 2652, 'total': 2688, 'pending': 36, 'percent_complete': 98.6607}
2026-09-05T05:36:59.880398+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 26, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2652, 'total': 2688, 'pending': 36, 'percent_complete': 98.6607}

2026-09-05T05:37:14.609550+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 26, 'target': 'delta_a', 'completed': 2653, 'total': 2688, 'pending': 35, 'percent_complete': 98.6979}

2026-09-05T05:37:32.607684+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 26, 'target': 'gain', 'completed': 2654, 'total': 2688, 'pending': 34, 'percent_complete': 98.7351}

2026-09-05T05:37:49.807789+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 26, 'target': 'gain_abs', 'completed': 2655, 'total': 2688, 'pending': 33, 'percent_complete': 98.7723}

2026-09-05T05:38:04.689823+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 26, 'target': 'z_bayes', 'completed': 2656, 'total': 2688, 'pending': 32, 'percent_complete': 98.8095}

2026-09-05T05:38:21.303630+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 26, 'target': 'z_heuristic', 'completed': 2657, 'total': 2688, 'pending': 31, 'percent_complete': 98.8467}

2026-09-05T05:38:23.372125+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 26, 'target': 'reliability_sign', 'completed': 2658, 'total': 2688, 'pending': 30, 'percent_complete': 98.8839}
2026-09-05T05:38:23.372476+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 27, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2658, 'total': 2688, 'pending': 30, 'percent_complete': 98.8839}

2026-09-05T05:38:38.690775+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 27, 'target': 'delta_a', 'completed': 2659, 'total': 2688, 'pending': 29, 'percent_complete': 98.9211}

2026-09-05T05:38:55.292500+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 27, 'target': 'gain', 'completed': 2660, 'total': 2688, 'pending': 28, 'percent_complete': 98.9583}

2026-09-05T05:39:09.912719+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 27, 'target': 'gain_abs', 'completed': 2661, 'total': 2688, 'pending': 27, 'percent_complete': 98.9955}

2026-09-05T05:39:26.397082+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 27, 'target': 'z_bayes', 'completed': 2662, 'total': 2688, 'pending': 26, 'percent_complete': 99.0327}

2026-09-05T05:39:40.787512+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 27, 'target': 'z_heuristic', 'completed': 2663, 'total': 2688, 'pending': 25, 'percent_complete': 99.0699}

2026-09-05T05:39:42.487300+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 27, 'target': 'reliability_sign', 'completed': 2664, 'total': 2688, 'pending': 24, 'percent_complete': 99.1071}
2026-09-05T05:39:42.487588+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 28, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2664, 'total': 2688, 'pending': 24, 'percent_complete': 99.1071}

2026-09-05T05:39:58.390823+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 28, 'target': 'delta_a', 'completed': 2665, 'total': 2688, 'pending': 23, 'percent_complete': 99.1443}

2026-09-05T05:40:12.601577+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 28, 'target': 'gain', 'completed': 2666, 'total': 2688, 'pending': 22, 'percent_complete': 99.1815}

2026-09-05T05:40:27.183715+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 28, 'target': 'gain_abs', 'completed': 2667, 'total': 2688, 'pending': 21, 'percent_complete': 99.2188}

2026-09-05T05:40:43.394972+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 28, 'target': 'z_bayes', 'completed': 2668, 'total': 2688, 'pending': 20, 'percent_complete': 99.256}

2026-09-05T05:40:58.210386+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 28, 'target': 'z_heuristic', 'completed': 2669, 'total': 2688, 'pending': 19, 'percent_complete': 99.2932}

2026-09-05T05:41:00.179535+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 28, 'target': 'reliability_sign', 'completed': 2670, 'total': 2688, 'pending': 18, 'percent_complete': 99.3304}
2026-09-05T05:41:00.179892+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 29, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2670, 'total': 2688, 'pending': 18, 'percent_complete': 99.3304}

2026-09-05T05:41:17.093570+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 29, 'target': 'delta_a', 'completed': 2671, 'total': 2688, 'pending': 17, 'percent_complete': 99.3676}

2026-09-05T05:41:34.103810+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 29, 'target': 'gain', 'completed': 2672, 'total': 2688, 'pending': 16, 'percent_complete': 99.4048}

2026-09-05T05:41:56.692130+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 29, 'target': 'gain_abs', 'completed': 2673, 'total': 2688, 'pending': 15, 'percent_complete': 99.442}

2026-09-05T05:42:10.173801+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 29, 'target': 'z_bayes', 'completed': 2674, 'total': 2688, 'pending': 14, 'percent_complete': 99.4792}

2026-09-05T05:42:26.995575+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 29, 'target': 'z_heuristic', 'completed': 2675, 'total': 2688, 'pending': 13, 'percent_complete': 99.5164}

2026-09-05T05:42:28.697963+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 29, 'target': 'reliability_sign', 'completed': 2676, 'total': 2688, 'pending': 12, 'percent_complete': 99.5536}
2026-09-05T05:42:28.698359+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 30, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2676, 'total': 2688, 'pending': 12, 'percent_complete': 99.5536}

2026-09-05T05:42:43.714631+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 30, 'target': 'delta_a', 'completed': 2677, 'total': 2688, 'pending': 11, 'percent_complete': 99.5908}

2026-09-05T05:43:03.385539+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 30, 'target': 'gain', 'completed': 2678, 'total': 2688, 'pending': 10, 'percent_complete': 99.628}

2026-09-05T05:43:23.286773+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 30, 'target': 'gain_abs', 'completed': 2679, 'total': 2688, 'pending': 9, 'percent_complete': 99.6652}

2026-09-05T05:43:38.496689+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 30, 'target': 'z_bayes', 'completed': 2680, 'total': 2688, 'pending': 8, 'percent_complete': 99.7024}

2026-09-05T05:43:57.617191+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 30, 'target': 'z_heuristic', 'completed': 2681, 'total': 2688, 'pending': 7, 'percent_complete': 99.7396}

2026-09-05T05:43:59.383646+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 30, 'target': 'reliability_sign', 'completed': 2682, 'total': 2688, 'pending': 6, 'percent_complete': 99.7768}
2026-09-05T05:43:59.383995+00:00 PROBE_LAYER_START {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 31, 'missing_targets': ['delta_a', 'gain', 'gain_abs', 'z_bayes', 'z_heuristic', 'reliability_sign'], 'completed': 2682, 'total': 2688, 'pending': 6, 'percent_complete': 99.7768}

2026-09-05T05:44:18.095661+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 31, 'target': 'delta_a', 'completed': 2683, 'total': 2688, 'pending': 5, 'percent_complete': 99.814}

2026-09-05T05:44:35.514296+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 31, 'target': 'gain', 'completed': 2684, 'total': 2688, 'pending': 4, 'percent_complete': 99.8512}

2026-09-05T05:44:53.715240+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 31, 'target': 'gain_abs', 'completed': 2685, 'total': 2688, 'pending': 3, 'percent_complete': 99.8884}

2026-09-05T05:45:11.880435+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 31, 'target': 'z_bayes', 'completed': 2686, 'total': 2688, 'pending': 2, 'percent_complete': 99.9256}

2026-09-05T05:45:30.695738+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 31, 'target': 'z_heuristic', 'completed': 2687, 'total': 2688, 'pending': 1, 'percent_complete': 99.9628}

2026-09-05T05:45:32.489474+00:00 PROBE_TARGET_CHECKPOINTED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary', 'layer': 31, 'target': 'reliability_sign', 'completed': 2688, 'total': 2688, 'pending': 0, 'percent_complete': 100.0}
2026-09-05T05:45:35.541314+00:00 PROBE_SITE_CACHE_RELEASED {'reasoning_mode': 'reasoning_off', 'site': 'observation_question_boundary'}
2026-09-05T05:45:35.542752+00:00 PROBE_SITE_SKIPPED_COMPLETE {'reasoning_mode': 'reasoning_off', 'site': 'report_3_answer', 'completed': 2688, 'total': 2688, 'pending': 0, 'percent_complete': 100.0}
2026-09-05T05:45:35.543308+00:00 PROBE_SITE_SKIPPED_COMPLETE {'reasoning_mode': 'reasoning_off', 'site': 'report_2_answer', 'completed': 2688, 'total': 2688, 'pending': 0, 'percent_complete': 100.0}
2026-09-05T05:45:35.543811+00:00 PROBE_SITE_SKIPPED_COMPLETE {'reasoning_mode': 'reasoning_off', 'site': 'report_1_answer', 'completed': 2688, 'total': 2688, 'pending': 0, 'percent_complete': 100.0}
2026-09-05T05:45:35.544303+00:00 PROBE_SITE_SKIPPED_COMPLETE {'reasoning_mode': 'reasoning_off', 'site': 'reliability_one_minus_r_value', 'completed': 2688, 'total': 2688, 'pending': 0, 'percent_complete': 100.0}
2026-09-05T05:45:35.544794+00:00 PROBE_SITE_SKIPPED_COMPLETE {'reasoning_mode': 'reasoning_off', 'site': 'reliability_r_value', 'completed': 2688, 'total': 2688, 'pending': 0, 'percent_complete': 100.0}
2026-09-05T05:45:35.545274+00:00 PROBE_SITE_SKIPPED_COMPLETE {'reasoning_mode': 'reasoning_off', 'site': 'reliability_rule_boundary', 'completed': 2688, 'total': 2688, 'pending': 0, 'percent_complete': 100.0}
2026-09-05T05:45:35.545750+00:00 PROBE_SITE_SKIPPED_COMPLETE {'reasoning_mode': 'reasoning_off', 'site': 'domain_boundary', 'completed': 2688, 'total': 2688, 'pending': 0, 'percent_complete': 100.0}
Completed training-only probe records: 2688

### Lock layers, then open the test set

Layer locking is deterministic and uses only `best_cv_score` from the 56 training
schedules in each reasoning mode. The test switch should remain false until every planned training probe exists
and `locked_layers.json` has been written. Test metrics include $R^2$, MAE, RMSE,
correlation, and calibration for regressions; and AUROC, balanced accuracy, and log loss
for reliability sign. Each mode's probe is evaluated only on that mode's 640 test rows.

In [ ]:
expected_probe_count = len(expected_probe_keys)
locked_layers_path = PROBE_ROOT / "locked_layers.json"
locked_layers: dict[str, dict[str, dict[str, list[int]]]] | None = None

if len(probe_cv_records) == expected_probe_count:
    locked_layers = {}
    for reasoning in ANALYSIS_REASONING_VALUES:
        mode_name = MODE_NAMES[reasoning]
        locked_layers[mode_name] = {}
        for site in PROBE_SITES:
            locked_layers[mode_name][site] = {}
            for target in CONTINUOUS_PROBE_TARGETS + BINARY_PROBE_TARGETS:
                candidates = [
                    row for row in probe_cv_records
                    if bool(row["reasoning"]) is reasoning
                    and row["site"] == site and row["target"] == target
                ]
                if len(candidates) != len(PROBE_LAYERS):
                    raise ValueError(
                        f"Incomplete layer sweep for {mode_name}/{site}/{target}."
                    )
                ranked = sorted(
                    candidates,
                    key=lambda row: (-float(row["best_cv_score"]), int(row["layer"])),
                )
                locked_layers[mode_name][site][target] = [
                    int(row["layer"]) for row in ranked[:PROBE_TOP_K_LAYERS]
                ]
    atomic_write_json(locked_layers_path, {
        "probe_config_fingerprint": PROBE_CONFIG_FINGERPRINT,
        "layers": locked_layers,
    })
    display(locked_layers)
elif locked_layers_path.exists():
    saved_lock = json.loads(locked_layers_path.read_text(encoding="utf-8"))
    if saved_lock.get("probe_config_fingerprint") == PROBE_CONFIG_FINGERPRINT:
        locked_layers = saved_lock["layers"]
    else:
        print("Ignoring locked_layers.json from a different probe configuration.")
else:
    print(
        f"Layer locking waits for {expected_probe_count} training probes; "
        f"currently have {len(probe_cv_records)}."
    )


def load_probe_prediction(
    X: np.ndarray, *, reasoning: bool, site: str, target: str, layer: int
) -> np.ndarray:
    if not probe_artifacts_match_configuration(reasoning, site, target, layer):
        raise ValueError("Probe weights or metadata do not match the locked configuration.")
    weights_path, _ = probe_paths(reasoning, site, target, layer)
    tensors = load_file(weights_path)
    mean = tensors["feature_mean"].numpy()
    scale = tensors["feature_scale"].numpy()
    coef = tensors["coef"].numpy()
    intercept = float(tensors["intercept"].reshape(-1)[0])
    score = ((X - mean) / scale) @ coef + intercept
    if target in BINARY_PROBE_TARGETS:
        score = np.where(
            score >= 0,
            1 / (1 + np.exp(-score)),
            np.exp(score) / (1 + np.exp(score)),
        )
    return np.asarray(score)


def continuous_metrics(
    y: np.ndarray, prediction: np.ndarray
) -> dict[str, float | None]:
    correlation = (
        float(np.corrcoef(y, prediction)[0, 1])
        if np.std(y) > 0 and np.std(prediction) > 0 else None
    )
    calibration_slope, calibration_intercept = (
        np.polyfit(prediction, y, 1) if np.std(prediction) > 0 else (None, None)
    )
    return {
        "r2": float(r2_score(y, prediction)),
        "mae": float(mean_absolute_error(y, prediction)),
        "rmse": float(math.sqrt(mean_squared_error(y, prediction))),
        "pearson": correlation,
        "calibration_slope_y_on_prediction": (
            float(calibration_slope) if calibration_slope is not None else None
        ),
        "calibration_intercept_y_on_prediction": (
            float(calibration_intercept) if calibration_intercept is not None else None
        ),
    }


def binary_metrics(y: np.ndarray, probability: np.ndarray) -> dict[str, float]:
    prediction = (probability >= 0.5).astype(int)
    return {
        "auroc": float(roc_auc_score(y, probability)),
        "balanced_accuracy": float(balanced_accuracy_score(y, prediction)),
        "log_loss": float(log_loss(y, probability, labels=[0, 1])),
    }


test_metric_rows: list[dict[str, object]] = []
test_availability_rows: list[dict[str, object]] = []
if RUN_LOCKED_TEST_EVALUATION:
    if results is None or locked_layers is None:
        raise RuntimeError("Completed captures and locked training-only layers are required.")
    cache: dict[
        tuple[bool, str, int], tuple[list[dict[str, object]], np.ndarray]
    ] = {}
    for reasoning in REASONING_VALUES:
        mode_name = MODE_NAMES[reasoning]
        mode_results = results_by_reasoning[reasoning]
        for site, targets in locked_layers[mode_name].items():
            available = rows_available_at_site(mode_results, site)
            selected_rows = [row for row in available if row["split"] == "test"]
            test_availability_rows.append({
                "reasoning": reasoning,
                "reasoning_mode": mode_name,
                "site": site,
                "available_test_rows": len(selected_rows),
                "expected_test_rows": EXPECTED_TEST_ROWS_PER_REASONING,
                "coverage_fraction": (
                    len(selected_rows) / EXPECTED_TEST_ROWS_PER_REASONING
                ),
                "analysis_role": (
                    "confirmatory"
                    if len(selected_rows) == EXPECTED_TEST_ROWS_PER_REASONING
                    else "availability_limited_exploratory"
                ),
                "probe_config_fingerprint": PROBE_CONFIG_FINGERPRINT,
            })
            for target, layers in targets.items():
                for layer in layers:
                    key = (reasoning, site, int(layer))
                    if key not in cache:
                        cache[key] = (
                            selected_rows,
                            activation_matrix(
                                selected_rows, site=site, layer=int(layer)
                            ),
                        )
                    metric_rows, X_test = cache[key]
                    y_test = target_array(metric_rows, target)
                    prediction = load_probe_prediction(
                        X_test, reasoning=reasoning, site=site,
                        target=target, layer=int(layer),
                    )
                    metrics = (
                        binary_metrics(y_test, prediction)
                        if target in BINARY_PROBE_TARGETS
                        else continuous_metrics(y_test, prediction)
                    )
                    test_metric_rows.append({
                        "reasoning": reasoning,
                        "reasoning_mode": mode_name,
                        "site": site,
                        "target": target,
                        "layer": int(layer),
                        "subset": "all",
                        "row_count": len(metric_rows),
                        "site_available_test_rows": len(metric_rows),
                        "site_coverage_fraction": (
                            len(metric_rows) / EXPECTED_TEST_ROWS_PER_REASONING
                        ),
                        "probe_config_fingerprint": PROBE_CONFIG_FINGERPRINT,
                        **metrics,
                    })
    atomic_write_jsonl(PROBE_ROOT / "locked_test_metrics.jsonl", test_metric_rows)
    atomic_write_jsonl(
        PROBE_ROOT / "locked_test_availability.jsonl", test_availability_rows
    )
    display(pd.DataFrame(test_availability_rows))
    display(pd.DataFrame(test_metric_rows))
else:
    print("The held-out test remains sealed: RUN_LOCKED_TEST_EVALUATION=False.")

## Probe geometry and information-transport visualizations

Write each fitted probe as

$$\hat y_{\ell,p}=w_{\ell,p}^{\mathsf T}h_{\ell,p}+b_{\ell,p},$$

where $\ell$ is the residual-stream layer and $p$ is a configured token site. The full
layer/location maps below use **grouped validation** $R^2$ from held-out training schedules;
they never use in-sample training $R^2$. Each separately locked 640-row mode-specific test
set is shown
only after `RUN_LOCKED_TEST_EVALUATION` has deliberately opened it, and only at the layers
selected before opening the test.

All 14 sites are swept independently in each reasoning mode. Figures and transfer matrices
therefore carry an explicit mode label; no plot pools the two probe datasets.

Ridge stores coefficients in standardized-feature coordinates. For geometric comparisons
in the shared residual-stream basis, the code converts them back to the exact raw-space
direction $w_{\rm raw}=w_{\rm standardized}/\sigma$. Cross-layer and cross-location tests
apply the complete source affine readout—including its source mean, scale, and intercept—to
the destination activations. Re-standardizing at the destination would test a different
readout and would not establish transport of the same code.

The generated `answer_line` site may be availability-limited if a completion does not obey
the answer contract. Training aborts if fewer than the configured coverage threshold—or
fewer than 4,097 rows—remain. Test coverage is always written beside its metrics.

In [ ]:
FIGURE_ROOT = PROBE_ROOT / "figures"
FIGURE_ROOT.mkdir(parents=True, exist_ok=True)


def figure_slug(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("_")


def save_and_display_figure(fig, name: str) -> Path:
    path = FIGURE_ROOT / f"{figure_slug(name)}.png"
    fig.tight_layout()
    fig.savefig(path, dpi=PROBE_FIGURE_DPI, bbox_inches="tight")
    display(fig)
    plt.close(fig)
    return path


def probe_affine_parameters(
    *, reasoning: bool, site: str, target: str, layer: int
) -> dict[str, np.ndarray | float]:
    if not probe_artifacts_match_configuration(reasoning, site, target, layer):
        raise ValueError(
            f"Missing or incompatible probe: "
            f"{MODE_NAMES[reasoning]}/{site}/{target}/layer_{layer:02d}"
        )
    weights_path, _ = probe_paths(reasoning, site, target, layer)
    tensors = load_file(weights_path)
    mean = tensors["feature_mean"].numpy().astype(np.float64, copy=False)
    scale = tensors["feature_scale"].numpy().astype(np.float64, copy=False)
    standardized_coef = tensors["coef"].numpy().astype(np.float64, copy=False)
    intercept = float(tensors["intercept"].reshape(-1)[0])
    raw_direction = standardized_coef / scale
    raw_intercept = intercept - float(mean @ raw_direction)
    return {
        "mean": mean,
        "scale": scale,
        "standardized_coef": standardized_coef,
        "intercept": intercept,
        "raw_direction": raw_direction,
        "raw_intercept": raw_intercept,
    }


def normalized_raw_direction(
    *, reasoning: bool, site: str, target: str, layer: int
) -> np.ndarray:
    direction = np.asarray(probe_affine_parameters(
        reasoning=reasoning, site=site, target=target, layer=layer
    )["raw_direction"])
    norm = float(np.linalg.norm(direction))
    if not np.isfinite(norm) or norm == 0:
        raise ValueError(
            f"Degenerate probe direction: "
            f"{MODE_NAMES[reasoning]}/{site}/{target}/layer_{layer:02d}"
        )
    return direction / norm


def grouped_validation_matrix(reasoning: bool, target: str) -> np.ndarray:
    matrix = np.full((len(PROBE_LAYERS), len(PROBE_SITES)), np.nan)
    layer_to_row = {int(layer): index for index, layer in enumerate(PROBE_LAYERS)}
    site_to_column = {site: index for index, site in enumerate(PROBE_SITES)}
    for row in probe_cv_records:
        if (
            bool(row["reasoning"]) is reasoning
            and row["target"] == target
            and row["site"] in site_to_column
        ):
            matrix[layer_to_row[int(row["layer"])], site_to_column[str(row["site"])]] = (
                float(row["best_cv_score"])
            )
    if np.isnan(matrix).any():
        raise ValueError(
            f"Incomplete grouped-validation matrix for "
            f"{MODE_NAMES[reasoning]}/{target}."
        )
    return matrix


def draw_matrix(
    matrix: np.ndarray,
    *,
    xlabels: list[str],
    ylabels: list[str],
    title: str,
    colorbar_label: str,
    vmin: float | None = None,
    vmax: float | None = None,
    figsize: tuple[float, float] = (8.0, 6.0),
):
    fig, ax = plt.subplots(figsize=figsize)
    cmap = plt.get_cmap("viridis").copy()
    cmap.set_bad("#e6e6e6")
    image = ax.imshow(
        np.ma.masked_invalid(matrix), aspect="auto", origin="lower",
        interpolation="nearest", cmap=cmap, vmin=vmin, vmax=vmax,
    )
    ax.set_xticks(np.arange(len(xlabels)), labels=xlabels, rotation=35, ha="right")
    y_step = max(1, len(ylabels) // 8)
    y_indices = np.arange(0, len(ylabels), y_step)
    ax.set_yticks(y_indices, labels=[ylabels[index] for index in y_indices])
    ax.set_xlabel("test location" if "transfer" in title.lower() else "token location")
    ax.set_ylabel("source/train layer" if "transfer" in title.lower() else "layer")
    ax.set_title(title)
    fig.colorbar(image, ax=ax, label=colorbar_label)
    return fig, ax

In [ ]:
# 1–4, 7, and 8: training-only grouped-validation performance and probe geometry.
if RUN_PROBE_VISUALIZATIONS:
    if len(probe_cv_records) != expected_probe_count:
        raise RuntimeError("Complete the configured probe sweep before plotting it.")

    for reasoning in REASONING_VALUES:
        mode_name = MODE_NAMES[reasoning]
        for target in PROBE_PLOT_TARGETS:
            validation = grouped_validation_matrix(reasoning, target)

            # 1. Layer × location grouped-validation heatmap.
            fig, _ = draw_matrix(
                validation,
                xlabels=list(PROBE_SITES),
                ylabels=[str(layer) for layer in PROBE_LAYERS],
                title=f"{mode_name} · {target}: grouped schedule-validation R²",
                colorbar_label="validation R²",
                vmin=min(0.0, float(np.nanmin(validation))),
                vmax=1.0,
            )
            save_and_display_figure(
                fig, f"01_validation_heatmap_{mode_name}_{target}"
            )

            # 2. Probe performance versus layer.
            fig, ax = plt.subplots(figsize=(11, 5.2))
            for site_index, site in enumerate(PROBE_SITES):
                ax.plot(
                    PROBE_LAYERS, validation[:, site_index],
                    marker="o", ms=2.5, label=site,
                )
            ax.axhline(0, color="black", lw=0.8, alpha=0.5)
            ax.set(
                xlabel="layer", ylabel="grouped validation R²",
                title=f"{mode_name} · {target}: decodability by layer",
            )
            ax.legend(ncol=2, fontsize=8)
            ax.grid(alpha=0.2)
            save_and_display_figure(
                fig, f"02_validation_by_layer_{mode_name}_{target}"
            )

            # 3. Best available location and its score at each layer.
            best_location_index = np.nanargmax(validation, axis=1)
            best_score = validation[np.arange(len(PROBE_LAYERS)), best_location_index]
            fig, (score_ax, site_ax) = plt.subplots(
                2, 1, figsize=(10, 7), sharex=True,
                gridspec_kw={"height_ratios": [2, 1]},
            )
            score_ax.plot(PROBE_LAYERS, best_score, marker="o", ms=3)
            score_ax.axhline(0, color="black", lw=0.8, alpha=0.5)
            score_ax.set(
                ylabel="max validation R²",
                title=f"{mode_name} · {target}: best location at each layer",
            )
            score_ax.grid(alpha=0.2)
            site_ax.scatter(
                PROBE_LAYERS, best_location_index,
                c=PROBE_LAYERS, cmap="viridis", s=24,
            )
            site_ax.set_yticks(np.arange(len(PROBE_SITES)), labels=PROBE_SITES)
            site_ax.set(xlabel="layer", ylabel="argmax location")
            site_ax.grid(axis="x", alpha=0.2)
            save_and_display_figure(
                fig, f"03_best_location_by_layer_{mode_name}_{target}"
            )

            # 4. Pairwise cosine similarity, one compact panel per location.
            n_columns = 3
            n_rows = math.ceil(len(PROBE_SITES) / n_columns)
            fig, axes = plt.subplots(
                n_rows, n_columns, figsize=(13, 4.1 * n_rows), squeeze=False
            )
            for site_index, site in enumerate(PROBE_SITES):
                directions = np.stack([
                    normalized_raw_direction(
                        reasoning=reasoning, site=site,
                        target=target, layer=int(layer),
                    )
                    for layer in PROBE_LAYERS
                ])
                similarity = directions @ directions.T
                ax = axes.flat[site_index]
                image = ax.imshow(
                    similarity, origin="lower", vmin=-1, vmax=1, cmap="coolwarm"
                )
                ax.set(xlabel="probe layer", ylabel="probe layer", title=site)
                ticks = np.arange(0, len(PROBE_LAYERS), 8)
                ax.set_xticks(ticks, labels=[PROBE_LAYERS[i] for i in ticks])
                ax.set_yticks(ticks, labels=[PROBE_LAYERS[i] for i in ticks])
            for ax in axes.flat[len(PROBE_SITES):]:
                ax.set_visible(False)
            fig.colorbar(image, ax=list(axes.flat), label="cosine similarity", shrink=0.65)
            fig.suptitle(
                f"{mode_name} · {target}: residual-basis direction similarity"
            )
            save_and_display_figure(
                fig, f"04_direction_cosine_{mode_name}_{target}"
            )

            # 7. PCA trajectory of every normalized layer/location direction.
            direction_rows = []
            for site in PROBE_SITES:
                for layer in PROBE_LAYERS:
                    direction_rows.append((
                        site, int(layer),
                        normalized_raw_direction(
                            reasoning=reasoning, site=site,
                            target=target, layer=int(layer),
                        ),
                    ))
            direction_matrix = np.stack([row[2] for row in direction_rows])
            pca = PCA(n_components=2)
            coordinates = pca.fit_transform(direction_matrix)
            fig, ax = plt.subplots(figsize=(8.5, 7.0))
            for site in PROBE_SITES:
                mask = np.asarray([row[0] == site for row in direction_rows])
                layers = np.asarray([row[1] for row in direction_rows])[mask]
                order = np.argsort(layers)
                points = coordinates[mask][order]
                layers = layers[order]
                ax.plot(points[:, 0], points[:, 1], alpha=0.55, label=site)
                scatter = ax.scatter(
                    points[:, 0], points[:, 1], c=layers,
                    cmap="viridis", s=26,
                )
            ax.set(
                xlabel=f"PC1 ({pca.explained_variance_ratio_[0]:.1%})",
                ylabel=f"PC2 ({pca.explained_variance_ratio_[1]:.1%})",
                title=f"{mode_name} · {target}: PCA of raw-space probe directions",
            )
            ax.legend(ncol=2, fontsize=8)
            fig.colorbar(scatter, ax=ax, label="layer")
            save_and_display_figure(
                fig, f"07_direction_pca_{mode_name}_{target}"
            )

            # 8. Standardized-coordinate and raw-space norms.
            fig, (standard_ax, raw_ax) = plt.subplots(
                2, 1, figsize=(11, 8), sharex=True
            )
            for site in PROBE_SITES:
                parameters = [
                    probe_affine_parameters(
                        reasoning=reasoning, site=site,
                        target=target, layer=int(layer),
                    )
                    for layer in PROBE_LAYERS
                ]
                standard_ax.plot(PROBE_LAYERS, [
                    np.linalg.norm(np.asarray(item["standardized_coef"]))
                    for item in parameters
                ], label=site)
                raw_ax.plot(PROBE_LAYERS, [
                    np.linalg.norm(np.asarray(item["raw_direction"]))
                    for item in parameters
                ], label=site)
            standard_ax.set(
                ylabel="‖w‖₂ after feature standardization",
                title=f"{mode_name} · {target}: probe norms",
            )
            raw_ax.set(xlabel="layer", ylabel="‖w raw‖₂")
            standard_ax.legend(ncol=2, fontsize=8)
            for ax in (standard_ax, raw_ax):
                ax.grid(alpha=0.2)
            save_and_display_figure(
                fig, f"08_probe_norm_{mode_name}_{target}"
            )
else:
    print("Probe visualizations are paused: RUN_PROBE_VISUALIZATIONS=False.")

In [ ]:
# 1 (locked-test supplement) and 9. These appear only after the test was opened once.
locked_test_metrics_path = PROBE_ROOT / "locked_test_metrics.jsonl"
locked_test_records = read_jsonl_if_present(locked_test_metrics_path)
locked_test_records = [
    row for row in locked_test_records
    if row.get("probe_config_fingerprint") == PROBE_CONFIG_FINGERPRINT
]

if RUN_PROBE_VISUALIZATIONS and locked_test_records:
    if results is None or locked_layers is None:
        raise RuntimeError("Loaded captures and locked layers are required for scatterplots.")
    for reasoning in REASONING_VALUES:
        mode_name = MODE_NAMES[reasoning]
        mode_results = results_by_reasoning[reasoning]
        for target in PROBE_PLOT_TARGETS:
            matrix = np.full((len(PROBE_LAYERS), len(PROBE_SITES)), np.nan)
            for row in locked_test_records:
                if (
                    bool(row["reasoning"]) is reasoning
                    and row["target"] == target
                    and row["subset"] == "all"
                ):
                    matrix[
                        int(row["layer"]), PROBE_SITES.index(str(row["site"]))
                    ] = float(row["r2"])
            fig, _ = draw_matrix(
                matrix,
                xlabels=list(PROBE_SITES),
                ylabels=[str(layer) for layer in PROBE_LAYERS],
                title=(
                    f"{mode_name} · {target}: locked-test R² "
                    "(blank = layer not preselected)"
                ),
                colorbar_label="locked-test R²",
                vmin=min(0.0, float(np.nanmin(matrix))),
                vmax=max(1.0, float(np.nanmax(matrix))),
            )
            save_and_display_figure(
                fig, f"01_locked_test_sparse_heatmap_{mode_name}_{target}"
            )

            n_columns = 3
            n_rows = math.ceil(len(PROBE_SITES) / n_columns)
            fig, axes = plt.subplots(
                n_rows, n_columns, figsize=(13, 4.0 * n_rows), squeeze=False
            )
            for site_index, site in enumerate(PROBE_SITES):
                ax = axes.flat[site_index]
                layer = int(locked_layers[mode_name][site][target][0])
                rows = [
                    row for row in rows_available_at_site(mode_results, site)
                    if row["split"] == "test"
                ]
                X_test = activation_matrix(rows, site=site, layer=layer)
                observed = target_array(rows, target)
                predicted = load_probe_prediction(
                    X_test, reasoning=reasoning, site=site,
                    target=target, layer=layer,
                )
                ax.scatter(observed, predicted, s=18, alpha=0.65)
                limits = [
                    min(float(observed.min()), float(predicted.min())),
                    max(float(observed.max()), float(predicted.max())),
                ]
                ax.plot(limits, limits, color="black", ls="--", lw=1)
                metrics = continuous_metrics(observed, predicted)
                pearson_text = (
                    f"{metrics['pearson']:.3f}"
                    if metrics["pearson"] is not None else "undefined"
                )
                ax.set(
                    xlabel="true y", ylabel="predicted y",
                    title=(
                        f"{site} · L{layer}\n"
                        f"n={len(rows)}, R²={metrics['r2']:.3f}, r={pearson_text}"
                    ),
                )
                ax.grid(alpha=0.15)
            for ax in axes.flat[len(PROBE_SITES):]:
                ax.set_visible(False)
            fig.suptitle(f"{mode_name} · {target}: locked-test predictions")
            save_and_display_figure(
                fig, f"09_locked_test_scatter_{mode_name}_{target}"
            )
elif RUN_PROBE_VISUALIZATIONS:
    print("Locked-test heatmaps and scatterplots remain sealed until test evaluation runs.")

### Cross-layer and cross-location transfer

These are preregistered here before opening the test, but are separately gated because they
load many activation matrices. A matrix cell uses a probe trained at the row's source layer
or location and applies that exact affine readout to the column's destination activations.
Thus the diagonal is ordinary held-out decoding and off-diagonal structure measures whether
a common linear code persists or moves. These matrices are exploratory multiple comparisons
and must not change the already locked layers used for causal patching.

In [ ]:
# 5, 6, and the projection-variance companion to 8.
if RUN_PROBE_TRANSFER_ANALYSIS:
    if not locked_test_records:
        raise RuntimeError(
            "Cross-location/layer transfer is gated until locked test evaluation has run."
        )
    if results is None:
        raise RuntimeError("Load the completed activation capture first.")

    projection_rows = []
    for reasoning in REASONING_VALUES:
        mode_name = MODE_NAMES[reasoning]
        mode_results = results_by_reasoning[reasoning]
        for target in PROBE_TRANSFER_TARGETS:
            for site in PROBE_SITES:
                rows = [
                    row for row in rows_available_at_site(mode_results, site)
                    if row["split"] == "test"
                ]
                observed = target_array(rows, target)
                destination_matrices = {
                    int(layer): activation_matrix(
                        rows, site=site, layer=int(layer)
                    )
                    for layer in PROBE_LAYERS
                }
                source_parameters = [
                    probe_affine_parameters(
                        reasoning=reasoning, site=site,
                        target=target, layer=int(layer),
                    )
                    for layer in PROBE_LAYERS
                ]
                directions = np.stack([
                    np.asarray(item["raw_direction"])
                    for item in source_parameters
                ], axis=1)
                intercepts = np.asarray([
                    float(item["raw_intercept"]) for item in source_parameters
                ])
                transfer = np.full(
                    (len(PROBE_LAYERS), len(PROBE_LAYERS)), np.nan
                )
                for destination_index, destination_layer in enumerate(PROBE_LAYERS):
                    predictions = (
                        destination_matrices[int(destination_layer)] @ directions
                        + intercepts
                    )
                    for source_index, _ in enumerate(PROBE_LAYERS):
                        transfer[source_index, destination_index] = r2_score(
                            observed, predictions[:, source_index]
                        )
                    diagonal_prediction = predictions[:, destination_index]
                    projection_rows.append({
                        "reasoning": reasoning,
                        "reasoning_mode": mode_name,
                        "site": site,
                        "target": target,
                        "layer": int(destination_layer),
                        "row_count": len(rows),
                        "projection_variance": float(np.var(diagonal_prediction)),
                        "projection_standard_deviation": float(
                            np.std(diagonal_prediction)
                        ),
                        "probe_config_fingerprint": PROBE_CONFIG_FINGERPRINT,
                    })
                np.savez_compressed(
                    FIGURE_ROOT
                    / (
                        f"cross_layer_{figure_slug(mode_name)}_"
                        f"{figure_slug(target)}_{figure_slug(site)}.npz"
                    ),
                    matrix=transfer,
                    layers=np.asarray(PROBE_LAYERS),
                )
                fig, ax = draw_matrix(
                    transfer,
                    xlabels=[str(layer) for layer in PROBE_LAYERS],
                    ylabels=[str(layer) for layer in PROBE_LAYERS],
                    title=(
                        f"{mode_name} · {target} · {site}: "
                        f"cross-layer transfer (n={len(rows)})"
                    ),
                    colorbar_label="held-out R²",
                    vmin=max(-1.0, float(np.nanpercentile(transfer, 5))),
                    vmax=min(
                        1.0,
                        max(0.0, float(np.nanpercentile(transfer, 95))),
                    ),
                    figsize=(7.4, 6.4),
                )
                ax.set_xlabel("test layer")
                ax.set_ylabel("train/source layer")
                save_and_display_figure(
                    fig, f"05_cross_layer_{mode_name}_{target}_{site}"
                )

            # Cross-location transfer uses the same rows at every destination.
            common_rows = [
                row for row in mode_results
                if row["split"] == "test"
                and all(
                    result_site_position(row, site) is not None
                    for site in PROBE_SITES
                )
            ]
            if not common_rows:
                raise RuntimeError(
                    f"No complete-site test rows for {mode_name}/{target}."
                )
            observed = target_array(common_rows, target)
            for layer in PROBE_TRANSFER_LAYERS:
                destination_matrices = {
                    site: activation_matrix(
                        common_rows, site=site, layer=int(layer)
                    )
                    for site in PROBE_SITES
                }
                transfer = np.full(
                    (len(PROBE_SITES), len(PROBE_SITES)), np.nan
                )
                for source_index, source_site in enumerate(PROBE_SITES):
                    parameters = probe_affine_parameters(
                        reasoning=reasoning, site=source_site,
                        target=target, layer=int(layer),
                    )
                    direction = np.asarray(parameters["raw_direction"])
                    offset = float(parameters["raw_intercept"])
                    for destination_index, destination_site in enumerate(PROBE_SITES):
                        prediction = (
                            destination_matrices[destination_site] @ direction + offset
                        )
                        transfer[source_index, destination_index] = r2_score(
                            observed, prediction
                        )
                np.savez_compressed(
                    FIGURE_ROOT
                    / (
                        f"cross_location_{figure_slug(mode_name)}_"
                        f"{figure_slug(target)}_layer_{int(layer):02d}.npz"
                    ),
                    matrix=transfer,
                    sites=np.asarray(PROBE_SITES),
                    layer=int(layer),
                )
                fig, ax = draw_matrix(
                    transfer,
                    xlabels=list(PROBE_SITES),
                    ylabels=list(PROBE_SITES),
                    title=(
                        f"{mode_name} · {target} · L{int(layer)}: "
                        f"cross-location transfer (n={len(common_rows)})"
                    ),
                    colorbar_label="held-out R²",
                    vmin=max(-1.0, float(np.nanmin(transfer))),
                    vmax=min(1.0, max(0.0, float(np.nanmax(transfer)))),
                    figsize=(8.0, 7.0),
                )
                ax.set_xlabel("test location")
                ax.set_ylabel("train/source location")
                save_and_display_figure(
                    fig,
                    f"06_cross_location_{mode_name}_{target}_layer_{int(layer):02d}",
                )

    atomic_write_jsonl(PROBE_ROOT / "projection_variance.jsonl", projection_rows)
    projection_frame = pd.DataFrame(projection_rows)
    for reasoning in REASONING_VALUES:
        mode_name = MODE_NAMES[reasoning]
        for target in PROBE_TRANSFER_TARGETS:
            fig, ax = plt.subplots(figsize=(11, 5.2))
            selected = projection_frame[
                (projection_frame["reasoning"] == reasoning)
                & (projection_frame["target"] == target)
            ]
            for site in PROBE_SITES:
                site_rows = selected[selected["site"] == site].sort_values("layer")
                ax.plot(
                    site_rows["layer"],
                    site_rows["projection_standard_deviation"],
                    marker="o", ms=3, label=site,
                )
            ax.set(
                xlabel="layer", ylabel="held-out std(wᵀh + b)",
                title=(
                    f"{mode_name} · {target}: variance of fitted probe projection"
                ),
            )
            ax.legend(ncol=2, fontsize=8)
            ax.grid(alpha=0.2)
            save_and_display_figure(
                fig, f"08_projection_std_{mode_name}_{target}"
            )
else:
    print("Transfer matrices are paused: RUN_PROBE_TRANSFER_ANALYSIS=False.")

## Whole-residual reliability interchange

A successful probe is only evidence of decodability. This first causal screen patches the
complete `resid_post` vector at the final prompt token between test rows that have identical
questions, reports, answer pattern, and reasoning condition but paired reliabilities.
Directions are tested both ways. The 64-patch budget is explicitly stratified over held-out
schedule, reasoning mode, reliability pair, and direction. Within each stratum, examples
are spread over the ordered agreement cells. This prevents a sorted-list subsample from
accidentally retaining only one reliability magnitude or one direction.

Patching uses TransformerLens 3's `TransformerBridge`, not the deprecated
`HookedTransformer.from_pretrained` path. The hook name is resolved from the live bridge
rather than assumed. Only held-out schedules are patched. The code truncates the
teacher-forced input at the answer boundary and asks Qwen for only the last-position logits,
reducing transient GPU memory.

Before intervention, several bridge margins must reproduce the margins saved by the native
capture runner within `BRIDGE_LOGIT_TOLERANCE`. A mismatch aborts rather than silently
combining incompatible hook conventions.

In [ ]:
def canonical_saved_margin(row: dict[str, object]) -> float:
    values = row.get("answer_surface_raw_logits")
    if not isinstance(values, dict):
        raise ValueError(f"Row {row['row_id']} has no answer-boundary surface logits.")
    return float(values[str(row["candidate_1"])]) - float(values[str(row["candidate_2"])])


def bridge_resid_post_hook_name(bridge, layer: int) -> str:
    candidates = (
        f"blocks.{layer}.hook_resid_post",
        f"blocks.{layer}.hook_out",
    )
    for name in candidates:
        if name in bridge.hook_dict:
            return name
    nearby = sorted(
        name for name in bridge.hook_dict
        if name.startswith(f"blocks.{layer}.") and ("resid" in name or name.endswith("hook_out"))
    )
    raise KeyError(f"No residual-post hook for layer {layer}; nearby hooks={nearby}")


def bridge_margin(
    bridge, row: dict[str, object], *, hook: tuple[str, object] | None = None
) -> float:
    boundary = result_site_position(row, "answer_prefix")
    if boundary is None:
        raise ValueError(f"Row {row['row_id']} lacks an answer boundary.")
    input_ids = torch.tensor(
        [row["teacher_forced_input_ids"][: boundary + 1]],
        dtype=torch.long,
        device="cuda",
    )
    attention_mask = torch.ones_like(input_ids)
    kwargs = {
        "attention_mask": attention_mask,
        "return_type": "logits",
        "prepend_bos": False,
        "use_cache": False,
        "logits_to_keep": 1,
    }
    with torch.inference_mode():
        if hook is None:
            logits = bridge(input_ids, **kwargs)
        else:
            logits = bridge.run_with_hooks(input_ids, fwd_hooks=[hook], **kwargs)
    token_1 = int(row["candidate_1_answer_token_ids"][0])
    token_2 = int(row["candidate_2_answer_token_ids"][0])
    if len(row["candidate_1_answer_token_ids"]) != 1 or len(row["candidate_2_answer_token_ids"]) != 1:
        raise ValueError("Patching margin requires single-token candidate surfaces.")
    return float((logits[0, -1, token_1] - logits[0, -1, token_2]).float().cpu())


def reliability_patch_directions(result_rows: TranscriptDataset) -> list[tuple[dict, dict]]:
    test = [dict(row) for row in result_rows if row["split"] == "test"]
    index = {
        (
            int(row["question_set_index"]),
            int(row["answer_pattern_index"]),
            bool(row["reasoning"]),
            row_reliability_exact(row),
        ): row
        for row in test
        if result_site_position(row, "answer_prefix") is not None
    }
    strata: dict[tuple[int, bool, int, int], list[tuple[dict, dict]]] = defaultdict(list)
    for schedule in sorted(test_schedule_set):
        for pattern in range(NUM_ANSWER_PATTERNS):
            for reasoning in REASONING_VALUES:
                for pair_index, (low, high) in enumerate(PATCH_RELIABILITY_PAIRS):
                    low_row = index.get((schedule, pattern, reasoning, low))
                    high_row = index.get((schedule, pattern, reasoning, high))
                    if low_row is not None and high_row is not None:
                        strata[(schedule, reasoning, pair_index, 0)].append((low_row, high_row))
                        strata[(schedule, reasoning, pair_index, 1)].append((high_row, low_row))

    expected_strata = {
        (schedule, reasoning, pair_index, direction)
        for schedule in test_schedule_set
        for reasoning in REASONING_VALUES
        for pair_index in range(len(PATCH_RELIABILITY_PAIRS))
        for direction in (0, 1)
    }
    if set(strata) != expected_strata:
        missing = sorted(expected_strata - set(strata))
        raise ValueError(
            "Cannot construct a balanced patch design because answer-boundary rows "
            f"are missing from strata {missing}."
        )
    if not len(strata) <= PATCH_MAX_DIRECTIONS <= sum(map(len, strata.values())):
        raise ValueError(
            "PATCH_MAX_DIRECTIONS must cover every patch stratum without exceeding "
            "the available paired directions."
        )

    base_quota, remainder = divmod(PATCH_MAX_DIRECTIONS, len(strata))
    directions = []
    for stratum_index, key in enumerate(sorted(strata)):
        candidates = sorted(strata[key], key=lambda pair: (
            float(pair[0]["delta_a"]),
            int(pair[0]["agreement_c1"]),
            int(pair[0]["agreement_c2"]),
            int(pair[0]["answer_pattern_index"]),
        ))
        quota = base_quota + int(stratum_index < remainder)
        if quota > len(candidates):
            raise ValueError(f"Patch stratum {key} has only {len(candidates)} candidates.")
        if quota == 1:
            selected_indices = [len(candidates) // 2]
        else:
            selected_indices = [
                round(index * (len(candidates) - 1) / (quota - 1))
                for index in range(quota)
            ]
        directions.extend(candidates[index] for index in selected_indices)

    assert len(directions) == PATCH_MAX_DIRECTIONS
    assert all(base["split"] == donor["split"] == "test" for base, donor in directions)
    return directions


if RUN_ACTIVATION_PATCHING:
    if results is None or locked_layers is None:
        raise RuntimeError("Completed captures and locked training-only layers are required.")
    from transformer_lens.model_bridge import TransformerBridge

    patch_layers_by_mode = {
        mode_name: locked_layers[mode_name][PATCH_SITE]["z_bayes"]
        for mode_name in MODE_NAMES.values()
    }
    directions = reliability_patch_directions(results)
    patch_configuration = {
        "schema_version": 1,
        "probe_config_fingerprint": PROBE_CONFIG_FINGERPRINT,
        "patch_run_id": PATCH_RUN_ID,
        "site": PATCH_SITE,
        "layers_by_reasoning_mode": {
            mode_name: [int(layer) for layer in layers]
            for mode_name, layers in patch_layers_by_mode.items()
        },
        "reliability_pairs": [list(pair) for pair in PATCH_RELIABILITY_PAIRS],
        "directions": [
            [str(base["row_id"]), str(donor["row_id"])] for base, donor in directions
        ],
    }
    PATCH_CONFIG_FINGERPRINT = hashlib.sha256(json.dumps(
        patch_configuration, sort_keys=True, separators=(",", ":"), allow_nan=False
    ).encode()).hexdigest()
    patch_design = {
        **patch_configuration,
        "patch_config_fingerprint": PATCH_CONFIG_FINGERPRINT,
        "row_count": len(directions),
        "test_schedules": sorted(test_schedule_set),
        "reasoning_counts": dict(Counter(str(base["reasoning"]) for base, _ in directions)),
        "directed_reliability_counts": dict(Counter(
            f"{row_reliability_exact(base)}->{row_reliability_exact(donor)}"
            for base, donor in directions
        )),
        "delta_a_counts": dict(Counter(str(base["delta_a"]) for base, _ in directions)),
    }
    atomic_write_json(PATCH_ROOT / "patch_design.json", patch_design)
    display(patch_design)
    bridge = TransformerBridge.boot_transformers(
        MODEL_ID,
        revision=MODEL_REVISION,
        device="cuda",
        dtype=torch.bfloat16,
        tokenizer=tokenizer,
        trust_remote_code=False,
    )
    all_patch_layers = sorted({
        int(layer)
        for layers in patch_layers_by_mode.values()
        for layer in layers
    })
    print("Resolved patch hooks:", {
        layer: bridge_resid_post_hook_name(bridge, layer)
        for layer in all_patch_layers
    })

    # Compatibility gate: cover each reasoning mode and base reliability before patching.
    compatibility_rows = []
    compatibility_strata = set()
    for base, _ in directions:
        key = (bool(base["reasoning"]), row_reliability_exact(base))
        if key not in compatibility_strata:
            compatibility_strata.add(key)
            compatibility_rows.append(base)
    patched_reliabilities = {
        reliability
        for pair in PATCH_RELIABILITY_PAIRS
        for reliability in pair
    }
    assert len(compatibility_rows) == (
        len(REASONING_VALUES) * len(patched_reliabilities)
    )
    for row in compatibility_rows:
        difference = abs(bridge_margin(bridge, row) - canonical_saved_margin(row))
        if difference > BRIDGE_LOGIT_TOLERANCE:
            raise RuntimeError(
                f"TransformerBridge/native margin mismatch {difference:.4f} exceeds tolerance."
            )

    patch_results_path = PATCH_ROOT / "results.jsonl"
    completed_patches = {
        (row["base_row_id"], row["donor_row_id"], int(row["layer"])): row
        for row in read_jsonl_if_present(patch_results_path)
        if row.get("patch_config_fingerprint") == PATCH_CONFIG_FINGERPRINT
    }
    baseline_margins: dict[str, float] = {}
    for base, donor in directions:
        base_id, donor_id = str(base["row_id"]), str(donor["row_id"])
        if base_id not in baseline_margins:
            baseline_margins[base_id] = bridge_margin(bridge, base)
        patch_layers = patch_layers_by_mode[MODE_NAMES[bool(base["reasoning"])]]
        for layer in patch_layers:
            patch_key = (base_id, donor_id, int(layer))
            if patch_key in completed_patches:
                continue
            donor_vector = torch.from_numpy(
                activation_vector(donor, site=PATCH_SITE, layer=int(layer))
            ).to(device="cuda", dtype=torch.bfloat16)
            base_position = result_site_position(base, PATCH_SITE)
            assert base_position is not None

            def replace_residual(activation, hook, *, vector=donor_vector, position=base_position):
                del hook
                patched = activation.clone()
                patched[0, position, :] = vector
                return patched

            hook_name = bridge_resid_post_hook_name(bridge, int(layer))
            patched_margin = bridge_margin(
                bridge, base, hook=(hook_name, replace_residual)
            )
            record = {
                "base_row_id": base_id,
                "donor_row_id": donor_id,
                "split": "test",
                "site": PATCH_SITE,
                "layer": int(layer),
                "reasoning": bool(base["reasoning"]),
                "question_set_index": int(base["question_set_index"]),
                "answer_pattern_index": int(base["answer_pattern_index"]),
                "delta_a": float(base["delta_a"]),
                "base_reliability": row_reliability_exact(base),
                "donor_reliability": row_reliability_exact(donor),
                "base_z_bayes": float(base["z_bayes"]),
                "counterfactual_z_bayes": float(donor["z_bayes"]),
                "baseline_margin": baseline_margins[base_id],
                "patched_margin": patched_margin,
                "margin_change": patched_margin - baseline_margins[base_id],
                "patch_config_fingerprint": PATCH_CONFIG_FINGERPRINT,
            }
            completed_patches[patch_key] = record
            atomic_write_jsonl(
                patch_results_path,
                sorted(
                    completed_patches.values(),
                    key=lambda row: (
                        str(row["base_row_id"]), str(row["donor_row_id"]), int(row["layer"])
                    ),
                ),
            )
    del bridge
    gc.collect()
    torch.cuda.empty_cache()
    display(pd.DataFrame(completed_patches.values()))
else:
    print("Activation patching is paused: RUN_ACTIVATION_PATCHING=False.")

In [ ]:
final_status = {
    "dataset_ready": len(dataset) == EXPECTED_ROWS,
    "split_ready": (
        len(train_rows) == EXPECTED_TRAIN_ROWS
        and len(test_rows) == EXPECTED_TEST_ROWS
    ),
    "paired_prompt_lengths_equal": not prompt_length_mismatches,
    "test_schedules": list(selected_test_schedules),
    "all_tie_cells_in_test": TIE_CELLS <= {agreement_cell(row) for row in test_rows},
    "storage_preflight_passed": worst_case_activation_gib <= allowed_payload_gib,
    "capture_loaded": results is not None,
    "probe_training_records": len(probe_cv_records),
    "layers_locked": locked_layers is not None,
    "gpu_execution_requested": any((RUN_GPU_CAPTURE, RUN_ACTIVATION_PATCHING)),
}
display(final_status)